<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x27f): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x21e): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1f2): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xd9): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x7a): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x188): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xc2): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x26e): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xf0): long unsigned int
<1><63>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x161): __quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
DW_AT_type        : <0x32>
<1><6e>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2bc): __u_quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 56
DW_AT_type        : <0x4e>
<1><79>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x27): __uid_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 125
DW_AT_type        : <0x47>
<1><84>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1d6): __gid_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 126
DW_AT_type        : <0x47>
<1><8f>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x277): __pid_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 133
DW_AT_type        : <0x2b>
<1><9a>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1de): sizetype
<1><a1>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x12e): __time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 139
DW_AT_type        : <0x63>
<1><ac>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1b7): __key_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 144
DW_AT_type        : <0x2b>
<1><b7>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x8d): __syscall_ulong_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 177
DW_AT_type        : <0x6e>
<1><c2>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1ad): char
<1><c9>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xcf>
<1><cf>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0xc2>
<1><d4>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x107): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 4
DW_AT_sibling     : <0x127>
<2><e0>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x148): nargs
DW_AT_decl_file   : 2
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><ee>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb8): sys_flags
DW_AT_decl_file   : 2
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><fc>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 2
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><10a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe7): sys_func
DW_AT_decl_file   : 2
DW_AT_decl_line   : 8
DW_AT_type        : <0x132>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><118>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa9): sys_name
DW_AT_decl_file   : 2
DW_AT_decl_line   : 9
DW_AT_type        : <0xc9>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><127>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0x132>
<2><130>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><132>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x127>
<1><138>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x19f): struct_sysent
DW_AT_decl_file   : 2
DW_AT_decl_line   : 10
DW_AT_type        : <0xd4>
<1><143>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x149>
<1><149>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x138>
<1><14e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x1a): _Bool
<1><155>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x23a): ipc_perm
DW_AT_byte_size   : 48
DW_AT_decl_file   : 3
DW_AT_decl_line   : 42
DW_AT_sibling     : <0x1fc>
<2><161>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x218): __key
DW_AT_decl_file   : 3
DW_AT_decl_line   : 44
DW_AT_type        : <0xac>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><16f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : uid
DW_AT_decl_file   : 3
DW_AT_decl_line   : 45
DW_AT_type        : <0x79>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><17d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : gid
DW_AT_decl_file   : 3
DW_AT_decl_line   : 46
DW_AT_type        : <0x84>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><18b>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10e): cuid
DW_AT_decl_file   : 3
DW_AT_decl_line   : 47
DW_AT_type        : <0x79>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><199>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x102): cgid
DW_AT_decl_file   : 3
DW_AT_decl_line   : 48
DW_AT_type        : <0x84>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><1a7>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b2): mode
DW_AT_decl_file   : 3
DW_AT_decl_line   : 49
DW_AT_type        : <0x40>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><1b5>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x267): __pad1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 50
DW_AT_type        : <0x40>
DW_AT_data_member_location: 2 byte block: 23 16 	(DW_OP_plus_uconst: 22)
<2><1c3>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb2): __seq
DW_AT_decl_file   : 3
DW_AT_decl_line   : 51
DW_AT_type        : <0x40>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><1d1>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20): __pad2
DW_AT_decl_file   : 3
DW_AT_decl_line   : 52
DW_AT_type        : <0x40>
DW_AT_data_member_location: 2 byte block: 23 1a 	(DW_OP_plus_uconst: 26)
<2><1df>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x113): __glibc_reserved1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_type        : <0xb7>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><1ed>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x228): __glibc_reserved2
DW_AT_decl_file   : 3
DW_AT_decl_line   : 54
DW_AT_type        : <0xb7>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<1><1fc>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x175): msgqnum_t
DW_AT_decl_file   : 4
DW_AT_decl_line   : 32
DW_AT_type        : <0xb7>
<1><207>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x17f): msglen_t
DW_AT_decl_file   : 4
DW_AT_decl_line   : 33
DW_AT_type        : <0xb7>
<1><212>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x0): msqid_ds
DW_AT_byte_size   : 120
DW_AT_decl_file   : 4
DW_AT_decl_line   : 37
DW_AT_sibling     : <0x2b9>
<2><21e>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x125): msg_perm
DW_AT_decl_file   : 4
DW_AT_decl_line   : 39
DW_AT_type        : <0x155>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><22c>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c7): msg_stime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 40
DW_AT_type        : <0xa1>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><23a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x195): msg_rtime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 44
DW_AT_type        : <0xa1>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><248>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14e): msg_ctime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 48
DW_AT_type        : <0xa1>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><256>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bf): __msg_cbytes
DW_AT_decl_file   : 4
DW_AT_decl_line   : 52
DW_AT_type        : <0xb7>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><264>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x158): msg_qnum
DW_AT_decl_file   : 4
DW_AT_decl_line   : 53
DW_AT_type        : <0x1fc>
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<2><272>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16a): msg_qbytes
DW_AT_decl_file   : 4
DW_AT_decl_line   : 54
DW_AT_type        : <0x207>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><280>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9f): msg_lspid
DW_AT_decl_file   : 4
DW_AT_decl_line   : 55
DW_AT_type        : <0x8f>
DW_AT_data_member_location: 2 byte block: 23 60 	(DW_OP_plus_uconst: 96)
<2><28e>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d1): msg_lrpid
DW_AT_decl_file   : 4
DW_AT_decl_line   : 56
DW_AT_type        : <0x8f>
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><29c>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x243): __glibc_reserved4
DW_AT_decl_file   : 4
DW_AT_decl_line   : 57
DW_AT_type        : <0xb7>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><2aa>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x255): __glibc_reserved5
DW_AT_decl_file   : 4
DW_AT_decl_line   : 58
DW_AT_type        : <0xb7>
DW_AT_data_member_location: 2 byte block: 23 70 	(DW_OP_plus_uconst: 112)
<1><2b9>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1e7): msqid_ds_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 41
DW_AT_type        : <0x212>
<1><2c4>
Abbrev Number: 12 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x137): current_wordsize
DW_AT_decl_file   : 6
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><2d2>
Abbrev Number: 12 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x107): sysent
DW_AT_decl_file   : 6
DW_AT_decl_line   : 892
DW_AT_type        : <0x143>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><2e0>
Abbrev Number: 12 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1cc): nsyscalls
DW_AT_decl_file   : 6
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><2ee>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9): mpers_target_var
DW_AT_decl_file   : 5
DW_AT_decl_line   : 48
DW_AT_type        : <0x2b9>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
