<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1a8): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x5e): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x129): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x194): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x204): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1e3): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1c5): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x137): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x288): long unsigned int
<1><63>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x0): __quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
DW_AT_type        : <0x32>
<1><6e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x78): sizetype
<1><75>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2bc): __time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 139
DW_AT_type        : <0x63>
<1><80>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x327): __suseconds_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 141
DW_AT_type        : <0x63>
<1><8b>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x9e): __syscall_slong_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 175
DW_AT_type        : <0x63>
<1><96>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x230): char
<1><9d>
Abbrev Number: 5 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2c5): timeval
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_sibling     : <0xc6>
<2><a9>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3e): tv_sec
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_type        : <0x75>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b7>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2eb): tv_usec
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
DW_AT_type        : <0x80>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><c6>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xcc>
<1><cc>
Abbrev Number: 8 (DW_TAG_const_type)
DW_AT_type        : <0x96>
<1><d1>
Abbrev Number: 5 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x317): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 4
DW_AT_sibling     : <0x124>
<2><dd>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a2): nargs
DW_AT_decl_file   : 3
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><eb>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f0): sys_flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><f9>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 3
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><107>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9): sys_func
DW_AT_decl_file   : 3
DW_AT_decl_line   : 8
DW_AT_type        : <0x12f>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><115>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x95): sys_name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 9
DW_AT_type        : <0xc6>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><124>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0x12f>
<2><12d>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><12f>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x124>
<1><135>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2dd): struct_sysent
DW_AT_decl_file   : 3
DW_AT_decl_line   : 10
DW_AT_type        : <0xd1>
<1><140>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x146>
<1><146>
Abbrev Number: 8 (DW_TAG_const_type)
DW_AT_type        : <0x135>
<1><14b>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x235): _Bool
<1><152>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 194
DW_AT_sibling     : <0x171>
<2><15a>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10e): ru_maxrss
DW_AT_decl_file   : 4
DW_AT_decl_line   : 196
DW_AT_type        : <0x55>
<2><165>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x151): __ru_maxrss_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 197
DW_AT_type        : <0x8b>
<1><171>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 202
DW_AT_sibling     : <0x190>
<2><179>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x35): ru_ixrss
DW_AT_decl_file   : 4
DW_AT_decl_line   : 204
DW_AT_type        : <0x55>
<2><184>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2cd): __ru_ixrss_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 205
DW_AT_type        : <0x8b>
<1><190>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 208
DW_AT_sibling     : <0x1af>
<2><198>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x55): ru_idrss
DW_AT_decl_file   : 4
DW_AT_decl_line   : 210
DW_AT_type        : <0x55>
<2><1a3>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x45): __ru_idrss_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 211
DW_AT_type        : <0x8b>
<1><1af>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 214
DW_AT_sibling     : <0x1ce>
<2><1b7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xba): ru_isrss
DW_AT_decl_file   : 4
DW_AT_decl_line   : 216
DW_AT_type        : <0x55>
<2><1c2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x220): __ru_isrss_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 217
DW_AT_type        : <0x8b>
<1><1ce>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 221
DW_AT_sibling     : <0x1ed>
<2><1d6>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x12): ru_minflt
DW_AT_decl_file   : 4
DW_AT_decl_line   : 223
DW_AT_type        : <0x55>
<2><1e1>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x118): __ru_minflt_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 224
DW_AT_type        : <0x8b>
<1><1ed>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 227
DW_AT_sibling     : <0x20c>
<2><1f5>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb0): ru_majflt
DW_AT_decl_file   : 4
DW_AT_decl_line   : 229
DW_AT_type        : <0x55>
<2><200>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x183): __ru_majflt_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 230
DW_AT_type        : <0x8b>
<1><20c>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 233
DW_AT_sibling     : <0x22b>
<2><214>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x81): ru_nswap
DW_AT_decl_file   : 4
DW_AT_decl_line   : 235
DW_AT_type        : <0x55>
<2><21f>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x68): __ru_nswap_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 236
DW_AT_type        : <0x8b>
<1><22b>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 240
DW_AT_sibling     : <0x24a>
<2><233>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x162): ru_inblock
DW_AT_decl_file   : 4
DW_AT_decl_line   : 242
DW_AT_type        : <0x55>
<2><23e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x251): __ru_inblock_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 243
DW_AT_type        : <0x8b>
<1><24a>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 246
DW_AT_sibling     : <0x269>
<2><252>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8a): ru_oublock
DW_AT_decl_file   : 4
DW_AT_decl_line   : 248
DW_AT_type        : <0x55>
<2><25d>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x276): __ru_oublock_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 249
DW_AT_type        : <0x8b>
<1><269>
Abbrev Number: 12 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 252
DW_AT_sibling     : <0x288>
<2><271>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x23b): ru_msgsnd
DW_AT_decl_file   : 4
DW_AT_decl_line   : 254
DW_AT_type        : <0x55>
<2><27c>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x29a): __ru_msgsnd_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 255
DW_AT_type        : <0x8b>
<1><288>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 258
DW_AT_sibling     : <0x2aa>
<2><291>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x335): ru_msgrcv
DW_AT_decl_file   : 4
DW_AT_decl_line   : 260
DW_AT_type        : <0x55>
<2><29d>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f3): __ru_msgrcv_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 261
DW_AT_type        : <0x8b>
<1><2aa>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 264
DW_AT_sibling     : <0x2cc>
<2><2b3>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x245): ru_nsignals
DW_AT_decl_file   : 4
DW_AT_decl_line   : 266
DW_AT_type        : <0x55>
<2><2bf>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x263): __ru_nsignals_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 267
DW_AT_type        : <0x8b>
<1><2cc>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 272
DW_AT_sibling     : <0x2ee>
<2><2d5>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c): ru_nvcsw
DW_AT_decl_file   : 4
DW_AT_decl_line   : 274
DW_AT_type        : <0x55>
<2><2e1>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x25): __ru_nvcsw_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 275
DW_AT_type        : <0x8b>
<1><2ee>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 279
DW_AT_sibling     : <0x310>
<2><2f7>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x304): ru_nivcsw
DW_AT_decl_file   : 4
DW_AT_decl_line   : 281
DW_AT_type        : <0x55>
<2><303>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ab): __ru_nivcsw_word
DW_AT_decl_file   : 4
DW_AT_decl_line   : 282
DW_AT_type        : <0x8b>
<1><310>
Abbrev Number: 5 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1dc): rusage
DW_AT_byte_size   : 144
DW_AT_decl_file   : 4
DW_AT_decl_line   : 187
DW_AT_sibling     : <0x3ab>
<2><31c>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x217): ru_utime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 190
DW_AT_type        : <0x9d>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><32a>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x31e): ru_stime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 192
DW_AT_type        : <0x9d>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><338>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x152>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><340>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x171>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><348>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x190>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><350>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x1af>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><358>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x1ce>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><360>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x1ed>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><368>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x20c>
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<2><370>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x22b>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><378>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x24a>
DW_AT_data_member_location: 2 byte block: 23 60 	(DW_OP_plus_uconst: 96)
<2><380>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x269>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><388>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x288>
DW_AT_data_member_location: 2 byte block: 23 70 	(DW_OP_plus_uconst: 112)
<2><390>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x2aa>
DW_AT_data_member_location: 2 byte block: 23 78 	(DW_OP_plus_uconst: 120)
<2><398>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x2cc>
DW_AT_data_member_location: 3 byte block: 23 80 1 	(DW_OP_plus_uconst: 128)
<2><3a1>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_type        : <0x2ee>
DW_AT_data_member_location: 3 byte block: 23 88 1 	(DW_OP_plus_uconst: 136)
<1><3ab>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x30e): rusage_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 35
DW_AT_type        : <0x310>
<1><3b6>
Abbrev Number: 17 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1b4): current_wordsize
DW_AT_decl_file   : 6
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><3c4>
Abbrev Number: 17 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x317): sysent
DW_AT_decl_file   : 6
DW_AT_decl_line   : 892
DW_AT_type        : <0x140>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><3d2>
Abbrev Number: 17 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1fa): nsyscalls
DW_AT_decl_file   : 6
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><3e0>
Abbrev Number: 18 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x140): mpers_target_var
DW_AT_decl_file   : 5
DW_AT_decl_line   : 37
DW_AT_type        : <0x3ab>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
