<1><1d>
Abbrev Number: 2 (DW_TAG_structure_type)
DW_AT_byte_size   : 72
DW_AT_decl_file   : 1
DW_AT_decl_line   : 3
DW_AT_sibling     : <0xd0>
<2><25>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : p
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_type        : <0xd0>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><31>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : sc
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0xd2>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><3e>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : ss
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0xd9>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><4b>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : uc
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><58>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : si
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0xe7>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><65>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : ui
DW_AT_decl_file   : 1
DW_AT_decl_line   : 11
DW_AT_type        : <0xee>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><72>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : sl
DW_AT_decl_file   : 1
DW_AT_decl_line   : 12
DW_AT_type        : <0xf5>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><7f>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : us
DW_AT_decl_file   : 1
DW_AT_decl_line   : 13
DW_AT_type        : <0xfc>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><8c>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : sll
DW_AT_decl_file   : 1
DW_AT_decl_line   : 15
DW_AT_type        : <0x103>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><9a>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : ull
DW_AT_decl_file   : 1
DW_AT_decl_line   : 16
DW_AT_type        : <0x10a>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><a8>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : ul
DW_AT_decl_file   : 1
DW_AT_decl_line   : 17
DW_AT_type        : <0x111>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><b5>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : asl
DW_AT_decl_file   : 1
DW_AT_decl_line   : 18
DW_AT_type        : <0x118>
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><c3>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : f
DW_AT_decl_file   : 1
DW_AT_decl_line   : 19
DW_AT_type        : <0xd2>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<1><d0>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><d2>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0xb6): char
<1><d9>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x105): short int
<1><e0>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xa8): unsigned char
<1><e7>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><ee>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xe): unsigned int
<1><f5>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0xbb): long int
<1><fc>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xe9): short unsigned int
<1><103>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x0): long long int
<1><10a>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xc4): long long unsigned int
<1><111>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x12a): long unsigned int
<1><118>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0xf5>
DW_AT_sibling     : <0x128>
<2><121>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0x128>
DW_AT_upper_bound : 2
<1><128>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xfc): sizetype
<1><12f>
Abbrev Number: 9 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 22
DW_AT_sibling     : <0x1a7>
<2><137>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : sll
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
DW_AT_type        : <0x103>
<2><142>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : ull
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
DW_AT_type        : <0x10a>
<2><14d>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : p
DW_AT_decl_file   : 1
DW_AT_decl_line   : 25
DW_AT_type        : <0xd0>
<2><156>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : sl
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
DW_AT_type        : <0xf5>
<2><160>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : ul
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
DW_AT_type        : <0x111>
<2><16a>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : si
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
DW_AT_type        : <0xe7>
<2><174>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : ui
DW_AT_decl_file   : 1
DW_AT_decl_line   : 29
DW_AT_type        : <0xee>
<2><17e>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : ss
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
DW_AT_type        : <0xd9>
<2><188>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : us
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
DW_AT_type        : <0xfc>
<2><192>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : sc
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
DW_AT_type        : <0xd2>
<2><19c>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : uc
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_type        : <0xe0>
<1><1a7>
Abbrev Number: 2 (DW_TAG_structure_type)
DW_AT_byte_size   : 96
DW_AT_decl_file   : 1
DW_AT_decl_line   : 2
DW_AT_sibling     : <0x1d4>
<2><1af>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : s
DW_AT_decl_file   : 1
DW_AT_decl_line   : 21
DW_AT_type        : <0x1d>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1bb>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : u
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_type        : <0x1d4>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><1c7>
Abbrev Number: 3 (DW_TAG_member)
DW_AT_name        : f
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_type        : <0x1e4>
DW_AT_data_member_location: 2 byte block: 23 60 	(DW_OP_plus_uconst: 96)
<1><1d4>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0x12f>
DW_AT_sibling     : <0x1e4>
<2><1dd>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0x128>
DW_AT_upper_bound : 2
<1><1e4>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0xd9>
DW_AT_sibling     : <0x1f3>
<2><1ed>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x128>
<1><1f3>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xdb): sample_struct
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
DW_AT_type        : <0x1a7>
<1><1fe>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x66): mpers_target_var
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_type        : <0x1f3>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
