<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1a9): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x186): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x172): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xaa): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x58): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x105): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x93): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1a0): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xc4): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x169): sizetype
<1><6a>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><6c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x120): char
<1><73>
Abbrev Number: 5 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x0): size_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 212
DW_AT_type        : <0x47>
<1><7e>
Abbrev Number: 6 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x84>
<1><84>
Abbrev Number: 7 (DW_TAG_const_type)
DW_AT_type        : <0x6c>
<1><89>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xd6): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xdc>
<2><95>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xee): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><a3>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x89): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><b1>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><bf>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b5): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xe7>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><cd>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6b): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x7e>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><dc>
Abbrev Number: 11 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xe7>
<2><e5>
Abbrev Number: 12 (DW_TAG_unspecified_parameters)
<1><e7>
Abbrev Number: 6 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xdc>
<1><ed>
Abbrev Number: 5 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x112): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x89>
<1><f8>
Abbrev Number: 6 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xfe>
<1><fe>
Abbrev Number: 7 (DW_TAG_const_type)
DW_AT_type        : <0xed>
<1><103>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x7): _Bool
<1><10a>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xb8): sigaltstack
DW_AT_byte_size   : 12
DW_AT_decl_file   : 3
DW_AT_decl_line   : 49
DW_AT_sibling     : <0x141>
<2><116>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): ss_sp
DW_AT_decl_file   : 3
DW_AT_decl_line   : 51
DW_AT_type        : <0x6a>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><124>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x160): ss_flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 52
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><132>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): ss_size
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_type        : <0x73>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><141>
Abbrev Number: 5 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x198): stack_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 54
DW_AT_type        : <0x10a>
<1><14c>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdd): current_wordsize
DW_AT_decl_file   : 4
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><15a>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd6): sysent
DW_AT_decl_file   : 4
DW_AT_decl_line   : 892
DW_AT_type        : <0xf8>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><168>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x156): nsyscalls
DW_AT_decl_file   : 4
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><176>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf4): mpers_target_var
DW_AT_decl_file   : 5
DW_AT_decl_line   : 38
DW_AT_type        : <0x141>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
