<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x141): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x47): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0xb5): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x11a): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1af): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x161): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xc3): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0xda): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x249): long unsigned int
<1><63>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x11): __quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
DW_AT_type        : <0x32>
<1><6e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x51): sizetype
<1><75>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x27b): __time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 139
DW_AT_type        : <0x63>
<1><80>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2d9): __suseconds_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 141
DW_AT_type        : <0x63>
<1><8b>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1d0): char
<1><92>
Abbrev Number: 5 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x284): timeval
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_sibling     : <0xbb>
<2><9e>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x40): tv_sec
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_type        : <0x75>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><ac>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ab): tv_usec
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
DW_AT_type        : <0x80>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><bb>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xc1>
<1><c1>
Abbrev Number: 8 (DW_TAG_const_type)
DW_AT_type        : <0x8b>
<1><c6>
Abbrev Number: 5 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2cc): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 4
DW_AT_sibling     : <0x119>
<2><d2>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13b): nargs
DW_AT_decl_file   : 3
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><e0>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x91): sys_flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><ee>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 3
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><fc>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24): sys_func
DW_AT_decl_file   : 3
DW_AT_decl_line   : 8
DW_AT_type        : <0x124>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><10a>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x88): sys_name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 9
DW_AT_type        : <0xbb>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><119>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0x124>
<2><122>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><124>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x119>
<1><12a>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x29d): struct_sysent
DW_AT_decl_file   : 3
DW_AT_decl_line   : 10
DW_AT_type        : <0xc6>
<1><135>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x13b>
<1><13b>
Abbrev Number: 8 (DW_TAG_const_type)
DW_AT_type        : <0x12a>
<1><140>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x1df): _Bool
<1><147>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x244): __u8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 20
DW_AT_type        : <0x39>
<1><152>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x28c): __s32
DW_AT_decl_file   : 4
DW_AT_decl_line   : 25
DW_AT_type        : <0x2b>
<1><15d>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xa1): __u32
DW_AT_decl_file   : 4
DW_AT_decl_line   : 26
DW_AT_type        : <0x47>
<1><168>
Abbrev Number: 12 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x2bb): v4l2_preemphasis
DW_AT_byte_size   : 4
DW_AT_decl_file   : 8
DW_AT_decl_line   : 763
DW_AT_sibling     : <0x188>
<2><175>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x6e): V4L2_PREEMPHASIS_DISABLED
DW_AT_const_value : 0
<2><17b>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x185): V4L2_PREEMPHASIS_50_uS
DW_AT_const_value : 1
<2><181>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x16e): V4L2_PREEMPHASIS_75_uS
DW_AT_const_value : 2
<1><188>
Abbrev Number: 14 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xf4): v4l2_timecode
DW_AT_byte_size   : 16
DW_AT_decl_file   : 5
DW_AT_decl_line   : 519
DW_AT_sibling     : <0x1ff>
<2><195>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15c): type
DW_AT_decl_file   : 5
DW_AT_decl_line   : 520
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1a4>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14d): flags
DW_AT_decl_file   : 5
DW_AT_decl_line   : 521
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1b3>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d): frames
DW_AT_decl_file   : 5
DW_AT_decl_line   : 522
DW_AT_type        : <0x147>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><1c2>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c2): seconds
DW_AT_decl_file   : 5
DW_AT_decl_line   : 523
DW_AT_type        : <0x147>
DW_AT_data_member_location: 2 byte block: 23 9 	(DW_OP_plus_uconst: 9)
<2><1d1>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2b3): minutes
DW_AT_decl_file   : 5
DW_AT_decl_line   : 524
DW_AT_type        : <0x147>
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><1e0>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ca): hours
DW_AT_decl_file   : 5
DW_AT_decl_line   : 525
DW_AT_type        : <0x147>
DW_AT_data_member_location: 2 byte block: 23 b 	(DW_OP_plus_uconst: 11)
<2><1ef>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f0): userbits
DW_AT_decl_file   : 5
DW_AT_decl_line   : 526
DW_AT_type        : <0x1ff>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><1ff>
Abbrev Number: 16 (DW_TAG_array_type)
DW_AT_type        : <0x147>
DW_AT_sibling     : <0x20f>
<2><208>
Abbrev Number: 17 (DW_TAG_subrange_type)
DW_AT_type        : <0x6e>
DW_AT_upper_bound : 3
<1><20f>
Abbrev Number: 18 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 5
DW_AT_decl_line   : 606
DW_AT_sibling     : <0x23c>
<2><218>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e5): mem_offset
DW_AT_decl_file   : 5
DW_AT_decl_line   : 607
DW_AT_type        : <0x15d>
<2><224>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5a): userptr
DW_AT_decl_file   : 5
DW_AT_decl_line   : 608
DW_AT_type        : <0x5c>
<2><230>
Abbrev Number: 20 (DW_TAG_member)
DW_AT_name        : fd
DW_AT_decl_file   : 5
DW_AT_decl_line   : 609
DW_AT_type        : <0x152>
<1><23c>
Abbrev Number: 14 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x292): v4l2_plane
DW_AT_byte_size   : 60
DW_AT_decl_file   : 5
DW_AT_decl_line   : 603
DW_AT_sibling     : <0x293>
<2><249>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d5): bytesused
DW_AT_decl_file   : 5
DW_AT_decl_line   : 604
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><258>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x113): length
DW_AT_decl_file   : 5
DW_AT_decl_line   : 605
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><267>
Abbrev Number: 21 (DW_TAG_member)
DW_AT_name        : m
DW_AT_decl_file   : 5
DW_AT_decl_line   : 610
DW_AT_type        : <0x20f>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><274>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x34): data_offset
DW_AT_decl_file   : 5
DW_AT_decl_line   : 611
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><283>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2e7): reserved
DW_AT_decl_file   : 5
DW_AT_decl_line   : 612
DW_AT_type        : <0x293>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><293>
Abbrev Number: 16 (DW_TAG_array_type)
DW_AT_type        : <0x15d>
DW_AT_sibling     : <0x2a3>
<2><29c>
Abbrev Number: 17 (DW_TAG_subrange_type)
DW_AT_type        : <0x6e>
DW_AT_upper_bound : 10
<1><2a3>
Abbrev Number: 18 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 5
DW_AT_decl_line   : 658
DW_AT_sibling     : <0x2dc>
<2><2ac>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xed): offset
DW_AT_decl_file   : 5
DW_AT_decl_line   : 659
DW_AT_type        : <0x15d>
<2><2b8>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5a): userptr
DW_AT_decl_file   : 5
DW_AT_decl_line   : 660
DW_AT_type        : <0x5c>
<2><2c4>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa7): planes
DW_AT_decl_file   : 5
DW_AT_decl_line   : 661
DW_AT_type        : <0x2dc>
<2><2d0>
Abbrev Number: 20 (DW_TAG_member)
DW_AT_name        : fd
DW_AT_decl_file   : 5
DW_AT_decl_line   : 662
DW_AT_type        : <0x152>
<1><2dc>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x23c>
<1><2e2>
Abbrev Number: 14 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x62): v4l2_buffer
DW_AT_byte_size   : 80
DW_AT_decl_file   : 5
DW_AT_decl_line   : 646
DW_AT_sibling     : <0x3b1>
<2><2ef>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9b): index
DW_AT_decl_file   : 5
DW_AT_decl_line   : 647
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><2fe>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15c): type
DW_AT_decl_file   : 5
DW_AT_decl_line   : 648
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><30d>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d5): bytesused
DW_AT_decl_file   : 5
DW_AT_decl_line   : 649
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><31c>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14d): flags
DW_AT_decl_file   : 5
DW_AT_decl_line   : 650
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><32b>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d3): field
DW_AT_decl_file   : 5
DW_AT_decl_line   : 651
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><33a>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a): timestamp
DW_AT_decl_file   : 5
DW_AT_decl_line   : 652
DW_AT_type        : <0x92>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><349>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19c): timecode
DW_AT_decl_file   : 5
DW_AT_decl_line   : 653
DW_AT_type        : <0x188>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><358>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x153): sequence
DW_AT_decl_file   : 5
DW_AT_decl_line   : 654
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><367>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xae): memory
DW_AT_decl_file   : 5
DW_AT_decl_line   : 657
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><376>
Abbrev Number: 21 (DW_TAG_member)
DW_AT_name        : m
DW_AT_decl_file   : 5
DW_AT_decl_line   : 663
DW_AT_type        : <0x2a3>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><383>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x113): length
DW_AT_decl_file   : 5
DW_AT_decl_line   : 664
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><392>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe3): reserved2
DW_AT_decl_file   : 5
DW_AT_decl_line   : 665
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><3a1>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2e7): reserved
DW_AT_decl_file   : 5
DW_AT_decl_line   : 666
DW_AT_type        : <0x15d>
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<1><3b1>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x128): struct_v4l2_buffer
DW_AT_decl_file   : 6
DW_AT_decl_line   : 38
DW_AT_type        : <0x2e2>
<1><3bc>
Abbrev Number: 22 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x102): current_wordsize
DW_AT_decl_file   : 7
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><3ca>
Abbrev Number: 22 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x2cc): sysent
DW_AT_decl_file   : 7
DW_AT_decl_line   : 892
DW_AT_type        : <0x135>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><3d8>
Abbrev Number: 22 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1a5): nsyscalls
DW_AT_decl_file   : 7
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><3e6>
Abbrev Number: 23 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x0): mpers_target_var
DW_AT_decl_file   : 6
DW_AT_decl_line   : 47
DW_AT_type        : <0x3b1>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
