<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x213): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1ea): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1d0): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xe1): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x82): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x159): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xca): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1f4): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xef): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1c7): sizetype
<1><6a>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><6c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x174): char
<1><73>
Abbrev Number: 5 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x207): __socklen_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 189
DW_AT_type        : <0x47>
<1><7e>
Abbrev Number: 5 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xf): size_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 212
DW_AT_type        : <0x47>
<1><89>
Abbrev Number: 6 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1fd): socklen_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 274
DW_AT_type        : <0x73>
<1><95>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x9b>
<1><9b>
Abbrev Number: 8 (DW_TAG_const_type)
DW_AT_type        : <0x6c>
<1><a0>
Abbrev Number: 9 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x101): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 4
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xf3>
<2><ac>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x133): nargs
DW_AT_decl_file   : 4
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><ba>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc0): sys_flags
DW_AT_decl_file   : 4
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><c8>
Abbrev Number: 11 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 4
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><d6>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21f): sys_func
DW_AT_decl_file   : 4
DW_AT_decl_line   : 8
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><e4>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb0): sys_name
DW_AT_decl_file   : 4
DW_AT_decl_line   : 9
DW_AT_type        : <0x95>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><f3>
Abbrev Number: 12 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xfe>
<2><fc>
Abbrev Number: 13 (DW_TAG_unspecified_parameters)
<1><fe>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf3>
<1><104>
Abbrev Number: 5 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x166): struct_sysent
DW_AT_decl_file   : 4
DW_AT_decl_line   : 10
DW_AT_type        : <0xa0>
<1><10f>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x115>
<1><115>
Abbrev Number: 8 (DW_TAG_const_type)
DW_AT_type        : <0x104>
<1><11a>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x1f): _Bool
<1><121>
Abbrev Number: 9 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x139): iovec
DW_AT_byte_size   : 8
DW_AT_decl_file   : 5
DW_AT_decl_line   : 43
DW_AT_sibling     : <0x14a>
<2><12d>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x150): iov_base
DW_AT_decl_file   : 5
DW_AT_decl_line   : 45
DW_AT_type        : <0x6a>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><13b>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x25): iov_len
DW_AT_decl_file   : 5
DW_AT_decl_line   : 46
DW_AT_type        : <0x7e>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><14a>
Abbrev Number: 9 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xb9): msghdr
DW_AT_byte_size   : 28
DW_AT_decl_file   : 6
DW_AT_decl_line   : 224
DW_AT_sibling     : <0x1b9>
<2><156>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16): msg_name
DW_AT_decl_file   : 6
DW_AT_decl_line   : 226
DW_AT_type        : <0x6a>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><164>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1de): msg_namelen
DW_AT_decl_file   : 6
DW_AT_decl_line   : 227
DW_AT_type        : <0x89>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><172>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): msg_iov
DW_AT_decl_file   : 6
DW_AT_decl_line   : 229
DW_AT_type        : <0x1b9>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><180>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bc): msg_iovlen
DW_AT_decl_file   : 6
DW_AT_decl_line   : 230
DW_AT_type        : <0x7e>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><18e>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x119): msg_control
DW_AT_decl_file   : 6
DW_AT_decl_line   : 232
DW_AT_type        : <0x6a>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><19c>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x0): msg_controllen
DW_AT_decl_file   : 6
DW_AT_decl_line   : 233
DW_AT_type        : <0x7e>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><1aa>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d): msg_flags
DW_AT_decl_file   : 6
DW_AT_decl_line   : 238
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<1><1b9>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x121>
<1><1bf>
Abbrev Number: 5 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x125): struct_msghdr
DW_AT_decl_file   : 7
DW_AT_decl_line   : 32
DW_AT_type        : <0x14a>
<1><1ca>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x108): current_wordsize
DW_AT_decl_file   : 8
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1d8>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x101): sysent
DW_AT_decl_file   : 8
DW_AT_decl_line   : 892
DW_AT_type        : <0x10f>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1e6>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1b2): nsyscalls
DW_AT_decl_file   : 8
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1f4>
Abbrev Number: 15 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x13f): mpers_target_var
DW_AT_decl_file   : 7
DW_AT_decl_line   : 34
DW_AT_type        : <0x1bf>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 10 0 0 0 	(DW_OP_addr: 10)
