<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1a7): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x33): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0xdb): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x193): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x20f): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x339): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1c4): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x11f): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x2b4): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x3d): sizetype
<1><6a>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x238): char
<1><71>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x77>
<1><77>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0x6a>
<1><7c>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x31c): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xcf>
<2><88>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a1): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><96>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f1): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><a4>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b2>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xda>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><c0>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x7e): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x71>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><cf>
Abbrev Number: 9 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xda>
<2><d8>
Abbrev Number: 10 (DW_TAG_unspecified_parameters)
<1><da>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xcf>
<1><e0>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2de): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x7c>
<1><eb>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf1>
<1><f1>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0xe0>
<1><f6>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x25d): _Bool
<1><fd>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2c6): __s16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 22
DW_AT_type        : <0x24>
<1><108>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x263): __u16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
DW_AT_type        : <0x40>
<1><113>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xb8): __u32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_type        : <0x47>
<1><11e>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x32f): ff_replay
DW_AT_byte_size   : 4
DW_AT_decl_file   : 3
DW_AT_decl_line   : 974
DW_AT_sibling     : <0x14a>
<2><12b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x181): length
DW_AT_decl_file   : 3
DW_AT_decl_line   : 975
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><13a>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x87): delay
DW_AT_decl_file   : 3
DW_AT_decl_line   : 976
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><14a>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x8d): ff_trigger
DW_AT_byte_size   : 4
DW_AT_decl_file   : 3
DW_AT_decl_line   : 984
DW_AT_sibling     : <0x176>
<2><157>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14c): button
DW_AT_decl_file   : 3
DW_AT_decl_line   : 985
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><166>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d5): interval
DW_AT_decl_file   : 3
DW_AT_decl_line   : 986
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><176>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x22c): ff_envelope
DW_AT_byte_size   : 8
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1001
DW_AT_sibling     : <0x1c0>
<2><183>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbe): attack_length
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1002
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><192>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x98): attack_level
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1003
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><1a1>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xac): fade_length
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1004
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1b0>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x188): fade_level
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1005
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<1><1c0>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x15a): ff_constant_effect
DW_AT_byte_size   : 10
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1013
DW_AT_sibling     : <0x1ec>
<2><1cd>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ec): level
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1014
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1dc>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x313): envelope
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1015
DW_AT_type        : <0x176>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><1ec>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xcc): ff_ramp_effect
DW_AT_byte_size   : 12
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1024
DW_AT_sibling     : <0x227>
<2><1f9>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x128): start_level
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1025
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><208>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x177): end_level
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1026
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><217>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x313): envelope
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1027
DW_AT_type        : <0x176>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><227>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x4f): ff_condition_effect
DW_AT_byte_size   : 12
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1040
DW_AT_sibling     : <0x28f>
<2><234>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f2): right_saturation
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1041
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><243>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x303): left_saturation
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1042
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><252>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x346): right_coeff
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1044
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><261>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x0): left_coeff
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1045
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><270>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x394): deadband
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1047
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><27f>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19): center
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1048
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<1><28f>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x20): ff_periodic_effect
DW_AT_byte_size   : 28
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1069
DW_AT_sibling     : <0x315>
<2><29c>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2cc): waveform
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1070
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><2ab>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x153): period
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1071
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><2ba>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16d): magnitude
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1072
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><2c9>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x145): offset
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1073
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><2d8>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6e): phase
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1074
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><2e7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x313): envelope
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1076
DW_AT_type        : <0x176>
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><2f6>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x63): custom_len
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1078
DW_AT_type        : <0x113>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><305>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x323): custom_data
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1079
DW_AT_type        : <0x315>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<1><315>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xfd>
<1><31b>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1e0): ff_rumble_effect
DW_AT_byte_size   : 4
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1090
DW_AT_sibling     : <0x347>
<2><328>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe9): strong_magnitude
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1091
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><337>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x246): weak_magnitude
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1092
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><347>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 28
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1125
DW_AT_sibling     : <0x38d>
<2><350>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x23d): constant
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1126
DW_AT_type        : <0x1c0>
<2><35c>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14): ramp
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1127
DW_AT_type        : <0x1ec>
<2><368>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x46): periodic
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1128
DW_AT_type        : <0x28f>
<2><374>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x222): condition
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1129
DW_AT_type        : <0x38d>
<2><380>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa5): rumble
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1130
DW_AT_type        : <0x31b>
<1><38d>
Abbrev Number: 16 (DW_TAG_array_type)
DW_AT_type        : <0x227>
DW_AT_sibling     : <0x39d>
<2><396>
Abbrev Number: 17 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 1
<1><39d>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1fb): ff_effect
DW_AT_byte_size   : 44
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1118
DW_AT_sibling     : <0x402>
<2><3aa>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1db): type
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1119
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><3b9>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : id
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1120
DW_AT_type        : <0xfd>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><3c7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x74): direction
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1121
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><3d6>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x255): trigger
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1122
DW_AT_type        : <0x14a>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><3e5>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x118): replay
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1123
DW_AT_type        : <0x11e>
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><3f4>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : u
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1131
DW_AT_type        : <0x347>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><402>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x352): struct_ff_effect
DW_AT_decl_file   : 4
DW_AT_decl_line   : 37
DW_AT_type        : <0x39d>
<1><40d>
Abbrev Number: 19 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1b3): current_wordsize
DW_AT_decl_file   : 5
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><41b>
Abbrev Number: 19 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x31c): sysent
DW_AT_decl_file   : 5
DW_AT_decl_line   : 892
DW_AT_type        : <0xeb>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><429>
Abbrev Number: 19 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x205): nsyscalls
DW_AT_decl_file   : 5
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><437>
Abbrev Number: 20 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x134): mpers_target_var
DW_AT_decl_file   : 4
DW_AT_decl_line   : 41
DW_AT_type        : <0x402>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
