<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1b0): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x19d): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x18f): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x9b): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x59): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x101): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x84): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1a7): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xa9): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x186): sizetype
<1><6a>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><6c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x122): char
<1><73>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x79>
<1><79>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x6c>
<1><7e>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xbb): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xd1>
<2><8a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd3): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><98>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x7a): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><a6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b4>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bc): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xdc>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><c2>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x71): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x73>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><d1>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xdc>
<2><da>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><dc>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xd1>
<1><e2>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x114): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x7e>
<1><ed>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf3>
<1><f3>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0xe2>
<1><f8>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x0): _Bool
<1><ff>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 35
DW_AT_sibling     : <0x13f>
<2><107>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : op
DW_AT_decl_file   : 2
DW_AT_decl_line   : 36
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><114>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10e): flags
DW_AT_decl_file   : 2
DW_AT_decl_line   : 37
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><122>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6): datalen
DW_AT_decl_file   : 2
DW_AT_decl_line   : 38
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><130>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6c): data
DW_AT_decl_file   : 2
DW_AT_decl_line   : 39
DW_AT_type        : <0x6a>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><13f>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xea): struct_blkpg_ioctl_arg
DW_AT_decl_file   : 2
DW_AT_decl_line   : 40
DW_AT_type        : <0xff>
<1><14a>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc2): current_wordsize
DW_AT_decl_file   : 3
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><158>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xbb): sysent
DW_AT_decl_file   : 3
DW_AT_decl_line   : 892
DW_AT_type        : <0xed>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><166>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x158): nsyscalls
DW_AT_decl_file   : 3
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><174>
Abbrev Number: 15 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd9): mpers_target_var
DW_AT_decl_file   : 2
DW_AT_decl_line   : 64
DW_AT_type        : <0x13f>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 10 0 0 0 	(DW_OP_addr: 10)
