<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1b4): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1a1): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x18b): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xa8): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x79): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x112): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1cb): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1ab): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xc9): long unsigned int
<1><63>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1c0): __u_quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 56
DW_AT_type        : <0x4e>
<1><6e>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x20): __ino_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 127
DW_AT_type        : <0x63>
<1><79>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x182): sizetype
<1><80>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xbf): __daddr_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 143
DW_AT_type        : <0x2b>
<1><8b>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x135): char
<1><92>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x98>
<1><98>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x8b>
<1><9d>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xdb): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xf0>
<2><a9>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfb): nargs
DW_AT_decl_file   : 2
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b7>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x95): sys_flags
DW_AT_decl_file   : 2
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><c5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 2
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><d3>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb6): sys_func
DW_AT_decl_file   : 2
DW_AT_decl_line   : 8
DW_AT_type        : <0xfb>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><e1>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8c): sys_name
DW_AT_decl_file   : 2
DW_AT_decl_line   : 9
DW_AT_type        : <0x92>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><f0>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xfb>
<2><f9>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><fb>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf0>
<1><101>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x11f): struct_sysent
DW_AT_decl_file   : 2
DW_AT_decl_line   : 10
DW_AT_type        : <0x9d>
<1><10c>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x112>
<1><112>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x101>
<1><117>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x28): _Bool
<1><11e>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x0): ustat
DW_AT_byte_size   : 32
DW_AT_decl_file   : 3
DW_AT_decl_line   : 24
DW_AT_sibling     : <0x163>
<2><12a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x199): f_tfree
DW_AT_decl_file   : 3
DW_AT_decl_line   : 26
DW_AT_type        : <0x80>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><138>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9f): f_tinode
DW_AT_decl_file   : 3
DW_AT_decl_line   : 27
DW_AT_type        : <0x6e>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><146>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe2): f_fname
DW_AT_decl_file   : 3
DW_AT_decl_line   : 28
DW_AT_type        : <0x163>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><154>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x12d): f_fpack
DW_AT_decl_file   : 3
DW_AT_decl_line   : 29
DW_AT_type        : <0x163>
DW_AT_data_member_location: 2 byte block: 23 16 	(DW_OP_plus_uconst: 22)
<1><163>
Abbrev Number: 12 (DW_TAG_array_type)
DW_AT_type        : <0x8b>
DW_AT_sibling     : <0x173>
<2><16c>
Abbrev Number: 13 (DW_TAG_subrange_type)
DW_AT_type        : <0x79>
DW_AT_upper_bound : 5
<1><173>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x13a): struct_ustat
DW_AT_decl_file   : 4
DW_AT_decl_line   : 31
DW_AT_type        : <0x11e>
<1><17e>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xea): current_wordsize
DW_AT_decl_file   : 5
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><18c>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdb): sysent
DW_AT_decl_file   : 5
DW_AT_decl_line   : 892
DW_AT_type        : <0x10c>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><19a>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x178): nsyscalls
DW_AT_decl_file   : 5
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1a8>
Abbrev Number: 15 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x101): mpers_target_var
DW_AT_decl_file   : 4
DW_AT_decl_line   : 34
DW_AT_type        : <0x173>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
