<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1aa): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x2e): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x3b5): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x168): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x244): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1df): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1bc): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0xf3): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x2e7): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x38): sizetype
<1><6a>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><6c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x265): char
<1><73>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x79>
<1><79>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x6c>
<1><7e>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x37b): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xd1>
<2><8a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x321): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><98>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6f): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><a6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b4>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xdc>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><c2>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x55): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x73>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><d1>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xdc>
<2><da>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><dc>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xd1>
<1><e2>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x333): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x7e>
<1><ed>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf3>
<1><f3>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0xe2>
<1><f8>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x26f): _Bool
<1><ff>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2e2): __u8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 20
DW_AT_type        : <0x39>
<1><10a>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x291): __u16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
DW_AT_type        : <0x40>
<1><115>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x327): __s32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_type        : <0x2b>
<1><120>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xaf): __u32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_type        : <0x47>
<1><12b>
Abbrev Number: 13 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x35c): v4l2_preemphasis
DW_AT_byte_size   : 4
DW_AT_decl_file   : 6
DW_AT_decl_line   : 763
DW_AT_sibling     : <0x14b>
<2><138>
Abbrev Number: 14 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x21a): V4L2_PREEMPHASIS_DISABLED
DW_AT_const_value : 0
<2><13e>
Abbrev Number: 14 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x1f7): V4L2_PREEMPHASIS_50_uS
DW_AT_const_value : 1
<2><144>
Abbrev Number: 14 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x89): V4L2_PREEMPHASIS_75_uS
DW_AT_const_value : 2
<1><14b>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xc): v4l2_rect
DW_AT_byte_size   : 16
DW_AT_decl_file   : 3
DW_AT_decl_line   : 205
DW_AT_sibling     : <0x190>
<2><157>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x26a): left
DW_AT_decl_file   : 3
DW_AT_decl_line   : 206
DW_AT_type        : <0x115>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><165>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : top
DW_AT_decl_file   : 3
DW_AT_decl_line   : 207
DW_AT_type        : <0x115>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><173>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd2): width
DW_AT_decl_file   : 3
DW_AT_decl_line   : 208
DW_AT_type        : <0x115>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><181>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d8): height
DW_AT_decl_file   : 3
DW_AT_decl_line   : 209
DW_AT_type        : <0x115>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><190>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x281): v4l2_pix_format
DW_AT_byte_size   : 32
DW_AT_decl_file   : 3
DW_AT_decl_line   : 274
DW_AT_sibling     : <0x216>
<2><19d>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd2): width
DW_AT_decl_file   : 3
DW_AT_decl_line   : 275
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1ac>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d8): height
DW_AT_decl_file   : 3
DW_AT_decl_line   : 276
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1bb>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x41): pixelformat
DW_AT_decl_file   : 3
DW_AT_decl_line   : 277
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><1ca>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x382): field
DW_AT_decl_file   : 3
DW_AT_decl_line   : 278
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><1d9>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe6): bytesperline
DW_AT_decl_file   : 3
DW_AT_decl_line   : 279
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><1e8>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f): sizeimage
DW_AT_decl_file   : 3
DW_AT_decl_line   : 280
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><1f7>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x125): colorspace
DW_AT_decl_file   : 3
DW_AT_decl_line   : 281
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><206>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x0): priv
DW_AT_decl_file   : 3
DW_AT_decl_line   : 282
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<1><216>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0x120>
DW_AT_sibling     : <0x226>
<2><21f>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 1
<1><226>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x388): v4l2_clip
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 745
DW_AT_sibling     : <0x250>
<2><233>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : c
DW_AT_decl_file   : 3
DW_AT_decl_line   : 746
DW_AT_type        : <0x14b>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><240>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x29): next
DW_AT_decl_file   : 3
DW_AT_decl_line   : 747
DW_AT_type        : <0x250>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><250>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x226>
<1><256>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xc6): v4l2_window
DW_AT_byte_size   : 40
DW_AT_decl_file   : 3
DW_AT_decl_line   : 750
DW_AT_sibling     : <0x2cb>
<2><263>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : w
DW_AT_decl_file   : 3
DW_AT_decl_line   : 751
DW_AT_type        : <0x14b>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><270>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x382): field
DW_AT_decl_file   : 3
DW_AT_decl_line   : 752
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><27f>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x39c): chromakey
DW_AT_decl_file   : 3
DW_AT_decl_line   : 753
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><28e>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3af): clips
DW_AT_decl_file   : 3
DW_AT_decl_line   : 754
DW_AT_type        : <0x250>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><29d>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbc): clipcount
DW_AT_decl_file   : 3
DW_AT_decl_line   : 755
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><2ac>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb5): bitmap
DW_AT_decl_file   : 3
DW_AT_decl_line   : 756
DW_AT_type        : <0x6a>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><2bb>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x130): global_alpha
DW_AT_decl_file   : 3
DW_AT_decl_line   : 757
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<1><2cb>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0x120>
DW_AT_sibling     : <0x2db>
<2><2d4>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 7
<1><2db>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x79): v4l2_vbi_format
DW_AT_byte_size   : 44
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1541
DW_AT_sibling     : <0x361>
<2><2e8>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x257): sampling_rate
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1542
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><2f7>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10d): offset
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1543
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><306>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5e): samples_per_line
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1544
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><315>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3c3): sample_format
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1545
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><324>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x23e): start
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1546
DW_AT_type        : <0x361>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><333>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32d): count
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1547
DW_AT_type        : <0x216>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><342>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b6): flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1548
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><351>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3a6): reserved
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1549
DW_AT_type        : <0x216>
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<1><361>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0x115>
DW_AT_sibling     : <0x371>
<2><36a>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 1
<1><371>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x18c): v4l2_sliced_vbi_format
DW_AT_byte_size   : 112
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1563
DW_AT_sibling     : <0x3bb>
<2><37e>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x275): service_set
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1564
DW_AT_type        : <0x10a>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><38d>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x36d): service_lines
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1569
DW_AT_type        : <0x3bb>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><39c>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4d): io_size
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1570
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><3ab>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3a6): reserved
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1571
DW_AT_type        : <0x216>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<1><3bb>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0x10a>
DW_AT_sibling     : <0x3d1>
<2><3c4>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 1
<2><3ca>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 23
<1><3d1>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x176): v4l2_plane_pix_format
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1664
DW_AT_sibling     : <0x40c>
<2><3de>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f): sizeimage
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1665
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><3ed>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe6): bytesperline
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1666
DW_AT_type        : <0x10a>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><3fc>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3a6): reserved
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1667
DW_AT_type        : <0x40c>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<1><40c>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0x10a>
DW_AT_sibling     : <0x41c>
<2><415>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 6
<1><41c>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x151): v4l2_pix_format_mplane
DW_AT_byte_size   : 192
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1680
DW_AT_sibling     : <0x4a4>
<2><429>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd2): width
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1681
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><438>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d8): height
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1682
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><447>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x41): pixelformat
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1683
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><456>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x382): field
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1684
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><465>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x125): colorspace
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1685
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><474>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x392): plane_fmt
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1687
DW_AT_type        : <0x4a4>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><483>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ec): num_planes
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1688
DW_AT_type        : <0xff>
DW_AT_data_member_location: 3 byte block: 23 b4 1 	(DW_OP_plus_uconst: 180)
<2><493>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3a6): reserved
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1689
DW_AT_type        : <0x4b4>
DW_AT_data_member_location: 3 byte block: 23 b5 1 	(DW_OP_plus_uconst: 181)
<1><4a4>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0x3d1>
DW_AT_sibling     : <0x4b4>
<2><4ad>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 7
<1><4b4>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0xff>
DW_AT_sibling     : <0x4c4>
<2><4bd>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 10
<1><4c4>
Abbrev Number: 20 (DW_TAG_union_type)
DW_AT_byte_size   : 200
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1704
DW_AT_sibling     : <0x516>
<2><4cd>
Abbrev Number: 21 (DW_TAG_member)
DW_AT_name        : pix
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1705
DW_AT_type        : <0x190>
<2><4d9>
Abbrev Number: 22 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5): pix_mp
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1706
DW_AT_type        : <0x41c>
<2><4e5>
Abbrev Number: 21 (DW_TAG_member)
DW_AT_name        : win
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1707
DW_AT_type        : <0x256>
<2><4f1>
Abbrev Number: 21 (DW_TAG_member)
DW_AT_name        : vbi
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1708
DW_AT_type        : <0x2db>
<2><4fd>
Abbrev Number: 22 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a3): sliced
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1709
DW_AT_type        : <0x371>
<2><509>
Abbrev Number: 22 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa6): raw_data
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1710
DW_AT_type        : <0x516>
<1><516>
Abbrev Number: 17 (DW_TAG_array_type)
DW_AT_type        : <0xff>
DW_AT_sibling     : <0x526>
<2><51f>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 199
<1><526>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x20e): v4l2_format
DW_AT_byte_size   : 204
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1702
DW_AT_sibling     : <0x552>
<2><533>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d3): type
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1703
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><542>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : fmt
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1711
DW_AT_type        : <0x4c4>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><552>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x13d): v4l2_create_buffers
DW_AT_byte_size   : 248
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1843
DW_AT_sibling     : <0x5ac>
<2><55f>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa0): index
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1844
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><56e>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32d): count
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1845
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><57d>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd8): memory
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1846
DW_AT_type        : <0x120>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><58c>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdf): format
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1847
DW_AT_type        : <0x526>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><59b>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3a6): reserved
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1848
DW_AT_type        : <0x2cb>
DW_AT_data_member_location: 3 byte block: 23 d8 1 	(DW_OP_plus_uconst: 216)
<1><5ac>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x341): struct_v4l2_create_buffers
DW_AT_decl_file   : 4
DW_AT_decl_line   : 39
DW_AT_type        : <0x552>
<1><5b7>
Abbrev Number: 23 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x114): current_wordsize
DW_AT_decl_file   : 5
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><5c5>
Abbrev Number: 23 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x37b): sysent
DW_AT_decl_file   : 5
DW_AT_decl_line   : 892
DW_AT_type        : <0xed>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><5d3>
Abbrev Number: 23 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x234): nsyscalls
DW_AT_decl_file   : 5
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><5e1>
Abbrev Number: 24 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfc): mpers_target_var
DW_AT_decl_file   : 4
DW_AT_decl_line   : 47
DW_AT_type        : <0x5ac>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
