<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x20f): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x158): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1ee): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xfd): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x9a): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x173): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xde): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x206): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x10b): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1e5): sizetype
<1><6a>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x70>
<1><70>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1a5): char
<1><77>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x7d>
<1><7d>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0x70>
<1><82>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x11d): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xd5>
<2><8e>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x152): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><9c>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd4): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><aa>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b8>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x220): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><c6>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb3): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x77>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><d5>
Abbrev Number: 9 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xe0>
<2><de>
Abbrev Number: 10 (DW_TAG_unspecified_parameters)
<1><e0>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xd5>
<1><e6>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x197): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x82>
<1><f1>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf7>
<1><f7>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0xe6>
<1><fc>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0xad): _Bool
<1><103>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x124): __s32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_type        : <0x2b>
<1><10e>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x32): __u32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_type        : <0x47>
<1><119>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x24e): __s64
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
DW_AT_type        : <0x32>
<1><124>
Abbrev Number: 12 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x162): v4l2_preemphasis
DW_AT_byte_size   : 4
DW_AT_decl_file   : 6
DW_AT_decl_line   : 763
DW_AT_sibling     : <0x144>
<2><131>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x0): V4L2_PREEMPHASIS_DISABLED
DW_AT_const_value : 0
<2><137>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x180): V4L2_PREEMPHASIS_50_uS
DW_AT_const_value : 1
<2><13d>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x13b): V4L2_PREEMPHASIS_75_uS
DW_AT_const_value : 2
<1><144>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1225
DW_AT_sibling     : <0x172>
<2><14d>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x38): value
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1226
DW_AT_type        : <0x103>
<2><159>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf5): value64
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1227
DW_AT_type        : <0x119>
<2><165>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbc): string
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1228
DW_AT_type        : <0x6a>
<1><172>
Abbrev Number: 16 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x3e): v4l2_ext_control
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1221
DW_AT_sibling     : <0x1b4>
<2><17f>
Abbrev Number: 17 (DW_TAG_member)
DW_AT_name        : id
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1222
DW_AT_type        : <0x10e>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><18d>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21b): size
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1223
DW_AT_type        : <0x10e>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><19c>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fc): reserved2
DW_AT_decl_file   : 3
DW_AT_decl_line   : 1224
DW_AT_type        : <0x1b4>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><1ab>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_type        : <0x144>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><1b4>
Abbrev Number: 20 (DW_TAG_array_type)
DW_AT_type        : <0x10e>
DW_AT_sibling     : <0x1c4>
<2><1bd>
Abbrev Number: 21 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 0
<1><1c4>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1a): struct_v4l2_ext_control
DW_AT_decl_file   : 4
DW_AT_decl_line   : 40
DW_AT_type        : <0x172>
<1><1cf>
Abbrev Number: 22 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x12a): current_wordsize
DW_AT_decl_file   : 5
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1dd>
Abbrev Number: 22 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x11d): sysent
DW_AT_decl_file   : 5
DW_AT_decl_line   : 892
DW_AT_type        : <0xf1>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1eb>
Abbrev Number: 22 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1db): nsyscalls
DW_AT_decl_file   : 5
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1f9>
Abbrev Number: 23 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc3): mpers_target_var
DW_AT_decl_file   : 4
DW_AT_decl_line   : 47
DW_AT_type        : <0x1c4>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 10 0 0 0 	(DW_OP_addr: 10)
