<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x178): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x18d): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x133): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xfc): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x165): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x197): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xaf): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x111): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x9d): long unsigned int
<1><63>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x11): __quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
DW_AT_type        : <0x32>
<1><6e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x184): sizetype
<1><75>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x141): __time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 139
DW_AT_type        : <0x63>
<1><80>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0xf7): char
<1><87>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x10a): time_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 75
DW_AT_type        : <0x75>
<1><92>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x98>
<1><98>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x80>
<1><9d>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x14a): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xf0>
<2><a9>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x97): nargs
DW_AT_decl_file   : 3
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b7>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x123): sys_flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><c5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 3
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><d3>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11a): sys_func
DW_AT_decl_file   : 3
DW_AT_decl_line   : 8
DW_AT_type        : <0xfb>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><e1>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a): sys_name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 9
DW_AT_type        : <0x92>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><f0>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xfb>
<2><f9>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><fb>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf0>
<1><101>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x23): struct_sysent
DW_AT_decl_file   : 3
DW_AT_decl_line   : 10
DW_AT_type        : <0x9d>
<1><10c>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x112>
<1><112>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x101>
<1><117>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x12d): _Bool
<1><11e>
Abbrev Number: 12 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x0): current_wordsize
DW_AT_decl_file   : 4
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><12c>
Abbrev Number: 12 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x14a): sysent
DW_AT_decl_file   : 4
DW_AT_decl_line   : 892
DW_AT_type        : <0x10c>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><13a>
Abbrev Number: 12 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x31): nsyscalls
DW_AT_decl_file   : 4
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><148>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x86): mpers_target_var
DW_AT_decl_file   : 5
DW_AT_decl_line   : 31
DW_AT_type        : <0x87>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
