<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1c0): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1a2): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x18a): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xc3): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x74): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x126): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xac): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1ac): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xd1): long unsigned int
<1><63>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x11d): __quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
DW_AT_type        : <0x32>
<1><6e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x181): sizetype
<1><75>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x198): __clock_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 135
DW_AT_type        : <0x63>
<1><80>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x141): char
<1><87>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x9a): clock_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 59
DW_AT_type        : <0x75>
<1><92>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x98>
<1><98>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x80>
<1><9d>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xe3): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xf0>
<2><a9>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x106): nargs
DW_AT_decl_file   : 3
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b7>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa2): sys_flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><c5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 3
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><d3>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cc): sys_func
DW_AT_decl_file   : 3
DW_AT_decl_line   : 8
DW_AT_type        : <0xfb>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><e1>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x91): sys_name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 9
DW_AT_type        : <0x92>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><f0>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xfb>
<2><f9>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><fb>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf0>
<1><101>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x133): struct_sysent
DW_AT_decl_file   : 3
DW_AT_decl_line   : 10
DW_AT_type        : <0x9d>
<1><10c>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x112>
<1><112>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x101>
<1><117>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x1d): _Bool
<1><11e>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : tms
DW_AT_byte_size   : 32
DW_AT_decl_file   : 4
DW_AT_decl_line   : 34
DW_AT_sibling     : <0x163>
<2><12a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13): tms_utime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
DW_AT_type        : <0x87>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><138>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x87): tms_stime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 37
DW_AT_type        : <0x87>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><146>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xea): tms_cutime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 39
DW_AT_type        : <0x87>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><154>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b5): tms_cstime
DW_AT_decl_file   : 4
DW_AT_decl_line   : 40
DW_AT_type        : <0x87>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<1><163>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x23): tms_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 36
DW_AT_type        : <0x11e>
<1><16e>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf5): current_wordsize
DW_AT_decl_file   : 6
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><17c>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe3): sysent
DW_AT_decl_file   : 6
DW_AT_decl_line   : 892
DW_AT_type        : <0x10c>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><18a>
Abbrev Number: 13 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x177): nsyscalls
DW_AT_decl_file   : 6
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><198>
Abbrev Number: 14 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x10c): mpers_target_var
DW_AT_decl_file   : 5
DW_AT_decl_line   : 37
DW_AT_type        : <0x163>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
