<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1b5): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x179): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x165): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x64): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x6): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x121): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x44): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1ac): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x72): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x15c): sizetype
<1><6a>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x13c): char
<1><71>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x77>
<1><77>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0x6a>
<1><7c>
Abbrev Number: 6 (DW_TAG_array_type)
DW_AT_type        : <0x6a>
DW_AT_sibling     : <0x8c>
<2><85>
Abbrev Number: 7 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 0
<1><8c>
Abbrev Number: 8 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x141): __kernel_ulong_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 15
DW_AT_type        : <0x5c>
<1><97>
Abbrev Number: 8 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x19d): kernel_ulong_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 36
DW_AT_type        : <0x8c>
<1><a2>
Abbrev Number: 9 (DW_TAG_structure_type)
DW_AT_byte_size   : 12
DW_AT_decl_file   : 2
DW_AT_decl_line   : 50
DW_AT_sibling     : <0xe3>
<2><aa>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x173): d_ino
DW_AT_decl_file   : 2
DW_AT_decl_line   : 51
DW_AT_type        : <0x97>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b8>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11b): d_off
DW_AT_decl_file   : 2
DW_AT_decl_line   : 52
DW_AT_type        : <0x97>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><c6>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5b): d_reclen
DW_AT_decl_file   : 2
DW_AT_decl_line   : 53
DW_AT_type        : <0x40>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><d4>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x22): d_name
DW_AT_decl_file   : 2
DW_AT_decl_line   : 54
DW_AT_type        : <0x7c>
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<1><e3>
Abbrev Number: 8 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1c1): kernel_dirent
DW_AT_decl_file   : 2
DW_AT_decl_line   : 55
DW_AT_type        : <0xa2>
<1><ee>
Abbrev Number: 11 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x84): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 3
DW_AT_decl_line   : 4
DW_AT_sibling     : <0x141>
<2><fa>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9c): nargs
DW_AT_decl_file   : 3
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><108>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3a): sys_flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><116>
Abbrev Number: 12 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 3
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><124>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cf): sys_func
DW_AT_decl_file   : 3
DW_AT_decl_line   : 8
DW_AT_type        : <0x14c>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><132>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19): sys_name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 9
DW_AT_type        : <0x71>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><141>
Abbrev Number: 13 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0x14c>
<2><14a>
Abbrev Number: 14 (DW_TAG_unspecified_parameters)
<1><14c>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x141>
<1><152>
Abbrev Number: 8 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x12e): struct_sysent
DW_AT_decl_file   : 3
DW_AT_decl_line   : 10
DW_AT_type        : <0xee>
<1><15d>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x163>
<1><163>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0x152>
<1><168>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x0): _Bool
<1><16f>
Abbrev Number: 15 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x8b): current_wordsize
DW_AT_decl_file   : 4
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><17d>
Abbrev Number: 15 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x84): sysent
DW_AT_decl_file   : 4
DW_AT_decl_line   : 892
DW_AT_type        : <0x15d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><18b>
Abbrev Number: 15 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x152): nsyscalls
DW_AT_decl_file   : 4
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><199>
Abbrev Number: 16 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x29): mpers_target_var
DW_AT_decl_file   : 5
DW_AT_decl_line   : 35
DW_AT_type        : <0xe3>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
