<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x157): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 39
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x1a2): msgbuf_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 38
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x19b): msgbuf
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 43
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x168): mtype
DW_AT_type        : <0x61>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 44
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x187): mtext
DW_AT_type        : <0x73>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 45
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><61>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x6c>
DW_AT_name        : (indirect string, offset: 0x177): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><6c>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x16e): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><73>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0x80>
<2><78>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0x87>
DW_AT_lower_bound : 0
DW_AT_count       : 1
<1><80>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x18d): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><87>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x192): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
