<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x8f): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 5
DW_AT_decl_line   : 49
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x238): msqid_ds_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 42
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x22d): msqid64_ds
DW_AT_byte_size   : 76
DW_AT_decl_file   : 4
DW_AT_decl_line   : 22
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa0): msg_perm
DW_AT_type        : <0xde>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 23
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): msg_stime
DW_AT_type        : <0x1ef>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c3): msg_rtime
DW_AT_type        : <0x1ef>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cd): msg_ctime
DW_AT_type        : <0x1ef>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d7): msg_cbytes
DW_AT_type        : <0x1dd>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e2): msg_qnum
DW_AT_type        : <0x1dd>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1eb): msg_qbytes
DW_AT_type        : <0x1dd>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f6): msg_lspid
DW_AT_type        : <0x20c>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20f): msg_lrpid
DW_AT_type        : <0x20c>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x219): __unused4
DW_AT_type        : <0x1dd>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x223): __unused5
DW_AT_type        : <0x1dd>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<1><de>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x185): ipc64_perm
DW_AT_byte_size   : 36
DW_AT_decl_file   : 2
DW_AT_decl_line   : 21
<2><e6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa9): key
DW_AT_type        : <0x181>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 22
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><f4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc0): uid
DW_AT_type        : <0x193>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><102>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe2): gid
DW_AT_type        : <0x1a5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><110>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf7): cuid
DW_AT_type        : <0x193>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><11e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfc): cgid
DW_AT_type        : <0x1a5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><12c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x101): mode
DW_AT_type        : <0x1b0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><13a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x116): __pad1
DW_AT_type        : <0x1bb>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><148>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x134): seq
DW_AT_type        : <0x1d6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><156>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x147): __pad2
DW_AT_type        : <0x1d6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 1a 	(DW_OP_plus_uconst: 26)
<2><164>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14e): __unused1
DW_AT_type        : <0x1dd>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><172>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17b): __unused2
DW_AT_type        : <0x1dd>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<1><181>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x18c>
DW_AT_name        : (indirect string, offset: 0xb1): __kernel_key_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><18c>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xad): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><193>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x19e>
DW_AT_name        : (indirect string, offset: 0xd1): __kernel_uid32_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 49
<1><19e>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc4): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><1a5>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x19e>
DW_AT_name        : (indirect string, offset: 0xe6): __kernel_gid32_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 50
<1><1b0>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x19e>
DW_AT_name        : (indirect string, offset: 0x106): __kernel_mode_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 30
<1><1bb>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0x1c8>
<2><1c0>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0x1cf>
DW_AT_lower_bound : 0
DW_AT_count       : 0
<1><1c8>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x11d): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1cf>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x12b): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><1d6>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x138): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><1dd>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1e8>
DW_AT_name        : (indirect string, offset: 0x16a): __kernel_ulong_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 24
<1><1e8>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x158): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><1ef>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1fa>
DW_AT_name        : (indirect string, offset: 0x1b3): __kernel_time_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 77
<1><1fa>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x205>
DW_AT_name        : (indirect string, offset: 0x1a3): __kernel_long_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 23
<1><205>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x19a): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><20c>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x18c>
DW_AT_name        : (indirect string, offset: 0x200): __kernel_pid_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 33
