<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x157): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 38
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x261): rusage_t
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x25a): rusage
DW_AT_byte_size   : 72
DW_AT_decl_file   : 3
DW_AT_decl_line   : 27
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x168): ru_utime
DW_AT_type        : <0x125>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c6): ru_stime
DW_AT_type        : <0x125>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cf): ru_maxrss
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d9): ru_ixrss
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><7c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e2): ru_idrss
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1eb): ru_isrss
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><98>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f4): ru_minflt
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><a6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fe): ru_majflt
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><b4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x208): ru_nswap
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x211): ru_inblock
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><d0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21c): ru_oublock
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><de>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x227): ru_msgsnd
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><ec>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x231): ru_msgrcv
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><fa>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x23b): ru_nsignals
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><108>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x247): ru_nvcsw
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><116>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x250): ru_nivcsw
DW_AT_type        : <0x155>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 43
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<1><125>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1be): timeval
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
<2><12d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x171): tv_sec
DW_AT_type        : <0x14a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><13b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a1): tv_usec
DW_AT_type        : <0x167>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><14a>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x155>
DW_AT_name        : (indirect string, offset: 0x191): __kernel_time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 77
<1><155>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x160>
DW_AT_name        : (indirect string, offset: 0x181): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><160>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x178): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><167>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x155>
DW_AT_name        : (indirect string, offset: 0x1a9): __kernel_suseconds_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
