<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x8d): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 38
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x197): rusage_t
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x190): rusage
DW_AT_byte_size   : 72
DW_AT_decl_file   : 3
DW_AT_decl_line   : 27
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9e): ru_utime
DW_AT_type        : <0x124>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfc): ru_stime
DW_AT_type        : <0x124>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x105): ru_maxrss
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10f): ru_ixrss
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x118): ru_idrss
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x121): ru_isrss
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x12a): ru_minflt
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x134): ru_majflt
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13e): ru_nswap
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x147): ru_inblock
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x152): ru_oublock
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><dd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15d): ru_msgsnd
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><eb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x167): ru_msgrcv
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><f9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x171): ru_nsignals
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><107>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17d): ru_nvcsw
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><115>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x186): ru_nivcsw
DW_AT_type        : <0x154>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 43
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<1><124>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xf4): timeval
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
<2><12c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa7): tv_sec
DW_AT_type        : <0x149>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><13a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd7): tv_usec
DW_AT_type        : <0x166>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><149>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x154>
DW_AT_name        : (indirect string, offset: 0xc7): __kernel_time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 77
<1><154>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x15f>
DW_AT_name        : (indirect string, offset: 0xb7): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><15f>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xae): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><166>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x154>
DW_AT_name        : (indirect string, offset: 0xdf): __kernel_suseconds_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
