<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x92): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x151): sample_struct
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 1248
DW_AT_decl_file   : 1
DW_AT_decl_line   : 2
<2><40>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa3): s
DW_AT_type        : <0x4e>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 21
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><4e>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 480
DW_AT_decl_file   : 1
DW_AT_decl_line   : 3
<3><53>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa5): p
DW_AT_type        : <0x1ca>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><61>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa7): sc
DW_AT_type        : <0x1cb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<3><6f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaf): ss
DW_AT_type        : <0x1d2>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<3><7d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb8): uc
DW_AT_type        : <0x1d9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<3><8b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc9): si
DW_AT_type        : <0x1e0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<3><99>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd0): ui
DW_AT_type        : <0x1e7>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 11
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<3><a7>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe0): sl
DW_AT_type        : <0x1ee>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 12
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<3><b5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xec): us
DW_AT_type        : <0x1f5>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 13
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<3><c3>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfe): sll
DW_AT_type        : <0x1fc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 15
Unknown AT value: 88: 8
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<3><d2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x110): ull
DW_AT_type        : <0x203>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 16
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<3><e0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x12b): ul
DW_AT_type        : <0x20a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 17
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<3><ee>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x140): asl
DW_AT_type        : <0x211>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 18
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<3><fc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14d): f
DW_AT_type        : <0x1cb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 19
DW_AT_data_member_location: 3 byte block: 23 d8 3 	(DW_OP_plus_uconst: 472)
<2><10c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14f): u
DW_AT_type        : <0x233>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_data_member_location: 3 byte block: 23 e0 3 	(DW_OP_plus_uconst: 480)
<2><11b>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 128
DW_AT_decl_file   : 1
DW_AT_decl_line   : 22
<3><11f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfe): sll
DW_AT_type        : <0x1fc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><12d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x110): ull
DW_AT_type        : <0x203>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><13b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa5): p
DW_AT_type        : <0x1ca>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><149>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe0): sl
DW_AT_type        : <0x1ee>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><157>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x12b): ul
DW_AT_type        : <0x20a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><165>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc9): si
DW_AT_type        : <0x1e0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><173>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd0): ui
DW_AT_type        : <0x1e7>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><181>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaf): ss
DW_AT_type        : <0x247>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><18f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xec): us
DW_AT_type        : <0x25b>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><19d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa7): sc
DW_AT_type        : <0x1cb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><1ab>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb8): uc
DW_AT_type        : <0x1d9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1ba>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14d): f
DW_AT_type        : <0x268>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_data_member_location: 3 byte block: 23 e0 9 	(DW_OP_plus_uconst: 1248)
<1><1ca>
Abbrev Number: 8 (DW_TAG_pointer_type)
<1><1cb>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xaa): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1d2>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xb2): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><1d9>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xbb): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1e0>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xcc): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><1e7>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xd3): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><1ee>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xe3): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><1f5>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xef): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><1fc>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x102): long long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 8
<1><203>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x114): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><20a>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x12e): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><211>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1ee>
<2><216>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 3
<2><21d>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 5
<2><224>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 7
<1><22c>
Abbrev Number: 12 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x144): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><233>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x11b>
<2><238>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 3
<2><23f>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><247>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1d2>
<2><24c>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 7
<2><253>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 9
<1><25b>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1f5>
<2><260>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 4
<1><268>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1d2>
<2><26d>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22c>
DW_AT_lower_bound : 0
DW_AT_count       : 0
