<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15c): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x21b): sample_struct
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 1248
DW_AT_decl_file   : 1
DW_AT_decl_line   : 2
<2><41>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16d): s
DW_AT_type        : <0x4f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 21
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><4f>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 480
DW_AT_decl_file   : 1
DW_AT_decl_line   : 3
<3><54>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16f): p
DW_AT_type        : <0x1cb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><62>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x171): sc
DW_AT_type        : <0x1cc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<3><70>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): ss
DW_AT_type        : <0x1d3>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<3><7e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x182): uc
DW_AT_type        : <0x1da>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<3><8c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x193): si
DW_AT_type        : <0x1e1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<3><9a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19a): ui
DW_AT_type        : <0x1e8>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 11
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<3><a8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1aa): sl
DW_AT_type        : <0x1ef>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 12
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<3><b6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b6): us
DW_AT_type        : <0x1f6>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 13
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<3><c4>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c8): sll
DW_AT_type        : <0x1fd>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 15
Unknown AT value: 88: 8
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<3><d3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1da): ull
DW_AT_type        : <0x204>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 16
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<3><e1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f5): ul
DW_AT_type        : <0x20b>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 17
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<3><ef>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20a): asl
DW_AT_type        : <0x212>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 18
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<3><fd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x217): f
DW_AT_type        : <0x1cc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 19
DW_AT_data_member_location: 3 byte block: 23 d8 3 	(DW_OP_plus_uconst: 472)
<2><10d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x219): u
DW_AT_type        : <0x234>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_data_member_location: 3 byte block: 23 e0 3 	(DW_OP_plus_uconst: 480)
<2><11c>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 128
DW_AT_decl_file   : 1
DW_AT_decl_line   : 22
<3><120>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c8): sll
DW_AT_type        : <0x1fd>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><12e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1da): ull
DW_AT_type        : <0x204>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><13c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16f): p
DW_AT_type        : <0x1cb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><14a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1aa): sl
DW_AT_type        : <0x1ef>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><158>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f5): ul
DW_AT_type        : <0x20b>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><166>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x193): si
DW_AT_type        : <0x1e1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><174>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19a): ui
DW_AT_type        : <0x1e8>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><182>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): ss
DW_AT_type        : <0x248>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><190>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b6): us
DW_AT_type        : <0x25c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><19e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x171): sc
DW_AT_type        : <0x1cc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><1ac>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x182): uc
DW_AT_type        : <0x1da>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1bb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x217): f
DW_AT_type        : <0x269>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_data_member_location: 3 byte block: 23 e0 9 	(DW_OP_plus_uconst: 1248)
<1><1cb>
Abbrev Number: 8 (DW_TAG_pointer_type)
<1><1cc>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x174): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1d3>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x17c): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><1da>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x185): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1e1>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x196): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><1e8>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x19d): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><1ef>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ad): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><1f6>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1b9): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><1fd>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1cc): long long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 8
<1><204>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1de): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><20b>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1f8): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><212>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1ef>
<2><217>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 3
<2><21e>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 5
<2><225>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 7
<1><22d>
Abbrev Number: 12 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x20e): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><234>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x11c>
<2><239>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 3
<2><240>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><248>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1d3>
<2><24d>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 7
<2><254>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 9
<1><25c>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1f6>
<2><261>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 4
<1><269>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x1d3>
<2><26e>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x22d>
DW_AT_lower_bound : 0
DW_AT_count       : 0
