<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x8f): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 6
DW_AT_decl_line   : 49
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x233): shmid_ds_t
DW_AT_decl_file   : 6
DW_AT_decl_line   : 42
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x228): shmid64_ds
DW_AT_byte_size   : 72
DW_AT_decl_file   : 4
DW_AT_decl_line   : 22
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa0): shm_perm
DW_AT_type        : <0xd0>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 23
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): shm_segsz
DW_AT_type        : <0x1e1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a1): shm_atime
DW_AT_type        : <0x1ec>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d4): shm_dtime
DW_AT_type        : <0x1ec>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1de): shm_ctime
DW_AT_type        : <0x1ec>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e8): shm_cpid
DW_AT_type        : <0x209>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x200): shm_lpid
DW_AT_type        : <0x209>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x209): shm_nattch
DW_AT_type        : <0x1cf>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x214): __unused4
DW_AT_type        : <0x1cf>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21e): __unused5
DW_AT_type        : <0x1cf>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<1><d0>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x185): ipc64_perm
DW_AT_byte_size   : 36
DW_AT_decl_file   : 2
DW_AT_decl_line   : 21
<2><d8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa9): key
DW_AT_type        : <0x173>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 22
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><e6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc0): uid
DW_AT_type        : <0x185>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><f4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe2): gid
DW_AT_type        : <0x197>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><102>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf7): cuid
DW_AT_type        : <0x185>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><110>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfc): cgid
DW_AT_type        : <0x197>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><11e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x101): mode
DW_AT_type        : <0x1a2>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><12c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x116): __pad1
DW_AT_type        : <0x1ad>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><13a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x134): seq
DW_AT_type        : <0x1c8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><148>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x147): __pad2
DW_AT_type        : <0x1c8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 1a 	(DW_OP_plus_uconst: 26)
<2><156>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14e): __unused1
DW_AT_type        : <0x1cf>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><164>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17b): __unused2
DW_AT_type        : <0x1cf>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<1><173>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x17e>
DW_AT_name        : (indirect string, offset: 0xb1): __kernel_key_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><17e>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xad): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><185>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x190>
DW_AT_name        : (indirect string, offset: 0xd1): __kernel_uid32_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 49
<1><190>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc4): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><197>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x190>
DW_AT_name        : (indirect string, offset: 0xe6): __kernel_gid32_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 50
<1><1a2>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x190>
DW_AT_name        : (indirect string, offset: 0x106): __kernel_mode_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 30
<1><1ad>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0x1ba>
<2><1b2>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0x1c1>
DW_AT_lower_bound : 0
DW_AT_count       : 0
<1><1ba>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x11d): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1c1>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x12b): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><1c8>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x138): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><1cf>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1da>
DW_AT_name        : (indirect string, offset: 0x16a): __kernel_ulong_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 24
<1><1da>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x158): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><1e1>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x190>
DW_AT_name        : (indirect string, offset: 0x19a): size_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 62
<1><1ec>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1f7>
DW_AT_name        : (indirect string, offset: 0x1c4): __kernel_time_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 77
<1><1f7>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x202>
DW_AT_name        : (indirect string, offset: 0x1b4): __kernel_long_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 23
<1><202>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ab): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><209>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x17e>
DW_AT_name        : (indirect string, offset: 0x1f1): __kernel_pid_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 33
