<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x8c): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 39
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0xd8): stack_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 97
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xcc): sigaltstack
DW_AT_byte_size   : 12
DW_AT_decl_file   : 1
DW_AT_decl_line   : 93
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9d): ss_sp
DW_AT_type        : <0x6e>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 94
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa3): ss_flags
DW_AT_type        : <0x6f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 95
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb0): ss_size
DW_AT_type        : <0x76>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 96
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><6e>
Abbrev Number: 6 (DW_TAG_pointer_type)
<1><6f>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xac): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><76>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x81>
DW_AT_name        : (indirect string, offset: 0xc5): size_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 62
<1><81>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xb8): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
