<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x160): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 2
DW_AT_decl_line   : 36
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x1c0): strace_aio_sigset
DW_AT_decl_file   : 2
DW_AT_decl_line   : 34
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
<2><40>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x171): sigmask
DW_AT_type        : <0x5d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><4e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a1): sigsetsize
DW_AT_type        : <0x9b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><5d>
Abbrev Number: 6 (DW_TAG_pointer_type)
DW_AT_type        : <0x62>
<1><62>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x6d>
DW_AT_name        : (indirect string, offset: 0x198): sigset_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 79
<1><6d>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 1
DW_AT_decl_line   : 77
<2><71>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): sig
DW_AT_type        : <0x80>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 78
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><80>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0x8d>
<2><85>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0x94>
DW_AT_lower_bound : 0
DW_AT_count       : 1
<1><8d>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x17d): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><94>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x18f): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><9b>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xa6>
DW_AT_name        : (indirect string, offset: 0x1b9): size_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 62
<1><a6>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ac): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
