<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x93): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x11d): struct_flock64
DW_AT_decl_file   : 4
DW_AT_decl_line   : 34
<1><3b>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x46>
DW_AT_name        : (indirect string, offset: 0x107): struct_kernel_flock64
DW_AT_decl_file   : 3
DW_AT_decl_line   : 43
<1><46>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xff): flock64
DW_AT_byte_size   : 32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 161
<2><4e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa4): l_type
DW_AT_type        : <0x95>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 162
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><5c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb1): l_whence
DW_AT_type        : <0x95>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 163
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><6a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xba): l_start
DW_AT_type        : <0x9c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 164
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><78>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe0): l_len
DW_AT_type        : <0x9c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 165
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><86>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe6): l_pid
DW_AT_type        : <0xae>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 166
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<1><95>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xab): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><9c>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xa7>
DW_AT_name        : (indirect string, offset: 0xd0): __kernel_loff_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 76
<1><a7>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc2): long long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 8
<1><ae>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xb9>
DW_AT_name        : (indirect string, offset: 0xf0): __kernel_pid_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
<1><b9>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xec): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
