<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x161): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 2
DW_AT_decl_line   : 41
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x1d9): struct_sg_req_info
DW_AT_decl_file   : 2
DW_AT_decl_line   : 37
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1cd): sg_req_info
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 79
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x172): req_state
DW_AT_type        : <0xb5>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 80
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x181): orphan
DW_AT_type        : <0xb5>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 81
DW_AT_data_member_location: 2 byte block: 23 1 	(DW_OP_plus_uconst: 1)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x188): sg_io_owned
DW_AT_type        : <0xb5>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 82
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x194): problem
DW_AT_type        : <0xb5>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 83
DW_AT_data_member_location: 2 byte block: 23 3 	(DW_OP_plus_uconst: 3)
<2><7c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19c): pack_id
DW_AT_type        : <0xbc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 84
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a8): usr_ptr
DW_AT_type        : <0xc3>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 85
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><98>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b0): duration
DW_AT_type        : <0xc4>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 86
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><a6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c6): unused
DW_AT_type        : <0xbc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 87
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><b5>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x17c): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><bc>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1a4): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><c3>
Abbrev Number: 7 (DW_TAG_pointer_type)
<1><c4>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1b9): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
