<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x169): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x421): struct_v4l2_create_buffers
DW_AT_decl_file   : 3
DW_AT_decl_line   : 44
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x40d): v4l2_create_buffers
DW_AT_byte_size   : 248
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1260
<2><45>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17a): index
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1261
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><54>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x193): count
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1262
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><63>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x199): memory
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1263
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><72>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a0): format
DW_AT_type        : <0xa4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1264
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><81>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24a): reserved
DW_AT_type        : <0x5e8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1265
DW_AT_data_member_location: 3 byte block: 23 d8 1 	(DW_OP_plus_uconst: 216)
<1><92>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x9d>
DW_AT_name        : (indirect string, offset: 0x18d): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><9d>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x180): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><a4>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x401): v4l2_format
DW_AT_byte_size   : 204
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1148
<2><ad>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a7): type
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1149
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><bc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ac): fmt
DW_AT_type        : <0xcb>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1159
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><cb>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 200
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1150
<3><d0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b0): pix
DW_AT_type        : <0x14a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1151
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><df>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x239): pix_mp
DW_AT_type        : <0x218>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1152
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><ee>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2bc): win
DW_AT_type        : <0x385>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1153
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><fd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32a): vbi
DW_AT_type        : <0x479>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1154
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><10c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x378): sliced
DW_AT_type        : <0x515>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1155
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><11b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3b8): sdr
DW_AT_type        : <0x56f>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1156
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><12a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3d7): meta
DW_AT_type        : <0x5b3>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1157
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><139>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3f8): raw_data
DW_AT_type        : <0x5db>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1158
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><14a>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x229): v4l2_pix_format
DW_AT_byte_size   : 48
DW_AT_decl_file   : 2
DW_AT_decl_line   : 182
<2><152>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b4): width
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 183
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><160>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ba): height
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 184
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><16e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c1): pixelformat
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 185
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><17c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cd): field
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 186
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><18a>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d3): bytesperline
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 187
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><198>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e0): sizeimage
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 188
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><1a6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ea): colorspace
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 189
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><1b4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f5): priv
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 190
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><1c2>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fa): flags
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 191
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><1d0>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_type        : <0x1da>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 192
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><1da>
Abbrev Number: 11 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 192
<3><1de>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x200): ycbcr_enc
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 193
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><1ec>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20a): hsv_enc
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 194
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1fb>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x212): quantization
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 196
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><209>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21f): xfer_func
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 197
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<1><218>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2a5): v4l2_pix_format_mplane
DW_AT_byte_size   : 192
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1122
<2><221>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b4): width
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1123
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><230>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ba): height
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1124
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><23f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c1): pixelformat
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1125
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><24e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cd): field
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1126
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><25d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ea): colorspace
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1127
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><26c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x240): plane_fmt
DW_AT_type        : <0x2fc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1128
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><27b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x287): num_planes
DW_AT_type        : <0x366>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1129
DW_AT_data_member_location: 3 byte block: 23 b4 1 	(DW_OP_plus_uconst: 180)
<2><28b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fa): flags
DW_AT_type        : <0x366>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1130
DW_AT_data_member_location: 3 byte block: 23 b5 1 	(DW_OP_plus_uconst: 181)
<2><29b>
Abbrev Number: 12 (DW_TAG_member)
DW_AT_type        : <0x2a7>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1131
DW_AT_data_member_location: 3 byte block: 23 b6 1 	(DW_OP_plus_uconst: 182)
<2><2a7>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 1
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1131
<3><2ac>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x200): ycbcr_enc
DW_AT_type        : <0x366>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1132
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2bb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20a): hsv_enc
DW_AT_type        : <0x366>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1133
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><2cb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x212): quantization
DW_AT_type        : <0x366>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1135
DW_AT_data_member_location: 3 byte block: 23 b7 1 	(DW_OP_plus_uconst: 183)
<2><2db>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21f): xfer_func
DW_AT_type        : <0x366>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1136
DW_AT_data_member_location: 3 byte block: 23 b8 1 	(DW_OP_plus_uconst: 184)
<2><2eb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24a): reserved
DW_AT_type        : <0x378>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1137
DW_AT_data_member_location: 3 byte block: 23 b9 1 	(DW_OP_plus_uconst: 185)
<1><2fc>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x309>
<2><301>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 8
<1><309>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x271): v4l2_plane_pix_format
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1117
<2><312>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e0): sizeimage
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1118
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><321>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d3): bytesperline
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1119
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><330>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24a): reserved
DW_AT_type        : <0x340>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1120
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><340>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x34d>
<2><345>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 6
<1><34d>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x358>
DW_AT_name        : (indirect string, offset: 0x262): __u16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
<1><358>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x253): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><35f>
Abbrev Number: 15 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x268): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><366>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x371>
DW_AT_name        : (indirect string, offset: 0x2a0): __u8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
<1><371>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x292): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><378>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x366>
<2><37d>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 7
<1><385>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x31e): v4l2_window
DW_AT_byte_size   : 40
DW_AT_decl_file   : 2
DW_AT_decl_line   : 554
<2><38e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c0): w
DW_AT_type        : <0x3f8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 555
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><39d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cd): field
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 556
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><3ac>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2df): chromakey
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 557
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><3bb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2e9): clips
DW_AT_type        : <0x44b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 558
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><3ca>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x300): clipcount
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 559
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><3d9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x30a): bitmap
DW_AT_type        : <0x478>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 560
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><3e8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x311): global_alpha
DW_AT_type        : <0x366>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 561
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<1><3f8>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2d5): v4l2_rect
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 135
<2><400>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c2): left
DW_AT_type        : <0x439>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 136
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><40e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d1): top
DW_AT_type        : <0x439>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 137
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><41c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b4): width
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 138
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><42a>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ba): height
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 139
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><439>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x444>
DW_AT_name        : (indirect string, offset: 0x2cb): __s32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
<1><444>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x2c7): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><44b>
Abbrev Number: 16 (DW_TAG_pointer_type)
DW_AT_type        : <0x450>
<1><450>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2f6): v4l2_clip
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 550
<2><459>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ef): c
DW_AT_type        : <0x3f8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 551
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><468>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f1): next
DW_AT_type        : <0x44b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 552
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><478>
Abbrev Number: 17 (DW_TAG_pointer_type)
<1><479>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x368): v4l2_vbi_format
DW_AT_byte_size   : 44
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1052
<2><482>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32e): sampling_rate
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1053
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><491>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x33c): offset
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1054
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><4a0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x343): samples_per_line
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1055
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><4af>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x354): sample_format
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1056
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><4be>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x362): start
DW_AT_type        : <0x4fb>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1057
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><4cd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x193): count
DW_AT_type        : <0x508>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1058
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><4dc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fa): flags
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1059
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><4eb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24a): reserved
DW_AT_type        : <0x508>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1060
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<1><4fb>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x439>
<2><500>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><508>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x92>
<2><50d>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><515>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x3a1): v4l2_sliced_vbi_format
DW_AT_byte_size   : 112
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1068
<2><51e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x37f): service_set
DW_AT_type        : <0x34d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1069
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x38b): service_lines
DW_AT_type        : <0x55b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1070
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><53c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x399): io_size
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1071
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><54b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24a): reserved
DW_AT_type        : <0x508>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1072
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<1><55b>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x34d>
<2><560>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<2><567>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 24
<1><56f>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x3c7): v4l2_sdr_format
DW_AT_byte_size   : 32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1139
<2><578>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c1): pixelformat
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1140
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><587>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3bc): buffersize
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1141
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><596>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24a): reserved
DW_AT_type        : <0x5a6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1142
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><5a6>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x366>
<2><5ab>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 24
<1><5b3>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x3e7): v4l2_meta_format
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1144
<2><5bc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3dc): dataformat
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1145
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><5cb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3bc): buffersize
DW_AT_type        : <0x92>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1146
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><5db>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x366>
<2><5e0>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 200
<1><5e8>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x92>
<2><5ed>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35f>
DW_AT_lower_bound : 0
DW_AT_count       : 8
