<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15e): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 37
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x232): struct_statfs64
DW_AT_decl_file   : 4
DW_AT_decl_line   : 35
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x229): statfs64
DW_AT_byte_size   : 88
DW_AT_decl_file   : 2
DW_AT_decl_line   : 46
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16f): f_type
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 47
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18f): f_bsize
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 48
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x197): f_blocks
DW_AT_type        : <0xff>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 49
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bd): f_bfree
DW_AT_type        : <0xff>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 50
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><7c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c5): f_bavail
DW_AT_type        : <0xff>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 51
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ce): f_files
DW_AT_type        : <0xff>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 52
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><98>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d6): f_ffree
DW_AT_type        : <0xff>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 53
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><a6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1de): f_fsid
DW_AT_type        : <0x111>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 54
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><b4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x206): f_namelen
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 55
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x210): f_frsize
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 56
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><d0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x219): f_flags
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 57
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><de>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x221): f_spare
DW_AT_type        : <0x14a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 58
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<1><ed>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf8>
DW_AT_name        : (indirect string, offset: 0x17f): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><f8>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x176): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><ff>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x10a>
DW_AT_name        : (indirect string, offset: 0x1b7): __u64
DW_AT_decl_file   : 3
DW_AT_decl_line   : 31
<1><10a>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1a0): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><111>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x11c>
DW_AT_name        : (indirect string, offset: 0x1f6): __kernel_fsid_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 73
<1><11c>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 71
<2><120>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e5): val
DW_AT_type        : <0x12f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 72
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><12f>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0x13c>
<2><134>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x143>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><13c>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1e9): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><143>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ed): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><14a>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0xed>
<2><14f>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x143>
DW_AT_lower_bound : 0
DW_AT_count       : 4
