<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x91): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x121): struct_flock
DW_AT_decl_file   : 4
DW_AT_decl_line   : 33
<1><3b>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x46>
DW_AT_name        : (indirect string, offset: 0x10d): struct_kernel_flock
DW_AT_decl_file   : 3
DW_AT_decl_line   : 35
<1><46>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x107): flock
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 148
<2><4e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa2): l_type
DW_AT_type        : <0x95>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 149
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><5c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaf): l_whence
DW_AT_type        : <0x95>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 150
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><6a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb8): l_start
DW_AT_type        : <0x9c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 151
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><78>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe8): l_len
DW_AT_type        : <0x9c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 152
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><86>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xee): l_pid
DW_AT_type        : <0xb9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 153
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><95>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xa9): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><9c>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xa7>
DW_AT_name        : (indirect string, offset: 0xd9): __kernel_off_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 75
<1><a7>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xb2>
DW_AT_name        : (indirect string, offset: 0xc9): __kernel_long_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
<1><b2>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc0): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><b9>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xc4>
DW_AT_name        : (indirect string, offset: 0xf8): __kernel_pid_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
<1><c4>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xf4): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
