<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x277): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x25e): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x21b): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xbf): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x5e): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x17b): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xa8): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x26e): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xcd): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x212): sizetype
<1><6a>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><6c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1b3): char
<1><73>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x79>
<1><79>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x6c>
<1><7e>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xdf): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xd1>
<2><8a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x117): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><98>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x208): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><a6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b4>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x283): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xdc>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><c2>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x77): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x73>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><d1>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xdc>
<2><da>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><dc>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xd1>
<1><e2>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x18e): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x7e>
<1><ed>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf3>
<1><f3>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0xe2>
<1><f8>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x71): _Bool
<1><ff>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x48): __u32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_type        : <0x47>
<1><10a>
Abbrev Number: 13 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x165): v4l2_preemphasis
DW_AT_byte_size   : 4
DW_AT_decl_file   : 6
DW_AT_decl_line   : 763
DW_AT_sibling     : <0x12a>
<2><117>
Abbrev Number: 14 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x18): V4L2_PREEMPHASIS_DISABLED
DW_AT_const_value : 0
<2><11d>
Abbrev Number: 14 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x91): V4L2_PREEMPHASIS_50_uS
DW_AT_const_value : 1
<2><123>
Abbrev Number: 14 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x19c): V4L2_PREEMPHASIS_75_uS
DW_AT_const_value : 2
<1><12a>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x4e): v4l2_pix_format
DW_AT_byte_size   : 32
DW_AT_decl_file   : 3
DW_AT_decl_line   : 274
DW_AT_sibling     : <0x1b0>
<2><137>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x258): width
DW_AT_decl_file   : 3
DW_AT_decl_line   : 275
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><146>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe6): height
DW_AT_decl_file   : 3
DW_AT_decl_line   : 276
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><155>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfe): pixelformat
DW_AT_decl_file   : 3
DW_AT_decl_line   : 277
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><164>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x268): field
DW_AT_decl_file   : 3
DW_AT_decl_line   : 278
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><173>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10a): bytesperline
DW_AT_decl_file   : 3
DW_AT_decl_line   : 279
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><182>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fe): sizeimage
DW_AT_decl_file   : 3
DW_AT_decl_line   : 280
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><191>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b8): colorspace
DW_AT_decl_file   : 3
DW_AT_decl_line   : 281
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><1a0>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x43): priv
DW_AT_decl_file   : 3
DW_AT_decl_line   : 282
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<1><1b0>
Abbrev Number: 15 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x32): v4l2_framebuffer
DW_AT_byte_size   : 44
DW_AT_decl_file   : 3
DW_AT_decl_line   : 719
DW_AT_sibling     : <0x1fa>
<2><1bd>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24d): capability
DW_AT_decl_file   : 3
DW_AT_decl_line   : 720
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1cc>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x188): flags
DW_AT_decl_file   : 3
DW_AT_decl_line   : 721
DW_AT_type        : <0xff>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1db>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x176): base
DW_AT_decl_file   : 3
DW_AT_decl_line   : 724
DW_AT_type        : <0x6a>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><1ea>
Abbrev Number: 17 (DW_TAG_member)
DW_AT_name        : fmt
DW_AT_decl_file   : 3
DW_AT_decl_line   : 725
DW_AT_type        : <0x12a>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><1fa>
Abbrev Number: 12 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x0): struct_v4l2_framebuffer
DW_AT_decl_file   : 4
DW_AT_decl_line   : 43
DW_AT_type        : <0x1b0>
<1><205>
Abbrev Number: 18 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xed): current_wordsize
DW_AT_decl_file   : 5
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><213>
Abbrev Number: 18 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdf): sysent
DW_AT_decl_file   : 5
DW_AT_decl_line   : 892
DW_AT_type        : <0xed>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><221>
Abbrev Number: 18 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1f4): nsyscalls
DW_AT_decl_file   : 5
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><22f>
Abbrev Number: 19 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x80): mpers_target_var
DW_AT_decl_file   : 4
DW_AT_decl_line   : 47
DW_AT_type        : <0x1fa>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
