<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15b): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 38
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x266): struct_timex
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x260): timex
DW_AT_byte_size   : 128
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16c): modes
DW_AT_type        : <0x15d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17f): offset
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19f): freq
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a4): maxerror
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ad): esterror
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b6): status
DW_AT_type        : <0x176>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><98>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c1): constant
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><a6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ca): precision
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><b4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d4): tolerance
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1de): time
DW_AT_type        : <0x17d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><d0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21f): tick
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><de>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x224): ppsfreq
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><ec>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x22c): jitter
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><fa>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x233): shift
DW_AT_type        : <0x176>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><108>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x239): stabil
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><116>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x240): jitcnt
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><124>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x247): calcnt
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><132>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24e): errcnt
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><140>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x255): stbcnt
DW_AT_type        : <0x164>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><14e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x25c): tai
DW_AT_type        : <0x176>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<1><15d>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x172): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><164>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x16f>
DW_AT_name        : (indirect string, offset: 0x18f): __kernel_long_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
<1><16f>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x186): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><176>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1bd): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><17d>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x217): timeval
DW_AT_byte_size   : 8
DW_AT_decl_file   : 3
DW_AT_decl_line   : 29
<2><185>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e3): tv_sec
DW_AT_type        : <0x1a2>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><193>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fa): tv_usec
DW_AT_type        : <0x1ad>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><1a2>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x164>
DW_AT_name        : (indirect string, offset: 0x1ea): __kernel_time_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 77
<1><1ad>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x164>
DW_AT_name        : (indirect string, offset: 0x202): __kernel_suseconds_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 43
