<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x166): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 1 0 0 0 	(DW_OP_addr: 1)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x22b): struct_v4l2_ext_control
DW_AT_decl_file   : 3
DW_AT_decl_line   : 46
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x21a): v4l2_ext_control
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 789
<2><45>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x177): id
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 790
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><54>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18d): size
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 791
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><63>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x192): reserved2
DW_AT_type        : <0xff>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 792
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><72>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_type        : <0x7d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 793
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7d>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 793
<3><82>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a5): value
DW_AT_type        : <0x113>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 794
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><91>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b5): value64
DW_AT_type        : <0x125>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 795
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><a0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d1): string
DW_AT_type        : <0x137>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 796
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><af>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1dd): p_u8
DW_AT_type        : <0x143>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 797
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><be>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f5): p_u16
DW_AT_type        : <0x15a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 798
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><cd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x210): p_u32
DW_AT_type        : <0x171>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 799
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><dc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x216): ptr
DW_AT_type        : <0x176>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 800
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><ed>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf8>
DW_AT_name        : (indirect string, offset: 0x187): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><f8>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x17a): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><ff>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0xed>
<2><104>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0x10c>
DW_AT_lower_bound : 0
DW_AT_count       : 1
<1><10c>
Abbrev Number: 11 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x19c): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><113>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x11e>
DW_AT_name        : (indirect string, offset: 0x1af): __s32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
<1><11e>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ab): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><125>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x130>
DW_AT_name        : (indirect string, offset: 0x1cb): __s64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
<1><130>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1bd): long long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 8
<1><137>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0x13c>
<1><13c>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1d8): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><143>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0x148>
<1><148>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x153>
DW_AT_name        : (indirect string, offset: 0x1f0): __u8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
<1><153>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1e2): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><15a>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0x15f>
<1><15f>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x16a>
DW_AT_name        : (indirect string, offset: 0x20a): __u16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
<1><16a>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1fb): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><171>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0xed>
<1><176>
Abbrev Number: 13 (DW_TAG_pointer_type)
