<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x91): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 38
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x19c): struct_timex
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x196): timex
DW_AT_byte_size   : 128
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa2): modes
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb5): offset
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd5): freq
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xda): maxerror
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe3): esterror
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xec): status
DW_AT_type        : <0x175>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf7): constant
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x100): precision
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10a): tolerance
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x114): time
DW_AT_type        : <0x17c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x155): tick
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><dd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15a): ppsfreq
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><eb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x162): jitter
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><f9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x169): shift
DW_AT_type        : <0x175>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><107>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16f): stabil
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><115>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x176): jitcnt
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><123>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17d): calcnt
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><131>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x184): errcnt
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><13f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18b): stbcnt
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><14d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x192): tai
DW_AT_type        : <0x175>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<1><15c>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xa8): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><163>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x16e>
DW_AT_name        : (indirect string, offset: 0xc5): __kernel_long_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
<1><16e>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xbc): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><175>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xf3): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><17c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x14d): timeval
DW_AT_byte_size   : 8
DW_AT_decl_file   : 3
DW_AT_decl_line   : 29
<2><184>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x119): tv_sec
DW_AT_type        : <0x1a1>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><192>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x130): tv_usec
DW_AT_type        : <0x1ac>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><1a1>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x163>
DW_AT_name        : (indirect string, offset: 0x120): __kernel_time_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 77
<1><1ac>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x163>
DW_AT_name        : (indirect string, offset: 0x138): __kernel_suseconds_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 43
