<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x92): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 5
DW_AT_decl_line   : 44
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x359): struct_ifconf
DW_AT_decl_file   : 5
DW_AT_decl_line   : 41
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x352): ifconf
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 164
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa3): ifc_len
DW_AT_type        : <0x81>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 165
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaf): ifc_ifcu
DW_AT_type        : <0x5f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 169
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5f>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 1
DW_AT_decl_line   : 166
<3><63>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb8): ifcu_buf
DW_AT_type        : <0x88>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 167
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><71>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc6): ifcu_req
DW_AT_type        : <0x94>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 168
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><81>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xab): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><88>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x8d>
<1><8d>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc1): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><94>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x99>
<1><99>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x34c): ifreq
DW_AT_byte_size   : 32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 124
<2><a1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcf): ifr_ifrn
DW_AT_type        : <0xaf>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 128
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><af>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 126
<3><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd8): ifrn_name
DW_AT_type        : <0x18c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 127
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xeb): ifr_ifru
DW_AT_type        : <0xd0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 143
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><d0>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 129
<3><d4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf4): ifru_addr
DW_AT_type        : <0x1a0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 130
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><e2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x134): ifru_dstaddr
DW_AT_type        : <0x1a0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 131
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><f0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x141): ifru_broadaddr
DW_AT_type        : <0x1a0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 132
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><fe>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x150): ifru_netmask
DW_AT_type        : <0x1a0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 133
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><10c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15d): ifru_hwaddr
DW_AT_type        : <0x1a0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 134
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><11a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x169): ifru_flags
DW_AT_type        : <0x1e4>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 135
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><128>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17a): ifru_ivalue
DW_AT_type        : <0x81>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 136
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><136>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x186): ifru_mtu
DW_AT_type        : <0x81>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 137
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><144>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18f): ifru_map
DW_AT_type        : <0x1eb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 138
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><152>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e7): ifru_slave
DW_AT_type        : <0x18c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 139
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><160>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f2): ifru_newname
DW_AT_type        : <0x18c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 140
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><16e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ff): ifru_data
DW_AT_type        : <0x256>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 141
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><17c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x209): ifru_settings
DW_AT_type        : <0x257>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 142
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><18c>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0x8d>
<2><191>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0x199>
DW_AT_lower_bound : 0
DW_AT_count       : 16
<1><199>
Abbrev Number: 11 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xe2): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><1a0>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x12b): sockaddr
DW_AT_byte_size   : 16
DW_AT_decl_file   : 3
DW_AT_decl_line   : 76
<2><1a8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfe): sa_family
DW_AT_type        : <0x1c5>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 77
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1b6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x123): sa_data
DW_AT_type        : <0x1d7>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 78
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><1c5>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1d0>
DW_AT_name        : (indirect string, offset: 0x117): sa_family_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 34
<1><1d0>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x108): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><1d7>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0x8d>
<2><1dc>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0x199>
DW_AT_lower_bound : 0
DW_AT_count       : 14
<1><1e4>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x174): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><1eb>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1e1): ifmap
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 101
<2><1f3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x198): mem_start
DW_AT_type        : <0x248>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 102
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><201>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b4): mem_end
DW_AT_type        : <0x248>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 103
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><20f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bc): base_addr
DW_AT_type        : <0x1d0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 104
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><21d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c6): irq
DW_AT_type        : <0x24f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 105
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><22b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d8): dma
DW_AT_type        : <0x24f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 106
DW_AT_data_member_location: 2 byte block: 23 b 	(DW_OP_plus_uconst: 11)
<2><239>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1dc): port
DW_AT_type        : <0x24f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 107
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><248>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1a2): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><24f>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ca): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><256>
Abbrev Number: 12 (DW_TAG_pointer_type)
<1><257>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x340): if_settings
DW_AT_byte_size   : 12
DW_AT_decl_file   : 1
DW_AT_decl_line   : 110
<2><25f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x217): type
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 111
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><26d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x229): size
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 112
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><27b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x22e): ifs_ifsu
DW_AT_type        : <0x289>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 121
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><289>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 1
DW_AT_decl_line   : 113
<3><28d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x237): raw_hdlc
DW_AT_type        : <0x2f8>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 114
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><29b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x25f): cisco
DW_AT_type        : <0x329>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 115
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2a9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x282): fr
DW_AT_type        : <0x35a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 116
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2b7>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2af): fr_pvc
DW_AT_type        : <0x3d1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 117
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2c5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c8): fr_pvc_info
DW_AT_type        : <0x3f4>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 118
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2d3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ed): sync
DW_AT_type        : <0x425>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 119
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2e1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x326): te1
DW_AT_type        : <0x464>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 120
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><2f1>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x21c): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><2f8>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x2fd>
<1><2fd>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x308>
DW_AT_name        : (indirect string, offset: 0x250): raw_hdlc_proto
DW_AT_decl_file   : 4
DW_AT_decl_line   : 61
<1><308>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 4
DW_AT_decl_line   : 58
<2><30c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x240): encoding
DW_AT_type        : <0x1d0>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 59
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><31a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x249): parity
DW_AT_type        : <0x1d0>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 60
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><329>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x32e>
<1><32e>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x339>
DW_AT_name        : (indirect string, offset: 0x276): cisco_proto
DW_AT_decl_file   : 4
DW_AT_decl_line   : 81
<1><339>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 78
<2><33d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x265): interval
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 79
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><34b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x26e): timeout
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 80
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><35a>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x35f>
<1><35f>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x36a>
DW_AT_name        : (indirect string, offset: 0x2a6): fr_proto
DW_AT_decl_file   : 4
DW_AT_decl_line   : 70
<1><36a>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 24
DW_AT_decl_file   : 4
DW_AT_decl_line   : 62
<2><36e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x285): t391
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 63
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><37c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x28a): t392
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 64
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><38a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x28f): n391
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 65
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><398>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x294): n392
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 66
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><3a6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x299): n393
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 67
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><3b4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x29e): lmi
DW_AT_type        : <0x1d0>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 68
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><3c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2a2): dce
DW_AT_type        : <0x1d0>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 69
DW_AT_data_member_location: 2 byte block: 23 16 	(DW_OP_plus_uconst: 22)
<1><3d1>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x3d6>
<1><3d6>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3e1>
DW_AT_name        : (indirect string, offset: 0x2bb): fr_proto_pvc
DW_AT_decl_file   : 4
DW_AT_decl_line   : 73
<1><3e1>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 4
DW_AT_decl_line   : 71
<2><3e5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2b6): dlci
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 72
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><3f4>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x3f9>
<1><3f9>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x404>
DW_AT_name        : (indirect string, offset: 0x2db): fr_proto_pvc_info
DW_AT_decl_file   : 4
DW_AT_decl_line   : 77
<1><404>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 20
DW_AT_decl_file   : 4
DW_AT_decl_line   : 74
<2><408>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2b6): dlci
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 75
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><416>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d4): master
DW_AT_type        : <0x18c>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 76
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><425>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x42a>
<1><42a>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x435>
DW_AT_name        : (indirect string, offset: 0x311): sync_serial_settings
DW_AT_decl_file   : 4
DW_AT_decl_line   : 51
<1><435>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 12
DW_AT_decl_file   : 4
DW_AT_decl_line   : 47
<2><439>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f2): clock_rate
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 48
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><447>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2fd): clock_type
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 49
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><455>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x308): loopback
DW_AT_type        : <0x1d0>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 50
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><464>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x469>
<1><469>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x474>
DW_AT_name        : (indirect string, offset: 0x333): te1_settings
DW_AT_decl_file   : 4
DW_AT_decl_line   : 57
<1><474>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 4
DW_AT_decl_line   : 52
<2><478>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f2): clock_rate
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 53
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><486>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2fd): clock_type
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 54
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><494>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x308): loopback
DW_AT_type        : <0x1d0>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 55
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><4a2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32a): slot_map
DW_AT_type        : <0x2f1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 56
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
