<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x90): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 2
DW_AT_decl_line   : 62
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x18b): struct_stat
DW_AT_decl_file   : 2
DW_AT_decl_line   : 60
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x186): stat
DW_AT_byte_size   : 80
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa1): st_dev
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xba): st_ino
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc1): st_mode
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd6): st_nlink
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdf): st_uid
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe6): st_gid
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xed): st_rdev
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf5): __pad1
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfc): st_size
DW_AT_type        : <0x16a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10d): st_blksize
DW_AT_type        : <0x171>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11c): __pad2
DW_AT_type        : <0x171>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><dd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x123): st_blocks
DW_AT_type        : <0x16a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><eb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x12d): st_atime
DW_AT_type        : <0x16a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><f9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x136): st_atime_nsec
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><107>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x144): st_mtime
DW_AT_type        : <0x16a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><115>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14d): st_mtime_nsec
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><123>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15b): st_ctime
DW_AT_type        : <0x16a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><131>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x164): st_ctime_nsec
DW_AT_type        : <0x15c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><13f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x172): __unused4
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><14d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17c): __unused5
DW_AT_type        : <0x163>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<1><15c>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xa8): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><163>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc9): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><16a>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x104): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><171>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x118): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
