<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x161): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 5
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x2ed): struct_v4l2_buffer
DW_AT_decl_file   : 5
DW_AT_decl_line   : 41
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2e1): v4l2_buffer
DW_AT_byte_size   : 68
DW_AT_decl_file   : 2
DW_AT_decl_line   : 473
<2><45>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x172): index
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 474
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><54>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18b): type
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 475
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><63>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): bytesused
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 476
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><72>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19a): flags
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 477
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><81>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a0): field
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 478
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><90>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a6): timestamp
DW_AT_type        : <0x15d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 479
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><9f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x205): timecode
DW_AT_type        : <0x1aa>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 480
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><ae>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x25e): sequence
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 481
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><bd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x267): memory
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 482
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><cc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x26e): m
DW_AT_type        : <0xdb>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 488
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><db>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 483
<3><e0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x270): offset
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 484
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><ef>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x277): userptr
DW_AT_type        : <0x243>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 485
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><fe>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x291): planes
DW_AT_type        : <0x24a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 486
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><10d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2aa): fd
DW_AT_type        : <0x2d7>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 487
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><11d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x298): length
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 489
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><12c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d7): reserved2
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 490
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><13b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c3): reserved
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 491
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<1><14b>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x156>
DW_AT_name        : (indirect string, offset: 0x185): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><156>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x178): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><15d>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1fd): timeval
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 29
<2><165>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b0): tv_sec
DW_AT_type        : <0x182>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><173>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e0): tv_usec
DW_AT_type        : <0x19f>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><182>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x18d>
DW_AT_name        : (indirect string, offset: 0x1d0): __kernel_time_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 77
<1><18d>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x198>
DW_AT_name        : (indirect string, offset: 0x1c0): __kernel_long_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 23
<1><198>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1b7): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><19f>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x18d>
DW_AT_name        : (indirect string, offset: 0x1e8): __kernel_suseconds_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 43
<1><1aa>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x250): v4l2_timecode
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 423
<2><1b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18b): type
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 424
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19a): flags
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 425
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1d1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20e): frames
DW_AT_type        : <0x21d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 426
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><1e0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x228): seconds
DW_AT_type        : <0x21d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 427
DW_AT_data_member_location: 2 byte block: 23 9 	(DW_OP_plus_uconst: 9)
<2><1ef>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x230): minutes
DW_AT_type        : <0x21d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 428
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><1fe>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x238): hours
DW_AT_type        : <0x21d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 429
DW_AT_data_member_location: 2 byte block: 23 b 	(DW_OP_plus_uconst: 11)
<2><20d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x23e): userbits
DW_AT_type        : <0x22f>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 430
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><21d>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x228>
DW_AT_name        : (indirect string, offset: 0x223): __u8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
<1><228>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x215): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><22f>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x21d>
<2><234>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x23c>
DW_AT_lower_bound : 0
DW_AT_count       : 4
<1><23c>
Abbrev Number: 12 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x247): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><243>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x27f): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><24a>
Abbrev Number: 13 (DW_TAG_pointer_type)
DW_AT_type        : <0x24f>
<1><24f>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2cc): v4l2_plane
DW_AT_byte_size   : 60
DW_AT_decl_file   : 2
DW_AT_decl_line   : 462
<2><258>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): bytesused
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 463
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><267>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x298): length
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 464
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><276>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x26e): m
DW_AT_type        : <0x285>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 469
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><285>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 465
<3><28a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x29f): mem_offset
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 466
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><299>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x277): userptr
DW_AT_type        : <0x243>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 467
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2a8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2aa): fd
DW_AT_type        : <0x2d7>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 468
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><2b8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2b7): data_offset
DW_AT_type        : <0x14b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 470
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><2c7>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c3): reserved
DW_AT_type        : <0x2e9>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 471
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><2d7>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x2e2>
DW_AT_name        : (indirect string, offset: 0x2b1): __s32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
<1><2e2>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x2ad): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><2e9>
Abbrev Number: 10 (DW_TAG_array_type)
DW_AT_type        : <0x14b>
<2><2ee>
Abbrev Number: 11 (DW_TAG_subrange_type)
DW_AT_type        : <0x23c>
DW_AT_lower_bound : 0
DW_AT_count       : 11
