<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x95): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 2
DW_AT_decl_line   : 41
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x1a9): struct_sg_io_hdr
DW_AT_decl_file   : 2
DW_AT_decl_line   : 37
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x19f): sg_io_hdr
DW_AT_byte_size   : 64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa6): interface_id
DW_AT_type        : <0x178>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb7): dxfer_direction
DW_AT_type        : <0x178>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc7): cmd_len
DW_AT_type        : <0x17f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 29
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdd): mx_sb_len
DW_AT_type        : <0x17f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 9 	(DW_OP_plus_uconst: 9)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe7): iovec_count
DW_AT_type        : <0x186>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x102): dxfer_len
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x119): dxferp
DW_AT_type        : <0x194>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x120): cmdp
DW_AT_type        : <0x195>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x125): sbp
DW_AT_type        : <0x194>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x129): timeout
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x131): flags
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><dd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x137): pack_id
DW_AT_type        : <0x178>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><eb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13f): usr_ptr
DW_AT_type        : <0x194>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><f9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x147): status
DW_AT_type        : <0x17f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><107>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14e): masked_status
DW_AT_type        : <0x17f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 2d 	(DW_OP_plus_uconst: 45)
<2><115>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15c): msg_status
DW_AT_type        : <0x17f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 2e 	(DW_OP_plus_uconst: 46)
<2><123>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x167): sb_len_wr
DW_AT_type        : <0x17f>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
DW_AT_data_member_location: 2 byte block: 23 2f 	(DW_OP_plus_uconst: 47)
<2><131>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x171): host_status
DW_AT_type        : <0x186>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 44
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><13f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17d): driver_status
DW_AT_type        : <0x186>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 45
DW_AT_data_member_location: 2 byte block: 23 32 	(DW_OP_plus_uconst: 50)
<2><14d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18b): resid
DW_AT_type        : <0x178>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 46
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><15b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x191): duration
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 47
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><169>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19a): info
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 48
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<1><178>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xb3): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><17f>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xcf): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><186>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xf3): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><18d>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x10c): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><194>
Abbrev Number: 7 (DW_TAG_pointer_type)
<1><195>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x17f>
