<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x92): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 1
DW_AT_decl_line   : 60
DW_AT_location    : 5 byte block: 3 1 0 0 0 	(DW_OP_addr: 1)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0xaa): struct_stat64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 58
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xa3): stat64
DW_AT_byte_size   : 0
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
