<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15f): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 42
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x397): struct_ff_effect
DW_AT_decl_file   : 3
DW_AT_decl_line   : 38
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x38d): ff_effect
DW_AT_byte_size   : 44
DW_AT_decl_file   : 2
DW_AT_decl_line   : 166
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x170): type
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 167
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18a): id
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 168
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x199): direction
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 169
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a3): trigger
DW_AT_type        : <0x108>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 170
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><7c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c6): replay
DW_AT_type        : <0x12d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 171
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e4): u
DW_AT_type        : <0x98>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 178
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><98>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 28
DW_AT_decl_file   : 2
DW_AT_decl_line   : 172
<3><9c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e6): constant
DW_AT_type        : <0x152>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 173
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><aa>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x24f): ramp
DW_AT_type        : <0x1b8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 174
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><b8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x279): periodic
DW_AT_type        : <0x1eb>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 175
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><c6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2e6): condition
DW_AT_type        : <0x27b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 176
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><d4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x355): rumble
DW_AT_type        : <0x2ec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 177
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><e4>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xef>
DW_AT_name        : (indirect string, offset: 0x184): __u16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
<1><ef>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x175): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><f6>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x101>
DW_AT_name        : (indirect string, offset: 0x193): __s16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 25
<1><101>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x18d): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><108>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1bb): ff_trigger
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 125
<2><110>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ab): button
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 126
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><11e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b2): interval
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 127
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><12d>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1da): ff_replay
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 121
<2><135>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1cd): length
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 122
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><143>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d4): delay
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 123
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><152>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x23c): ff_constant_effect
DW_AT_byte_size   : 10
DW_AT_decl_file   : 2
DW_AT_decl_line   : 135
<2><15a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ef): level
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 136
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><168>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f5): envelope
DW_AT_type        : <0x177>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 137
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><177>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x230): ff_envelope
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 129
<2><17f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fe): attack_length
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 130
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><18d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20c): attack_level
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 131
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><19b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x219): fade_length
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 132
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1a9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x225): fade_level
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 133
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<1><1b8>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x26a): ff_ramp_effect
DW_AT_byte_size   : 12
DW_AT_decl_file   : 2
DW_AT_decl_line   : 139
<2><1c0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x254): start_level
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 140
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1ce>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x260): end_level
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 141
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><1dc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f5): envelope
DW_AT_type        : <0x177>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 142
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><1eb>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2d3): ff_periodic_effect
DW_AT_byte_size   : 28
DW_AT_decl_file   : 2
DW_AT_decl_line   : 152
<2><1f3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x282): waveform
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 153
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><201>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x28b): period
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 154
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><20f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x292): magnitude
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 155
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><21d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x29c): offset
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 156
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><22b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2a3): phase
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 157
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><239>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f5): envelope
DW_AT_type        : <0x177>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 158
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><247>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2a9): custom_len
DW_AT_type        : <0x264>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 159
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><255>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c7): custom_data
DW_AT_type        : <0x276>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 160
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<1><264>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x26f>
DW_AT_name        : (indirect string, offset: 0x2c1): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><26f>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x2b4): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><276>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0xf6>
<1><27b>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0x288>
<2><280>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0x2e5>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><288>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x338): ff_condition_effect
DW_AT_byte_size   : 12
DW_AT_decl_file   : 2
DW_AT_decl_line   : 144
<2><290>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f0): right_saturation
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 145
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><29e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x301): left_saturation
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 146
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><2ac>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x311): right_coeff
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 147
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><2ba>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x31d): left_coeff
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 148
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><2c8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x328): deadband
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 149
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><2d6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x331): center
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 150
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<1><2e5>
Abbrev Number: 11 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x34c): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><2ec>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x37c): ff_rumble_effect
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 162
<2><2f4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x35c): strong_magnitude
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 163
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><302>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x36d): weak_magnitude
DW_AT_type        : <0xe4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 164
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
