<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x166): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x1fb): struct_v4l2_framebuffer
DW_AT_decl_file   : 3
DW_AT_decl_line   : 49
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1ea): v4l2_framebuffer
DW_AT_byte_size   : 44
DW_AT_decl_file   : 2
DW_AT_decl_line   : 520
<2><45>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x177): capability
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 521
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><54>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x195): flags
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 522
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><63>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19b): base
DW_AT_type        : <0x112>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 523
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><72>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a0): fmt
DW_AT_type        : <0x81>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 533
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><81>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_byte_size   : 32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 524
<3><86>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a4): width
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 525
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><95>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1aa): height
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 526
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<3><a4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b1): pixelformat
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 527
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<3><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bd): field
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 528
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<3><c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c3): bytesperline
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 529
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<3><d1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d0): sizeimage
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 530
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<3><e0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1da): colorspace
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 531
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<3><ef>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e5): priv
DW_AT_type        : <0x100>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 532
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<1><100>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x10b>
DW_AT_name        : (indirect string, offset: 0x18f): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><10b>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x182): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><112>
Abbrev Number: 8 (DW_TAG_pointer_type)
