<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9d): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x1a7): struct_v4l2_ext_controls
DW_AT_decl_file   : 3
DW_AT_decl_line   : 47
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x195): v4l2_ext_controls
DW_AT_byte_size   : 24
DW_AT_decl_file   : 2
DW_AT_decl_line   : 796
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_type        : <0x4f>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 797
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><4f>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 797
<3><54>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xae): ctrl_class
DW_AT_type        : <0xb0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 798
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><63>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcc): which
DW_AT_type        : <0xb0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 799
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><73>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd2): count
DW_AT_type        : <0xb0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 801
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><82>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd8): error_idx
DW_AT_type        : <0xb0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 802
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><91>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe2): reserved
DW_AT_type        : <0xc2>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 803
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><a0>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf4): controls
DW_AT_type        : <0xd6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 804
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<1><b0>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xbb>
DW_AT_name        : (indirect string, offset: 0xc6): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><bb>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xb9): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><c2>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0xb0>
<2><c7>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0xcf>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><cf>
Abbrev Number: 11 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xeb): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><d6>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0xdb>
<1><db>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x184): v4l2_ext_control
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 782
<2><e4>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfd): id
DW_AT_type        : <0xb0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 783
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><f3>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x100): size
DW_AT_type        : <0xb0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 784
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><102>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x105): reserved2
DW_AT_type        : <0x18c>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 785
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><111>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_type        : <0x11c>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 786
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><11c>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 786
<3><121>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10f): value
DW_AT_type        : <0x199>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 787
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><130>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11f): value64
DW_AT_type        : <0x1ab>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 788
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><13f>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13b): string
DW_AT_type        : <0x1bd>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 789
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><14e>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x147): p_u8
DW_AT_type        : <0x1c9>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 790
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><15d>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15f): p_u16
DW_AT_type        : <0x1e0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 791
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><16c>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17a): p_u32
DW_AT_type        : <0x1f7>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 792
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><17b>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): ptr
DW_AT_type        : <0x1fc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 793
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><18c>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0xb0>
<2><191>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0xcf>
DW_AT_lower_bound : 0
DW_AT_count       : 1
<1><199>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1a4>
DW_AT_name        : (indirect string, offset: 0x119): __s32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
<1><1a4>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x115): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><1ab>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1b6>
DW_AT_name        : (indirect string, offset: 0x135): __s64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
<1><1b6>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x127): long long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 8
<1><1bd>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0x1c2>
<1><1c2>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x142): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1c9>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0x1ce>
<1><1ce>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1d9>
DW_AT_name        : (indirect string, offset: 0x15a): __u8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
<1><1d9>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x14c): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><1e0>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0x1e5>
<1><1e5>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1f0>
DW_AT_name        : (indirect string, offset: 0x174): __u16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
<1><1f0>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x165): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><1f7>
Abbrev Number: 12 (DW_TAG_pointer_type)
DW_AT_type        : <0xb0>
<1><1fc>
Abbrev Number: 13 (DW_TAG_pointer_type)
