<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x94): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x121): struct_sigevent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 45
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
<2><3f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa5): sigev_value
DW_AT_type        : <0x4d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><4d>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 1
DW_AT_decl_line   : 32
<3><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb1): sival_int
DW_AT_type        : <0xdb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbf): sival_ptr
DW_AT_type        : <0xe2>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdb): sigev_signo
DW_AT_type        : <0xdb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><7c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe7): sigev_notify
DW_AT_type        : <0xdb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf4): sigev_un
DW_AT_type        : <0x98>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 44
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><98>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 38
<3><9c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfd): tid
DW_AT_type        : <0xdb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><aa>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x101): sigev_thread
DW_AT_type        : <0xb8>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><b8>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 40
<4><bc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10e): function
DW_AT_type        : <0xe2>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<4><ca>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x117): attribute
DW_AT_type        : <0xe2>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 42
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><db>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xbb): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><e2>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc9): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
