<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15b): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x1eb): struct_flock
DW_AT_decl_file   : 4
DW_AT_decl_line   : 33
<1><3c>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x47>
DW_AT_name        : (indirect string, offset: 0x1d7): struct_kernel_flock
DW_AT_decl_file   : 3
DW_AT_decl_line   : 35
<1><47>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1d1): flock
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 148
<2><4f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16c): l_type
DW_AT_type        : <0x96>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 149
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><5d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): l_whence
DW_AT_type        : <0x96>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 150
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><6b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x182): l_start
DW_AT_type        : <0x9d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 151
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><79>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b2): l_len
DW_AT_type        : <0x9d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 152
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><87>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b8): l_pid
DW_AT_type        : <0xba>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 153
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><96>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x173): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><9d>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xa8>
DW_AT_name        : (indirect string, offset: 0x1a3): __kernel_off_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 75
<1><a8>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xb3>
DW_AT_name        : (indirect string, offset: 0x193): __kernel_long_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
<1><b3>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x18a): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><ba>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xc5>
DW_AT_name        : (indirect string, offset: 0x1c2): __kernel_pid_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
<1><c5>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1be): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
