<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x92): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 37
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x147): struct_statfs
DW_AT_decl_file   : 3
DW_AT_decl_line   : 34
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x140): statfs
DW_AT_byte_size   : 64
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa3): f_type
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc3): f_bsize
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcb): f_blocks
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd4): f_bfree
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdc): f_bavail
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe5): f_files
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xed): f_ffree
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf5): f_fsid
DW_AT_type        : <0xfe>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11d): f_namelen
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x127): f_frsize
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x130): f_flags
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><dd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x138): f_spare
DW_AT_type        : <0x137>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<1><ec>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf7>
DW_AT_name        : (indirect string, offset: 0xb3): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><f7>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xaa): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><fe>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x109>
DW_AT_name        : (indirect string, offset: 0x10d): __kernel_fsid_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 73
<1><109>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 71
<2><10d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfc): val
DW_AT_type        : <0x11c>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 72
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><11c>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0x129>
<2><121>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x130>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><129>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x100): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><130>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x104): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><137>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0xec>
<2><13c>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x130>
DW_AT_lower_bound : 0
DW_AT_count       : 4
