<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x93): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 7
DW_AT_decl_line   : 34
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x19a): struct_mmsghdr
DW_AT_decl_file   : 7
DW_AT_decl_line   : 32
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x192): mmsghdr
DW_AT_byte_size   : 32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 96
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa4): msg_hdr
DW_AT_type        : <0x60>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 97
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18a): msg_len
DW_AT_type        : <0x151>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 98
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<1><60>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x183): msghdr
DW_AT_byte_size   : 28
DW_AT_decl_file   : 1
DW_AT_decl_line   : 86
<2><68>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xac): msg_name
DW_AT_type        : <0xcb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 87
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><76>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb5): msg_namelen
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 88
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><84>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xed): msg_iov
DW_AT_type        : <0xff>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 89
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><92>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13f): msg_iovlen
DW_AT_type        : <0x146>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 90
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><a0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15e): msg_control
DW_AT_type        : <0xcb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 91
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><ae>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16a): msg_controllen
DW_AT_type        : <0x146>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 92
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><bc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): msg_flags
DW_AT_type        : <0xf8>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 93
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<1><cb>
Abbrev Number: 6 (DW_TAG_pointer_type)
<1><cc>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xd7>
DW_AT_name        : (indirect string, offset: 0xe3): socklen_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 116
<1><d7>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xe2>
DW_AT_name        : (indirect string, offset: 0xd7): __socklen_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 111
<1><e2>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xed>
DW_AT_name        : (indirect string, offset: 0xcf): int32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 64
<1><ed>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf8>
DW_AT_name        : (indirect string, offset: 0xc5): __int32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 40
<1><f8>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc1): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><ff>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x104>
<1><104>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x139): iovec
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 23
<2><10c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf5): iov_base
DW_AT_type        : <0xcb>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><11a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfe): iov_len
DW_AT_type        : <0x129>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><129>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x134>
DW_AT_name        : (indirect string, offset: 0x129): __kernel_size_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 65
<1><134>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x13f>
DW_AT_name        : (indirect string, offset: 0x118): __kernel_ulong_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 24
<1><13f>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x106): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><146>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x151>
DW_AT_name        : (indirect string, offset: 0x157): size_t
DW_AT_decl_file   : 6
DW_AT_decl_line   : 62
<1><151>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x14a): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
