<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9f): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x357): struct_v4l2_create_buffers
DW_AT_decl_file   : 3
DW_AT_decl_line   : 44
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x343): v4l2_create_buffers
DW_AT_byte_size   : 248
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1253
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb0): index
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1254
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><53>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc9): count
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1255
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><62>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcf): memory
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1256
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><71>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd6): format
DW_AT_type        : <0xa3>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1257
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><80>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): reserved
DW_AT_type        : <0x5e7>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1258
DW_AT_data_member_location: 3 byte block: 23 d8 1 	(DW_OP_plus_uconst: 216)
<1><91>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x9c>
DW_AT_name        : (indirect string, offset: 0xc3): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><9c>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xb6): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><a3>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x337): v4l2_format
DW_AT_byte_size   : 204
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1141
<2><ac>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdd): type
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1142
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><bb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe2): fmt
DW_AT_type        : <0xca>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1152
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><ca>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 200
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1143
<3><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe6): pix
DW_AT_type        : <0x149>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1144
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><de>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16f): pix_mp
DW_AT_type        : <0x217>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1145
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><ed>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f2): win
DW_AT_type        : <0x384>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1146
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><fc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x260): vbi
DW_AT_type        : <0x478>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1147
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><10b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ae): sliced
DW_AT_type        : <0x514>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1148
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><11a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ee): sdr
DW_AT_type        : <0x56e>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1149
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><129>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x30d): meta
DW_AT_type        : <0x5b2>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1150
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><138>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32e): raw_data
DW_AT_type        : <0x5da>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1151
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><149>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x15f): v4l2_pix_format
DW_AT_byte_size   : 48
DW_AT_decl_file   : 2
DW_AT_decl_line   : 182
<2><151>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xea): width
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 183
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><15f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf0): height
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 184
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><16d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf7): pixelformat
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 185
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><17b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x103): field
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 186
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><189>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x109): bytesperline
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 187
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><197>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x116): sizeimage
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 188
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><1a5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x120): colorspace
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 189
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><1b3>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x12b): priv
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 190
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><1c1>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x130): flags
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 191
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><1cf>
Abbrev Number: 10 (DW_TAG_member)
DW_AT_type        : <0x1d9>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 192
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><1d9>
Abbrev Number: 11 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 2
DW_AT_decl_line   : 192
<3><1dd>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x136): ycbcr_enc
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 193
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><1eb>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x140): hsv_enc
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 194
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1fa>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x148): quantization
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 196
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><208>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x155): xfer_func
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 197
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<1><217>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1db): v4l2_pix_format_mplane
DW_AT_byte_size   : 192
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1115
<2><220>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xea): width
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1116
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><22f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf0): height
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1117
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><23e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf7): pixelformat
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1118
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><24d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x103): field
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1119
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><25c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x120): colorspace
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1120
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><26b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x176): plane_fmt
DW_AT_type        : <0x2fb>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1121
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><27a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bd): num_planes
DW_AT_type        : <0x365>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1122
DW_AT_data_member_location: 3 byte block: 23 b4 1 	(DW_OP_plus_uconst: 180)
<2><28a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x130): flags
DW_AT_type        : <0x365>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1123
DW_AT_data_member_location: 3 byte block: 23 b5 1 	(DW_OP_plus_uconst: 181)
<2><29a>
Abbrev Number: 12 (DW_TAG_member)
DW_AT_type        : <0x2a6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1124
DW_AT_data_member_location: 3 byte block: 23 b6 1 	(DW_OP_plus_uconst: 182)
<2><2a6>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 1
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1124
<3><2ab>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x136): ycbcr_enc
DW_AT_type        : <0x365>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1125
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2ba>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x140): hsv_enc
DW_AT_type        : <0x365>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1126
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><2ca>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x148): quantization
DW_AT_type        : <0x365>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1128
DW_AT_data_member_location: 3 byte block: 23 b7 1 	(DW_OP_plus_uconst: 183)
<2><2da>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x155): xfer_func
DW_AT_type        : <0x365>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1129
DW_AT_data_member_location: 3 byte block: 23 b8 1 	(DW_OP_plus_uconst: 184)
<2><2ea>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): reserved
DW_AT_type        : <0x377>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1130
DW_AT_data_member_location: 3 byte block: 23 b9 1 	(DW_OP_plus_uconst: 185)
<1><2fb>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x308>
<2><300>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 8
<1><308>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1a7): v4l2_plane_pix_format
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1110
<2><311>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x116): sizeimage
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1111
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><320>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x109): bytesperline
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1112
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><32f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): reserved
DW_AT_type        : <0x33f>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1113
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><33f>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x34c>
<2><344>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 6
<1><34c>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x357>
DW_AT_name        : (indirect string, offset: 0x198): __u16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 26
<1><357>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x189): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><35e>
Abbrev Number: 15 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x19e): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><365>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x370>
DW_AT_name        : (indirect string, offset: 0x1d6): __u8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
<1><370>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1c8): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><377>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x365>
<2><37c>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 7
<1><384>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x254): v4l2_window
DW_AT_byte_size   : 40
DW_AT_decl_file   : 2
DW_AT_decl_line   : 547
<2><38d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f6): w
DW_AT_type        : <0x3f7>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 548
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><39c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x103): field
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 549
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><3ab>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x215): chromakey
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 550
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><3ba>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21f): clips
DW_AT_type        : <0x44a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 551
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><3c9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x236): clipcount
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 552
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><3d8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x240): bitmap
DW_AT_type        : <0x477>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 553
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><3e7>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x247): global_alpha
DW_AT_type        : <0x365>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 554
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<1><3f7>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x20b): v4l2_rect
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 135
<2><3ff>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f8): left
DW_AT_type        : <0x438>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 136
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><40d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x207): top
DW_AT_type        : <0x438>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 137
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><41b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xea): width
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 138
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><429>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf0): height
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 139
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><438>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x443>
DW_AT_name        : (indirect string, offset: 0x201): __s32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
<1><443>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1fd): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><44a>
Abbrev Number: 16 (DW_TAG_pointer_type)
DW_AT_type        : <0x44f>
<1><44f>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x22c): v4l2_clip
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 543
<2><458>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x225): c
DW_AT_type        : <0x3f7>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 544
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><467>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x227): next
DW_AT_type        : <0x44a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 545
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><477>
Abbrev Number: 17 (DW_TAG_pointer_type)
<1><478>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x29e): v4l2_vbi_format
DW_AT_byte_size   : 44
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1045
<2><481>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x264): sampling_rate
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1046
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><490>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x272): offset
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1047
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><49f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x279): samples_per_line
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1048
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><4ae>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x28a): sample_format
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1049
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><4bd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x298): start
DW_AT_type        : <0x4fa>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1050
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><4cc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc9): count
DW_AT_type        : <0x507>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1051
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><4db>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x130): flags
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1052
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><4ea>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): reserved
DW_AT_type        : <0x507>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1053
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<1><4fa>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x438>
<2><4ff>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><507>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x91>
<2><50c>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><514>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2d7): v4l2_sliced_vbi_format
DW_AT_byte_size   : 112
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1061
<2><51d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2b5): service_set
DW_AT_type        : <0x34c>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1062
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c1): service_lines
DW_AT_type        : <0x55a>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1063
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><53b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2cf): io_size
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1064
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><54a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): reserved
DW_AT_type        : <0x507>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1065
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<1><55a>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x34c>
<2><55f>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<2><566>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 24
<1><56e>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2fd): v4l2_sdr_format
DW_AT_byte_size   : 32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1132
<2><577>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf7): pixelformat
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1133
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><586>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f2): buffersize
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1134
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><595>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): reserved
DW_AT_type        : <0x5a5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1135
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><5a5>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x365>
<2><5aa>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 24
<1><5b2>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x31d): v4l2_meta_format
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1137
<2><5bb>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x312): dataformat
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1138
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><5ca>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f2): buffersize
DW_AT_type        : <0x91>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 1139
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><5da>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x365>
<2><5df>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 200
<1><5e7>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x91>
<2><5ec>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x35e>
DW_AT_lower_bound : 0
DW_AT_count       : 8
