<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x95): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0xf4): struct_v4l2_clip
DW_AT_decl_file   : 3
DW_AT_decl_line   : 42
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xea): v4l2_clip
DW_AT_byte_size   : 20
DW_AT_decl_file   : 2
DW_AT_decl_line   : 543
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa6): c
DW_AT_type        : <0x63>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 544
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><53>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe5): next
DW_AT_type        : <0xc8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 545
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><63>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xdb): v4l2_rect
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 135
<2><6b>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa8): left
DW_AT_type        : <0xa4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 136
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><79>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb7): top
DW_AT_type        : <0xa4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 137
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><87>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbb): width
DW_AT_type        : <0xb6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 138
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><95>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd4): height
DW_AT_type        : <0xb6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 139
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><a4>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xaf>
DW_AT_name        : (indirect string, offset: 0xb1): __s32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 27
<1><af>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xad): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><b6>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xc1>
DW_AT_name        : (indirect string, offset: 0xce): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><c1>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc1): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><c8>
Abbrev Number: 9 (DW_TAG_pointer_type)
DW_AT_type        : <0x3b>
