<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x24d): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x71): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x21c): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xd6): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x5e): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x190): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xbf): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x244): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xe4): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x213): sizetype
<1><6a>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x1c2): char
<1><71>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x77>
<1><77>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0x6a>
<1><7c>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xf6): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xcf>
<2><88>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x131): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><96>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb5): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><a4>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b2>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x265): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xda>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><c0>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x90): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x71>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><cf>
Abbrev Number: 9 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xda>
<2><d8>
Abbrev Number: 10 (DW_TAG_unspecified_parameters)
<1><da>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xcf>
<1><e0>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1b4): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x7c>
<1><eb>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf1>
<1><f1>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0xe0>
<1><f6>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x28): _Bool
<1><fd>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x22a): __u8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 20
DW_AT_type        : <0x39>
<1><108>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2e): __u32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_type        : <0x47>
<1><113>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x20d): __u64
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_type        : <0x4e>
<1><11e>
Abbrev Number: 12 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x17f): v4l2_preemphasis
DW_AT_byte_size   : 4
DW_AT_decl_file   : 6
DW_AT_decl_line   : 763
DW_AT_sibling     : <0x13e>
<2><12b>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xe): V4L2_PREEMPHASIS_DISABLED
DW_AT_const_value : 0
<2><131>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x19d): V4L2_PREEMPHASIS_50_uS
DW_AT_const_value : 1
<2><137>
Abbrev Number: 13 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x10e): V4L2_PREEMPHASIS_75_uS
DW_AT_const_value : 2
<1><13e>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x99): v4l2_fract
DW_AT_byte_size   : 8
DW_AT_decl_file   : 3
DW_AT_decl_line   : 212
DW_AT_sibling     : <0x167>
<2><14a>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x23a): numerator
DW_AT_decl_file   : 3
DW_AT_decl_line   : 213
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><158>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x26e): denominator
DW_AT_decl_file   : 3
DW_AT_decl_line   : 214
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><167>
Abbrev Number: 14 (DW_TAG_array_type)
DW_AT_type        : <0x108>
DW_AT_sibling     : <0x177>
<2><170>
Abbrev Number: 15 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 3
<1><177>
Abbrev Number: 16 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x125): v4l2_std_id
DW_AT_decl_file   : 3
DW_AT_decl_line   : 826
DW_AT_type        : <0x113>
<1><183>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x0): v4l2_standard
DW_AT_byte_size   : 64
DW_AT_decl_file   : 3
DW_AT_decl_line   : 954
DW_AT_sibling     : <0x1ea>
<2><190>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x234): index
DW_AT_decl_file   : 3
DW_AT_decl_line   : 955
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><19f>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : id
DW_AT_decl_file   : 3
DW_AT_decl_line   : 956
DW_AT_type        : <0x177>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1ad>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x22f): name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 957
DW_AT_type        : <0x1ea>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><1bc>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x259): frameperiod
DW_AT_decl_file   : 3
DW_AT_decl_line   : 958
DW_AT_type        : <0x13e>
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><1cb>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f8): framelines
DW_AT_decl_file   : 3
DW_AT_decl_line   : 959
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><1da>
Abbrev Number: 18 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x34): reserved
DW_AT_decl_file   : 3
DW_AT_decl_line   : 960
DW_AT_type        : <0x167>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<1><1ea>
Abbrev Number: 14 (DW_TAG_array_type)
DW_AT_type        : <0xfd>
DW_AT_sibling     : <0x1fa>
<2><1f3>
Abbrev Number: 15 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 23
<1><1fa>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x7b): struct_v4l2_standard
DW_AT_decl_file   : 4
DW_AT_decl_line   : 45
DW_AT_type        : <0x183>
<1><205>
Abbrev Number: 20 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfd): current_wordsize
DW_AT_decl_file   : 5
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><213>
Abbrev Number: 20 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf6): sysent
DW_AT_decl_file   : 5
DW_AT_decl_line   : 892
DW_AT_type        : <0xeb>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><221>
Abbrev Number: 20 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x203): nsyscalls
DW_AT_decl_file   : 5
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><22f>
Abbrev Number: 21 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xa4): mpers_target_var
DW_AT_decl_file   : 4
DW_AT_decl_line   : 47
DW_AT_type        : <0x1fa>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
