<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x362): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x324): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x0): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xde): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x38c): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x20e): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xb9): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x334): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x11c): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x2a6): sizetype
<1><6a>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x229): char
<1><71>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x77>
<1><77>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0x6a>
<1><7c>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x12e): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xcf>
<2><88>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x153): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><96>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaf): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><a4>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b2>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x39f): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xda>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><c0>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x95): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x71>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><cf>
Abbrev Number: 9 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xda>
<2><d8>
Abbrev Number: 10 (DW_TAG_unspecified_parameters)
<1><da>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xcf>
<1><e0>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x21b): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x7c>
<1><eb>
Abbrev Number: 4 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xf1>
<1><f1>
Abbrev Number: 5 (DW_TAG_const_type)
DW_AT_type        : <0xe0>
<1><f6>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x36): _Bool
<1><fd>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2e2): __u8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 20
DW_AT_type        : <0x39>
<1><108>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x2a0): __u64
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_type        : <0x4e>
<1><113>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x33d): btrfs_ioctl_dev_replace_start_params
DW_AT_byte_size   : 2068
DW_AT_decl_file   : 3
DW_AT_decl_line   : 131
DW_AT_sibling     : <0x15a>
<2><120>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x56): srcdevid
DW_AT_decl_file   : 3
DW_AT_decl_line   : 132
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><12e>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x36e): cont_reading_from_srcdev_mode
DW_AT_decl_file   : 3
DW_AT_decl_line   : 133
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><13c>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x65): srcdev_name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 135
DW_AT_type        : <0x15a>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><14a>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3a8): tgtdev_name
DW_AT_decl_file   : 3
DW_AT_decl_line   : 136
DW_AT_type        : <0x15a>
DW_AT_data_member_location: 3 byte block: 23 91 8 	(DW_OP_plus_uconst: 1041)
<1><15a>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0xfd>
DW_AT_sibling     : <0x16b>
<2><163>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 1024
<1><16b>
Abbrev Number: 6 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1c0): btrfs_ioctl_dev_replace_status_params
DW_AT_byte_size   : 48
DW_AT_decl_file   : 3
DW_AT_decl_line   : 144
DW_AT_sibling     : <0x1cc>
<2><177>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd0): replace_state
DW_AT_decl_file   : 3
DW_AT_decl_line   : 145
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><185>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe): progress_1000
DW_AT_decl_file   : 3
DW_AT_decl_line   : 146
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><193>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x135): time_started
DW_AT_decl_file   : 3
DW_AT_decl_line   : 147
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><1a1>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2e7): time_stopped
DW_AT_decl_file   : 3
DW_AT_decl_line   : 148
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><1af>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x313): num_write_errors
DW_AT_decl_file   : 3
DW_AT_decl_line   : 149
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><1bd>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f0): num_uncorrectable_read_errors
DW_AT_decl_file   : 3
DW_AT_decl_line   : 150
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<1><1cc>
Abbrev Number: 15 (DW_TAG_union_type)
DW_AT_byte_size   : 2068
DW_AT_decl_file   : 3
DW_AT_decl_line   : 163
DW_AT_sibling     : <0x1ec>
<2><1d5>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5f): start
DW_AT_decl_file   : 3
DW_AT_decl_line   : 164
DW_AT_type        : <0x113>
<2><1e0>
Abbrev Number: 16 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8e): status
DW_AT_decl_file   : 3
DW_AT_decl_line   : 165
DW_AT_type        : <0x16b>
<1><1ec>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x71): btrfs_ioctl_dev_replace_args
DW_AT_byte_size   : 2596
DW_AT_decl_file   : 3
DW_AT_decl_line   : 159
DW_AT_sibling     : <0x22d>
<2><1f9>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : cmd
DW_AT_decl_file   : 3
DW_AT_decl_line   : 160
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><207>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x244): result
DW_AT_decl_file   : 3
DW_AT_decl_line   : 161
DW_AT_type        : <0x108>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><215>
Abbrev Number: 17 (DW_TAG_member)
DW_AT_type        : <0x1cc>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><21d>
Abbrev Number: 7 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32e): spare
DW_AT_decl_file   : 3
DW_AT_decl_line   : 168
DW_AT_type        : <0x22d>
DW_AT_data_member_location: 3 byte block: 23 a4 10 	(DW_OP_plus_uconst: 2084)
<1><22d>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x108>
DW_AT_sibling     : <0x23d>
<2><236>
Abbrev Number: 18 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 63
<1><23d>
Abbrev Number: 19 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x22e): btrfs_dev_stat_values
DW_AT_byte_size   : 4
DW_AT_decl_file   : 3
DW_AT_decl_line   : 369
DW_AT_sibling     : <0x26f>
<2><24a>
Abbrev Number: 20 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x3c): BTRFS_DEV_STAT_WRITE_ERRS
DW_AT_const_value : 0
<2><250>
Abbrev Number: 20 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x2c9): BTRFS_DEV_STAT_READ_ERRS
DW_AT_const_value : 1
<2><256>
Abbrev Number: 20 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x2af): BTRFS_DEV_STAT_FLUSH_ERRS
DW_AT_const_value : 2
<2><25c>
Abbrev Number: 20 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x1a1): BTRFS_DEV_STAT_CORRUPTION_ERRS
DW_AT_const_value : 3
<2><262>
Abbrev Number: 20 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x2f4): BTRFS_DEV_STAT_GENERATION_ERRS
DW_AT_const_value : 4
<2><268>
Abbrev Number: 20 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x1c): BTRFS_DEV_STAT_VALUES_MAX
DW_AT_const_value : 5
<1><26f>
Abbrev Number: 11 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x27c): struct_btrfs_ioctl_dev_replace_args
DW_AT_decl_file   : 4
DW_AT_decl_line   : 36
DW_AT_type        : <0x1ec>
<1><27a>
Abbrev Number: 21 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x142): current_wordsize
DW_AT_decl_file   : 5
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><288>
Abbrev Number: 21 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x12e): sysent
DW_AT_decl_file   : 5
DW_AT_decl_line   : 892
DW_AT_type        : <0xeb>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><296>
Abbrev Number: 21 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1e6): nsyscalls
DW_AT_decl_file   : 5
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><2a4>
Abbrev Number: 22 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9e): mpers_target_var
DW_AT_decl_file   : 4
DW_AT_decl_line   : 46
DW_AT_type        : <0x26f>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
