<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15c): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 5
DW_AT_decl_line   : 44
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x423): struct_ifconf
DW_AT_decl_file   : 5
DW_AT_decl_line   : 41
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x41c): ifconf
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 181
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16d): ifc_len
DW_AT_type        : <0x82>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 182
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): ifc_ifcu
DW_AT_type        : <0x60>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 186
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><60>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 1
DW_AT_decl_line   : 183
<3><64>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x182): ifcu_buf
DW_AT_type        : <0x89>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 184
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><72>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): ifcu_req
DW_AT_type        : <0x95>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 185
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><82>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x175): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><89>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x8e>
<1><8e>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x18b): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><95>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x9a>
<1><9a>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x416): ifreq
DW_AT_byte_size   : 32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 141
<2><a2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x199): ifr_ifrn
DW_AT_type        : <0xb0>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 145
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b0>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 143
<3><b4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a2): ifrn_name
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 144
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><c3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b5): ifr_ifru
DW_AT_type        : <0xd1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 160
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><d1>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 146
<3><d5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1be): ifru_addr
DW_AT_type        : <0x1a1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 147
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><e3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fe): ifru_dstaddr
DW_AT_type        : <0x1a1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 148
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><f1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20b): ifru_broadaddr
DW_AT_type        : <0x1a1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 149
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><ff>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x21a): ifru_netmask
DW_AT_type        : <0x1a1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 150
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><10d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x227): ifru_hwaddr
DW_AT_type        : <0x1a1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 151
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><11b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x233): ifru_flags
DW_AT_type        : <0x1e5>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 152
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><129>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x244): ifru_ivalue
DW_AT_type        : <0x82>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 153
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><137>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x250): ifru_mtu
DW_AT_type        : <0x82>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 154
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><145>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x259): ifru_map
DW_AT_type        : <0x1ec>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 155
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><153>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2b1): ifru_slave
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 156
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><161>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2bc): ifru_newname
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 157
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><16f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2c9): ifru_data
DW_AT_type        : <0x257>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 158
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><17d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2d3): ifru_settings
DW_AT_type        : <0x258>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 159
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><18d>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0x8e>
<2><192>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0x19a>
DW_AT_lower_bound : 0
DW_AT_count       : 16
<1><19a>
Abbrev Number: 11 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ac): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><1a1>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1f5): sockaddr
DW_AT_byte_size   : 16
DW_AT_decl_file   : 3
DW_AT_decl_line   : 74
<2><1a9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c8): sa_family
DW_AT_type        : <0x1c6>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 75
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1b7>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ed): sa_data
DW_AT_type        : <0x1d8>
DW_AT_decl_file   : 3
DW_AT_decl_line   : 76
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><1c6>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x1d1>
DW_AT_name        : (indirect string, offset: 0x1e1): sa_family_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 34
<1><1d1>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1d2): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><1d8>
Abbrev Number: 9 (DW_TAG_array_type)
DW_AT_type        : <0x8e>
<2><1dd>
Abbrev Number: 10 (DW_TAG_subrange_type)
DW_AT_type        : <0x19a>
DW_AT_lower_bound : 0
DW_AT_count       : 14
<1><1e5>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x23e): short
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 2
<1><1ec>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2ab): ifmap
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 118
<2><1f4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x262): mem_start
DW_AT_type        : <0x249>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 119
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><202>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x27e): mem_end
DW_AT_type        : <0x249>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 120
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><210>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x286): base_addr
DW_AT_type        : <0x1d1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 121
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><21e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x290): irq
DW_AT_type        : <0x250>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 122
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><22c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2a2): dma
DW_AT_type        : <0x250>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 123
DW_AT_data_member_location: 2 byte block: 23 b 	(DW_OP_plus_uconst: 11)
<2><23a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2a6): port
DW_AT_type        : <0x250>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 124
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><249>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x26c): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><250>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x294): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><257>
Abbrev Number: 12 (DW_TAG_pointer_type)
<1><258>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x40a): if_settings
DW_AT_byte_size   : 12
DW_AT_decl_file   : 1
DW_AT_decl_line   : 127
<2><260>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2e1): type
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 128
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><26e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f3): size
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 129
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><27c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2f8): ifs_ifsu
DW_AT_type        : <0x28a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 138
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><28a>
Abbrev Number: 6 (DW_TAG_union_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 1
DW_AT_decl_line   : 130
<3><28e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x301): raw_hdlc
DW_AT_type        : <0x2f9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 131
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><29c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x329): cisco
DW_AT_type        : <0x32a>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 132
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2aa>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x34c): fr
DW_AT_type        : <0x35b>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 133
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2b8>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x379): fr_pvc
DW_AT_type        : <0x3d2>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 134
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2c6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x392): fr_pvc_info
DW_AT_type        : <0x3f5>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 135
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2d4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3b7): sync
DW_AT_type        : <0x426>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 136
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><2e2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3f0): te1
DW_AT_type        : <0x465>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 137
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><2f2>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x2e6): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><2f9>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x2fe>
<1><2fe>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x309>
DW_AT_name        : (indirect string, offset: 0x31a): raw_hdlc_proto
DW_AT_decl_file   : 4
DW_AT_decl_line   : 61
<1><309>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 4
DW_AT_decl_line   : 58
<2><30d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x30a): encoding
DW_AT_type        : <0x1d1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 59
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><31b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x313): parity
DW_AT_type        : <0x1d1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 60
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><32a>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x32f>
<1><32f>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x33a>
DW_AT_name        : (indirect string, offset: 0x340): cisco_proto
DW_AT_decl_file   : 4
DW_AT_decl_line   : 81
<1><33a>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 78
<2><33e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32f): interval
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 79
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><34c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x338): timeout
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 80
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><35b>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x360>
<1><360>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x36b>
DW_AT_name        : (indirect string, offset: 0x370): fr_proto
DW_AT_decl_file   : 4
DW_AT_decl_line   : 70
<1><36b>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 24
DW_AT_decl_file   : 4
DW_AT_decl_line   : 62
<2><36f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x34f): t391
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 63
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><37d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x354): t392
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 64
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><38b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x359): n391
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 65
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><399>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x35e): n392
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 66
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><3a7>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x363): n393
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 67
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><3b5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x368): lmi
DW_AT_type        : <0x1d1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 68
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><3c3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x36c): dce
DW_AT_type        : <0x1d1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 69
DW_AT_data_member_location: 2 byte block: 23 16 	(DW_OP_plus_uconst: 22)
<1><3d2>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x3d7>
<1><3d7>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3e2>
DW_AT_name        : (indirect string, offset: 0x385): fr_proto_pvc
DW_AT_decl_file   : 4
DW_AT_decl_line   : 73
<1><3e2>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 4
DW_AT_decl_file   : 4
DW_AT_decl_line   : 71
<2><3e6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x380): dlci
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 72
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><3f5>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x3fa>
<1><3fa>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x405>
DW_AT_name        : (indirect string, offset: 0x3a5): fr_proto_pvc_info
DW_AT_decl_file   : 4
DW_AT_decl_line   : 77
<1><405>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 20
DW_AT_decl_file   : 4
DW_AT_decl_line   : 74
<2><409>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x380): dlci
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 75
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><417>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x39e): master
DW_AT_type        : <0x18d>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 76
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><426>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x42b>
<1><42b>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x436>
DW_AT_name        : (indirect string, offset: 0x3db): sync_serial_settings
DW_AT_decl_file   : 4
DW_AT_decl_line   : 51
<1><436>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 12
DW_AT_decl_file   : 4
DW_AT_decl_line   : 47
<2><43a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3bc): clock_rate
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 48
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><448>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3c7): clock_type
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 49
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><456>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3d2): loopback
DW_AT_type        : <0x1d1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 50
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><465>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x46a>
<1><46a>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x475>
DW_AT_name        : (indirect string, offset: 0x3fd): te1_settings
DW_AT_decl_file   : 4
DW_AT_decl_line   : 57
<1><475>
Abbrev Number: 13 (DW_TAG_structure_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 4
DW_AT_decl_line   : 52
<2><479>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3bc): clock_rate
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 53
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><487>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3c7): clock_type
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 54
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><495>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3d2): loopback
DW_AT_type        : <0x1d1>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 55
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><4a3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3f4): slot_map
DW_AT_type        : <0x2f2>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 56
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
