<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x96): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x14a): struct_v4l2_input
DW_AT_decl_file   : 3
DW_AT_decl_line   : 50
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x13f): v4l2_input
DW_AT_byte_size   : 80
DW_AT_decl_file   : 2
DW_AT_decl_line   : 728
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa7): index
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 729
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><53>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc0): name
DW_AT_type        : <0xde>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 730
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><62>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe1): type
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 731
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><71>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe6): audioset
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 732
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><80>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xef): tuner
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 733
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><8f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf5): std
DW_AT_type        : <0x104>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 734
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><9e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x122): status
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 735
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><ad>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x129): capabilities
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 736
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><bc>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x136): reserved
DW_AT_type        : <0x122>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 737
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<1><cc>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xd7>
DW_AT_name        : (indirect string, offset: 0xba): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><d7>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xad): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><de>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0xeb>
<2><e3>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0xfd>
DW_AT_lower_bound : 0
DW_AT_count       : 32
<1><eb>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf6>
DW_AT_name        : (indirect string, offset: 0xd3): __u8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
<1><f6>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc5): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><fd>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xd8): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><104>
Abbrev Number: 10 (DW_TAG_typedef)
DW_AT_type        : <0x110>
DW_AT_name        : (indirect string, offset: 0x116): v4l2_std_id
DW_AT_decl_file   : 2
DW_AT_decl_line   : 591
<1><110>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x11b>
DW_AT_name        : (indirect string, offset: 0x110): __u64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
<1><11b>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xf9): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><122>
Abbrev Number: 7 (DW_TAG_array_type)
DW_AT_type        : <0xcc>
<2><127>
Abbrev Number: 8 (DW_TAG_subrange_type)
DW_AT_type        : <0xfd>
DW_AT_lower_bound : 0
DW_AT_count       : 3
