<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xa0): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 1
DW_AT_decl_line   : 65
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x177): struct_blk_user_trace_setup
DW_AT_decl_file   : 1
DW_AT_decl_line   : 63
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x162): blk_user_trace_setup
DW_AT_byte_size   : 72
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb1): name
DW_AT_type        : <0xa6>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 56
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc4): act_mask
DW_AT_type        : <0xc1>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 57
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf0): buf_size
DW_AT_type        : <0xde>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 58
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11a): buf_nr
DW_AT_type        : <0xde>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 59
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x121): start_lba
DW_AT_type        : <0xfb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 60
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x156): end_lba
DW_AT_type        : <0xfb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 61
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x15e): pid
DW_AT_type        : <0xde>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 62
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<1><a6>
Abbrev Number: 6 (DW_TAG_array_type)
DW_AT_type        : <0xb3>
<2><ab>
Abbrev Number: 7 (DW_TAG_subrange_type)
DW_AT_type        : <0xba>
DW_AT_lower_bound : 0
DW_AT_count       : 32
<1><b3>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xb6): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><ba>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xbb): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><c1>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xcc>
DW_AT_name        : (indirect string, offset: 0xe7): uint16_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 62
<1><cc>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xd7>
DW_AT_name        : (indirect string, offset: 0xdc): __uint16_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 39
<1><d7>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xcd): unsigned short
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 2
<1><de>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xe9>
DW_AT_name        : (indirect string, offset: 0x111): uint32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 65
<1><e9>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf4>
DW_AT_name        : (indirect string, offset: 0x106): __uint32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 41
<1><f4>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xf9): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><fb>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x106>
DW_AT_name        : (indirect string, offset: 0x14d): uint64_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 68
<1><106>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x111>
DW_AT_name        : (indirect string, offset: 0x142): __uint64_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 47
<1><111>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x12b): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
