<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x24d): signed char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x203): short int
<1><2b>
Abbrev Number: 3 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><32>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x1e6): long long int
<1><39>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0xe3): unsigned char
<1><40>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x25): short unsigned int
<1><47>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x160): unsigned int
<1><4e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x6b): long long unsigned int
<1><55>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x233): long int
<1><5c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xa0): long unsigned int
<1><63>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x1dd): sizetype
<1><6a>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x4e): __caddr_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 183
DW_AT_type        : <0x75>
<1><75>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x7b>
<1><7b>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x17b): char
<1><82>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x88>
<1><88>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0x7b>
<1><8d>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xbf): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 1
DW_AT_decl_line   : 4
DW_AT_sibling     : <0xe0>
<2><99>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20d): nargs
DW_AT_decl_file   : 1
DW_AT_decl_line   : 5
DW_AT_type        : <0x47>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><a7>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x61): sys_flags
DW_AT_decl_file   : 1
DW_AT_decl_line   : 6
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><b5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 1
DW_AT_decl_line   : 7
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><c3>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x295): sys_func
DW_AT_decl_file   : 1
DW_AT_decl_line   : 8
DW_AT_type        : <0xeb>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><d1>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x45): sys_name
DW_AT_decl_file   : 1
DW_AT_decl_line   : 9
DW_AT_type        : <0x82>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><e0>
Abbrev Number: 10 (DW_TAG_subroutine_type)
DW_AT_type        : <0x2b>
DW_AT_sibling     : <0xeb>
<2><e9>
Abbrev Number: 11 (DW_TAG_unspecified_parameters)
<1><eb>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xe0>
<1><f1>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x16d): struct_sysent
DW_AT_decl_file   : 1
DW_AT_decl_line   : 10
DW_AT_type        : <0x8d>
<1><fc>
Abbrev Number: 5 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x102>
<1><102>
Abbrev Number: 6 (DW_TAG_const_type)
DW_AT_type        : <0xf1>
<1><107>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x1f): _Bool
<1><10e>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xd7): sa_family_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 28
DW_AT_type        : <0x40>
<1><119>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x23c): sockaddr
DW_AT_byte_size   : 16
DW_AT_decl_file   : 4
DW_AT_decl_line   : 149
DW_AT_sibling     : <0x142>
<2><125>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f4): sa_family
DW_AT_decl_file   : 4
DW_AT_decl_line   : 151
DW_AT_type        : <0x10e>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><133>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x245): sa_data
DW_AT_decl_file   : 4
DW_AT_decl_line   : 152
DW_AT_type        : <0x142>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<1><142>
Abbrev Number: 12 (DW_TAG_array_type)
DW_AT_type        : <0x7b>
DW_AT_sibling     : <0x152>
<2><14b>
Abbrev Number: 13 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 13
<1><152>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x0): ifmap
DW_AT_byte_size   : 16
DW_AT_decl_file   : 5
DW_AT_decl_line   : 111
DW_AT_sibling     : <0x1b3>
<2><15e>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x259): mem_start
DW_AT_decl_file   : 5
DW_AT_decl_line   : 113
DW_AT_type        : <0x5c>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><16c>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6): mem_end
DW_AT_decl_file   : 5
DW_AT_decl_line   : 114
DW_AT_type        : <0x5c>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><17a>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14d): base_addr
DW_AT_decl_file   : 5
DW_AT_decl_line   : 115
DW_AT_type        : <0x40>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><188>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : irq
DW_AT_decl_file   : 5
DW_AT_decl_line   : 116
DW_AT_type        : <0x39>
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<2><196>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : dma
DW_AT_decl_file   : 5
DW_AT_decl_line   : 117
DW_AT_type        : <0x39>
DW_AT_data_member_location: 2 byte block: 23 b 	(DW_OP_plus_uconst: 11)
<2><1a4>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fe): port
DW_AT_decl_file   : 5
DW_AT_decl_line   : 118
DW_AT_type        : <0x39>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><1b3>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 5
DW_AT_decl_line   : 130
DW_AT_sibling     : <0x1c7>
<2><1bb>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf1): ifrn_name
DW_AT_decl_file   : 5
DW_AT_decl_line   : 132
DW_AT_type        : <0x1c7>
<1><1c7>
Abbrev Number: 12 (DW_TAG_array_type)
DW_AT_type        : <0x7b>
DW_AT_sibling     : <0x1d7>
<2><1d0>
Abbrev Number: 13 (DW_TAG_subrange_type)
DW_AT_type        : <0x63>
DW_AT_upper_bound : 15
<1><1d7>
Abbrev Number: 14 (DW_TAG_union_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 5
DW_AT_decl_line   : 135
DW_AT_sibling     : <0x264>
<2><1df>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x82): ifru_addr
DW_AT_decl_file   : 5
DW_AT_decl_line   : 137
DW_AT_type        : <0x119>
<2><1ea>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x38): ifru_dstaddr
DW_AT_decl_file   : 5
DW_AT_decl_line   : 138
DW_AT_type        : <0x119>
<2><1f5>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x224): ifru_broadaddr
DW_AT_decl_file   : 5
DW_AT_decl_line   : 139
DW_AT_type        : <0x119>
<2><200>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x26f): ifru_netmask
DW_AT_decl_file   : 5
DW_AT_decl_line   : 140
DW_AT_type        : <0x119>
<2><20b>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x263): ifru_hwaddr
DW_AT_decl_file   : 5
DW_AT_decl_line   : 141
DW_AT_type        : <0x119>
<2><216>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8c): ifru_flags
DW_AT_decl_file   : 5
DW_AT_decl_line   : 142
DW_AT_type        : <0x24>
<2><221>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d1): ifru_ivalue
DW_AT_decl_file   : 5
DW_AT_decl_line   : 143
DW_AT_type        : <0x2b>
<2><22c>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x97): ifru_mtu
DW_AT_decl_file   : 5
DW_AT_decl_line   : 144
DW_AT_type        : <0x2b>
<2><237>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x58): ifru_map
DW_AT_decl_file   : 5
DW_AT_decl_line   : 145
DW_AT_type        : <0x152>
<2><242>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x213): ifru_slave
DW_AT_decl_file   : 5
DW_AT_decl_line   : 146
DW_AT_type        : <0x1c7>
<2><24d>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c4): ifru_newname
DW_AT_decl_file   : 5
DW_AT_decl_line   : 147
DW_AT_type        : <0x1c7>
<2><258>
Abbrev Number: 15 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x143): ifru_data
DW_AT_decl_file   : 5
DW_AT_decl_line   : 148
DW_AT_type        : <0x6a>
<1><264>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x21e): ifreq
DW_AT_byte_size   : 32
DW_AT_decl_file   : 5
DW_AT_decl_line   : 126
DW_AT_sibling     : <0x28d>
<2><270>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x157): ifr_ifrn
DW_AT_decl_file   : 5
DW_AT_decl_line   : 133
DW_AT_type        : <0x1b3>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><27e>
Abbrev Number: 8 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): ifr_ifru
DW_AT_decl_file   : 5
DW_AT_decl_line   : 149
DW_AT_type        : <0x1d7>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><28d>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xb2): struct_ifreq
DW_AT_decl_file   : 6
DW_AT_decl_line   : 40
DW_AT_type        : <0x264>
<1><298>
Abbrev Number: 16 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc6): current_wordsize
DW_AT_decl_file   : 7
DW_AT_decl_line   : 757
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><2a6>
Abbrev Number: 16 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xbf): sysent
DW_AT_decl_file   : 7
DW_AT_decl_line   : 892
DW_AT_type        : <0xfc>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><2b4>
Abbrev Number: 16 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1ba): nsyscalls
DW_AT_decl_file   : 7
DW_AT_decl_line   : 903
DW_AT_type        : <0x47>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><2c2>
Abbrev Number: 17 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe): mpers_target_var
DW_AT_decl_file   : 6
DW_AT_decl_line   : 42
DW_AT_type        : <0x28d>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 20 0 0 0 	(DW_OP_addr: 20)
