<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x165): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 1
DW_AT_decl_line   : 65
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x190): struct_blkpg_ioctl_arg
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 36
<2><40>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x176): op
DW_AT_type        : <0x79>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><4e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17d): flags
DW_AT_type        : <0x79>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x183): datalen
DW_AT_type        : <0x79>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18b): data
DW_AT_type        : <0x80>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><79>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x179): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><80>
Abbrev Number: 7 (DW_TAG_pointer_type)
