<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xa3): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 47
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x1c5): struct_btrfs_ioctl_vol_args_v2
DW_AT_decl_file   : 3
DW_AT_decl_line   : 43
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1ad): btrfs_ioctl_vol_args_v2
DW_AT_byte_size   : 4096
DW_AT_decl_file   : 2
DW_AT_decl_line   : 67
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xb4): fd
DW_AT_type        : <0xe3>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 68
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcb): transid
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 69
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf0): flags
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 70
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><6e>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_type        : <0x78>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 71
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><78>
Abbrev Number: 7 (DW_TAG_union_type)
DW_AT_byte_size   : 32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 71
<3><7c>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_type        : <0x86>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 72
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><86>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 72
<4><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf6): size
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 73
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<4><98>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfb): qgroup_inherit
DW_AT_type        : <0x107>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 74
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<3><a7>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x196): unused
DW_AT_type        : <0x1cc>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 76
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b6>
Abbrev Number: 6 (DW_TAG_member)
DW_AT_type        : <0xc0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 78
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><c0>
Abbrev Number: 9 (DW_TAG_union_type)
DW_AT_byte_size   : 4040
DW_AT_decl_file   : 2
DW_AT_decl_line   : 78
<3><c5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19d): name
DW_AT_type        : <0x1d9>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 79
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<3><d3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a7): devid
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 80
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><e3>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xee>
DW_AT_name        : (indirect string, offset: 0xc5): __s64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
<1><ee>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xb7): long long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 8
<1><f5>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x100>
DW_AT_name        : (indirect string, offset: 0xea): __u64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
<1><100>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xd3): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><107>
Abbrev Number: 11 (DW_TAG_pointer_type)
DW_AT_type        : <0x10c>
<1><10c>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x181): btrfs_qgroup_inherit
DW_AT_byte_size   : 72
DW_AT_decl_file   : 2
DW_AT_decl_line   : 51
<2><114>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf0): flags
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 52
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><122>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10a): num_qgroups
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 53
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><130>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x116): num_ref_copies
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 54
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><13e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x125): num_excl_copies
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 55
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><14c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x135): lim
DW_AT_type        : <0x169>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 56
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><15a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x170): qgroups
DW_AT_type        : <0x1b8>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 57
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<1><169>
Abbrev Number: 12 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x15d): btrfs_qgroup_limit
DW_AT_byte_size   : 40
DW_AT_decl_file   : 2
DW_AT_decl_line   : 43
<2><171>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf0): flags
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 44
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><17f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x139): max_rfer
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 45
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><18d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x142): max_excl
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 46
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><19b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14b): rsv_rfer
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 47
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><1a9>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x154): rsv_excl
DW_AT_type        : <0xf5>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 48
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<1><1b8>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0xf5>
<2><1bd>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x1c5>
DW_AT_lower_bound : 0
DW_AT_count       : 0
<1><1c5>
Abbrev Number: 15 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x178): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><1cc>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0xf5>
<2><1d1>
Abbrev Number: 14 (DW_TAG_subrange_type)
DW_AT_type        : <0x1c5>
DW_AT_lower_bound : 0
DW_AT_count       : 4
<1><1d9>
Abbrev Number: 13 (DW_TAG_array_type)
DW_AT_type        : <0x1e7>
<2><1de>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x1c5>
DW_AT_lower_bound : 0
DW_AT_count       : 4040
<1><1e7>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1a2): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
