<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15c): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 37
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x211): struct_statfs
DW_AT_decl_file   : 3
DW_AT_decl_line   : 34
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x20a): statfs
DW_AT_byte_size   : 64
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16d): f_type
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18d): f_bsize
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x195): f_blocks
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 32
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19e): f_bfree
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 33
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7c>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a6): f_bavail
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 34
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><8a>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1af): f_files
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 35
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><98>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b7): f_ffree
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 36
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><a6>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bf): f_fsid
DW_AT_type        : <0xff>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 37
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><b4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e7): f_namelen
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 38
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><c2>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f1): f_frsize
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 39
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><d0>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1fa): f_flags
DW_AT_type        : <0xed>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 40
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><de>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x202): f_spare
DW_AT_type        : <0x138>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 41
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<1><ed>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf8>
DW_AT_name        : (indirect string, offset: 0x17d): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><f8>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x174): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><ff>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x10a>
DW_AT_name        : (indirect string, offset: 0x1d7): __kernel_fsid_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 73
<1><10a>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 71
<2><10e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c6): val
DW_AT_type        : <0x11d>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 72
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><11d>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0x12a>
<2><122>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x131>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><12a>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ca): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><131>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ce): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><138>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0xed>
<2><13d>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x131>
DW_AT_lower_bound : 0
DW_AT_count       : 4
