<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xac): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 47
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x16c): struct_btrfs_ioctl_received_subvol_args
DW_AT_decl_file   : 3
DW_AT_decl_line   : 41
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x14b): btrfs_ioctl_received_subvol_args
DW_AT_byte_size   : 200
DW_AT_decl_file   : 1
DW_AT_decl_line   : 386
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbd): uuid
DW_AT_type        : <0xae>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 387
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><53>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd0): stransid
DW_AT_type        : <0xc9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 388
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><62>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf6): rtransid
DW_AT_type        : <0xc9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 389
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><71>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xff): stime
DW_AT_type        : <0xdb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 390
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><80>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x136): rtime
DW_AT_type        : <0xdb>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 391
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><8f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13c): flags
DW_AT_type        : <0xc9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 392
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><9e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x142): reserved
DW_AT_type        : <0x115>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 393
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<1><ae>
Abbrev Number: 6 (DW_TAG_array_type)
DW_AT_type        : <0xbb>
<2><b3>
Abbrev Number: 7 (DW_TAG_subrange_type)
DW_AT_type        : <0xc2>
DW_AT_lower_bound : 0
DW_AT_count       : 16
<1><bb>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc2): char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><c2>
Abbrev Number: 9 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xc7): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><c9>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xd4>
DW_AT_name        : (indirect string, offset: 0xf0): __u64
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
<1><d4>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xd9): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><db>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x121): btrfs_ioctl_timespec
DW_AT_byte_size   : 16
DW_AT_decl_file   : 1
DW_AT_decl_line   : 382
<2><e4>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x105): sec
DW_AT_type        : <0xc9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 383
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><f3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x109): nsec
DW_AT_type        : <0x103>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 384
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><103>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x10e>
DW_AT_name        : (indirect string, offset: 0x11b): __u32
DW_AT_decl_file   : 2
DW_AT_decl_line   : 28
<1><10e>
Abbrev Number: 8 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x10e): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><115>
Abbrev Number: 6 (DW_TAG_array_type)
DW_AT_type        : <0xc9>
<2><11a>
Abbrev Number: 7 (DW_TAG_subrange_type)
DW_AT_type        : <0xc2>
DW_AT_lower_bound : 0
DW_AT_count       : 16
