<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x16b): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 47
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x211): struct_btrfs_ioctl_send_args
DW_AT_decl_file   : 3
DW_AT_decl_line   : 39
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1fb): btrfs_ioctl_send_args
DW_AT_byte_size   : 72
DW_AT_decl_file   : 2
DW_AT_decl_line   : 401
<2><45>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17c): send_fd
DW_AT_type        : <0xa0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 402
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><54>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x198): clone_sources_count
DW_AT_type        : <0xb2>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 403
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><63>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c9): clone_sources
DW_AT_type        : <0xc4>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 404
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><72>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d7): parent_root
DW_AT_type        : <0xb2>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 405
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><81>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e3): flags
DW_AT_type        : <0xb2>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 406
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><90>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e9): reserved
DW_AT_type        : <0xc9>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 407
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<1><a0>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xab>
DW_AT_name        : (indirect string, offset: 0x192): __s64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 30
<1><ab>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x184): long long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 8
<1><b2>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xbd>
DW_AT_name        : (indirect string, offset: 0x1c3): __u64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
<1><bd>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1ac): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><c4>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_type        : <0xb2>
<1><c9>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0xb2>
<2><ce>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0xd6>
DW_AT_lower_bound : 0
DW_AT_count       : 4
<1><d6>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1f2): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
