<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x163): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 53
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x229): struct_v4l2_standard
DW_AT_decl_file   : 3
DW_AT_decl_line   : 51
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x21b): v4l2_standard
DW_AT_byte_size   : 72
DW_AT_decl_file   : 2
DW_AT_decl_line   : 645
<2><45>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x174): index
DW_AT_type        : <0xa0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 646
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><54>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18d): id
DW_AT_type        : <0xb2>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 647
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><63>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b9): name
DW_AT_type        : <0xd0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 648
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><72>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1da): frameperiod
DW_AT_type        : <0xf6>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 649
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><81>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x207): framelines
DW_AT_type        : <0xa0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 650
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><90>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x212): reserved
DW_AT_type        : <0x11b>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 651
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<1><a0>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xab>
DW_AT_name        : (indirect string, offset: 0x187): __u32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 28
<1><ab>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x17a): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><b2>
Abbrev Number: 7 (DW_TAG_typedef)
DW_AT_type        : <0xbe>
DW_AT_name        : (indirect string, offset: 0x1ad): v4l2_std_id
DW_AT_decl_file   : 2
DW_AT_decl_line   : 598
<1><be>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xc9>
DW_AT_name        : (indirect string, offset: 0x1a7): __u64
DW_AT_decl_file   : 1
DW_AT_decl_line   : 31
<1><c9>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x190): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><d0>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0xdd>
<2><d5>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0xef>
DW_AT_lower_bound : 0
DW_AT_count       : 24
<1><dd>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xe8>
DW_AT_name        : (indirect string, offset: 0x1cc): __u8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 24
<1><e8>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1be): unsigned char
DW_AT_encoding    : 8	(unsigned char)
DW_AT_byte_size   : 1
<1><ef>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1d1): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><f6>
Abbrev Number: 11 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1fc): v4l2_fract
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 141
<2><fe>
Abbrev Number: 12 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1e6): numerator
DW_AT_type        : <0xa0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 142
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><10c>
Abbrev Number: 12 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1f0): denominator
DW_AT_type        : <0xa0>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 143
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><11b>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0xa0>
<2><120>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0xef>
DW_AT_lower_bound : 0
DW_AT_count       : 4
