<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x15d): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 7
DW_AT_decl_line   : 34
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x264): struct_mmsghdr
DW_AT_decl_file   : 7
DW_AT_decl_line   : 32
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x25c): mmsghdr
DW_AT_byte_size   : 32
DW_AT_decl_file   : 1
DW_AT_decl_line   : 94
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16e): msg_hdr
DW_AT_type        : <0x61>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 95
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x254): msg_len
DW_AT_type        : <0x152>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 96
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<1><61>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x24d): msghdr
DW_AT_byte_size   : 28
DW_AT_decl_file   : 1
DW_AT_decl_line   : 84
<2><69>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x176): msg_name
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 85
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><77>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17f): msg_namelen
DW_AT_type        : <0xcd>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 86
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><85>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1b7): msg_iov
DW_AT_type        : <0x100>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 87
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><93>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x209): msg_iovlen
DW_AT_type        : <0x147>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 88
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><a1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x228): msg_control
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 89
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><af>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x234): msg_controllen
DW_AT_type        : <0x147>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 90
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><bd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x243): msg_flags
DW_AT_type        : <0xf9>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 91
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<1><cc>
Abbrev Number: 6 (DW_TAG_pointer_type)
<1><cd>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xd8>
DW_AT_name        : (indirect string, offset: 0x1ad): socklen_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 117
<1><d8>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xe3>
DW_AT_name        : (indirect string, offset: 0x1a1): __socklen_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 112
<1><e3>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xee>
DW_AT_name        : (indirect string, offset: 0x199): int32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 64
<1><ee>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf9>
DW_AT_name        : (indirect string, offset: 0x18f): __int32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 40
<1><f9>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x18b): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><100>
Abbrev Number: 8 (DW_TAG_pointer_type)
DW_AT_type        : <0x105>
<1><105>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x203): iovec
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 23
<2><10d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1bf): iov_base
DW_AT_type        : <0xcc>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><11b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c8): iov_len
DW_AT_type        : <0x12a>
DW_AT_decl_file   : 4
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><12a>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x135>
DW_AT_name        : (indirect string, offset: 0x1f3): __kernel_size_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 65
<1><135>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x140>
DW_AT_name        : (indirect string, offset: 0x1e2): __kernel_ulong_t
DW_AT_decl_file   : 5
DW_AT_decl_line   : 24
<1><140>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x1d0): long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
<1><147>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x152>
DW_AT_name        : (indirect string, offset: 0x221): size_t
DW_AT_decl_file   : 6
DW_AT_decl_line   : 62
<1><152>
Abbrev Number: 7 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x214): unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
