<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x94): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 4
DW_AT_decl_line   : 37
DW_AT_location    : 5 byte block: 3 8 0 0 0 	(DW_OP_addr: 8)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0x168): struct_statfs64
DW_AT_decl_file   : 4
DW_AT_decl_line   : 35
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x15f): statfs64
DW_AT_byte_size   : 88
DW_AT_decl_file   : 2
DW_AT_decl_line   : 46
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa5): f_type
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 47
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc5): f_bsize
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 48
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><5f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcd): f_blocks
DW_AT_type        : <0xfe>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 49
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6d>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf3): f_bfree
DW_AT_type        : <0xfe>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 50
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><7b>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfb): f_bavail
DW_AT_type        : <0xfe>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 51
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><89>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x104): f_files
DW_AT_type        : <0xfe>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 52
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><97>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x10c): f_ffree
DW_AT_type        : <0xfe>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 53
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><a5>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x114): f_fsid
DW_AT_type        : <0x110>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 54
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><b3>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x13c): f_namelen
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 55
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><c1>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x146): f_frsize
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 56
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><cf>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x14f): f_flags
DW_AT_type        : <0xec>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 57
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><dd>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x157): f_spare
DW_AT_type        : <0x149>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 58
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<1><ec>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0xf7>
DW_AT_name        : (indirect string, offset: 0xb5): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><f7>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xac): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><fe>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x109>
DW_AT_name        : (indirect string, offset: 0xed): __u64
DW_AT_decl_file   : 3
DW_AT_decl_line   : 31
<1><109>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xd6): long long unsigned int
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 8
<1><110>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x11b>
DW_AT_name        : (indirect string, offset: 0x12c): __kernel_fsid_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 73
<1><11b>
Abbrev Number: 7 (DW_TAG_structure_type)
DW_AT_byte_size   : 8
DW_AT_decl_file   : 1
DW_AT_decl_line   : 71
<2><11f>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11b): val
DW_AT_type        : <0x12e>
DW_AT_decl_file   : 1
DW_AT_decl_line   : 72
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><12e>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0x13b>
<2><133>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x142>
DW_AT_lower_bound : 0
DW_AT_count       : 2
<1><13b>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x11f): int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><142>
Abbrev Number: 10 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x123): sizetype
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
<1><149>
Abbrev Number: 8 (DW_TAG_array_type)
DW_AT_type        : <0xec>
<2><14e>
Abbrev Number: 9 (DW_TAG_subrange_type)
DW_AT_type        : <0x142>
DW_AT_lower_bound : 0
DW_AT_count       : 4
