<1><1e>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x8f): mpers_target_var
DW_AT_type        : <0x30>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 34
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><30>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3b>
DW_AT_name        : (indirect string, offset: 0xe1): timespec_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 32
<1><3b>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xd8): timespec
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 24
<2><43>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa0): tv_sec
DW_AT_type        : <0x60>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><51>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd0): tv_nsec
DW_AT_type        : <0x76>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><60>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x6b>
DW_AT_name        : (indirect string, offset: 0xc0): __kernel_time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 77
<1><6b>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x76>
DW_AT_name        : (indirect string, offset: 0xb0): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><76>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0xa7): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
