<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x158): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 34
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x1be): timeval_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 32
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1b6): timeval
DW_AT_byte_size   : 8
DW_AT_decl_file   : 2
DW_AT_decl_line   : 29
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x169): tv_sec
DW_AT_type        : <0x61>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 30
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x199): tv_usec
DW_AT_type        : <0x7e>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 31
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><61>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x6c>
DW_AT_name        : (indirect string, offset: 0x189): __kernel_time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 77
<1><6c>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x77>
DW_AT_name        : (indirect string, offset: 0x179): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><77>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x170): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
<1><7e>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x6c>
DW_AT_name        : (indirect string, offset: 0x1a1): __kernel_suseconds_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 43
