<1><1f>
Abbrev Number: 2 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x154): mpers_target_var
DW_AT_type        : <0x31>
DW_AT_external    : 1
DW_AT_decl_file   : 3
DW_AT_decl_line   : 38
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
<1><31>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x3c>
DW_AT_name        : (indirect string, offset: 0x1bd): tms_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 37
<1><3c>
Abbrev Number: 4 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1b9): tms
DW_AT_byte_size   : 16
DW_AT_decl_file   : 2
DW_AT_decl_line   : 22
<2><44>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x165): tms_utime
DW_AT_type        : <0x7d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 23
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><52>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x199): tms_stime
DW_AT_type        : <0x7d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 24
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><60>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a3): tms_cutime
DW_AT_type        : <0x7d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><6e>
Abbrev Number: 5 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ae): tms_cstime
DW_AT_type        : <0x7d>
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<1><7d>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x88>
DW_AT_name        : (indirect string, offset: 0x188): __kernel_clock_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 78
<1><88>
Abbrev Number: 3 (DW_TAG_typedef)
DW_AT_type        : <0x93>
DW_AT_name        : (indirect string, offset: 0x178): __kernel_long_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 23
<1><93>
Abbrev Number: 6 (DW_TAG_base_type)
DW_AT_name        : (indirect string, offset: 0x16f): long int
DW_AT_encoding    : 5	(signed)
DW_AT_byte_size   : 4
