/* Generated by ./xlat/gen.sh from ./xlat/at_flags.in; do not edit. */

const struct xlat at_flags[] = {
#if !(defined(AT_SYMLINK_NOFOLLOW) || (defined(HAVE_DECL_AT_SYMLINK_NOFOLLOW) && HAVE_DECL_AT_SYMLINK_NOFOLLOW))
# define AT_SYMLINK_NOFOLLOW 0x100
#endif
 XLAT(AT_SYMLINK_NOFOLLOW),
#if !(defined(AT_REMOVEDIR) || (defined(HAVE_DECL_AT_REMOVEDIR) && HAVE_DECL_AT_REMOVEDIR))
# define AT_REMOVEDIR 0x200
#endif
 XLAT(AT_REMOVEDIR),
#if !(defined(AT_SYMLINK_FOLLOW) || (defined(HAVE_DECL_AT_SYMLINK_FOLLOW) && HAVE_DECL_AT_SYMLINK_FOLLOW))
# define AT_SYMLINK_FOLLOW 0x400
#endif
 XLAT(AT_SYMLINK_FOLLOW),
#if !(defined(AT_NO_AUTOMOUNT) || (defined(HAVE_DECL_AT_NO_AUTOMOUNT) && HAVE_DECL_AT_NO_AUTOMOUNT))
# define AT_NO_AUTOMOUNT 0x800
#endif
 XLAT(AT_NO_AUTOMOUNT),
#if !(defined(AT_EMPTY_PATH) || (defined(HAVE_DECL_AT_EMPTY_PATH) && HAVE_DECL_AT_EMPTY_PATH))
# define AT_EMPTY_PATH 0x1000
#endif
 XLAT(AT_EMPTY_PATH),
 XLAT_END
};
