/* Generated by ./xlat/gen.sh from ./xlat/at_statx_sync_types.in; do not edit. */
#if !(defined(AT_STATX_SYNC_AS_STAT) || (defined(HAVE_DECL_AT_STATX_SYNC_AS_STAT) && HAVE_DECL_AT_STATX_SYNC_AS_STAT))
# define AT_STATX_SYNC_AS_STAT 0x0000
#endif
#if !(defined(AT_STATX_FORCE_SYNC) || (defined(HAVE_DECL_AT_STATX_FORCE_SYNC) && HAVE_DECL_AT_STATX_FORCE_SYNC))
# define AT_STATX_FORCE_SYNC 0x2000
#endif
#if !(defined(AT_STATX_DONT_SYNC) || (defined(HAVE_DECL_AT_STATX_DONT_SYNC) && HAVE_DECL_AT_STATX_DONT_SYNC))
# define AT_STATX_DONT_SYNC 0x4000
#endif
#if !(defined(AT_STATX_SYNC_TYPE) || (defined(HAVE_DECL_AT_STATX_SYNC_TYPE) && HAVE_DECL_AT_STATX_SYNC_TYPE))
# define AT_STATX_SYNC_TYPE 0x6000
#endif

#ifdef IN_MPERS

# error static const struct xlat at_statx_sync_types in mpers mode

#else

static
const struct xlat at_statx_sync_types[] = {
 XLAT(AT_STATX_SYNC_AS_STAT),
 XLAT(AT_STATX_FORCE_SYNC),
 XLAT(AT_STATX_DONT_SYNC),

 XLAT(AT_STATX_SYNC_TYPE),
 XLAT_END
};

#endif /* !IN_MPERS */
