/* Generated by ./xlat/gen.sh from ./xlat/bpf_file_mode_flags.in; do not edit. */
#if !(defined(BPF_F_RDONLY) || (defined(HAVE_DECL_BPF_F_RDONLY) && HAVE_DECL_BPF_F_RDONLY))
# define BPF_F_RDONLY (1U << 3)
#endif
#if !(defined(BPF_F_WRONLY) || (defined(HAVE_DECL_BPF_F_WRONLY) && HAVE_DECL_BPF_F_WRONLY))
# define BPF_F_WRONLY (1U << 4)
#endif

#ifdef IN_MPERS

# error static const struct xlat bpf_file_mode_flags in mpers mode

#else

static
const struct xlat bpf_file_mode_flags[] = {
 XLAT(BPF_F_RDONLY),
 XLAT(BPF_F_WRONLY),
 XLAT_END
};

#endif /* !IN_MPERS */
