/* Generated by ./xlat/gen.sh from ./xlat/bpf_map_types.in; do not edit. */

static const struct xlat bpf_map_types[] = {
#if !(defined(BPF_MAP_TYPE_UNSPEC) || (defined(HAVE_DECL_BPF_MAP_TYPE_UNSPEC) && HAVE_DECL_BPF_MAP_TYPE_UNSPEC))
# define BPF_MAP_TYPE_UNSPEC 0
#endif
 XLAT(BPF_MAP_TYPE_UNSPEC),
#if !(defined(BPF_MAP_TYPE_HASH) || (defined(HAVE_DECL_BPF_MAP_TYPE_HASH) && HAVE_DECL_BPF_MAP_TYPE_HASH))
# define BPF_MAP_TYPE_HASH 1
#endif
 XLAT(BPF_MAP_TYPE_HASH),
#if !(defined(BPF_MAP_TYPE_ARRAY) || (defined(HAVE_DECL_BPF_MAP_TYPE_ARRAY) && HAVE_DECL_BPF_MAP_TYPE_ARRAY))
# define BPF_MAP_TYPE_ARRAY 2
#endif
 XLAT(BPF_MAP_TYPE_ARRAY),
#if !(defined(BPF_MAP_TYPE_PROG_ARRAY) || (defined(HAVE_DECL_BPF_MAP_TYPE_PROG_ARRAY) && HAVE_DECL_BPF_MAP_TYPE_PROG_ARRAY))
# define BPF_MAP_TYPE_PROG_ARRAY 3
#endif
 XLAT(BPF_MAP_TYPE_PROG_ARRAY),
 XLAT_END
};
