/* Generated by ./xlat/gen.sh from ./xlat/bpf_map_update_elem_flags.in; do not edit. */

static const struct xlat bpf_map_update_elem_flags[] = {
#if !(defined(BPF_ANY) || (defined(HAVE_DECL_BPF_ANY) && HAVE_DECL_BPF_ANY))
# define BPF_ANY 0
#endif
 XLAT(BPF_ANY),
#if !(defined(BPF_NOEXIST) || (defined(HAVE_DECL_BPF_NOEXIST) && HAVE_DECL_BPF_NOEXIST))
# define BPF_NOEXIST 1
#endif
 XLAT(BPF_NOEXIST),
#if !(defined(BPF_EXIST) || (defined(HAVE_DECL_BPF_EXIST) && HAVE_DECL_BPF_EXIST))
# define BPF_EXIST 2
#endif
 XLAT(BPF_EXIST),
 XLAT_END
};
