/* Generated by ./xlat/gen.sh from ./xlat/bpf_attach_flags.in; do not edit. */
#if !(defined(BPF_F_ALLOW_OVERRIDE) || (defined(HAVE_DECL_BPF_F_ALLOW_OVERRIDE) && HAVE_DECL_BPF_F_ALLOW_OVERRIDE))
# define BPF_F_ALLOW_OVERRIDE 1
#endif

#ifdef IN_MPERS

# error static const struct xlat bpf_attach_flags in mpers mode

#else

static
const struct xlat bpf_attach_flags[] = {
 XLAT(BPF_F_ALLOW_OVERRIDE),
 XLAT_END
};

#endif /* !IN_MPERS */
