/* Generated by ./xlat/gen.sh from ./xlat/bpf_commands.in; do not edit. */

static const struct xlat bpf_commands[] = {
#if !(defined(BPF_MAP_CREATE) || (defined(HAVE_DECL_BPF_MAP_CREATE) && HAVE_DECL_BPF_MAP_CREATE))
# define BPF_MAP_CREATE 0
#endif
 XLAT(BPF_MAP_CREATE),
#if !(defined(BPF_MAP_LOOKUP_ELEM) || (defined(HAVE_DECL_BPF_MAP_LOOKUP_ELEM) && HAVE_DECL_BPF_MAP_LOOKUP_ELEM))
# define BPF_MAP_LOOKUP_ELEM 1
#endif
 XLAT(BPF_MAP_LOOKUP_ELEM),
#if !(defined(BPF_MAP_UPDATE_ELEM) || (defined(HAVE_DECL_BPF_MAP_UPDATE_ELEM) && HAVE_DECL_BPF_MAP_UPDATE_ELEM))
# define BPF_MAP_UPDATE_ELEM 2
#endif
 XLAT(BPF_MAP_UPDATE_ELEM),
#if !(defined(BPF_MAP_DELETE_ELEM) || (defined(HAVE_DECL_BPF_MAP_DELETE_ELEM) && HAVE_DECL_BPF_MAP_DELETE_ELEM))
# define BPF_MAP_DELETE_ELEM 3
#endif
 XLAT(BPF_MAP_DELETE_ELEM),
#if !(defined(BPF_MAP_GET_NEXT_KEY) || (defined(HAVE_DECL_BPF_MAP_GET_NEXT_KEY) && HAVE_DECL_BPF_MAP_GET_NEXT_KEY))
# define BPF_MAP_GET_NEXT_KEY 4
#endif
 XLAT(BPF_MAP_GET_NEXT_KEY),
#if !(defined(BPF_PROG_LOAD) || (defined(HAVE_DECL_BPF_PROG_LOAD) && HAVE_DECL_BPF_PROG_LOAD))
# define BPF_PROG_LOAD 5
#endif
 XLAT(BPF_PROG_LOAD),
 XLAT_END
};
