/* Generated by ./xlat/gen.sh from ./xlat/btrfs_compress_types.in; do not edit. */
#if !(defined(BTRFS_COMPRESS_NONE) || (defined(HAVE_DECL_BTRFS_COMPRESS_NONE) && HAVE_DECL_BTRFS_COMPRESS_NONE))
# define BTRFS_COMPRESS_NONE 0
#endif
#if !(defined(BTRFS_COMPRESS_ZLIB) || (defined(HAVE_DECL_BTRFS_COMPRESS_ZLIB) && HAVE_DECL_BTRFS_COMPRESS_ZLIB))
# define BTRFS_COMPRESS_ZLIB 1
#endif
#if !(defined(BTRFS_COMPRESS_LZO) || (defined(HAVE_DECL_BTRFS_COMPRESS_LZO) && HAVE_DECL_BTRFS_COMPRESS_LZO))
# define BTRFS_COMPRESS_LZO 2
#endif

#ifdef IN_MPERS

extern const struct xlat btrfs_compress_types[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat btrfs_compress_types[] = {
 XLAT(BTRFS_COMPRESS_NONE),
 XLAT(BTRFS_COMPRESS_ZLIB),
 XLAT(BTRFS_COMPRESS_LZO),
 XLAT_END
};

#endif /* !IN_MPERS */
