/* Generated by ./xlat/gen.sh from ./xlat/btrfs_features_compat.in; do not edit. */

#ifdef IN_MPERS

extern const struct xlat btrfs_features_compat[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat btrfs_features_compat[] = {
 XLAT_END
};

#endif /* !IN_MPERS */
