/* Generated by ./xlat/gen.sh from ./xlat/btrfs_dev_stats_flags.in; do not edit. */

#ifdef IN_MPERS

extern const struct xlat btrfs_dev_stats_flags[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat btrfs_dev_stats_flags[] = {
#if defined(BTRFS_DEV_STATS_RESET) || (defined(HAVE_DECL_BTRFS_DEV_STATS_RESET) && HAVE_DECL_BTRFS_DEV_STATS_RESET)
  XLAT_TYPE(uint64_t, BTRFS_DEV_STATS_RESET),
#endif
 XLAT_END
};

#endif /* !IN_MPERS */
