/* Generated by ./xlat/gen.sh from ./xlat/btrfs_scrub_flags.in; do not edit. */
#if !(defined(BTRFS_SCRUB_READONLY) || (defined(HAVE_DECL_BTRFS_SCRUB_READONLY) && HAVE_DECL_BTRFS_SCRUB_READONLY))
# define BTRFS_SCRUB_READONLY 1
#endif

#ifdef IN_MPERS

extern const struct xlat btrfs_scrub_flags[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat btrfs_scrub_flags[] = {
 XLAT_TYPE(uint64_t, BTRFS_SCRUB_READONLY),
 XLAT_END
};

#endif /* !IN_MPERS */
