/* Generated by ./xlat/gen.sh from ./xlat/btrfs_qgroup_status_flags.in; do not edit. */
#if !(defined(BTRFS_QGROUP_STATUS_FLAG_ON) || (defined(HAVE_DECL_BTRFS_QGROUP_STATUS_FLAG_ON) && HAVE_DECL_BTRFS_QGROUP_STATUS_FLAG_ON))
# define BTRFS_QGROUP_STATUS_FLAG_ON (1ULL << 0)
#endif
#if !(defined(BTRFS_QGROUP_STATUS_FLAG_RESCAN) || (defined(HAVE_DECL_BTRFS_QGROUP_STATUS_FLAG_RESCAN) && HAVE_DECL_BTRFS_QGROUP_STATUS_FLAG_RESCAN))
# define BTRFS_QGROUP_STATUS_FLAG_RESCAN (1ULL << 1)
#endif

#ifdef IN_MPERS

extern const struct xlat btrfs_qgroup_status_flags[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat btrfs_qgroup_status_flags[] = {
 XLAT_TYPE(uint64_t, BTRFS_QGROUP_STATUS_FLAG_ON),
 XLAT_TYPE(uint64_t, BTRFS_QGROUP_STATUS_FLAG_RESCAN),
 XLAT_END
};

#endif /* !IN_MPERS */
