/* Generated by ./xlat/gen.sh from ./xlat/evdev_autorepeat.in; do not edit. */

#ifdef IN_MPERS

extern const struct xlat evdev_autorepeat[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat evdev_autorepeat[] = {
#if defined(REP_DELAY) || (defined(HAVE_DECL_REP_DELAY) && HAVE_DECL_REP_DELAY)
  XLAT(REP_DELAY),
#endif
#if defined(REP_PERIOD) || (defined(HAVE_DECL_REP_PERIOD) && HAVE_DECL_REP_PERIOD)
  XLAT(REP_PERIOD),
#endif
 XLAT_END
};

#endif /* !IN_MPERS */
