/* Generated by ./xlat/gen.sh from ./xlat/evdev_keycode.in; do not edit. */
#if !(defined(KEY_RESERVED) || (defined(HAVE_DECL_KEY_RESERVED) && HAVE_DECL_KEY_RESERVED))
# define KEY_RESERVED 0
#endif
#if !(defined(KEY_ESC) || (defined(HAVE_DECL_KEY_ESC) && HAVE_DECL_KEY_ESC))
# define KEY_ESC 1
#endif
#if !(defined(KEY_1) || (defined(HAVE_DECL_KEY_1) && HAVE_DECL_KEY_1))
# define KEY_1 2
#endif
#if !(defined(KEY_2) || (defined(HAVE_DECL_KEY_2) && HAVE_DECL_KEY_2))
# define KEY_2 3
#endif
#if !(defined(KEY_3) || (defined(HAVE_DECL_KEY_3) && HAVE_DECL_KEY_3))
# define KEY_3 4
#endif
#if !(defined(KEY_4) || (defined(HAVE_DECL_KEY_4) && HAVE_DECL_KEY_4))
# define KEY_4 5
#endif
#if !(defined(KEY_5) || (defined(HAVE_DECL_KEY_5) && HAVE_DECL_KEY_5))
# define KEY_5 6
#endif
#if !(defined(KEY_6) || (defined(HAVE_DECL_KEY_6) && HAVE_DECL_KEY_6))
# define KEY_6 7
#endif
#if !(defined(KEY_7) || (defined(HAVE_DECL_KEY_7) && HAVE_DECL_KEY_7))
# define KEY_7 8
#endif
#if !(defined(KEY_8) || (defined(HAVE_DECL_KEY_8) && HAVE_DECL_KEY_8))
# define KEY_8 9
#endif
#if !(defined(KEY_9) || (defined(HAVE_DECL_KEY_9) && HAVE_DECL_KEY_9))
# define KEY_9 10
#endif
#if !(defined(KEY_0) || (defined(HAVE_DECL_KEY_0) && HAVE_DECL_KEY_0))
# define KEY_0 11
#endif
#if !(defined(KEY_MINUS) || (defined(HAVE_DECL_KEY_MINUS) && HAVE_DECL_KEY_MINUS))
# define KEY_MINUS 12
#endif
#if !(defined(KEY_EQUAL) || (defined(HAVE_DECL_KEY_EQUAL) && HAVE_DECL_KEY_EQUAL))
# define KEY_EQUAL 13
#endif
#if !(defined(KEY_BACKSPACE) || (defined(HAVE_DECL_KEY_BACKSPACE) && HAVE_DECL_KEY_BACKSPACE))
# define KEY_BACKSPACE 14
#endif
#if !(defined(KEY_TAB) || (defined(HAVE_DECL_KEY_TAB) && HAVE_DECL_KEY_TAB))
# define KEY_TAB 15
#endif
#if !(defined(KEY_Q) || (defined(HAVE_DECL_KEY_Q) && HAVE_DECL_KEY_Q))
# define KEY_Q 16
#endif
#if !(defined(KEY_W) || (defined(HAVE_DECL_KEY_W) && HAVE_DECL_KEY_W))
# define KEY_W 17
#endif
#if !(defined(KEY_E) || (defined(HAVE_DECL_KEY_E) && HAVE_DECL_KEY_E))
# define KEY_E 18
#endif
#if !(defined(KEY_R) || (defined(HAVE_DECL_KEY_R) && HAVE_DECL_KEY_R))
# define KEY_R 19
#endif
#if !(defined(KEY_T) || (defined(HAVE_DECL_KEY_T) && HAVE_DECL_KEY_T))
# define KEY_T 20
#endif
#if !(defined(KEY_Y) || (defined(HAVE_DECL_KEY_Y) && HAVE_DECL_KEY_Y))
# define KEY_Y 21
#endif
#if !(defined(KEY_U) || (defined(HAVE_DECL_KEY_U) && HAVE_DECL_KEY_U))
# define KEY_U 22
#endif
#if !(defined(KEY_I) || (defined(HAVE_DECL_KEY_I) && HAVE_DECL_KEY_I))
# define KEY_I 23
#endif
#if !(defined(KEY_O) || (defined(HAVE_DECL_KEY_O) && HAVE_DECL_KEY_O))
# define KEY_O 24
#endif
#if !(defined(KEY_P) || (defined(HAVE_DECL_KEY_P) && HAVE_DECL_KEY_P))
# define KEY_P 25
#endif
#if !(defined(KEY_LEFTBRACE) || (defined(HAVE_DECL_KEY_LEFTBRACE) && HAVE_DECL_KEY_LEFTBRACE))
# define KEY_LEFTBRACE 26
#endif
#if !(defined(KEY_RIGHTBRACE) || (defined(HAVE_DECL_KEY_RIGHTBRACE) && HAVE_DECL_KEY_RIGHTBRACE))
# define KEY_RIGHTBRACE 27
#endif
#if !(defined(KEY_ENTER) || (defined(HAVE_DECL_KEY_ENTER) && HAVE_DECL_KEY_ENTER))
# define KEY_ENTER 28
#endif
#if !(defined(KEY_LEFTCTRL) || (defined(HAVE_DECL_KEY_LEFTCTRL) && HAVE_DECL_KEY_LEFTCTRL))
# define KEY_LEFTCTRL 29
#endif
#if !(defined(KEY_A) || (defined(HAVE_DECL_KEY_A) && HAVE_DECL_KEY_A))
# define KEY_A 30
#endif
#if !(defined(KEY_S) || (defined(HAVE_DECL_KEY_S) && HAVE_DECL_KEY_S))
# define KEY_S 31
#endif
#if !(defined(KEY_D) || (defined(HAVE_DECL_KEY_D) && HAVE_DECL_KEY_D))
# define KEY_D 32
#endif
#if !(defined(KEY_F) || (defined(HAVE_DECL_KEY_F) && HAVE_DECL_KEY_F))
# define KEY_F 33
#endif
#if !(defined(KEY_G) || (defined(HAVE_DECL_KEY_G) && HAVE_DECL_KEY_G))
# define KEY_G 34
#endif
#if !(defined(KEY_H) || (defined(HAVE_DECL_KEY_H) && HAVE_DECL_KEY_H))
# define KEY_H 35
#endif
#if !(defined(KEY_J) || (defined(HAVE_DECL_KEY_J) && HAVE_DECL_KEY_J))
# define KEY_J 36
#endif
#if !(defined(KEY_K) || (defined(HAVE_DECL_KEY_K) && HAVE_DECL_KEY_K))
# define KEY_K 37
#endif
#if !(defined(KEY_L) || (defined(HAVE_DECL_KEY_L) && HAVE_DECL_KEY_L))
# define KEY_L 38
#endif
#if !(defined(KEY_SEMICOLON) || (defined(HAVE_DECL_KEY_SEMICOLON) && HAVE_DECL_KEY_SEMICOLON))
# define KEY_SEMICOLON 39
#endif
#if !(defined(KEY_APOSTROPHE) || (defined(HAVE_DECL_KEY_APOSTROPHE) && HAVE_DECL_KEY_APOSTROPHE))
# define KEY_APOSTROPHE 40
#endif
#if !(defined(KEY_GRAVE) || (defined(HAVE_DECL_KEY_GRAVE) && HAVE_DECL_KEY_GRAVE))
# define KEY_GRAVE 41
#endif
#if !(defined(KEY_LEFTSHIFT) || (defined(HAVE_DECL_KEY_LEFTSHIFT) && HAVE_DECL_KEY_LEFTSHIFT))
# define KEY_LEFTSHIFT 42
#endif
#if !(defined(KEY_BACKSLASH) || (defined(HAVE_DECL_KEY_BACKSLASH) && HAVE_DECL_KEY_BACKSLASH))
# define KEY_BACKSLASH 43
#endif
#if !(defined(KEY_Z) || (defined(HAVE_DECL_KEY_Z) && HAVE_DECL_KEY_Z))
# define KEY_Z 44
#endif
#if !(defined(KEY_X) || (defined(HAVE_DECL_KEY_X) && HAVE_DECL_KEY_X))
# define KEY_X 45
#endif
#if !(defined(KEY_C) || (defined(HAVE_DECL_KEY_C) && HAVE_DECL_KEY_C))
# define KEY_C 46
#endif
#if !(defined(KEY_V) || (defined(HAVE_DECL_KEY_V) && HAVE_DECL_KEY_V))
# define KEY_V 47
#endif
#if !(defined(KEY_B) || (defined(HAVE_DECL_KEY_B) && HAVE_DECL_KEY_B))
# define KEY_B 48
#endif
#if !(defined(KEY_N) || (defined(HAVE_DECL_KEY_N) && HAVE_DECL_KEY_N))
# define KEY_N 49
#endif
#if !(defined(KEY_M) || (defined(HAVE_DECL_KEY_M) && HAVE_DECL_KEY_M))
# define KEY_M 50
#endif
#if !(defined(KEY_COMMA) || (defined(HAVE_DECL_KEY_COMMA) && HAVE_DECL_KEY_COMMA))
# define KEY_COMMA 51
#endif
#if !(defined(KEY_DOT) || (defined(HAVE_DECL_KEY_DOT) && HAVE_DECL_KEY_DOT))
# define KEY_DOT 52
#endif
#if !(defined(KEY_SLASH) || (defined(HAVE_DECL_KEY_SLASH) && HAVE_DECL_KEY_SLASH))
# define KEY_SLASH 53
#endif
#if !(defined(KEY_RIGHTSHIFT) || (defined(HAVE_DECL_KEY_RIGHTSHIFT) && HAVE_DECL_KEY_RIGHTSHIFT))
# define KEY_RIGHTSHIFT 54
#endif
#if !(defined(KEY_KPASTERISK) || (defined(HAVE_DECL_KEY_KPASTERISK) && HAVE_DECL_KEY_KPASTERISK))
# define KEY_KPASTERISK 55
#endif
#if !(defined(KEY_LEFTALT) || (defined(HAVE_DECL_KEY_LEFTALT) && HAVE_DECL_KEY_LEFTALT))
# define KEY_LEFTALT 56
#endif
#if !(defined(KEY_SPACE) || (defined(HAVE_DECL_KEY_SPACE) && HAVE_DECL_KEY_SPACE))
# define KEY_SPACE 57
#endif
#if !(defined(KEY_CAPSLOCK) || (defined(HAVE_DECL_KEY_CAPSLOCK) && HAVE_DECL_KEY_CAPSLOCK))
# define KEY_CAPSLOCK 58
#endif
#if !(defined(KEY_F1) || (defined(HAVE_DECL_KEY_F1) && HAVE_DECL_KEY_F1))
# define KEY_F1 59
#endif
#if !(defined(KEY_F2) || (defined(HAVE_DECL_KEY_F2) && HAVE_DECL_KEY_F2))
# define KEY_F2 60
#endif
#if !(defined(KEY_F3) || (defined(HAVE_DECL_KEY_F3) && HAVE_DECL_KEY_F3))
# define KEY_F3 61
#endif
#if !(defined(KEY_F4) || (defined(HAVE_DECL_KEY_F4) && HAVE_DECL_KEY_F4))
# define KEY_F4 62
#endif
#if !(defined(KEY_F5) || (defined(HAVE_DECL_KEY_F5) && HAVE_DECL_KEY_F5))
# define KEY_F5 63
#endif
#if !(defined(KEY_F6) || (defined(HAVE_DECL_KEY_F6) && HAVE_DECL_KEY_F6))
# define KEY_F6 64
#endif
#if !(defined(KEY_F7) || (defined(HAVE_DECL_KEY_F7) && HAVE_DECL_KEY_F7))
# define KEY_F7 65
#endif
#if !(defined(KEY_F8) || (defined(HAVE_DECL_KEY_F8) && HAVE_DECL_KEY_F8))
# define KEY_F8 66
#endif
#if !(defined(KEY_F9) || (defined(HAVE_DECL_KEY_F9) && HAVE_DECL_KEY_F9))
# define KEY_F9 67
#endif
#if !(defined(KEY_F10) || (defined(HAVE_DECL_KEY_F10) && HAVE_DECL_KEY_F10))
# define KEY_F10 68
#endif
#if !(defined(KEY_NUMLOCK) || (defined(HAVE_DECL_KEY_NUMLOCK) && HAVE_DECL_KEY_NUMLOCK))
# define KEY_NUMLOCK 69
#endif
#if !(defined(KEY_SCROLLLOCK) || (defined(HAVE_DECL_KEY_SCROLLLOCK) && HAVE_DECL_KEY_SCROLLLOCK))
# define KEY_SCROLLLOCK 70
#endif
#if !(defined(KEY_KP7) || (defined(HAVE_DECL_KEY_KP7) && HAVE_DECL_KEY_KP7))
# define KEY_KP7 71
#endif
#if !(defined(KEY_KP8) || (defined(HAVE_DECL_KEY_KP8) && HAVE_DECL_KEY_KP8))
# define KEY_KP8 72
#endif
#if !(defined(KEY_KP9) || (defined(HAVE_DECL_KEY_KP9) && HAVE_DECL_KEY_KP9))
# define KEY_KP9 73
#endif
#if !(defined(KEY_KPMINUS) || (defined(HAVE_DECL_KEY_KPMINUS) && HAVE_DECL_KEY_KPMINUS))
# define KEY_KPMINUS 74
#endif
#if !(defined(KEY_KP4) || (defined(HAVE_DECL_KEY_KP4) && HAVE_DECL_KEY_KP4))
# define KEY_KP4 75
#endif
#if !(defined(KEY_KP5) || (defined(HAVE_DECL_KEY_KP5) && HAVE_DECL_KEY_KP5))
# define KEY_KP5 76
#endif
#if !(defined(KEY_KP6) || (defined(HAVE_DECL_KEY_KP6) && HAVE_DECL_KEY_KP6))
# define KEY_KP6 77
#endif
#if !(defined(KEY_KPPLUS) || (defined(HAVE_DECL_KEY_KPPLUS) && HAVE_DECL_KEY_KPPLUS))
# define KEY_KPPLUS 78
#endif
#if !(defined(KEY_KP1) || (defined(HAVE_DECL_KEY_KP1) && HAVE_DECL_KEY_KP1))
# define KEY_KP1 79
#endif
#if !(defined(KEY_KP2) || (defined(HAVE_DECL_KEY_KP2) && HAVE_DECL_KEY_KP2))
# define KEY_KP2 80
#endif
#if !(defined(KEY_KP3) || (defined(HAVE_DECL_KEY_KP3) && HAVE_DECL_KEY_KP3))
# define KEY_KP3 81
#endif
#if !(defined(KEY_KP0) || (defined(HAVE_DECL_KEY_KP0) && HAVE_DECL_KEY_KP0))
# define KEY_KP0 82
#endif
#if !(defined(KEY_KPDOT) || (defined(HAVE_DECL_KEY_KPDOT) && HAVE_DECL_KEY_KPDOT))
# define KEY_KPDOT 83
#endif
#if !(defined(KEY_ZENKAKUHANKAKU) || (defined(HAVE_DECL_KEY_ZENKAKUHANKAKU) && HAVE_DECL_KEY_ZENKAKUHANKAKU))
# define KEY_ZENKAKUHANKAKU 85
#endif
#if !(defined(KEY_102ND) || (defined(HAVE_DECL_KEY_102ND) && HAVE_DECL_KEY_102ND))
# define KEY_102ND 86
#endif
#if !(defined(KEY_F11) || (defined(HAVE_DECL_KEY_F11) && HAVE_DECL_KEY_F11))
# define KEY_F11 87
#endif
#if !(defined(KEY_F12) || (defined(HAVE_DECL_KEY_F12) && HAVE_DECL_KEY_F12))
# define KEY_F12 88
#endif
#if !(defined(KEY_RO) || (defined(HAVE_DECL_KEY_RO) && HAVE_DECL_KEY_RO))
# define KEY_RO 89
#endif
#if !(defined(KEY_KATAKANA) || (defined(HAVE_DECL_KEY_KATAKANA) && HAVE_DECL_KEY_KATAKANA))
# define KEY_KATAKANA 90
#endif
#if !(defined(KEY_HIRAGANA) || (defined(HAVE_DECL_KEY_HIRAGANA) && HAVE_DECL_KEY_HIRAGANA))
# define KEY_HIRAGANA 91
#endif
#if !(defined(KEY_HENKAN) || (defined(HAVE_DECL_KEY_HENKAN) && HAVE_DECL_KEY_HENKAN))
# define KEY_HENKAN 92
#endif
#if !(defined(KEY_KATAKANAHIRAGANA) || (defined(HAVE_DECL_KEY_KATAKANAHIRAGANA) && HAVE_DECL_KEY_KATAKANAHIRAGANA))
# define KEY_KATAKANAHIRAGANA 93
#endif
#if !(defined(KEY_MUHENKAN) || (defined(HAVE_DECL_KEY_MUHENKAN) && HAVE_DECL_KEY_MUHENKAN))
# define KEY_MUHENKAN 94
#endif
#if !(defined(KEY_KPJPCOMMA) || (defined(HAVE_DECL_KEY_KPJPCOMMA) && HAVE_DECL_KEY_KPJPCOMMA))
# define KEY_KPJPCOMMA 95
#endif
#if !(defined(KEY_KPENTER) || (defined(HAVE_DECL_KEY_KPENTER) && HAVE_DECL_KEY_KPENTER))
# define KEY_KPENTER 96
#endif
#if !(defined(KEY_RIGHTCTRL) || (defined(HAVE_DECL_KEY_RIGHTCTRL) && HAVE_DECL_KEY_RIGHTCTRL))
# define KEY_RIGHTCTRL 97
#endif
#if !(defined(KEY_KPSLASH) || (defined(HAVE_DECL_KEY_KPSLASH) && HAVE_DECL_KEY_KPSLASH))
# define KEY_KPSLASH 98
#endif
#if !(defined(KEY_SYSRQ) || (defined(HAVE_DECL_KEY_SYSRQ) && HAVE_DECL_KEY_SYSRQ))
# define KEY_SYSRQ 99
#endif
#if !(defined(KEY_RIGHTALT) || (defined(HAVE_DECL_KEY_RIGHTALT) && HAVE_DECL_KEY_RIGHTALT))
# define KEY_RIGHTALT 100
#endif
#if !(defined(KEY_LINEFEED) || (defined(HAVE_DECL_KEY_LINEFEED) && HAVE_DECL_KEY_LINEFEED))
# define KEY_LINEFEED 101
#endif
#if !(defined(KEY_HOME) || (defined(HAVE_DECL_KEY_HOME) && HAVE_DECL_KEY_HOME))
# define KEY_HOME 102
#endif
#if !(defined(KEY_UP) || (defined(HAVE_DECL_KEY_UP) && HAVE_DECL_KEY_UP))
# define KEY_UP 103
#endif
#if !(defined(KEY_PAGEUP) || (defined(HAVE_DECL_KEY_PAGEUP) && HAVE_DECL_KEY_PAGEUP))
# define KEY_PAGEUP 104
#endif
#if !(defined(KEY_LEFT) || (defined(HAVE_DECL_KEY_LEFT) && HAVE_DECL_KEY_LEFT))
# define KEY_LEFT 105
#endif
#if !(defined(KEY_RIGHT) || (defined(HAVE_DECL_KEY_RIGHT) && HAVE_DECL_KEY_RIGHT))
# define KEY_RIGHT 106
#endif
#if !(defined(KEY_END) || (defined(HAVE_DECL_KEY_END) && HAVE_DECL_KEY_END))
# define KEY_END 107
#endif
#if !(defined(KEY_DOWN) || (defined(HAVE_DECL_KEY_DOWN) && HAVE_DECL_KEY_DOWN))
# define KEY_DOWN 108
#endif
#if !(defined(KEY_PAGEDOWN) || (defined(HAVE_DECL_KEY_PAGEDOWN) && HAVE_DECL_KEY_PAGEDOWN))
# define KEY_PAGEDOWN 109
#endif
#if !(defined(KEY_INSERT) || (defined(HAVE_DECL_KEY_INSERT) && HAVE_DECL_KEY_INSERT))
# define KEY_INSERT 110
#endif
#if !(defined(KEY_DELETE) || (defined(HAVE_DECL_KEY_DELETE) && HAVE_DECL_KEY_DELETE))
# define KEY_DELETE 111
#endif
#if !(defined(KEY_MACRO) || (defined(HAVE_DECL_KEY_MACRO) && HAVE_DECL_KEY_MACRO))
# define KEY_MACRO 112
#endif
#if !(defined(KEY_MUTE) || (defined(HAVE_DECL_KEY_MUTE) && HAVE_DECL_KEY_MUTE))
# define KEY_MUTE 113
#endif
#if !(defined(KEY_VOLUMEDOWN) || (defined(HAVE_DECL_KEY_VOLUMEDOWN) && HAVE_DECL_KEY_VOLUMEDOWN))
# define KEY_VOLUMEDOWN 114
#endif
#if !(defined(KEY_VOLUMEUP) || (defined(HAVE_DECL_KEY_VOLUMEUP) && HAVE_DECL_KEY_VOLUMEUP))
# define KEY_VOLUMEUP 115
#endif
#if !(defined(KEY_POWER) || (defined(HAVE_DECL_KEY_POWER) && HAVE_DECL_KEY_POWER))
# define KEY_POWER 116
#endif
#if !(defined(KEY_KPEQUAL) || (defined(HAVE_DECL_KEY_KPEQUAL) && HAVE_DECL_KEY_KPEQUAL))
# define KEY_KPEQUAL 117
#endif
#if !(defined(KEY_KPPLUSMINUS) || (defined(HAVE_DECL_KEY_KPPLUSMINUS) && HAVE_DECL_KEY_KPPLUSMINUS))
# define KEY_KPPLUSMINUS 118
#endif
#if !(defined(KEY_PAUSE) || (defined(HAVE_DECL_KEY_PAUSE) && HAVE_DECL_KEY_PAUSE))
# define KEY_PAUSE 119
#endif
#if !(defined(KEY_SCALE) || (defined(HAVE_DECL_KEY_SCALE) && HAVE_DECL_KEY_SCALE))
# define KEY_SCALE 120
#endif
#if !(defined(KEY_KPCOMMA) || (defined(HAVE_DECL_KEY_KPCOMMA) && HAVE_DECL_KEY_KPCOMMA))
# define KEY_KPCOMMA 121
#endif
#if !(defined(KEY_HANGEUL) || (defined(HAVE_DECL_KEY_HANGEUL) && HAVE_DECL_KEY_HANGEUL))
# define KEY_HANGEUL 122
#endif
#if !(defined(KEY_HANJA) || (defined(HAVE_DECL_KEY_HANJA) && HAVE_DECL_KEY_HANJA))
# define KEY_HANJA 123
#endif
#if !(defined(KEY_YEN) || (defined(HAVE_DECL_KEY_YEN) && HAVE_DECL_KEY_YEN))
# define KEY_YEN 124
#endif
#if !(defined(KEY_LEFTMETA) || (defined(HAVE_DECL_KEY_LEFTMETA) && HAVE_DECL_KEY_LEFTMETA))
# define KEY_LEFTMETA 125
#endif
#if !(defined(KEY_RIGHTMETA) || (defined(HAVE_DECL_KEY_RIGHTMETA) && HAVE_DECL_KEY_RIGHTMETA))
# define KEY_RIGHTMETA 126
#endif
#if !(defined(KEY_COMPOSE) || (defined(HAVE_DECL_KEY_COMPOSE) && HAVE_DECL_KEY_COMPOSE))
# define KEY_COMPOSE 127
#endif
#if !(defined(KEY_STOP) || (defined(HAVE_DECL_KEY_STOP) && HAVE_DECL_KEY_STOP))
# define KEY_STOP 128
#endif
#if !(defined(KEY_AGAIN) || (defined(HAVE_DECL_KEY_AGAIN) && HAVE_DECL_KEY_AGAIN))
# define KEY_AGAIN 129
#endif
#if !(defined(KEY_PROPS) || (defined(HAVE_DECL_KEY_PROPS) && HAVE_DECL_KEY_PROPS))
# define KEY_PROPS 130
#endif
#if !(defined(KEY_UNDO) || (defined(HAVE_DECL_KEY_UNDO) && HAVE_DECL_KEY_UNDO))
# define KEY_UNDO 131
#endif
#if !(defined(KEY_FRONT) || (defined(HAVE_DECL_KEY_FRONT) && HAVE_DECL_KEY_FRONT))
# define KEY_FRONT 132
#endif
#if !(defined(KEY_COPY) || (defined(HAVE_DECL_KEY_COPY) && HAVE_DECL_KEY_COPY))
# define KEY_COPY 133
#endif
#if !(defined(KEY_OPEN) || (defined(HAVE_DECL_KEY_OPEN) && HAVE_DECL_KEY_OPEN))
# define KEY_OPEN 134
#endif
#if !(defined(KEY_PASTE) || (defined(HAVE_DECL_KEY_PASTE) && HAVE_DECL_KEY_PASTE))
# define KEY_PASTE 135
#endif
#if !(defined(KEY_FIND) || (defined(HAVE_DECL_KEY_FIND) && HAVE_DECL_KEY_FIND))
# define KEY_FIND 136
#endif
#if !(defined(KEY_CUT) || (defined(HAVE_DECL_KEY_CUT) && HAVE_DECL_KEY_CUT))
# define KEY_CUT 137
#endif
#if !(defined(KEY_HELP) || (defined(HAVE_DECL_KEY_HELP) && HAVE_DECL_KEY_HELP))
# define KEY_HELP 138
#endif
#if !(defined(KEY_MENU) || (defined(HAVE_DECL_KEY_MENU) && HAVE_DECL_KEY_MENU))
# define KEY_MENU 139
#endif
#if !(defined(KEY_CALC) || (defined(HAVE_DECL_KEY_CALC) && HAVE_DECL_KEY_CALC))
# define KEY_CALC 140
#endif
#if !(defined(KEY_SETUP) || (defined(HAVE_DECL_KEY_SETUP) && HAVE_DECL_KEY_SETUP))
# define KEY_SETUP 141
#endif
#if !(defined(KEY_SLEEP) || (defined(HAVE_DECL_KEY_SLEEP) && HAVE_DECL_KEY_SLEEP))
# define KEY_SLEEP 142
#endif
#if !(defined(KEY_WAKEUP) || (defined(HAVE_DECL_KEY_WAKEUP) && HAVE_DECL_KEY_WAKEUP))
# define KEY_WAKEUP 143
#endif
#if !(defined(KEY_FILE) || (defined(HAVE_DECL_KEY_FILE) && HAVE_DECL_KEY_FILE))
# define KEY_FILE 144
#endif
#if !(defined(KEY_SENDFILE) || (defined(HAVE_DECL_KEY_SENDFILE) && HAVE_DECL_KEY_SENDFILE))
# define KEY_SENDFILE 145
#endif
#if !(defined(KEY_DELETEFILE) || (defined(HAVE_DECL_KEY_DELETEFILE) && HAVE_DECL_KEY_DELETEFILE))
# define KEY_DELETEFILE 146
#endif
#if !(defined(KEY_XFER) || (defined(HAVE_DECL_KEY_XFER) && HAVE_DECL_KEY_XFER))
# define KEY_XFER 147
#endif
#if !(defined(KEY_PROG1) || (defined(HAVE_DECL_KEY_PROG1) && HAVE_DECL_KEY_PROG1))
# define KEY_PROG1 148
#endif
#if !(defined(KEY_PROG2) || (defined(HAVE_DECL_KEY_PROG2) && HAVE_DECL_KEY_PROG2))
# define KEY_PROG2 149
#endif
#if !(defined(KEY_WWW) || (defined(HAVE_DECL_KEY_WWW) && HAVE_DECL_KEY_WWW))
# define KEY_WWW 150
#endif
#if !(defined(KEY_MSDOS) || (defined(HAVE_DECL_KEY_MSDOS) && HAVE_DECL_KEY_MSDOS))
# define KEY_MSDOS 151
#endif
#if !(defined(KEY_COFFEE) || (defined(HAVE_DECL_KEY_COFFEE) && HAVE_DECL_KEY_COFFEE))
# define KEY_COFFEE 152
#endif
#if !(defined(KEY_ROTATE_DISPLAY) || (defined(HAVE_DECL_KEY_ROTATE_DISPLAY) && HAVE_DECL_KEY_ROTATE_DISPLAY))
# define KEY_ROTATE_DISPLAY 153
#endif
#if !(defined(KEY_CYCLEWINDOWS) || (defined(HAVE_DECL_KEY_CYCLEWINDOWS) && HAVE_DECL_KEY_CYCLEWINDOWS))
# define KEY_CYCLEWINDOWS 154
#endif
#if !(defined(KEY_MAIL) || (defined(HAVE_DECL_KEY_MAIL) && HAVE_DECL_KEY_MAIL))
# define KEY_MAIL 155
#endif
#if !(defined(KEY_BOOKMARKS) || (defined(HAVE_DECL_KEY_BOOKMARKS) && HAVE_DECL_KEY_BOOKMARKS))
# define KEY_BOOKMARKS 156
#endif
#if !(defined(KEY_COMPUTER) || (defined(HAVE_DECL_KEY_COMPUTER) && HAVE_DECL_KEY_COMPUTER))
# define KEY_COMPUTER 157
#endif
#if !(defined(KEY_BACK) || (defined(HAVE_DECL_KEY_BACK) && HAVE_DECL_KEY_BACK))
# define KEY_BACK 158
#endif
#if !(defined(KEY_FORWARD) || (defined(HAVE_DECL_KEY_FORWARD) && HAVE_DECL_KEY_FORWARD))
# define KEY_FORWARD 159
#endif
#if !(defined(KEY_CLOSECD) || (defined(HAVE_DECL_KEY_CLOSECD) && HAVE_DECL_KEY_CLOSECD))
# define KEY_CLOSECD 160
#endif
#if !(defined(KEY_EJECTCD) || (defined(HAVE_DECL_KEY_EJECTCD) && HAVE_DECL_KEY_EJECTCD))
# define KEY_EJECTCD 161
#endif
#if !(defined(KEY_EJECTCLOSECD) || (defined(HAVE_DECL_KEY_EJECTCLOSECD) && HAVE_DECL_KEY_EJECTCLOSECD))
# define KEY_EJECTCLOSECD 162
#endif
#if !(defined(KEY_NEXTSONG) || (defined(HAVE_DECL_KEY_NEXTSONG) && HAVE_DECL_KEY_NEXTSONG))
# define KEY_NEXTSONG 163
#endif
#if !(defined(KEY_PLAYPAUSE) || (defined(HAVE_DECL_KEY_PLAYPAUSE) && HAVE_DECL_KEY_PLAYPAUSE))
# define KEY_PLAYPAUSE 164
#endif
#if !(defined(KEY_PREVIOUSSONG) || (defined(HAVE_DECL_KEY_PREVIOUSSONG) && HAVE_DECL_KEY_PREVIOUSSONG))
# define KEY_PREVIOUSSONG 165
#endif
#if !(defined(KEY_STOPCD) || (defined(HAVE_DECL_KEY_STOPCD) && HAVE_DECL_KEY_STOPCD))
# define KEY_STOPCD 166
#endif
#if !(defined(KEY_RECORD) || (defined(HAVE_DECL_KEY_RECORD) && HAVE_DECL_KEY_RECORD))
# define KEY_RECORD 167
#endif
#if !(defined(KEY_REWIND) || (defined(HAVE_DECL_KEY_REWIND) && HAVE_DECL_KEY_REWIND))
# define KEY_REWIND 168
#endif
#if !(defined(KEY_PHONE) || (defined(HAVE_DECL_KEY_PHONE) && HAVE_DECL_KEY_PHONE))
# define KEY_PHONE 169
#endif
#if !(defined(KEY_ISO) || (defined(HAVE_DECL_KEY_ISO) && HAVE_DECL_KEY_ISO))
# define KEY_ISO 170
#endif
#if !(defined(KEY_CONFIG) || (defined(HAVE_DECL_KEY_CONFIG) && HAVE_DECL_KEY_CONFIG))
# define KEY_CONFIG 171
#endif
#if !(defined(KEY_HOMEPAGE) || (defined(HAVE_DECL_KEY_HOMEPAGE) && HAVE_DECL_KEY_HOMEPAGE))
# define KEY_HOMEPAGE 172
#endif
#if !(defined(KEY_REFRESH) || (defined(HAVE_DECL_KEY_REFRESH) && HAVE_DECL_KEY_REFRESH))
# define KEY_REFRESH 173
#endif
#if !(defined(KEY_EXIT) || (defined(HAVE_DECL_KEY_EXIT) && HAVE_DECL_KEY_EXIT))
# define KEY_EXIT 174
#endif
#if !(defined(KEY_MOVE) || (defined(HAVE_DECL_KEY_MOVE) && HAVE_DECL_KEY_MOVE))
# define KEY_MOVE 175
#endif
#if !(defined(KEY_EDIT) || (defined(HAVE_DECL_KEY_EDIT) && HAVE_DECL_KEY_EDIT))
# define KEY_EDIT 176
#endif
#if !(defined(KEY_SCROLLUP) || (defined(HAVE_DECL_KEY_SCROLLUP) && HAVE_DECL_KEY_SCROLLUP))
# define KEY_SCROLLUP 177
#endif
#if !(defined(KEY_SCROLLDOWN) || (defined(HAVE_DECL_KEY_SCROLLDOWN) && HAVE_DECL_KEY_SCROLLDOWN))
# define KEY_SCROLLDOWN 178
#endif
#if !(defined(KEY_KPLEFTPAREN) || (defined(HAVE_DECL_KEY_KPLEFTPAREN) && HAVE_DECL_KEY_KPLEFTPAREN))
# define KEY_KPLEFTPAREN 179
#endif
#if !(defined(KEY_KPRIGHTPAREN) || (defined(HAVE_DECL_KEY_KPRIGHTPAREN) && HAVE_DECL_KEY_KPRIGHTPAREN))
# define KEY_KPRIGHTPAREN 180
#endif
#if !(defined(KEY_NEW) || (defined(HAVE_DECL_KEY_NEW) && HAVE_DECL_KEY_NEW))
# define KEY_NEW 181
#endif
#if !(defined(KEY_REDO) || (defined(HAVE_DECL_KEY_REDO) && HAVE_DECL_KEY_REDO))
# define KEY_REDO 182
#endif
#if !(defined(KEY_F13) || (defined(HAVE_DECL_KEY_F13) && HAVE_DECL_KEY_F13))
# define KEY_F13 183
#endif
#if !(defined(KEY_F14) || (defined(HAVE_DECL_KEY_F14) && HAVE_DECL_KEY_F14))
# define KEY_F14 184
#endif
#if !(defined(KEY_F15) || (defined(HAVE_DECL_KEY_F15) && HAVE_DECL_KEY_F15))
# define KEY_F15 185
#endif
#if !(defined(KEY_F16) || (defined(HAVE_DECL_KEY_F16) && HAVE_DECL_KEY_F16))
# define KEY_F16 186
#endif
#if !(defined(KEY_F17) || (defined(HAVE_DECL_KEY_F17) && HAVE_DECL_KEY_F17))
# define KEY_F17 187
#endif
#if !(defined(KEY_F18) || (defined(HAVE_DECL_KEY_F18) && HAVE_DECL_KEY_F18))
# define KEY_F18 188
#endif
#if !(defined(KEY_F19) || (defined(HAVE_DECL_KEY_F19) && HAVE_DECL_KEY_F19))
# define KEY_F19 189
#endif
#if !(defined(KEY_F20) || (defined(HAVE_DECL_KEY_F20) && HAVE_DECL_KEY_F20))
# define KEY_F20 190
#endif
#if !(defined(KEY_F21) || (defined(HAVE_DECL_KEY_F21) && HAVE_DECL_KEY_F21))
# define KEY_F21 191
#endif
#if !(defined(KEY_F22) || (defined(HAVE_DECL_KEY_F22) && HAVE_DECL_KEY_F22))
# define KEY_F22 192
#endif
#if !(defined(KEY_F23) || (defined(HAVE_DECL_KEY_F23) && HAVE_DECL_KEY_F23))
# define KEY_F23 193
#endif
#if !(defined(KEY_F24) || (defined(HAVE_DECL_KEY_F24) && HAVE_DECL_KEY_F24))
# define KEY_F24 194
#endif
#if !(defined(KEY_PLAYCD) || (defined(HAVE_DECL_KEY_PLAYCD) && HAVE_DECL_KEY_PLAYCD))
# define KEY_PLAYCD 200
#endif
#if !(defined(KEY_PAUSECD) || (defined(HAVE_DECL_KEY_PAUSECD) && HAVE_DECL_KEY_PAUSECD))
# define KEY_PAUSECD 201
#endif
#if !(defined(KEY_PROG3) || (defined(HAVE_DECL_KEY_PROG3) && HAVE_DECL_KEY_PROG3))
# define KEY_PROG3 202
#endif
#if !(defined(KEY_PROG4) || (defined(HAVE_DECL_KEY_PROG4) && HAVE_DECL_KEY_PROG4))
# define KEY_PROG4 203
#endif
#if !(defined(KEY_DASHBOARD) || (defined(HAVE_DECL_KEY_DASHBOARD) && HAVE_DECL_KEY_DASHBOARD))
# define KEY_DASHBOARD 204
#endif
#if !(defined(KEY_SUSPEND) || (defined(HAVE_DECL_KEY_SUSPEND) && HAVE_DECL_KEY_SUSPEND))
# define KEY_SUSPEND 205
#endif
#if !(defined(KEY_CLOSE) || (defined(HAVE_DECL_KEY_CLOSE) && HAVE_DECL_KEY_CLOSE))
# define KEY_CLOSE 206
#endif
#if !(defined(KEY_PLAY) || (defined(HAVE_DECL_KEY_PLAY) && HAVE_DECL_KEY_PLAY))
# define KEY_PLAY 207
#endif
#if !(defined(KEY_FASTFORWARD) || (defined(HAVE_DECL_KEY_FASTFORWARD) && HAVE_DECL_KEY_FASTFORWARD))
# define KEY_FASTFORWARD 208
#endif
#if !(defined(KEY_BASSBOOST) || (defined(HAVE_DECL_KEY_BASSBOOST) && HAVE_DECL_KEY_BASSBOOST))
# define KEY_BASSBOOST 209
#endif
#if !(defined(KEY_PRINT) || (defined(HAVE_DECL_KEY_PRINT) && HAVE_DECL_KEY_PRINT))
# define KEY_PRINT 210
#endif
#if !(defined(KEY_HP) || (defined(HAVE_DECL_KEY_HP) && HAVE_DECL_KEY_HP))
# define KEY_HP 211
#endif
#if !(defined(KEY_CAMERA) || (defined(HAVE_DECL_KEY_CAMERA) && HAVE_DECL_KEY_CAMERA))
# define KEY_CAMERA 212
#endif
#if !(defined(KEY_SOUND) || (defined(HAVE_DECL_KEY_SOUND) && HAVE_DECL_KEY_SOUND))
# define KEY_SOUND 213
#endif
#if !(defined(KEY_QUESTION) || (defined(HAVE_DECL_KEY_QUESTION) && HAVE_DECL_KEY_QUESTION))
# define KEY_QUESTION 214
#endif
#if !(defined(KEY_EMAIL) || (defined(HAVE_DECL_KEY_EMAIL) && HAVE_DECL_KEY_EMAIL))
# define KEY_EMAIL 215
#endif
#if !(defined(KEY_CHAT) || (defined(HAVE_DECL_KEY_CHAT) && HAVE_DECL_KEY_CHAT))
# define KEY_CHAT 216
#endif
#if !(defined(KEY_SEARCH) || (defined(HAVE_DECL_KEY_SEARCH) && HAVE_DECL_KEY_SEARCH))
# define KEY_SEARCH 217
#endif
#if !(defined(KEY_CONNECT) || (defined(HAVE_DECL_KEY_CONNECT) && HAVE_DECL_KEY_CONNECT))
# define KEY_CONNECT 218
#endif
#if !(defined(KEY_FINANCE) || (defined(HAVE_DECL_KEY_FINANCE) && HAVE_DECL_KEY_FINANCE))
# define KEY_FINANCE 219
#endif
#if !(defined(KEY_SPORT) || (defined(HAVE_DECL_KEY_SPORT) && HAVE_DECL_KEY_SPORT))
# define KEY_SPORT 220
#endif
#if !(defined(KEY_SHOP) || (defined(HAVE_DECL_KEY_SHOP) && HAVE_DECL_KEY_SHOP))
# define KEY_SHOP 221
#endif
#if !(defined(KEY_ALTERASE) || (defined(HAVE_DECL_KEY_ALTERASE) && HAVE_DECL_KEY_ALTERASE))
# define KEY_ALTERASE 222
#endif
#if !(defined(KEY_CANCEL) || (defined(HAVE_DECL_KEY_CANCEL) && HAVE_DECL_KEY_CANCEL))
# define KEY_CANCEL 223
#endif
#if !(defined(KEY_BRIGHTNESSDOWN) || (defined(HAVE_DECL_KEY_BRIGHTNESSDOWN) && HAVE_DECL_KEY_BRIGHTNESSDOWN))
# define KEY_BRIGHTNESSDOWN 224
#endif
#if !(defined(KEY_BRIGHTNESSUP) || (defined(HAVE_DECL_KEY_BRIGHTNESSUP) && HAVE_DECL_KEY_BRIGHTNESSUP))
# define KEY_BRIGHTNESSUP 225
#endif
#if !(defined(KEY_MEDIA) || (defined(HAVE_DECL_KEY_MEDIA) && HAVE_DECL_KEY_MEDIA))
# define KEY_MEDIA 226
#endif
#if !(defined(KEY_SWITCHVIDEOMODE) || (defined(HAVE_DECL_KEY_SWITCHVIDEOMODE) && HAVE_DECL_KEY_SWITCHVIDEOMODE))
# define KEY_SWITCHVIDEOMODE 227
#endif
#if !(defined(KEY_KBDILLUMTOGGLE) || (defined(HAVE_DECL_KEY_KBDILLUMTOGGLE) && HAVE_DECL_KEY_KBDILLUMTOGGLE))
# define KEY_KBDILLUMTOGGLE 228
#endif
#if !(defined(KEY_KBDILLUMDOWN) || (defined(HAVE_DECL_KEY_KBDILLUMDOWN) && HAVE_DECL_KEY_KBDILLUMDOWN))
# define KEY_KBDILLUMDOWN 229
#endif
#if !(defined(KEY_KBDILLUMUP) || (defined(HAVE_DECL_KEY_KBDILLUMUP) && HAVE_DECL_KEY_KBDILLUMUP))
# define KEY_KBDILLUMUP 230
#endif
#if !(defined(KEY_SEND) || (defined(HAVE_DECL_KEY_SEND) && HAVE_DECL_KEY_SEND))
# define KEY_SEND 231
#endif
#if !(defined(KEY_REPLY) || (defined(HAVE_DECL_KEY_REPLY) && HAVE_DECL_KEY_REPLY))
# define KEY_REPLY 232
#endif
#if !(defined(KEY_FORWARDMAIL) || (defined(HAVE_DECL_KEY_FORWARDMAIL) && HAVE_DECL_KEY_FORWARDMAIL))
# define KEY_FORWARDMAIL 233
#endif
#if !(defined(KEY_SAVE) || (defined(HAVE_DECL_KEY_SAVE) && HAVE_DECL_KEY_SAVE))
# define KEY_SAVE 234
#endif
#if !(defined(KEY_DOCUMENTS) || (defined(HAVE_DECL_KEY_DOCUMENTS) && HAVE_DECL_KEY_DOCUMENTS))
# define KEY_DOCUMENTS 235
#endif
#if !(defined(KEY_BATTERY) || (defined(HAVE_DECL_KEY_BATTERY) && HAVE_DECL_KEY_BATTERY))
# define KEY_BATTERY 236
#endif
#if !(defined(KEY_BLUETOOTH) || (defined(HAVE_DECL_KEY_BLUETOOTH) && HAVE_DECL_KEY_BLUETOOTH))
# define KEY_BLUETOOTH 237
#endif
#if !(defined(KEY_WLAN) || (defined(HAVE_DECL_KEY_WLAN) && HAVE_DECL_KEY_WLAN))
# define KEY_WLAN 238
#endif
#if !(defined(KEY_UWB) || (defined(HAVE_DECL_KEY_UWB) && HAVE_DECL_KEY_UWB))
# define KEY_UWB 239
#endif
#if !(defined(KEY_UNKNOWN) || (defined(HAVE_DECL_KEY_UNKNOWN) && HAVE_DECL_KEY_UNKNOWN))
# define KEY_UNKNOWN 240
#endif
#if !(defined(KEY_VIDEO_NEXT) || (defined(HAVE_DECL_KEY_VIDEO_NEXT) && HAVE_DECL_KEY_VIDEO_NEXT))
# define KEY_VIDEO_NEXT 241
#endif
#if !(defined(KEY_VIDEO_PREV) || (defined(HAVE_DECL_KEY_VIDEO_PREV) && HAVE_DECL_KEY_VIDEO_PREV))
# define KEY_VIDEO_PREV 242
#endif
#if !(defined(KEY_BRIGHTNESS_CYCLE) || (defined(HAVE_DECL_KEY_BRIGHTNESS_CYCLE) && HAVE_DECL_KEY_BRIGHTNESS_CYCLE))
# define KEY_BRIGHTNESS_CYCLE 243
#endif
#if !(defined(KEY_BRIGHTNESS_AUTO) || (defined(HAVE_DECL_KEY_BRIGHTNESS_AUTO) && HAVE_DECL_KEY_BRIGHTNESS_AUTO))
# define KEY_BRIGHTNESS_AUTO 244
#endif
#if !(defined(KEY_DISPLAY_OFF) || (defined(HAVE_DECL_KEY_DISPLAY_OFF) && HAVE_DECL_KEY_DISPLAY_OFF))
# define KEY_DISPLAY_OFF 245
#endif
#if !(defined(KEY_WWAN) || (defined(HAVE_DECL_KEY_WWAN) && HAVE_DECL_KEY_WWAN))
# define KEY_WWAN 246
#endif
#if !(defined(KEY_RFKILL) || (defined(HAVE_DECL_KEY_RFKILL) && HAVE_DECL_KEY_RFKILL))
# define KEY_RFKILL 247
#endif
#if !(defined(KEY_MICMUTE) || (defined(HAVE_DECL_KEY_MICMUTE) && HAVE_DECL_KEY_MICMUTE))
# define KEY_MICMUTE 248
#endif
#if !(defined(BTN_0) || (defined(HAVE_DECL_BTN_0) && HAVE_DECL_BTN_0))
# define BTN_0 0x100
#endif
#if !(defined(BTN_1) || (defined(HAVE_DECL_BTN_1) && HAVE_DECL_BTN_1))
# define BTN_1 0x101
#endif
#if !(defined(BTN_2) || (defined(HAVE_DECL_BTN_2) && HAVE_DECL_BTN_2))
# define BTN_2 0x102
#endif
#if !(defined(BTN_3) || (defined(HAVE_DECL_BTN_3) && HAVE_DECL_BTN_3))
# define BTN_3 0x103
#endif
#if !(defined(BTN_4) || (defined(HAVE_DECL_BTN_4) && HAVE_DECL_BTN_4))
# define BTN_4 0x104
#endif
#if !(defined(BTN_5) || (defined(HAVE_DECL_BTN_5) && HAVE_DECL_BTN_5))
# define BTN_5 0x105
#endif
#if !(defined(BTN_6) || (defined(HAVE_DECL_BTN_6) && HAVE_DECL_BTN_6))
# define BTN_6 0x106
#endif
#if !(defined(BTN_7) || (defined(HAVE_DECL_BTN_7) && HAVE_DECL_BTN_7))
# define BTN_7 0x107
#endif
#if !(defined(BTN_8) || (defined(HAVE_DECL_BTN_8) && HAVE_DECL_BTN_8))
# define BTN_8 0x108
#endif
#if !(defined(BTN_9) || (defined(HAVE_DECL_BTN_9) && HAVE_DECL_BTN_9))
# define BTN_9 0x109
#endif
#if !(defined(BTN_MOUSE) || (defined(HAVE_DECL_BTN_MOUSE) && HAVE_DECL_BTN_MOUSE))
# define BTN_MOUSE 0x110
#endif
#if !(defined(BTN_LEFT) || (defined(HAVE_DECL_BTN_LEFT) && HAVE_DECL_BTN_LEFT))
# define BTN_LEFT 0x110
#endif
#if !(defined(BTN_RIGHT) || (defined(HAVE_DECL_BTN_RIGHT) && HAVE_DECL_BTN_RIGHT))
# define BTN_RIGHT 0x111
#endif
#if !(defined(BTN_MIDDLE) || (defined(HAVE_DECL_BTN_MIDDLE) && HAVE_DECL_BTN_MIDDLE))
# define BTN_MIDDLE 0x112
#endif
#if !(defined(BTN_SIDE) || (defined(HAVE_DECL_BTN_SIDE) && HAVE_DECL_BTN_SIDE))
# define BTN_SIDE 0x113
#endif
#if !(defined(BTN_EXTRA) || (defined(HAVE_DECL_BTN_EXTRA) && HAVE_DECL_BTN_EXTRA))
# define BTN_EXTRA 0x114
#endif
#if !(defined(BTN_FORWARD) || (defined(HAVE_DECL_BTN_FORWARD) && HAVE_DECL_BTN_FORWARD))
# define BTN_FORWARD 0x115
#endif
#if !(defined(BTN_BACK) || (defined(HAVE_DECL_BTN_BACK) && HAVE_DECL_BTN_BACK))
# define BTN_BACK 0x116
#endif
#if !(defined(BTN_TASK) || (defined(HAVE_DECL_BTN_TASK) && HAVE_DECL_BTN_TASK))
# define BTN_TASK 0x117
#endif
#if !(defined(BTN_JOYSTICK) || (defined(HAVE_DECL_BTN_JOYSTICK) && HAVE_DECL_BTN_JOYSTICK))
# define BTN_JOYSTICK 0x120
#endif
#if !(defined(BTN_TRIGGER) || (defined(HAVE_DECL_BTN_TRIGGER) && HAVE_DECL_BTN_TRIGGER))
# define BTN_TRIGGER 0x120
#endif
#if !(defined(BTN_THUMB) || (defined(HAVE_DECL_BTN_THUMB) && HAVE_DECL_BTN_THUMB))
# define BTN_THUMB 0x121
#endif
#if !(defined(BTN_THUMB2) || (defined(HAVE_DECL_BTN_THUMB2) && HAVE_DECL_BTN_THUMB2))
# define BTN_THUMB2 0x122
#endif
#if !(defined(BTN_TOP) || (defined(HAVE_DECL_BTN_TOP) && HAVE_DECL_BTN_TOP))
# define BTN_TOP 0x123
#endif
#if !(defined(BTN_TOP2) || (defined(HAVE_DECL_BTN_TOP2) && HAVE_DECL_BTN_TOP2))
# define BTN_TOP2 0x124
#endif
#if !(defined(BTN_PINKIE) || (defined(HAVE_DECL_BTN_PINKIE) && HAVE_DECL_BTN_PINKIE))
# define BTN_PINKIE 0x125
#endif
#if !(defined(BTN_BASE) || (defined(HAVE_DECL_BTN_BASE) && HAVE_DECL_BTN_BASE))
# define BTN_BASE 0x126
#endif
#if !(defined(BTN_BASE2) || (defined(HAVE_DECL_BTN_BASE2) && HAVE_DECL_BTN_BASE2))
# define BTN_BASE2 0x127
#endif
#if !(defined(BTN_BASE3) || (defined(HAVE_DECL_BTN_BASE3) && HAVE_DECL_BTN_BASE3))
# define BTN_BASE3 0x128
#endif
#if !(defined(BTN_BASE4) || (defined(HAVE_DECL_BTN_BASE4) && HAVE_DECL_BTN_BASE4))
# define BTN_BASE4 0x129
#endif
#if !(defined(BTN_BASE5) || (defined(HAVE_DECL_BTN_BASE5) && HAVE_DECL_BTN_BASE5))
# define BTN_BASE5 0x12a
#endif
#if !(defined(BTN_BASE6) || (defined(HAVE_DECL_BTN_BASE6) && HAVE_DECL_BTN_BASE6))
# define BTN_BASE6 0x12b
#endif
#if !(defined(BTN_DEAD) || (defined(HAVE_DECL_BTN_DEAD) && HAVE_DECL_BTN_DEAD))
# define BTN_DEAD 0x12f
#endif
#if !(defined(BTN_GAMEPAD) || (defined(HAVE_DECL_BTN_GAMEPAD) && HAVE_DECL_BTN_GAMEPAD))
# define BTN_GAMEPAD 0x130
#endif
#if !(defined(BTN_SOUTH) || (defined(HAVE_DECL_BTN_SOUTH) && HAVE_DECL_BTN_SOUTH))
# define BTN_SOUTH 0x130
#endif
#if !(defined(BTN_EAST) || (defined(HAVE_DECL_BTN_EAST) && HAVE_DECL_BTN_EAST))
# define BTN_EAST 0x131
#endif
#if !(defined(BTN_C) || (defined(HAVE_DECL_BTN_C) && HAVE_DECL_BTN_C))
# define BTN_C 0x132
#endif
#if !(defined(BTN_NORTH) || (defined(HAVE_DECL_BTN_NORTH) && HAVE_DECL_BTN_NORTH))
# define BTN_NORTH 0x133
#endif
#if !(defined(BTN_WEST) || (defined(HAVE_DECL_BTN_WEST) && HAVE_DECL_BTN_WEST))
# define BTN_WEST 0x134
#endif
#if !(defined(BTN_Z) || (defined(HAVE_DECL_BTN_Z) && HAVE_DECL_BTN_Z))
# define BTN_Z 0x135
#endif
#if !(defined(BTN_TL) || (defined(HAVE_DECL_BTN_TL) && HAVE_DECL_BTN_TL))
# define BTN_TL 0x136
#endif
#if !(defined(BTN_TR) || (defined(HAVE_DECL_BTN_TR) && HAVE_DECL_BTN_TR))
# define BTN_TR 0x137
#endif
#if !(defined(BTN_TL2) || (defined(HAVE_DECL_BTN_TL2) && HAVE_DECL_BTN_TL2))
# define BTN_TL2 0x138
#endif
#if !(defined(BTN_TR2) || (defined(HAVE_DECL_BTN_TR2) && HAVE_DECL_BTN_TR2))
# define BTN_TR2 0x139
#endif
#if !(defined(BTN_SELECT) || (defined(HAVE_DECL_BTN_SELECT) && HAVE_DECL_BTN_SELECT))
# define BTN_SELECT 0x13a
#endif
#if !(defined(BTN_START) || (defined(HAVE_DECL_BTN_START) && HAVE_DECL_BTN_START))
# define BTN_START 0x13b
#endif
#if !(defined(BTN_MODE) || (defined(HAVE_DECL_BTN_MODE) && HAVE_DECL_BTN_MODE))
# define BTN_MODE 0x13c
#endif
#if !(defined(BTN_THUMBL) || (defined(HAVE_DECL_BTN_THUMBL) && HAVE_DECL_BTN_THUMBL))
# define BTN_THUMBL 0x13d
#endif
#if !(defined(BTN_THUMBR) || (defined(HAVE_DECL_BTN_THUMBR) && HAVE_DECL_BTN_THUMBR))
# define BTN_THUMBR 0x13e
#endif
#if !(defined(BTN_DIGI) || (defined(HAVE_DECL_BTN_DIGI) && HAVE_DECL_BTN_DIGI))
# define BTN_DIGI 0x140
#endif
#if !(defined(BTN_TOOL_PEN) || (defined(HAVE_DECL_BTN_TOOL_PEN) && HAVE_DECL_BTN_TOOL_PEN))
# define BTN_TOOL_PEN 0x140
#endif
#if !(defined(BTN_TOOL_RUBBER) || (defined(HAVE_DECL_BTN_TOOL_RUBBER) && HAVE_DECL_BTN_TOOL_RUBBER))
# define BTN_TOOL_RUBBER 0x141
#endif
#if !(defined(BTN_TOOL_BRUSH) || (defined(HAVE_DECL_BTN_TOOL_BRUSH) && HAVE_DECL_BTN_TOOL_BRUSH))
# define BTN_TOOL_BRUSH 0x142
#endif
#if !(defined(BTN_TOOL_PENCIL) || (defined(HAVE_DECL_BTN_TOOL_PENCIL) && HAVE_DECL_BTN_TOOL_PENCIL))
# define BTN_TOOL_PENCIL 0x143
#endif
#if !(defined(BTN_TOOL_AIRBRUSH) || (defined(HAVE_DECL_BTN_TOOL_AIRBRUSH) && HAVE_DECL_BTN_TOOL_AIRBRUSH))
# define BTN_TOOL_AIRBRUSH 0x144
#endif
#if !(defined(BTN_TOOL_FINGER) || (defined(HAVE_DECL_BTN_TOOL_FINGER) && HAVE_DECL_BTN_TOOL_FINGER))
# define BTN_TOOL_FINGER 0x145
#endif
#if !(defined(BTN_TOOL_MOUSE) || (defined(HAVE_DECL_BTN_TOOL_MOUSE) && HAVE_DECL_BTN_TOOL_MOUSE))
# define BTN_TOOL_MOUSE 0x146
#endif
#if !(defined(BTN_TOOL_LENS) || (defined(HAVE_DECL_BTN_TOOL_LENS) && HAVE_DECL_BTN_TOOL_LENS))
# define BTN_TOOL_LENS 0x147
#endif
#if !(defined(BTN_TOOL_QUINTTAP) || (defined(HAVE_DECL_BTN_TOOL_QUINTTAP) && HAVE_DECL_BTN_TOOL_QUINTTAP))
# define BTN_TOOL_QUINTTAP 0x148
#endif
#if !(defined(BTN_STYLUS3) || (defined(HAVE_DECL_BTN_STYLUS3) && HAVE_DECL_BTN_STYLUS3))
# define BTN_STYLUS3 0x149
#endif
#if !(defined(BTN_TOUCH) || (defined(HAVE_DECL_BTN_TOUCH) && HAVE_DECL_BTN_TOUCH))
# define BTN_TOUCH 0x14a
#endif
#if !(defined(BTN_STYLUS) || (defined(HAVE_DECL_BTN_STYLUS) && HAVE_DECL_BTN_STYLUS))
# define BTN_STYLUS 0x14b
#endif
#if !(defined(BTN_STYLUS2) || (defined(HAVE_DECL_BTN_STYLUS2) && HAVE_DECL_BTN_STYLUS2))
# define BTN_STYLUS2 0x14c
#endif
#if !(defined(BTN_TOOL_DOUBLETAP) || (defined(HAVE_DECL_BTN_TOOL_DOUBLETAP) && HAVE_DECL_BTN_TOOL_DOUBLETAP))
# define BTN_TOOL_DOUBLETAP 0x14d
#endif
#if !(defined(BTN_TOOL_TRIPLETAP) || (defined(HAVE_DECL_BTN_TOOL_TRIPLETAP) && HAVE_DECL_BTN_TOOL_TRIPLETAP))
# define BTN_TOOL_TRIPLETAP 0x14e
#endif
#if !(defined(BTN_TOOL_QUADTAP) || (defined(HAVE_DECL_BTN_TOOL_QUADTAP) && HAVE_DECL_BTN_TOOL_QUADTAP))
# define BTN_TOOL_QUADTAP 0x14f
#endif
#if !(defined(BTN_WHEEL) || (defined(HAVE_DECL_BTN_WHEEL) && HAVE_DECL_BTN_WHEEL))
# define BTN_WHEEL 0x150
#endif
#if !(defined(BTN_GEAR_DOWN) || (defined(HAVE_DECL_BTN_GEAR_DOWN) && HAVE_DECL_BTN_GEAR_DOWN))
# define BTN_GEAR_DOWN 0x150
#endif
#if !(defined(BTN_GEAR_UP) || (defined(HAVE_DECL_BTN_GEAR_UP) && HAVE_DECL_BTN_GEAR_UP))
# define BTN_GEAR_UP 0x151
#endif
#if !(defined(KEY_OK) || (defined(HAVE_DECL_KEY_OK) && HAVE_DECL_KEY_OK))
# define KEY_OK 0x160
#endif
#if !(defined(KEY_SELECT) || (defined(HAVE_DECL_KEY_SELECT) && HAVE_DECL_KEY_SELECT))
# define KEY_SELECT 0x161
#endif
#if !(defined(KEY_GOTO) || (defined(HAVE_DECL_KEY_GOTO) && HAVE_DECL_KEY_GOTO))
# define KEY_GOTO 0x162
#endif
#if !(defined(KEY_CLEAR) || (defined(HAVE_DECL_KEY_CLEAR) && HAVE_DECL_KEY_CLEAR))
# define KEY_CLEAR 0x163
#endif
#if !(defined(KEY_POWER2) || (defined(HAVE_DECL_KEY_POWER2) && HAVE_DECL_KEY_POWER2))
# define KEY_POWER2 0x164
#endif
#if !(defined(KEY_OPTION) || (defined(HAVE_DECL_KEY_OPTION) && HAVE_DECL_KEY_OPTION))
# define KEY_OPTION 0x165
#endif
#if !(defined(KEY_INFO) || (defined(HAVE_DECL_KEY_INFO) && HAVE_DECL_KEY_INFO))
# define KEY_INFO 0x166
#endif
#if !(defined(KEY_TIME) || (defined(HAVE_DECL_KEY_TIME) && HAVE_DECL_KEY_TIME))
# define KEY_TIME 0x167
#endif
#if !(defined(KEY_VENDOR) || (defined(HAVE_DECL_KEY_VENDOR) && HAVE_DECL_KEY_VENDOR))
# define KEY_VENDOR 0x168
#endif
#if !(defined(KEY_ARCHIVE) || (defined(HAVE_DECL_KEY_ARCHIVE) && HAVE_DECL_KEY_ARCHIVE))
# define KEY_ARCHIVE 0x169
#endif
#if !(defined(KEY_PROGRAM) || (defined(HAVE_DECL_KEY_PROGRAM) && HAVE_DECL_KEY_PROGRAM))
# define KEY_PROGRAM 0x16a
#endif
#if !(defined(KEY_CHANNEL) || (defined(HAVE_DECL_KEY_CHANNEL) && HAVE_DECL_KEY_CHANNEL))
# define KEY_CHANNEL 0x16b
#endif
#if !(defined(KEY_FAVORITES) || (defined(HAVE_DECL_KEY_FAVORITES) && HAVE_DECL_KEY_FAVORITES))
# define KEY_FAVORITES 0x16c
#endif
#if !(defined(KEY_EPG) || (defined(HAVE_DECL_KEY_EPG) && HAVE_DECL_KEY_EPG))
# define KEY_EPG 0x16d
#endif
#if !(defined(KEY_PVR) || (defined(HAVE_DECL_KEY_PVR) && HAVE_DECL_KEY_PVR))
# define KEY_PVR 0x16e
#endif
#if !(defined(KEY_MHP) || (defined(HAVE_DECL_KEY_MHP) && HAVE_DECL_KEY_MHP))
# define KEY_MHP 0x16f
#endif
#if !(defined(KEY_LANGUAGE) || (defined(HAVE_DECL_KEY_LANGUAGE) && HAVE_DECL_KEY_LANGUAGE))
# define KEY_LANGUAGE 0x170
#endif
#if !(defined(KEY_TITLE) || (defined(HAVE_DECL_KEY_TITLE) && HAVE_DECL_KEY_TITLE))
# define KEY_TITLE 0x171
#endif
#if !(defined(KEY_SUBTITLE) || (defined(HAVE_DECL_KEY_SUBTITLE) && HAVE_DECL_KEY_SUBTITLE))
# define KEY_SUBTITLE 0x172
#endif
#if !(defined(KEY_ANGLE) || (defined(HAVE_DECL_KEY_ANGLE) && HAVE_DECL_KEY_ANGLE))
# define KEY_ANGLE 0x173
#endif
#if !(defined(KEY_ZOOM) || (defined(HAVE_DECL_KEY_ZOOM) && HAVE_DECL_KEY_ZOOM))
# define KEY_ZOOM 0x174
#endif
#if !(defined(KEY_MODE) || (defined(HAVE_DECL_KEY_MODE) && HAVE_DECL_KEY_MODE))
# define KEY_MODE 0x175
#endif
#if !(defined(KEY_KEYBOARD) || (defined(HAVE_DECL_KEY_KEYBOARD) && HAVE_DECL_KEY_KEYBOARD))
# define KEY_KEYBOARD 0x176
#endif
#if !(defined(KEY_SCREEN) || (defined(HAVE_DECL_KEY_SCREEN) && HAVE_DECL_KEY_SCREEN))
# define KEY_SCREEN 0x177
#endif
#if !(defined(KEY_PC) || (defined(HAVE_DECL_KEY_PC) && HAVE_DECL_KEY_PC))
# define KEY_PC 0x178
#endif
#if !(defined(KEY_TV) || (defined(HAVE_DECL_KEY_TV) && HAVE_DECL_KEY_TV))
# define KEY_TV 0x179
#endif
#if !(defined(KEY_TV2) || (defined(HAVE_DECL_KEY_TV2) && HAVE_DECL_KEY_TV2))
# define KEY_TV2 0x17a
#endif
#if !(defined(KEY_VCR) || (defined(HAVE_DECL_KEY_VCR) && HAVE_DECL_KEY_VCR))
# define KEY_VCR 0x17b
#endif
#if !(defined(KEY_VCR2) || (defined(HAVE_DECL_KEY_VCR2) && HAVE_DECL_KEY_VCR2))
# define KEY_VCR2 0x17c
#endif
#if !(defined(KEY_SAT) || (defined(HAVE_DECL_KEY_SAT) && HAVE_DECL_KEY_SAT))
# define KEY_SAT 0x17d
#endif
#if !(defined(KEY_SAT2) || (defined(HAVE_DECL_KEY_SAT2) && HAVE_DECL_KEY_SAT2))
# define KEY_SAT2 0x17e
#endif
#if !(defined(KEY_CD) || (defined(HAVE_DECL_KEY_CD) && HAVE_DECL_KEY_CD))
# define KEY_CD 0x17f
#endif
#if !(defined(KEY_TAPE) || (defined(HAVE_DECL_KEY_TAPE) && HAVE_DECL_KEY_TAPE))
# define KEY_TAPE 0x180
#endif
#if !(defined(KEY_RADIO) || (defined(HAVE_DECL_KEY_RADIO) && HAVE_DECL_KEY_RADIO))
# define KEY_RADIO 0x181
#endif
#if !(defined(KEY_TUNER) || (defined(HAVE_DECL_KEY_TUNER) && HAVE_DECL_KEY_TUNER))
# define KEY_TUNER 0x182
#endif
#if !(defined(KEY_PLAYER) || (defined(HAVE_DECL_KEY_PLAYER) && HAVE_DECL_KEY_PLAYER))
# define KEY_PLAYER 0x183
#endif
#if !(defined(KEY_TEXT) || (defined(HAVE_DECL_KEY_TEXT) && HAVE_DECL_KEY_TEXT))
# define KEY_TEXT 0x184
#endif
#if !(defined(KEY_DVD) || (defined(HAVE_DECL_KEY_DVD) && HAVE_DECL_KEY_DVD))
# define KEY_DVD 0x185
#endif
#if !(defined(KEY_AUX) || (defined(HAVE_DECL_KEY_AUX) && HAVE_DECL_KEY_AUX))
# define KEY_AUX 0x186
#endif
#if !(defined(KEY_MP3) || (defined(HAVE_DECL_KEY_MP3) && HAVE_DECL_KEY_MP3))
# define KEY_MP3 0x187
#endif
#if !(defined(KEY_AUDIO) || (defined(HAVE_DECL_KEY_AUDIO) && HAVE_DECL_KEY_AUDIO))
# define KEY_AUDIO 0x188
#endif
#if !(defined(KEY_VIDEO) || (defined(HAVE_DECL_KEY_VIDEO) && HAVE_DECL_KEY_VIDEO))
# define KEY_VIDEO 0x189
#endif
#if !(defined(KEY_DIRECTORY) || (defined(HAVE_DECL_KEY_DIRECTORY) && HAVE_DECL_KEY_DIRECTORY))
# define KEY_DIRECTORY 0x18a
#endif
#if !(defined(KEY_LIST) || (defined(HAVE_DECL_KEY_LIST) && HAVE_DECL_KEY_LIST))
# define KEY_LIST 0x18b
#endif
#if !(defined(KEY_MEMO) || (defined(HAVE_DECL_KEY_MEMO) && HAVE_DECL_KEY_MEMO))
# define KEY_MEMO 0x18c
#endif
#if !(defined(KEY_CALENDAR) || (defined(HAVE_DECL_KEY_CALENDAR) && HAVE_DECL_KEY_CALENDAR))
# define KEY_CALENDAR 0x18d
#endif
#if !(defined(KEY_RED) || (defined(HAVE_DECL_KEY_RED) && HAVE_DECL_KEY_RED))
# define KEY_RED 0x18e
#endif
#if !(defined(KEY_GREEN) || (defined(HAVE_DECL_KEY_GREEN) && HAVE_DECL_KEY_GREEN))
# define KEY_GREEN 0x18f
#endif
#if !(defined(KEY_YELLOW) || (defined(HAVE_DECL_KEY_YELLOW) && HAVE_DECL_KEY_YELLOW))
# define KEY_YELLOW 0x190
#endif
#if !(defined(KEY_BLUE) || (defined(HAVE_DECL_KEY_BLUE) && HAVE_DECL_KEY_BLUE))
# define KEY_BLUE 0x191
#endif
#if !(defined(KEY_CHANNELUP) || (defined(HAVE_DECL_KEY_CHANNELUP) && HAVE_DECL_KEY_CHANNELUP))
# define KEY_CHANNELUP 0x192
#endif
#if !(defined(KEY_CHANNELDOWN) || (defined(HAVE_DECL_KEY_CHANNELDOWN) && HAVE_DECL_KEY_CHANNELDOWN))
# define KEY_CHANNELDOWN 0x193
#endif
#if !(defined(KEY_FIRST) || (defined(HAVE_DECL_KEY_FIRST) && HAVE_DECL_KEY_FIRST))
# define KEY_FIRST 0x194
#endif
#if !(defined(KEY_LAST) || (defined(HAVE_DECL_KEY_LAST) && HAVE_DECL_KEY_LAST))
# define KEY_LAST 0x195
#endif
#if !(defined(KEY_AB) || (defined(HAVE_DECL_KEY_AB) && HAVE_DECL_KEY_AB))
# define KEY_AB 0x196
#endif
#if !(defined(KEY_NEXT) || (defined(HAVE_DECL_KEY_NEXT) && HAVE_DECL_KEY_NEXT))
# define KEY_NEXT 0x197
#endif
#if !(defined(KEY_RESTART) || (defined(HAVE_DECL_KEY_RESTART) && HAVE_DECL_KEY_RESTART))
# define KEY_RESTART 0x198
#endif
#if !(defined(KEY_SLOW) || (defined(HAVE_DECL_KEY_SLOW) && HAVE_DECL_KEY_SLOW))
# define KEY_SLOW 0x199
#endif
#if !(defined(KEY_SHUFFLE) || (defined(HAVE_DECL_KEY_SHUFFLE) && HAVE_DECL_KEY_SHUFFLE))
# define KEY_SHUFFLE 0x19a
#endif
#if !(defined(KEY_BREAK) || (defined(HAVE_DECL_KEY_BREAK) && HAVE_DECL_KEY_BREAK))
# define KEY_BREAK 0x19b
#endif
#if !(defined(KEY_PREVIOUS) || (defined(HAVE_DECL_KEY_PREVIOUS) && HAVE_DECL_KEY_PREVIOUS))
# define KEY_PREVIOUS 0x19c
#endif
#if !(defined(KEY_DIGITS) || (defined(HAVE_DECL_KEY_DIGITS) && HAVE_DECL_KEY_DIGITS))
# define KEY_DIGITS 0x19d
#endif
#if !(defined(KEY_TEEN) || (defined(HAVE_DECL_KEY_TEEN) && HAVE_DECL_KEY_TEEN))
# define KEY_TEEN 0x19e
#endif
#if !(defined(KEY_TWEN) || (defined(HAVE_DECL_KEY_TWEN) && HAVE_DECL_KEY_TWEN))
# define KEY_TWEN 0x19f
#endif
#if !(defined(KEY_VIDEOPHONE) || (defined(HAVE_DECL_KEY_VIDEOPHONE) && HAVE_DECL_KEY_VIDEOPHONE))
# define KEY_VIDEOPHONE 0x1a0
#endif
#if !(defined(KEY_GAMES) || (defined(HAVE_DECL_KEY_GAMES) && HAVE_DECL_KEY_GAMES))
# define KEY_GAMES 0x1a1
#endif
#if !(defined(KEY_ZOOMIN) || (defined(HAVE_DECL_KEY_ZOOMIN) && HAVE_DECL_KEY_ZOOMIN))
# define KEY_ZOOMIN 0x1a2
#endif
#if !(defined(KEY_ZOOMOUT) || (defined(HAVE_DECL_KEY_ZOOMOUT) && HAVE_DECL_KEY_ZOOMOUT))
# define KEY_ZOOMOUT 0x1a3
#endif
#if !(defined(KEY_ZOOMRESET) || (defined(HAVE_DECL_KEY_ZOOMRESET) && HAVE_DECL_KEY_ZOOMRESET))
# define KEY_ZOOMRESET 0x1a4
#endif
#if !(defined(KEY_WORDPROCESSOR) || (defined(HAVE_DECL_KEY_WORDPROCESSOR) && HAVE_DECL_KEY_WORDPROCESSOR))
# define KEY_WORDPROCESSOR 0x1a5
#endif
#if !(defined(KEY_EDITOR) || (defined(HAVE_DECL_KEY_EDITOR) && HAVE_DECL_KEY_EDITOR))
# define KEY_EDITOR 0x1a6
#endif
#if !(defined(KEY_SPREADSHEET) || (defined(HAVE_DECL_KEY_SPREADSHEET) && HAVE_DECL_KEY_SPREADSHEET))
# define KEY_SPREADSHEET 0x1a7
#endif
#if !(defined(KEY_GRAPHICSEDITOR) || (defined(HAVE_DECL_KEY_GRAPHICSEDITOR) && HAVE_DECL_KEY_GRAPHICSEDITOR))
# define KEY_GRAPHICSEDITOR 0x1a8
#endif
#if !(defined(KEY_PRESENTATION) || (defined(HAVE_DECL_KEY_PRESENTATION) && HAVE_DECL_KEY_PRESENTATION))
# define KEY_PRESENTATION 0x1a9
#endif
#if !(defined(KEY_DATABASE) || (defined(HAVE_DECL_KEY_DATABASE) && HAVE_DECL_KEY_DATABASE))
# define KEY_DATABASE 0x1aa
#endif
#if !(defined(KEY_NEWS) || (defined(HAVE_DECL_KEY_NEWS) && HAVE_DECL_KEY_NEWS))
# define KEY_NEWS 0x1ab
#endif
#if !(defined(KEY_VOICEMAIL) || (defined(HAVE_DECL_KEY_VOICEMAIL) && HAVE_DECL_KEY_VOICEMAIL))
# define KEY_VOICEMAIL 0x1ac
#endif
#if !(defined(KEY_ADDRESSBOOK) || (defined(HAVE_DECL_KEY_ADDRESSBOOK) && HAVE_DECL_KEY_ADDRESSBOOK))
# define KEY_ADDRESSBOOK 0x1ad
#endif
#if !(defined(KEY_MESSENGER) || (defined(HAVE_DECL_KEY_MESSENGER) && HAVE_DECL_KEY_MESSENGER))
# define KEY_MESSENGER 0x1ae
#endif
#if !(defined(KEY_DISPLAYTOGGLE) || (defined(HAVE_DECL_KEY_DISPLAYTOGGLE) && HAVE_DECL_KEY_DISPLAYTOGGLE))
# define KEY_DISPLAYTOGGLE 0x1af
#endif
#if !(defined(KEY_SPELLCHECK) || (defined(HAVE_DECL_KEY_SPELLCHECK) && HAVE_DECL_KEY_SPELLCHECK))
# define KEY_SPELLCHECK 0x1b0
#endif
#if !(defined(KEY_LOGOFF) || (defined(HAVE_DECL_KEY_LOGOFF) && HAVE_DECL_KEY_LOGOFF))
# define KEY_LOGOFF 0x1b1
#endif
#if !(defined(KEY_DOLLAR) || (defined(HAVE_DECL_KEY_DOLLAR) && HAVE_DECL_KEY_DOLLAR))
# define KEY_DOLLAR 0x1b2
#endif
#if !(defined(KEY_EURO) || (defined(HAVE_DECL_KEY_EURO) && HAVE_DECL_KEY_EURO))
# define KEY_EURO 0x1b3
#endif
#if !(defined(KEY_FRAMEBACK) || (defined(HAVE_DECL_KEY_FRAMEBACK) && HAVE_DECL_KEY_FRAMEBACK))
# define KEY_FRAMEBACK 0x1b4
#endif
#if !(defined(KEY_FRAMEFORWARD) || (defined(HAVE_DECL_KEY_FRAMEFORWARD) && HAVE_DECL_KEY_FRAMEFORWARD))
# define KEY_FRAMEFORWARD 0x1b5
#endif
#if !(defined(KEY_CONTEXT_MENU) || (defined(HAVE_DECL_KEY_CONTEXT_MENU) && HAVE_DECL_KEY_CONTEXT_MENU))
# define KEY_CONTEXT_MENU 0x1b6
#endif
#if !(defined(KEY_MEDIA_REPEAT) || (defined(HAVE_DECL_KEY_MEDIA_REPEAT) && HAVE_DECL_KEY_MEDIA_REPEAT))
# define KEY_MEDIA_REPEAT 0x1b7
#endif
#if !(defined(KEY_10CHANNELSUP) || (defined(HAVE_DECL_KEY_10CHANNELSUP) && HAVE_DECL_KEY_10CHANNELSUP))
# define KEY_10CHANNELSUP 0x1b8
#endif
#if !(defined(KEY_10CHANNELSDOWN) || (defined(HAVE_DECL_KEY_10CHANNELSDOWN) && HAVE_DECL_KEY_10CHANNELSDOWN))
# define KEY_10CHANNELSDOWN 0x1b9
#endif
#if !(defined(KEY_IMAGES) || (defined(HAVE_DECL_KEY_IMAGES) && HAVE_DECL_KEY_IMAGES))
# define KEY_IMAGES 0x1ba
#endif
#if !(defined(KEY_DEL_EOL) || (defined(HAVE_DECL_KEY_DEL_EOL) && HAVE_DECL_KEY_DEL_EOL))
# define KEY_DEL_EOL 0x1c0
#endif
#if !(defined(KEY_DEL_EOS) || (defined(HAVE_DECL_KEY_DEL_EOS) && HAVE_DECL_KEY_DEL_EOS))
# define KEY_DEL_EOS 0x1c1
#endif
#if !(defined(KEY_INS_LINE) || (defined(HAVE_DECL_KEY_INS_LINE) && HAVE_DECL_KEY_INS_LINE))
# define KEY_INS_LINE 0x1c2
#endif
#if !(defined(KEY_DEL_LINE) || (defined(HAVE_DECL_KEY_DEL_LINE) && HAVE_DECL_KEY_DEL_LINE))
# define KEY_DEL_LINE 0x1c3
#endif
#if !(defined(KEY_FN) || (defined(HAVE_DECL_KEY_FN) && HAVE_DECL_KEY_FN))
# define KEY_FN 0x1d0
#endif
#if !(defined(KEY_FN_ESC) || (defined(HAVE_DECL_KEY_FN_ESC) && HAVE_DECL_KEY_FN_ESC))
# define KEY_FN_ESC 0x1d1
#endif
#if !(defined(KEY_FN_F1) || (defined(HAVE_DECL_KEY_FN_F1) && HAVE_DECL_KEY_FN_F1))
# define KEY_FN_F1 0x1d2
#endif
#if !(defined(KEY_FN_F2) || (defined(HAVE_DECL_KEY_FN_F2) && HAVE_DECL_KEY_FN_F2))
# define KEY_FN_F2 0x1d3
#endif
#if !(defined(KEY_FN_F3) || (defined(HAVE_DECL_KEY_FN_F3) && HAVE_DECL_KEY_FN_F3))
# define KEY_FN_F3 0x1d4
#endif
#if !(defined(KEY_FN_F4) || (defined(HAVE_DECL_KEY_FN_F4) && HAVE_DECL_KEY_FN_F4))
# define KEY_FN_F4 0x1d5
#endif
#if !(defined(KEY_FN_F5) || (defined(HAVE_DECL_KEY_FN_F5) && HAVE_DECL_KEY_FN_F5))
# define KEY_FN_F5 0x1d6
#endif
#if !(defined(KEY_FN_F6) || (defined(HAVE_DECL_KEY_FN_F6) && HAVE_DECL_KEY_FN_F6))
# define KEY_FN_F6 0x1d7
#endif
#if !(defined(KEY_FN_F7) || (defined(HAVE_DECL_KEY_FN_F7) && HAVE_DECL_KEY_FN_F7))
# define KEY_FN_F7 0x1d8
#endif
#if !(defined(KEY_FN_F8) || (defined(HAVE_DECL_KEY_FN_F8) && HAVE_DECL_KEY_FN_F8))
# define KEY_FN_F8 0x1d9
#endif
#if !(defined(KEY_FN_F9) || (defined(HAVE_DECL_KEY_FN_F9) && HAVE_DECL_KEY_FN_F9))
# define KEY_FN_F9 0x1da
#endif
#if !(defined(KEY_FN_F10) || (defined(HAVE_DECL_KEY_FN_F10) && HAVE_DECL_KEY_FN_F10))
# define KEY_FN_F10 0x1db
#endif
#if !(defined(KEY_FN_F11) || (defined(HAVE_DECL_KEY_FN_F11) && HAVE_DECL_KEY_FN_F11))
# define KEY_FN_F11 0x1dc
#endif
#if !(defined(KEY_FN_F12) || (defined(HAVE_DECL_KEY_FN_F12) && HAVE_DECL_KEY_FN_F12))
# define KEY_FN_F12 0x1dd
#endif
#if !(defined(KEY_FN_1) || (defined(HAVE_DECL_KEY_FN_1) && HAVE_DECL_KEY_FN_1))
# define KEY_FN_1 0x1de
#endif
#if !(defined(KEY_FN_2) || (defined(HAVE_DECL_KEY_FN_2) && HAVE_DECL_KEY_FN_2))
# define KEY_FN_2 0x1df
#endif
#if !(defined(KEY_FN_D) || (defined(HAVE_DECL_KEY_FN_D) && HAVE_DECL_KEY_FN_D))
# define KEY_FN_D 0x1e0
#endif
#if !(defined(KEY_FN_E) || (defined(HAVE_DECL_KEY_FN_E) && HAVE_DECL_KEY_FN_E))
# define KEY_FN_E 0x1e1
#endif
#if !(defined(KEY_FN_F) || (defined(HAVE_DECL_KEY_FN_F) && HAVE_DECL_KEY_FN_F))
# define KEY_FN_F 0x1e2
#endif
#if !(defined(KEY_FN_S) || (defined(HAVE_DECL_KEY_FN_S) && HAVE_DECL_KEY_FN_S))
# define KEY_FN_S 0x1e3
#endif
#if !(defined(KEY_FN_B) || (defined(HAVE_DECL_KEY_FN_B) && HAVE_DECL_KEY_FN_B))
# define KEY_FN_B 0x1e4
#endif
#if !(defined(KEY_BRL_DOT1) || (defined(HAVE_DECL_KEY_BRL_DOT1) && HAVE_DECL_KEY_BRL_DOT1))
# define KEY_BRL_DOT1 0x1f1
#endif
#if !(defined(KEY_BRL_DOT2) || (defined(HAVE_DECL_KEY_BRL_DOT2) && HAVE_DECL_KEY_BRL_DOT2))
# define KEY_BRL_DOT2 0x1f2
#endif
#if !(defined(KEY_BRL_DOT3) || (defined(HAVE_DECL_KEY_BRL_DOT3) && HAVE_DECL_KEY_BRL_DOT3))
# define KEY_BRL_DOT3 0x1f3
#endif
#if !(defined(KEY_BRL_DOT4) || (defined(HAVE_DECL_KEY_BRL_DOT4) && HAVE_DECL_KEY_BRL_DOT4))
# define KEY_BRL_DOT4 0x1f4
#endif
#if !(defined(KEY_BRL_DOT5) || (defined(HAVE_DECL_KEY_BRL_DOT5) && HAVE_DECL_KEY_BRL_DOT5))
# define KEY_BRL_DOT5 0x1f5
#endif
#if !(defined(KEY_BRL_DOT6) || (defined(HAVE_DECL_KEY_BRL_DOT6) && HAVE_DECL_KEY_BRL_DOT6))
# define KEY_BRL_DOT6 0x1f6
#endif
#if !(defined(KEY_BRL_DOT7) || (defined(HAVE_DECL_KEY_BRL_DOT7) && HAVE_DECL_KEY_BRL_DOT7))
# define KEY_BRL_DOT7 0x1f7
#endif
#if !(defined(KEY_BRL_DOT8) || (defined(HAVE_DECL_KEY_BRL_DOT8) && HAVE_DECL_KEY_BRL_DOT8))
# define KEY_BRL_DOT8 0x1f8
#endif
#if !(defined(KEY_BRL_DOT9) || (defined(HAVE_DECL_KEY_BRL_DOT9) && HAVE_DECL_KEY_BRL_DOT9))
# define KEY_BRL_DOT9 0x1f9
#endif
#if !(defined(KEY_BRL_DOT10) || (defined(HAVE_DECL_KEY_BRL_DOT10) && HAVE_DECL_KEY_BRL_DOT10))
# define KEY_BRL_DOT10 0x1fa
#endif
#if !(defined(KEY_NUMERIC_0) || (defined(HAVE_DECL_KEY_NUMERIC_0) && HAVE_DECL_KEY_NUMERIC_0))
# define KEY_NUMERIC_0 0x200
#endif
#if !(defined(KEY_NUMERIC_1) || (defined(HAVE_DECL_KEY_NUMERIC_1) && HAVE_DECL_KEY_NUMERIC_1))
# define KEY_NUMERIC_1 0x201
#endif
#if !(defined(KEY_NUMERIC_2) || (defined(HAVE_DECL_KEY_NUMERIC_2) && HAVE_DECL_KEY_NUMERIC_2))
# define KEY_NUMERIC_2 0x202
#endif
#if !(defined(KEY_NUMERIC_3) || (defined(HAVE_DECL_KEY_NUMERIC_3) && HAVE_DECL_KEY_NUMERIC_3))
# define KEY_NUMERIC_3 0x203
#endif
#if !(defined(KEY_NUMERIC_4) || (defined(HAVE_DECL_KEY_NUMERIC_4) && HAVE_DECL_KEY_NUMERIC_4))
# define KEY_NUMERIC_4 0x204
#endif
#if !(defined(KEY_NUMERIC_5) || (defined(HAVE_DECL_KEY_NUMERIC_5) && HAVE_DECL_KEY_NUMERIC_5))
# define KEY_NUMERIC_5 0x205
#endif
#if !(defined(KEY_NUMERIC_6) || (defined(HAVE_DECL_KEY_NUMERIC_6) && HAVE_DECL_KEY_NUMERIC_6))
# define KEY_NUMERIC_6 0x206
#endif
#if !(defined(KEY_NUMERIC_7) || (defined(HAVE_DECL_KEY_NUMERIC_7) && HAVE_DECL_KEY_NUMERIC_7))
# define KEY_NUMERIC_7 0x207
#endif
#if !(defined(KEY_NUMERIC_8) || (defined(HAVE_DECL_KEY_NUMERIC_8) && HAVE_DECL_KEY_NUMERIC_8))
# define KEY_NUMERIC_8 0x208
#endif
#if !(defined(KEY_NUMERIC_9) || (defined(HAVE_DECL_KEY_NUMERIC_9) && HAVE_DECL_KEY_NUMERIC_9))
# define KEY_NUMERIC_9 0x209
#endif
#if !(defined(KEY_NUMERIC_STAR) || (defined(HAVE_DECL_KEY_NUMERIC_STAR) && HAVE_DECL_KEY_NUMERIC_STAR))
# define KEY_NUMERIC_STAR 0x20a
#endif
#if !(defined(KEY_NUMERIC_POUND) || (defined(HAVE_DECL_KEY_NUMERIC_POUND) && HAVE_DECL_KEY_NUMERIC_POUND))
# define KEY_NUMERIC_POUND 0x20b
#endif
#if !(defined(KEY_NUMERIC_A) || (defined(HAVE_DECL_KEY_NUMERIC_A) && HAVE_DECL_KEY_NUMERIC_A))
# define KEY_NUMERIC_A 0x20c
#endif
#if !(defined(KEY_NUMERIC_B) || (defined(HAVE_DECL_KEY_NUMERIC_B) && HAVE_DECL_KEY_NUMERIC_B))
# define KEY_NUMERIC_B 0x20d
#endif
#if !(defined(KEY_NUMERIC_C) || (defined(HAVE_DECL_KEY_NUMERIC_C) && HAVE_DECL_KEY_NUMERIC_C))
# define KEY_NUMERIC_C 0x20e
#endif
#if !(defined(KEY_NUMERIC_D) || (defined(HAVE_DECL_KEY_NUMERIC_D) && HAVE_DECL_KEY_NUMERIC_D))
# define KEY_NUMERIC_D 0x20f
#endif
#if !(defined(KEY_CAMERA_FOCUS) || (defined(HAVE_DECL_KEY_CAMERA_FOCUS) && HAVE_DECL_KEY_CAMERA_FOCUS))
# define KEY_CAMERA_FOCUS 0x210
#endif
#if !(defined(KEY_WPS_BUTTON) || (defined(HAVE_DECL_KEY_WPS_BUTTON) && HAVE_DECL_KEY_WPS_BUTTON))
# define KEY_WPS_BUTTON 0x211
#endif
#if !(defined(KEY_TOUCHPAD_TOGGLE) || (defined(HAVE_DECL_KEY_TOUCHPAD_TOGGLE) && HAVE_DECL_KEY_TOUCHPAD_TOGGLE))
# define KEY_TOUCHPAD_TOGGLE 0x212
#endif
#if !(defined(KEY_TOUCHPAD_ON) || (defined(HAVE_DECL_KEY_TOUCHPAD_ON) && HAVE_DECL_KEY_TOUCHPAD_ON))
# define KEY_TOUCHPAD_ON 0x213
#endif
#if !(defined(KEY_TOUCHPAD_OFF) || (defined(HAVE_DECL_KEY_TOUCHPAD_OFF) && HAVE_DECL_KEY_TOUCHPAD_OFF))
# define KEY_TOUCHPAD_OFF 0x214
#endif
#if !(defined(KEY_CAMERA_ZOOMIN) || (defined(HAVE_DECL_KEY_CAMERA_ZOOMIN) && HAVE_DECL_KEY_CAMERA_ZOOMIN))
# define KEY_CAMERA_ZOOMIN 0x215
#endif
#if !(defined(KEY_CAMERA_ZOOMOUT) || (defined(HAVE_DECL_KEY_CAMERA_ZOOMOUT) && HAVE_DECL_KEY_CAMERA_ZOOMOUT))
# define KEY_CAMERA_ZOOMOUT 0x216
#endif
#if !(defined(KEY_CAMERA_UP) || (defined(HAVE_DECL_KEY_CAMERA_UP) && HAVE_DECL_KEY_CAMERA_UP))
# define KEY_CAMERA_UP 0x217
#endif
#if !(defined(KEY_CAMERA_DOWN) || (defined(HAVE_DECL_KEY_CAMERA_DOWN) && HAVE_DECL_KEY_CAMERA_DOWN))
# define KEY_CAMERA_DOWN 0x218
#endif
#if !(defined(KEY_CAMERA_LEFT) || (defined(HAVE_DECL_KEY_CAMERA_LEFT) && HAVE_DECL_KEY_CAMERA_LEFT))
# define KEY_CAMERA_LEFT 0x219
#endif
#if !(defined(KEY_CAMERA_RIGHT) || (defined(HAVE_DECL_KEY_CAMERA_RIGHT) && HAVE_DECL_KEY_CAMERA_RIGHT))
# define KEY_CAMERA_RIGHT 0x21a
#endif
#if !(defined(KEY_ATTENDANT_ON) || (defined(HAVE_DECL_KEY_ATTENDANT_ON) && HAVE_DECL_KEY_ATTENDANT_ON))
# define KEY_ATTENDANT_ON 0x21b
#endif
#if !(defined(KEY_ATTENDANT_OFF) || (defined(HAVE_DECL_KEY_ATTENDANT_OFF) && HAVE_DECL_KEY_ATTENDANT_OFF))
# define KEY_ATTENDANT_OFF 0x21c
#endif
#if !(defined(KEY_ATTENDANT_TOGGLE) || (defined(HAVE_DECL_KEY_ATTENDANT_TOGGLE) && HAVE_DECL_KEY_ATTENDANT_TOGGLE))
# define KEY_ATTENDANT_TOGGLE 0x21d
#endif
#if !(defined(KEY_LIGHTS_TOGGLE) || (defined(HAVE_DECL_KEY_LIGHTS_TOGGLE) && HAVE_DECL_KEY_LIGHTS_TOGGLE))
# define KEY_LIGHTS_TOGGLE 0x21e
#endif
#if !(defined(BTN_DPAD_UP) || (defined(HAVE_DECL_BTN_DPAD_UP) && HAVE_DECL_BTN_DPAD_UP))
# define BTN_DPAD_UP 0x220
#endif
#if !(defined(BTN_DPAD_DOWN) || (defined(HAVE_DECL_BTN_DPAD_DOWN) && HAVE_DECL_BTN_DPAD_DOWN))
# define BTN_DPAD_DOWN 0x221
#endif
#if !(defined(BTN_DPAD_LEFT) || (defined(HAVE_DECL_BTN_DPAD_LEFT) && HAVE_DECL_BTN_DPAD_LEFT))
# define BTN_DPAD_LEFT 0x222
#endif
#if !(defined(BTN_DPAD_RIGHT) || (defined(HAVE_DECL_BTN_DPAD_RIGHT) && HAVE_DECL_BTN_DPAD_RIGHT))
# define BTN_DPAD_RIGHT 0x223
#endif
#if !(defined(KEY_ALS_TOGGLE) || (defined(HAVE_DECL_KEY_ALS_TOGGLE) && HAVE_DECL_KEY_ALS_TOGGLE))
# define KEY_ALS_TOGGLE 0x230
#endif
#if !(defined(KEY_ROTATE_LOCK_TOGGLE) || (defined(HAVE_DECL_KEY_ROTATE_LOCK_TOGGLE) && HAVE_DECL_KEY_ROTATE_LOCK_TOGGLE))
# define KEY_ROTATE_LOCK_TOGGLE 0x231
#endif
#if !(defined(KEY_BUTTONCONFIG) || (defined(HAVE_DECL_KEY_BUTTONCONFIG) && HAVE_DECL_KEY_BUTTONCONFIG))
# define KEY_BUTTONCONFIG 0x240
#endif
#if !(defined(KEY_TASKMANAGER) || (defined(HAVE_DECL_KEY_TASKMANAGER) && HAVE_DECL_KEY_TASKMANAGER))
# define KEY_TASKMANAGER 0x241
#endif
#if !(defined(KEY_JOURNAL) || (defined(HAVE_DECL_KEY_JOURNAL) && HAVE_DECL_KEY_JOURNAL))
# define KEY_JOURNAL 0x242
#endif
#if !(defined(KEY_CONTROLPANEL) || (defined(HAVE_DECL_KEY_CONTROLPANEL) && HAVE_DECL_KEY_CONTROLPANEL))
# define KEY_CONTROLPANEL 0x243
#endif
#if !(defined(KEY_APPSELECT) || (defined(HAVE_DECL_KEY_APPSELECT) && HAVE_DECL_KEY_APPSELECT))
# define KEY_APPSELECT 0x244
#endif
#if !(defined(KEY_SCREENSAVER) || (defined(HAVE_DECL_KEY_SCREENSAVER) && HAVE_DECL_KEY_SCREENSAVER))
# define KEY_SCREENSAVER 0x245
#endif
#if !(defined(KEY_VOICECOMMAND) || (defined(HAVE_DECL_KEY_VOICECOMMAND) && HAVE_DECL_KEY_VOICECOMMAND))
# define KEY_VOICECOMMAND 0x246
#endif
#if !(defined(KEY_ASSISTANT) || (defined(HAVE_DECL_KEY_ASSISTANT) && HAVE_DECL_KEY_ASSISTANT))
# define KEY_ASSISTANT 0x247
#endif
#if !(defined(KEY_BRIGHTNESS_MIN) || (defined(HAVE_DECL_KEY_BRIGHTNESS_MIN) && HAVE_DECL_KEY_BRIGHTNESS_MIN))
# define KEY_BRIGHTNESS_MIN 0x250
#endif
#if !(defined(KEY_BRIGHTNESS_MAX) || (defined(HAVE_DECL_KEY_BRIGHTNESS_MAX) && HAVE_DECL_KEY_BRIGHTNESS_MAX))
# define KEY_BRIGHTNESS_MAX 0x251
#endif
#if !(defined(KEY_KBDINPUTASSIST_PREV) || (defined(HAVE_DECL_KEY_KBDINPUTASSIST_PREV) && HAVE_DECL_KEY_KBDINPUTASSIST_PREV))
# define KEY_KBDINPUTASSIST_PREV 0x260
#endif
#if !(defined(KEY_KBDINPUTASSIST_NEXT) || (defined(HAVE_DECL_KEY_KBDINPUTASSIST_NEXT) && HAVE_DECL_KEY_KBDINPUTASSIST_NEXT))
# define KEY_KBDINPUTASSIST_NEXT 0x261
#endif
#if !(defined(KEY_KBDINPUTASSIST_PREVGROUP) || (defined(HAVE_DECL_KEY_KBDINPUTASSIST_PREVGROUP) && HAVE_DECL_KEY_KBDINPUTASSIST_PREVGROUP))
# define KEY_KBDINPUTASSIST_PREVGROUP 0x262
#endif
#if !(defined(KEY_KBDINPUTASSIST_NEXTGROUP) || (defined(HAVE_DECL_KEY_KBDINPUTASSIST_NEXTGROUP) && HAVE_DECL_KEY_KBDINPUTASSIST_NEXTGROUP))
# define KEY_KBDINPUTASSIST_NEXTGROUP 0x263
#endif
#if !(defined(KEY_KBDINPUTASSIST_ACCEPT) || (defined(HAVE_DECL_KEY_KBDINPUTASSIST_ACCEPT) && HAVE_DECL_KEY_KBDINPUTASSIST_ACCEPT))
# define KEY_KBDINPUTASSIST_ACCEPT 0x264
#endif
#if !(defined(KEY_KBDINPUTASSIST_CANCEL) || (defined(HAVE_DECL_KEY_KBDINPUTASSIST_CANCEL) && HAVE_DECL_KEY_KBDINPUTASSIST_CANCEL))
# define KEY_KBDINPUTASSIST_CANCEL 0x265
#endif
#if !(defined(KEY_RIGHT_UP) || (defined(HAVE_DECL_KEY_RIGHT_UP) && HAVE_DECL_KEY_RIGHT_UP))
# define KEY_RIGHT_UP 0x266
#endif
#if !(defined(KEY_RIGHT_DOWN) || (defined(HAVE_DECL_KEY_RIGHT_DOWN) && HAVE_DECL_KEY_RIGHT_DOWN))
# define KEY_RIGHT_DOWN 0x267
#endif
#if !(defined(KEY_LEFT_UP) || (defined(HAVE_DECL_KEY_LEFT_UP) && HAVE_DECL_KEY_LEFT_UP))
# define KEY_LEFT_UP 0x268
#endif
#if !(defined(KEY_LEFT_DOWN) || (defined(HAVE_DECL_KEY_LEFT_DOWN) && HAVE_DECL_KEY_LEFT_DOWN))
# define KEY_LEFT_DOWN 0x269
#endif
#if !(defined(KEY_ROOT_MENU) || (defined(HAVE_DECL_KEY_ROOT_MENU) && HAVE_DECL_KEY_ROOT_MENU))
# define KEY_ROOT_MENU 0x26a
#endif
#if !(defined(KEY_MEDIA_TOP_MENU) || (defined(HAVE_DECL_KEY_MEDIA_TOP_MENU) && HAVE_DECL_KEY_MEDIA_TOP_MENU))
# define KEY_MEDIA_TOP_MENU 0x26b
#endif
#if !(defined(KEY_NUMERIC_11) || (defined(HAVE_DECL_KEY_NUMERIC_11) && HAVE_DECL_KEY_NUMERIC_11))
# define KEY_NUMERIC_11 0x26c
#endif
#if !(defined(KEY_NUMERIC_12) || (defined(HAVE_DECL_KEY_NUMERIC_12) && HAVE_DECL_KEY_NUMERIC_12))
# define KEY_NUMERIC_12 0x26d
#endif
#if !(defined(KEY_AUDIO_DESC) || (defined(HAVE_DECL_KEY_AUDIO_DESC) && HAVE_DECL_KEY_AUDIO_DESC))
# define KEY_AUDIO_DESC 0x26e
#endif
#if !(defined(KEY_3D_MODE) || (defined(HAVE_DECL_KEY_3D_MODE) && HAVE_DECL_KEY_3D_MODE))
# define KEY_3D_MODE 0x26f
#endif
#if !(defined(KEY_NEXT_FAVORITE) || (defined(HAVE_DECL_KEY_NEXT_FAVORITE) && HAVE_DECL_KEY_NEXT_FAVORITE))
# define KEY_NEXT_FAVORITE 0x270
#endif
#if !(defined(KEY_STOP_RECORD) || (defined(HAVE_DECL_KEY_STOP_RECORD) && HAVE_DECL_KEY_STOP_RECORD))
# define KEY_STOP_RECORD 0x271
#endif
#if !(defined(KEY_PAUSE_RECORD) || (defined(HAVE_DECL_KEY_PAUSE_RECORD) && HAVE_DECL_KEY_PAUSE_RECORD))
# define KEY_PAUSE_RECORD 0x272
#endif
#if !(defined(KEY_VOD) || (defined(HAVE_DECL_KEY_VOD) && HAVE_DECL_KEY_VOD))
# define KEY_VOD 0x273
#endif
#if !(defined(KEY_UNMUTE) || (defined(HAVE_DECL_KEY_UNMUTE) && HAVE_DECL_KEY_UNMUTE))
# define KEY_UNMUTE 0x274
#endif
#if !(defined(KEY_FASTREVERSE) || (defined(HAVE_DECL_KEY_FASTREVERSE) && HAVE_DECL_KEY_FASTREVERSE))
# define KEY_FASTREVERSE 0x275
#endif
#if !(defined(KEY_SLOWREVERSE) || (defined(HAVE_DECL_KEY_SLOWREVERSE) && HAVE_DECL_KEY_SLOWREVERSE))
# define KEY_SLOWREVERSE 0x276
#endif
#if !(defined(KEY_DATA) || (defined(HAVE_DECL_KEY_DATA) && HAVE_DECL_KEY_DATA))
# define KEY_DATA 0x277
#endif
#if !(defined(KEY_ONSCREEN_KEYBOARD) || (defined(HAVE_DECL_KEY_ONSCREEN_KEYBOARD) && HAVE_DECL_KEY_ONSCREEN_KEYBOARD))
# define KEY_ONSCREEN_KEYBOARD 0x278
#endif
#if !(defined(BTN_TRIGGER_HAPPY) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY) && HAVE_DECL_BTN_TRIGGER_HAPPY))
# define BTN_TRIGGER_HAPPY 0x2c0
#endif
#if !(defined(BTN_TRIGGER_HAPPY1) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY1) && HAVE_DECL_BTN_TRIGGER_HAPPY1))
# define BTN_TRIGGER_HAPPY1 0x2c0
#endif
#if !(defined(BTN_TRIGGER_HAPPY2) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY2) && HAVE_DECL_BTN_TRIGGER_HAPPY2))
# define BTN_TRIGGER_HAPPY2 0x2c1
#endif
#if !(defined(BTN_TRIGGER_HAPPY3) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY3) && HAVE_DECL_BTN_TRIGGER_HAPPY3))
# define BTN_TRIGGER_HAPPY3 0x2c2
#endif
#if !(defined(BTN_TRIGGER_HAPPY4) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY4) && HAVE_DECL_BTN_TRIGGER_HAPPY4))
# define BTN_TRIGGER_HAPPY4 0x2c3
#endif
#if !(defined(BTN_TRIGGER_HAPPY5) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY5) && HAVE_DECL_BTN_TRIGGER_HAPPY5))
# define BTN_TRIGGER_HAPPY5 0x2c4
#endif
#if !(defined(BTN_TRIGGER_HAPPY6) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY6) && HAVE_DECL_BTN_TRIGGER_HAPPY6))
# define BTN_TRIGGER_HAPPY6 0x2c5
#endif
#if !(defined(BTN_TRIGGER_HAPPY7) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY7) && HAVE_DECL_BTN_TRIGGER_HAPPY7))
# define BTN_TRIGGER_HAPPY7 0x2c6
#endif
#if !(defined(BTN_TRIGGER_HAPPY8) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY8) && HAVE_DECL_BTN_TRIGGER_HAPPY8))
# define BTN_TRIGGER_HAPPY8 0x2c7
#endif
#if !(defined(BTN_TRIGGER_HAPPY9) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY9) && HAVE_DECL_BTN_TRIGGER_HAPPY9))
# define BTN_TRIGGER_HAPPY9 0x2c8
#endif
#if !(defined(BTN_TRIGGER_HAPPY10) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY10) && HAVE_DECL_BTN_TRIGGER_HAPPY10))
# define BTN_TRIGGER_HAPPY10 0x2c9
#endif
#if !(defined(BTN_TRIGGER_HAPPY11) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY11) && HAVE_DECL_BTN_TRIGGER_HAPPY11))
# define BTN_TRIGGER_HAPPY11 0x2ca
#endif
#if !(defined(BTN_TRIGGER_HAPPY12) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY12) && HAVE_DECL_BTN_TRIGGER_HAPPY12))
# define BTN_TRIGGER_HAPPY12 0x2cb
#endif
#if !(defined(BTN_TRIGGER_HAPPY13) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY13) && HAVE_DECL_BTN_TRIGGER_HAPPY13))
# define BTN_TRIGGER_HAPPY13 0x2cc
#endif
#if !(defined(BTN_TRIGGER_HAPPY14) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY14) && HAVE_DECL_BTN_TRIGGER_HAPPY14))
# define BTN_TRIGGER_HAPPY14 0x2cd
#endif
#if !(defined(BTN_TRIGGER_HAPPY15) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY15) && HAVE_DECL_BTN_TRIGGER_HAPPY15))
# define BTN_TRIGGER_HAPPY15 0x2ce
#endif
#if !(defined(BTN_TRIGGER_HAPPY16) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY16) && HAVE_DECL_BTN_TRIGGER_HAPPY16))
# define BTN_TRIGGER_HAPPY16 0x2cf
#endif
#if !(defined(BTN_TRIGGER_HAPPY17) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY17) && HAVE_DECL_BTN_TRIGGER_HAPPY17))
# define BTN_TRIGGER_HAPPY17 0x2d0
#endif
#if !(defined(BTN_TRIGGER_HAPPY18) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY18) && HAVE_DECL_BTN_TRIGGER_HAPPY18))
# define BTN_TRIGGER_HAPPY18 0x2d1
#endif
#if !(defined(BTN_TRIGGER_HAPPY19) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY19) && HAVE_DECL_BTN_TRIGGER_HAPPY19))
# define BTN_TRIGGER_HAPPY19 0x2d2
#endif
#if !(defined(BTN_TRIGGER_HAPPY20) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY20) && HAVE_DECL_BTN_TRIGGER_HAPPY20))
# define BTN_TRIGGER_HAPPY20 0x2d3
#endif
#if !(defined(BTN_TRIGGER_HAPPY21) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY21) && HAVE_DECL_BTN_TRIGGER_HAPPY21))
# define BTN_TRIGGER_HAPPY21 0x2d4
#endif
#if !(defined(BTN_TRIGGER_HAPPY22) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY22) && HAVE_DECL_BTN_TRIGGER_HAPPY22))
# define BTN_TRIGGER_HAPPY22 0x2d5
#endif
#if !(defined(BTN_TRIGGER_HAPPY23) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY23) && HAVE_DECL_BTN_TRIGGER_HAPPY23))
# define BTN_TRIGGER_HAPPY23 0x2d6
#endif
#if !(defined(BTN_TRIGGER_HAPPY24) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY24) && HAVE_DECL_BTN_TRIGGER_HAPPY24))
# define BTN_TRIGGER_HAPPY24 0x2d7
#endif
#if !(defined(BTN_TRIGGER_HAPPY25) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY25) && HAVE_DECL_BTN_TRIGGER_HAPPY25))
# define BTN_TRIGGER_HAPPY25 0x2d8
#endif
#if !(defined(BTN_TRIGGER_HAPPY26) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY26) && HAVE_DECL_BTN_TRIGGER_HAPPY26))
# define BTN_TRIGGER_HAPPY26 0x2d9
#endif
#if !(defined(BTN_TRIGGER_HAPPY27) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY27) && HAVE_DECL_BTN_TRIGGER_HAPPY27))
# define BTN_TRIGGER_HAPPY27 0x2da
#endif
#if !(defined(BTN_TRIGGER_HAPPY28) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY28) && HAVE_DECL_BTN_TRIGGER_HAPPY28))
# define BTN_TRIGGER_HAPPY28 0x2db
#endif
#if !(defined(BTN_TRIGGER_HAPPY29) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY29) && HAVE_DECL_BTN_TRIGGER_HAPPY29))
# define BTN_TRIGGER_HAPPY29 0x2dc
#endif
#if !(defined(BTN_TRIGGER_HAPPY30) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY30) && HAVE_DECL_BTN_TRIGGER_HAPPY30))
# define BTN_TRIGGER_HAPPY30 0x2dd
#endif
#if !(defined(BTN_TRIGGER_HAPPY31) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY31) && HAVE_DECL_BTN_TRIGGER_HAPPY31))
# define BTN_TRIGGER_HAPPY31 0x2de
#endif
#if !(defined(BTN_TRIGGER_HAPPY32) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY32) && HAVE_DECL_BTN_TRIGGER_HAPPY32))
# define BTN_TRIGGER_HAPPY32 0x2df
#endif
#if !(defined(BTN_TRIGGER_HAPPY33) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY33) && HAVE_DECL_BTN_TRIGGER_HAPPY33))
# define BTN_TRIGGER_HAPPY33 0x2e0
#endif
#if !(defined(BTN_TRIGGER_HAPPY34) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY34) && HAVE_DECL_BTN_TRIGGER_HAPPY34))
# define BTN_TRIGGER_HAPPY34 0x2e1
#endif
#if !(defined(BTN_TRIGGER_HAPPY35) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY35) && HAVE_DECL_BTN_TRIGGER_HAPPY35))
# define BTN_TRIGGER_HAPPY35 0x2e2
#endif
#if !(defined(BTN_TRIGGER_HAPPY36) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY36) && HAVE_DECL_BTN_TRIGGER_HAPPY36))
# define BTN_TRIGGER_HAPPY36 0x2e3
#endif
#if !(defined(BTN_TRIGGER_HAPPY37) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY37) && HAVE_DECL_BTN_TRIGGER_HAPPY37))
# define BTN_TRIGGER_HAPPY37 0x2e4
#endif
#if !(defined(BTN_TRIGGER_HAPPY38) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY38) && HAVE_DECL_BTN_TRIGGER_HAPPY38))
# define BTN_TRIGGER_HAPPY38 0x2e5
#endif
#if !(defined(BTN_TRIGGER_HAPPY39) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY39) && HAVE_DECL_BTN_TRIGGER_HAPPY39))
# define BTN_TRIGGER_HAPPY39 0x2e6
#endif
#if !(defined(BTN_TRIGGER_HAPPY40) || (defined(HAVE_DECL_BTN_TRIGGER_HAPPY40) && HAVE_DECL_BTN_TRIGGER_HAPPY40))
# define BTN_TRIGGER_HAPPY40 0x2e7
#endif

#ifdef IN_MPERS

# error static const struct xlat evdev_keycode in mpers mode

#else

static
const struct xlat evdev_keycode[] = {

 XLAT(KEY_RESERVED),
 XLAT(KEY_ESC),
 XLAT(KEY_1),
 XLAT(KEY_2),
 XLAT(KEY_3),
 XLAT(KEY_4),
 XLAT(KEY_5),
 XLAT(KEY_6),
 XLAT(KEY_7),
 XLAT(KEY_8),
 XLAT(KEY_9),
 XLAT(KEY_0),
 XLAT(KEY_MINUS),
 XLAT(KEY_EQUAL),
 XLAT(KEY_BACKSPACE),
 XLAT(KEY_TAB),
 XLAT(KEY_Q),
 XLAT(KEY_W),
 XLAT(KEY_E),
 XLAT(KEY_R),
 XLAT(KEY_T),
 XLAT(KEY_Y),
 XLAT(KEY_U),
 XLAT(KEY_I),
 XLAT(KEY_O),
 XLAT(KEY_P),
 XLAT(KEY_LEFTBRACE),
 XLAT(KEY_RIGHTBRACE),
 XLAT(KEY_ENTER),
 XLAT(KEY_LEFTCTRL),
 XLAT(KEY_A),
 XLAT(KEY_S),
 XLAT(KEY_D),
 XLAT(KEY_F),
 XLAT(KEY_G),
 XLAT(KEY_H),
 XLAT(KEY_J),
 XLAT(KEY_K),
 XLAT(KEY_L),
 XLAT(KEY_SEMICOLON),
 XLAT(KEY_APOSTROPHE),
 XLAT(KEY_GRAVE),
 XLAT(KEY_LEFTSHIFT),
 XLAT(KEY_BACKSLASH),
 XLAT(KEY_Z),
 XLAT(KEY_X),
 XLAT(KEY_C),
 XLAT(KEY_V),
 XLAT(KEY_B),
 XLAT(KEY_N),
 XLAT(KEY_M),
 XLAT(KEY_COMMA),
 XLAT(KEY_DOT),
 XLAT(KEY_SLASH),
 XLAT(KEY_RIGHTSHIFT),
 XLAT(KEY_KPASTERISK),
 XLAT(KEY_LEFTALT),
 XLAT(KEY_SPACE),
 XLAT(KEY_CAPSLOCK),
 XLAT(KEY_F1),
 XLAT(KEY_F2),
 XLAT(KEY_F3),
 XLAT(KEY_F4),
 XLAT(KEY_F5),
 XLAT(KEY_F6),
 XLAT(KEY_F7),
 XLAT(KEY_F8),
 XLAT(KEY_F9),
 XLAT(KEY_F10),
 XLAT(KEY_NUMLOCK),
 XLAT(KEY_SCROLLLOCK),
 XLAT(KEY_KP7),
 XLAT(KEY_KP8),
 XLAT(KEY_KP9),
 XLAT(KEY_KPMINUS),
 XLAT(KEY_KP4),
 XLAT(KEY_KP5),
 XLAT(KEY_KP6),
 XLAT(KEY_KPPLUS),
 XLAT(KEY_KP1),
 XLAT(KEY_KP2),
 XLAT(KEY_KP3),
 XLAT(KEY_KP0),
 XLAT(KEY_KPDOT),

 XLAT(KEY_ZENKAKUHANKAKU),
 XLAT(KEY_102ND),
 XLAT(KEY_F11),
 XLAT(KEY_F12),
 XLAT(KEY_RO),
 XLAT(KEY_KATAKANA),
 XLAT(KEY_HIRAGANA),
 XLAT(KEY_HENKAN),
 XLAT(KEY_KATAKANAHIRAGANA),
 XLAT(KEY_MUHENKAN),
 XLAT(KEY_KPJPCOMMA),
 XLAT(KEY_KPENTER),
 XLAT(KEY_RIGHTCTRL),
 XLAT(KEY_KPSLASH),
 XLAT(KEY_SYSRQ),
 XLAT(KEY_RIGHTALT),
 XLAT(KEY_LINEFEED),
 XLAT(KEY_HOME),
 XLAT(KEY_UP),
 XLAT(KEY_PAGEUP),
 XLAT(KEY_LEFT),
 XLAT(KEY_RIGHT),
 XLAT(KEY_END),
 XLAT(KEY_DOWN),
 XLAT(KEY_PAGEDOWN),
 XLAT(KEY_INSERT),
 XLAT(KEY_DELETE),
 XLAT(KEY_MACRO),
 XLAT(KEY_MUTE),
 XLAT(KEY_VOLUMEDOWN),
 XLAT(KEY_VOLUMEUP),
 XLAT(KEY_POWER),
 XLAT(KEY_KPEQUAL),
 XLAT(KEY_KPPLUSMINUS),
 XLAT(KEY_PAUSE),
 XLAT(KEY_SCALE),

 XLAT(KEY_KPCOMMA),
 XLAT(KEY_HANGEUL),
 XLAT(KEY_HANJA),
 XLAT(KEY_YEN),
 XLAT(KEY_LEFTMETA),
 XLAT(KEY_RIGHTMETA),
 XLAT(KEY_COMPOSE),

 XLAT(KEY_STOP),
 XLAT(KEY_AGAIN),
 XLAT(KEY_PROPS),
 XLAT(KEY_UNDO),
 XLAT(KEY_FRONT),
 XLAT(KEY_COPY),
 XLAT(KEY_OPEN),
 XLAT(KEY_PASTE),
 XLAT(KEY_FIND),
 XLAT(KEY_CUT),
 XLAT(KEY_HELP),
 XLAT(KEY_MENU),
 XLAT(KEY_CALC),
 XLAT(KEY_SETUP),
 XLAT(KEY_SLEEP),
 XLAT(KEY_WAKEUP),
 XLAT(KEY_FILE),
 XLAT(KEY_SENDFILE),
 XLAT(KEY_DELETEFILE),
 XLAT(KEY_XFER),
 XLAT(KEY_PROG1),
 XLAT(KEY_PROG2),
 XLAT(KEY_WWW),
 XLAT(KEY_MSDOS),
 XLAT(KEY_COFFEE),
 XLAT(KEY_ROTATE_DISPLAY),
 XLAT(KEY_CYCLEWINDOWS),
 XLAT(KEY_MAIL),
 XLAT(KEY_BOOKMARKS),
 XLAT(KEY_COMPUTER),
 XLAT(KEY_BACK),
 XLAT(KEY_FORWARD),
 XLAT(KEY_CLOSECD),
 XLAT(KEY_EJECTCD),
 XLAT(KEY_EJECTCLOSECD),
 XLAT(KEY_NEXTSONG),
 XLAT(KEY_PLAYPAUSE),
 XLAT(KEY_PREVIOUSSONG),
 XLAT(KEY_STOPCD),
 XLAT(KEY_RECORD),
 XLAT(KEY_REWIND),
 XLAT(KEY_PHONE),
 XLAT(KEY_ISO),
 XLAT(KEY_CONFIG),
 XLAT(KEY_HOMEPAGE),
 XLAT(KEY_REFRESH),
 XLAT(KEY_EXIT),
 XLAT(KEY_MOVE),
 XLAT(KEY_EDIT),
 XLAT(KEY_SCROLLUP),
 XLAT(KEY_SCROLLDOWN),
 XLAT(KEY_KPLEFTPAREN),
 XLAT(KEY_KPRIGHTPAREN),
 XLAT(KEY_NEW),
 XLAT(KEY_REDO),

 XLAT(KEY_F13),
 XLAT(KEY_F14),
 XLAT(KEY_F15),
 XLAT(KEY_F16),
 XLAT(KEY_F17),
 XLAT(KEY_F18),
 XLAT(KEY_F19),
 XLAT(KEY_F20),
 XLAT(KEY_F21),
 XLAT(KEY_F22),
 XLAT(KEY_F23),
 XLAT(KEY_F24),

 XLAT(KEY_PLAYCD),
 XLAT(KEY_PAUSECD),
 XLAT(KEY_PROG3),
 XLAT(KEY_PROG4),
 XLAT(KEY_DASHBOARD),
 XLAT(KEY_SUSPEND),
 XLAT(KEY_CLOSE),
 XLAT(KEY_PLAY),
 XLAT(KEY_FASTFORWARD),
 XLAT(KEY_BASSBOOST),
 XLAT(KEY_PRINT),
 XLAT(KEY_HP),
 XLAT(KEY_CAMERA),
 XLAT(KEY_SOUND),
 XLAT(KEY_QUESTION),
 XLAT(KEY_EMAIL),
 XLAT(KEY_CHAT),
 XLAT(KEY_SEARCH),
 XLAT(KEY_CONNECT),
 XLAT(KEY_FINANCE),
 XLAT(KEY_SPORT),
 XLAT(KEY_SHOP),
 XLAT(KEY_ALTERASE),
 XLAT(KEY_CANCEL),
 XLAT(KEY_BRIGHTNESSDOWN),
 XLAT(KEY_BRIGHTNESSUP),
 XLAT(KEY_MEDIA),

 XLAT(KEY_SWITCHVIDEOMODE),

 XLAT(KEY_KBDILLUMTOGGLE),
 XLAT(KEY_KBDILLUMDOWN),
 XLAT(KEY_KBDILLUMUP),

 XLAT(KEY_SEND),
 XLAT(KEY_REPLY),
 XLAT(KEY_FORWARDMAIL),
 XLAT(KEY_SAVE),
 XLAT(KEY_DOCUMENTS),

 XLAT(KEY_BATTERY),

 XLAT(KEY_BLUETOOTH),
 XLAT(KEY_WLAN),
 XLAT(KEY_UWB),

 XLAT(KEY_UNKNOWN),

 XLAT(KEY_VIDEO_NEXT),
 XLAT(KEY_VIDEO_PREV),
 XLAT(KEY_BRIGHTNESS_CYCLE),
 XLAT(KEY_BRIGHTNESS_AUTO),
 XLAT(KEY_DISPLAY_OFF),

 XLAT(KEY_WWAN),
 XLAT(KEY_RFKILL),

 XLAT(KEY_MICMUTE),

 XLAT(BTN_0),
 XLAT(BTN_1),
 XLAT(BTN_2),
 XLAT(BTN_3),
 XLAT(BTN_4),
 XLAT(BTN_5),
 XLAT(BTN_6),
 XLAT(BTN_7),
 XLAT(BTN_8),
 XLAT(BTN_9),

 XLAT(BTN_MOUSE),
 XLAT(BTN_LEFT),
 XLAT(BTN_RIGHT),
 XLAT(BTN_MIDDLE),
 XLAT(BTN_SIDE),
 XLAT(BTN_EXTRA),
 XLAT(BTN_FORWARD),
 XLAT(BTN_BACK),
 XLAT(BTN_TASK),

 XLAT(BTN_JOYSTICK),
 XLAT(BTN_TRIGGER),
 XLAT(BTN_THUMB),
 XLAT(BTN_THUMB2),
 XLAT(BTN_TOP),
 XLAT(BTN_TOP2),
 XLAT(BTN_PINKIE),
 XLAT(BTN_BASE),
 XLAT(BTN_BASE2),
 XLAT(BTN_BASE3),
 XLAT(BTN_BASE4),
 XLAT(BTN_BASE5),
 XLAT(BTN_BASE6),
 XLAT(BTN_DEAD),

 XLAT(BTN_GAMEPAD),
 XLAT(BTN_SOUTH),
 XLAT(BTN_EAST),
 XLAT(BTN_C),
 XLAT(BTN_NORTH),
 XLAT(BTN_WEST),
 XLAT(BTN_Z),
 XLAT(BTN_TL),
 XLAT(BTN_TR),
 XLAT(BTN_TL2),
 XLAT(BTN_TR2),
 XLAT(BTN_SELECT),
 XLAT(BTN_START),
 XLAT(BTN_MODE),
 XLAT(BTN_THUMBL),
 XLAT(BTN_THUMBR),

 XLAT(BTN_DIGI),
 XLAT(BTN_TOOL_PEN),
 XLAT(BTN_TOOL_RUBBER),
 XLAT(BTN_TOOL_BRUSH),
 XLAT(BTN_TOOL_PENCIL),
 XLAT(BTN_TOOL_AIRBRUSH),
 XLAT(BTN_TOOL_FINGER),
 XLAT(BTN_TOOL_MOUSE),
 XLAT(BTN_TOOL_LENS),
 XLAT(BTN_TOOL_QUINTTAP),
 XLAT(BTN_STYLUS3),
 XLAT(BTN_TOUCH),
 XLAT(BTN_STYLUS),
 XLAT(BTN_STYLUS2),
 XLAT(BTN_TOOL_DOUBLETAP),
 XLAT(BTN_TOOL_TRIPLETAP),
 XLAT(BTN_TOOL_QUADTAP),

 XLAT(BTN_WHEEL),
 XLAT(BTN_GEAR_DOWN),
 XLAT(BTN_GEAR_UP),

 XLAT(KEY_OK),
 XLAT(KEY_SELECT),
 XLAT(KEY_GOTO),
 XLAT(KEY_CLEAR),
 XLAT(KEY_POWER2),
 XLAT(KEY_OPTION),
 XLAT(KEY_INFO),
 XLAT(KEY_TIME),
 XLAT(KEY_VENDOR),
 XLAT(KEY_ARCHIVE),
 XLAT(KEY_PROGRAM),
 XLAT(KEY_CHANNEL),
 XLAT(KEY_FAVORITES),
 XLAT(KEY_EPG),
 XLAT(KEY_PVR),
 XLAT(KEY_MHP),
 XLAT(KEY_LANGUAGE),
 XLAT(KEY_TITLE),
 XLAT(KEY_SUBTITLE),
 XLAT(KEY_ANGLE),
 XLAT(KEY_ZOOM),
 XLAT(KEY_MODE),
 XLAT(KEY_KEYBOARD),
 XLAT(KEY_SCREEN),
 XLAT(KEY_PC),
 XLAT(KEY_TV),
 XLAT(KEY_TV2),
 XLAT(KEY_VCR),
 XLAT(KEY_VCR2),
 XLAT(KEY_SAT),
 XLAT(KEY_SAT2),
 XLAT(KEY_CD),
 XLAT(KEY_TAPE),
 XLAT(KEY_RADIO),
 XLAT(KEY_TUNER),
 XLAT(KEY_PLAYER),
 XLAT(KEY_TEXT),
 XLAT(KEY_DVD),
 XLAT(KEY_AUX),
 XLAT(KEY_MP3),
 XLAT(KEY_AUDIO),
 XLAT(KEY_VIDEO),
 XLAT(KEY_DIRECTORY),
 XLAT(KEY_LIST),
 XLAT(KEY_MEMO),
 XLAT(KEY_CALENDAR),
 XLAT(KEY_RED),
 XLAT(KEY_GREEN),
 XLAT(KEY_YELLOW),
 XLAT(KEY_BLUE),
 XLAT(KEY_CHANNELUP),
 XLAT(KEY_CHANNELDOWN),
 XLAT(KEY_FIRST),
 XLAT(KEY_LAST),
 XLAT(KEY_AB),
 XLAT(KEY_NEXT),
 XLAT(KEY_RESTART),
 XLAT(KEY_SLOW),
 XLAT(KEY_SHUFFLE),
 XLAT(KEY_BREAK),
 XLAT(KEY_PREVIOUS),
 XLAT(KEY_DIGITS),
 XLAT(KEY_TEEN),
 XLAT(KEY_TWEN),
 XLAT(KEY_VIDEOPHONE),
 XLAT(KEY_GAMES),
 XLAT(KEY_ZOOMIN),
 XLAT(KEY_ZOOMOUT),
 XLAT(KEY_ZOOMRESET),
 XLAT(KEY_WORDPROCESSOR),
 XLAT(KEY_EDITOR),
 XLAT(KEY_SPREADSHEET),
 XLAT(KEY_GRAPHICSEDITOR),
 XLAT(KEY_PRESENTATION),
 XLAT(KEY_DATABASE),
 XLAT(KEY_NEWS),
 XLAT(KEY_VOICEMAIL),
 XLAT(KEY_ADDRESSBOOK),
 XLAT(KEY_MESSENGER),
 XLAT(KEY_DISPLAYTOGGLE),
 XLAT(KEY_SPELLCHECK),
 XLAT(KEY_LOGOFF),

 XLAT(KEY_DOLLAR),
 XLAT(KEY_EURO),

 XLAT(KEY_FRAMEBACK),
 XLAT(KEY_FRAMEFORWARD),
 XLAT(KEY_CONTEXT_MENU),
 XLAT(KEY_MEDIA_REPEAT),
 XLAT(KEY_10CHANNELSUP),
 XLAT(KEY_10CHANNELSDOWN),
 XLAT(KEY_IMAGES),

 XLAT(KEY_DEL_EOL),
 XLAT(KEY_DEL_EOS),
 XLAT(KEY_INS_LINE),
 XLAT(KEY_DEL_LINE),

 XLAT(KEY_FN),
 XLAT(KEY_FN_ESC),
 XLAT(KEY_FN_F1),
 XLAT(KEY_FN_F2),
 XLAT(KEY_FN_F3),
 XLAT(KEY_FN_F4),
 XLAT(KEY_FN_F5),
 XLAT(KEY_FN_F6),
 XLAT(KEY_FN_F7),
 XLAT(KEY_FN_F8),
 XLAT(KEY_FN_F9),
 XLAT(KEY_FN_F10),
 XLAT(KEY_FN_F11),
 XLAT(KEY_FN_F12),
 XLAT(KEY_FN_1),
 XLAT(KEY_FN_2),
 XLAT(KEY_FN_D),
 XLAT(KEY_FN_E),
 XLAT(KEY_FN_F),
 XLAT(KEY_FN_S),
 XLAT(KEY_FN_B),

 XLAT(KEY_BRL_DOT1),
 XLAT(KEY_BRL_DOT2),
 XLAT(KEY_BRL_DOT3),
 XLAT(KEY_BRL_DOT4),
 XLAT(KEY_BRL_DOT5),
 XLAT(KEY_BRL_DOT6),
 XLAT(KEY_BRL_DOT7),
 XLAT(KEY_BRL_DOT8),
 XLAT(KEY_BRL_DOT9),
 XLAT(KEY_BRL_DOT10),

 XLAT(KEY_NUMERIC_0),
 XLAT(KEY_NUMERIC_1),
 XLAT(KEY_NUMERIC_2),
 XLAT(KEY_NUMERIC_3),
 XLAT(KEY_NUMERIC_4),
 XLAT(KEY_NUMERIC_5),
 XLAT(KEY_NUMERIC_6),
 XLAT(KEY_NUMERIC_7),
 XLAT(KEY_NUMERIC_8),
 XLAT(KEY_NUMERIC_9),
 XLAT(KEY_NUMERIC_STAR),
 XLAT(KEY_NUMERIC_POUND),
 XLAT(KEY_NUMERIC_A),
 XLAT(KEY_NUMERIC_B),
 XLAT(KEY_NUMERIC_C),
 XLAT(KEY_NUMERIC_D),

 XLAT(KEY_CAMERA_FOCUS),
 XLAT(KEY_WPS_BUTTON),

 XLAT(KEY_TOUCHPAD_TOGGLE),
 XLAT(KEY_TOUCHPAD_ON),
 XLAT(KEY_TOUCHPAD_OFF),

 XLAT(KEY_CAMERA_ZOOMIN),
 XLAT(KEY_CAMERA_ZOOMOUT),
 XLAT(KEY_CAMERA_UP),
 XLAT(KEY_CAMERA_DOWN),
 XLAT(KEY_CAMERA_LEFT),
 XLAT(KEY_CAMERA_RIGHT),

 XLAT(KEY_ATTENDANT_ON),
 XLAT(KEY_ATTENDANT_OFF),
 XLAT(KEY_ATTENDANT_TOGGLE),
 XLAT(KEY_LIGHTS_TOGGLE),

 XLAT(BTN_DPAD_UP),
 XLAT(BTN_DPAD_DOWN),
 XLAT(BTN_DPAD_LEFT),
 XLAT(BTN_DPAD_RIGHT),

 XLAT(KEY_ALS_TOGGLE),
 XLAT(KEY_ROTATE_LOCK_TOGGLE),

 XLAT(KEY_BUTTONCONFIG),
 XLAT(KEY_TASKMANAGER),
 XLAT(KEY_JOURNAL),
 XLAT(KEY_CONTROLPANEL),
 XLAT(KEY_APPSELECT),
 XLAT(KEY_SCREENSAVER),
 XLAT(KEY_VOICECOMMAND),
 XLAT(KEY_ASSISTANT),

 XLAT(KEY_BRIGHTNESS_MIN),
 XLAT(KEY_BRIGHTNESS_MAX),

 XLAT(KEY_KBDINPUTASSIST_PREV),
 XLAT(KEY_KBDINPUTASSIST_NEXT),
 XLAT(KEY_KBDINPUTASSIST_PREVGROUP),
 XLAT(KEY_KBDINPUTASSIST_NEXTGROUP),
 XLAT(KEY_KBDINPUTASSIST_ACCEPT),
 XLAT(KEY_KBDINPUTASSIST_CANCEL),

 XLAT(KEY_RIGHT_UP),
 XLAT(KEY_RIGHT_DOWN),
 XLAT(KEY_LEFT_UP),
 XLAT(KEY_LEFT_DOWN),

 XLAT(KEY_ROOT_MENU),
 XLAT(KEY_MEDIA_TOP_MENU),
 XLAT(KEY_NUMERIC_11),
 XLAT(KEY_NUMERIC_12),

 XLAT(KEY_AUDIO_DESC),
 XLAT(KEY_3D_MODE),
 XLAT(KEY_NEXT_FAVORITE),
 XLAT(KEY_STOP_RECORD),
 XLAT(KEY_PAUSE_RECORD),
 XLAT(KEY_VOD),
 XLAT(KEY_UNMUTE),
 XLAT(KEY_FASTREVERSE),
 XLAT(KEY_SLOWREVERSE),
 XLAT(KEY_DATA),
 XLAT(KEY_ONSCREEN_KEYBOARD),

 XLAT(BTN_TRIGGER_HAPPY),
 XLAT(BTN_TRIGGER_HAPPY1),
 XLAT(BTN_TRIGGER_HAPPY2),
 XLAT(BTN_TRIGGER_HAPPY3),
 XLAT(BTN_TRIGGER_HAPPY4),
 XLAT(BTN_TRIGGER_HAPPY5),
 XLAT(BTN_TRIGGER_HAPPY6),
 XLAT(BTN_TRIGGER_HAPPY7),
 XLAT(BTN_TRIGGER_HAPPY8),
 XLAT(BTN_TRIGGER_HAPPY9),
 XLAT(BTN_TRIGGER_HAPPY10),
 XLAT(BTN_TRIGGER_HAPPY11),
 XLAT(BTN_TRIGGER_HAPPY12),
 XLAT(BTN_TRIGGER_HAPPY13),
 XLAT(BTN_TRIGGER_HAPPY14),
 XLAT(BTN_TRIGGER_HAPPY15),
 XLAT(BTN_TRIGGER_HAPPY16),
 XLAT(BTN_TRIGGER_HAPPY17),
 XLAT(BTN_TRIGGER_HAPPY18),
 XLAT(BTN_TRIGGER_HAPPY19),
 XLAT(BTN_TRIGGER_HAPPY20),
 XLAT(BTN_TRIGGER_HAPPY21),
 XLAT(BTN_TRIGGER_HAPPY22),
 XLAT(BTN_TRIGGER_HAPPY23),
 XLAT(BTN_TRIGGER_HAPPY24),
 XLAT(BTN_TRIGGER_HAPPY25),
 XLAT(BTN_TRIGGER_HAPPY26),
 XLAT(BTN_TRIGGER_HAPPY27),
 XLAT(BTN_TRIGGER_HAPPY28),
 XLAT(BTN_TRIGGER_HAPPY29),
 XLAT(BTN_TRIGGER_HAPPY30),
 XLAT(BTN_TRIGGER_HAPPY31),
 XLAT(BTN_TRIGGER_HAPPY32),
 XLAT(BTN_TRIGGER_HAPPY33),
 XLAT(BTN_TRIGGER_HAPPY34),
 XLAT(BTN_TRIGGER_HAPPY35),
 XLAT(BTN_TRIGGER_HAPPY36),
 XLAT(BTN_TRIGGER_HAPPY37),
 XLAT(BTN_TRIGGER_HAPPY38),
 XLAT(BTN_TRIGGER_HAPPY39),
 XLAT(BTN_TRIGGER_HAPPY40),
 XLAT_END
};

#endif /* !IN_MPERS */
