/* Generated by ./xlat/gen.sh from ./xlat/evdev_ff_status.in; do not edit. */

#ifdef IN_MPERS

extern const struct xlat evdev_ff_status[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat evdev_ff_status[] = {
#if defined(FF_STATUS_STOPPED) || (defined(HAVE_DECL_FF_STATUS_STOPPED) && HAVE_DECL_FF_STATUS_STOPPED)
  XLAT(FF_STATUS_STOPPED),
#endif
#if defined(FF_STATUS_PLAYING) || (defined(HAVE_DECL_FF_STATUS_PLAYING) && HAVE_DECL_FF_STATUS_PLAYING)
  XLAT(FF_STATUS_PLAYING),
#endif
 XLAT_END
};

#endif /* !IN_MPERS */
