/* Generated by ./xlat/gen.sh from ./xlat/fan_classes.in; do not edit. */

static const struct xlat fan_classes[] = {
#if defined(FAN_CLASS_NOTIF) || (defined(HAVE_DECL_FAN_CLASS_NOTIF) && HAVE_DECL_FAN_CLASS_NOTIF)
	XLAT(FAN_CLASS_NOTIF),
#endif
#if defined(FAN_CLASS_CONTENT) || (defined(HAVE_DECL_FAN_CLASS_CONTENT) && HAVE_DECL_FAN_CLASS_CONTENT)
	XLAT(FAN_CLASS_CONTENT),
#endif
#if defined(FAN_CLASS_PRE_CONTENT) || (defined(HAVE_DECL_FAN_CLASS_PRE_CONTENT) && HAVE_DECL_FAN_CLASS_PRE_CONTENT)
	XLAT(FAN_CLASS_PRE_CONTENT),
#endif
	XLAT_END
};
