/* Generated by ./xlat/gen.sh from ./xlat/fiemap_flags.in; do not edit. */
#if !(defined(FIEMAP_FLAG_SYNC) || (defined(HAVE_DECL_FIEMAP_FLAG_SYNC) && HAVE_DECL_FIEMAP_FLAG_SYNC))
# define FIEMAP_FLAG_SYNC 1
#endif
#if !(defined(FIEMAP_FLAG_XATTR) || (defined(HAVE_DECL_FIEMAP_FLAG_XATTR) && HAVE_DECL_FIEMAP_FLAG_XATTR))
# define FIEMAP_FLAG_XATTR 2
#endif
#if !(defined(FIEMAP_FLAG_CACHE) || (defined(HAVE_DECL_FIEMAP_FLAG_CACHE) && HAVE_DECL_FIEMAP_FLAG_CACHE))
# define FIEMAP_FLAG_CACHE 4
#endif

#ifdef IN_MPERS

# error static const struct xlat fiemap_flags in mpers mode

#else

static
const struct xlat fiemap_flags[] = {
 XLAT(FIEMAP_FLAG_SYNC),
 XLAT(FIEMAP_FLAG_XATTR),
 XLAT(FIEMAP_FLAG_CACHE),
 XLAT_END
};

#endif /* !IN_MPERS */
