/* Generated by ./xlat/gen.sh from ./xlat/flockcmds.in; do not edit. */

static const struct xlat flockcmds[] = {
#if defined(LOCK_SH) || (defined(HAVE_DECL_LOCK_SH) && HAVE_DECL_LOCK_SH)
	XLAT(LOCK_SH),
#endif
#if defined(LOCK_EX) || (defined(HAVE_DECL_LOCK_EX) && HAVE_DECL_LOCK_EX)
	XLAT(LOCK_EX),
#endif
#if defined(LOCK_NB) || (defined(HAVE_DECL_LOCK_NB) && HAVE_DECL_LOCK_NB)
	XLAT(LOCK_NB),
#endif
#if defined(LOCK_UN) || (defined(HAVE_DECL_LOCK_UN) && HAVE_DECL_LOCK_UN)
	XLAT(LOCK_UN),
#endif
	XLAT_END
};
