/* Generated by ./xlat/gen.sh from ./xlat/futexwakeops.in; do not edit. */

static const struct xlat futexwakeops[] = {
#if !(defined(FUTEX_OP_SET) || (defined(HAVE_DECL_FUTEX_OP_SET) && HAVE_DECL_FUTEX_OP_SET))
# define FUTEX_OP_SET 0
#endif
 XLAT(FUTEX_OP_SET),
#if !(defined(FUTEX_OP_ADD) || (defined(HAVE_DECL_FUTEX_OP_ADD) && HAVE_DECL_FUTEX_OP_ADD))
# define FUTEX_OP_ADD 1
#endif
 XLAT(FUTEX_OP_ADD),
#if !(defined(FUTEX_OP_OR) || (defined(HAVE_DECL_FUTEX_OP_OR) && HAVE_DECL_FUTEX_OP_OR))
# define FUTEX_OP_OR 2
#endif
 XLAT(FUTEX_OP_OR),
#if !(defined(FUTEX_OP_ANDN) || (defined(HAVE_DECL_FUTEX_OP_ANDN) && HAVE_DECL_FUTEX_OP_ANDN))
# define FUTEX_OP_ANDN 3
#endif
 XLAT(FUTEX_OP_ANDN),
#if !(defined(FUTEX_OP_XOR) || (defined(HAVE_DECL_FUTEX_OP_XOR) && HAVE_DECL_FUTEX_OP_XOR))
# define FUTEX_OP_XOR 4
#endif
 XLAT(FUTEX_OP_XOR),
 XLAT_END
};
