/* Generated by ./xlat/gen.sh from ./xlat/futexwakeops.in; do not edit. */

static const struct xlat futexwakeops[] = {
#if defined(FUTEX_OP_SET) || (defined(HAVE_DECL_FUTEX_OP_SET) && HAVE_DECL_FUTEX_OP_SET)
	XLAT(FUTEX_OP_SET),
#endif
#if defined(FUTEX_OP_ADD) || (defined(HAVE_DECL_FUTEX_OP_ADD) && HAVE_DECL_FUTEX_OP_ADD)
	XLAT(FUTEX_OP_ADD),
#endif
#if defined(FUTEX_OP_OR) || (defined(HAVE_DECL_FUTEX_OP_OR) && HAVE_DECL_FUTEX_OP_OR)
	XLAT(FUTEX_OP_OR),
#endif
#if defined(FUTEX_OP_ANDN) || (defined(HAVE_DECL_FUTEX_OP_ANDN) && HAVE_DECL_FUTEX_OP_ANDN)
	XLAT(FUTEX_OP_ANDN),
#endif
#if defined(FUTEX_OP_XOR) || (defined(HAVE_DECL_FUTEX_OP_XOR) && HAVE_DECL_FUTEX_OP_XOR)
	XLAT(FUTEX_OP_XOR),
#endif
	XLAT_END
};
