/* Generated by ./xlat/gen.sh from ./xlat/futexwakecmps.in; do not edit. */

static const struct xlat futexwakecmps[] = {
#if defined(FUTEX_OP_CMP_EQ) || (defined(HAVE_DECL_FUTEX_OP_CMP_EQ) && HAVE_DECL_FUTEX_OP_CMP_EQ)
	XLAT(FUTEX_OP_CMP_EQ),
#endif
#if defined(FUTEX_OP_CMP_NE) || (defined(HAVE_DECL_FUTEX_OP_CMP_NE) && HAVE_DECL_FUTEX_OP_CMP_NE)
	XLAT(FUTEX_OP_CMP_NE),
#endif
#if defined(FUTEX_OP_CMP_LT) || (defined(HAVE_DECL_FUTEX_OP_CMP_LT) && HAVE_DECL_FUTEX_OP_CMP_LT)
	XLAT(FUTEX_OP_CMP_LT),
#endif
#if defined(FUTEX_OP_CMP_LE) || (defined(HAVE_DECL_FUTEX_OP_CMP_LE) && HAVE_DECL_FUTEX_OP_CMP_LE)
	XLAT(FUTEX_OP_CMP_LE),
#endif
#if defined(FUTEX_OP_CMP_GT) || (defined(HAVE_DECL_FUTEX_OP_CMP_GT) && HAVE_DECL_FUTEX_OP_CMP_GT)
	XLAT(FUTEX_OP_CMP_GT),
#endif
#if defined(FUTEX_OP_CMP_GE) || (defined(HAVE_DECL_FUTEX_OP_CMP_GE) && HAVE_DECL_FUTEX_OP_CMP_GE)
	XLAT(FUTEX_OP_CMP_GE),
#endif
	XLAT_END
};
