/* Generated by ./xlat/gen.sh from ./xlat/futexwakecmps.in; do not edit. */

static const struct xlat futexwakecmps[] = {
#if !(defined(FUTEX_OP_CMP_EQ) || (defined(HAVE_DECL_FUTEX_OP_CMP_EQ) && HAVE_DECL_FUTEX_OP_CMP_EQ))
# define FUTEX_OP_CMP_EQ 0
#endif
 XLAT(FUTEX_OP_CMP_EQ),
#if !(defined(FUTEX_OP_CMP_NE) || (defined(HAVE_DECL_FUTEX_OP_CMP_NE) && HAVE_DECL_FUTEX_OP_CMP_NE))
# define FUTEX_OP_CMP_NE 1
#endif
 XLAT(FUTEX_OP_CMP_NE),
#if !(defined(FUTEX_OP_CMP_LT) || (defined(HAVE_DECL_FUTEX_OP_CMP_LT) && HAVE_DECL_FUTEX_OP_CMP_LT))
# define FUTEX_OP_CMP_LT 2
#endif
 XLAT(FUTEX_OP_CMP_LT),
#if !(defined(FUTEX_OP_CMP_LE) || (defined(HAVE_DECL_FUTEX_OP_CMP_LE) && HAVE_DECL_FUTEX_OP_CMP_LE))
# define FUTEX_OP_CMP_LE 3
#endif
 XLAT(FUTEX_OP_CMP_LE),
#if !(defined(FUTEX_OP_CMP_GT) || (defined(HAVE_DECL_FUTEX_OP_CMP_GT) && HAVE_DECL_FUTEX_OP_CMP_GT))
# define FUTEX_OP_CMP_GT 4
#endif
 XLAT(FUTEX_OP_CMP_GT),
#if !(defined(FUTEX_OP_CMP_GE) || (defined(HAVE_DECL_FUTEX_OP_CMP_GE) && HAVE_DECL_FUTEX_OP_CMP_GE))
# define FUTEX_OP_CMP_GE 5
#endif
 XLAT(FUTEX_OP_CMP_GE),
 XLAT_END
};
