/* Generated by ./xlat/gen.sh from ./xlat/getrandom_flags.in; do not edit. */

static const struct xlat getrandom_flags[] = {

#ifndef GRND_NONBLOCK
# define GRND_NONBLOCK 1
#endif

#ifndef GRND_RANDOM
# define GRND_RANDOM 2
#endif

 XLAT(GRND_NONBLOCK),
 XLAT(GRND_RANDOM),
 XLAT_END
};
