/* Generated by ./xlat/gen.sh from ./xlat/hw_breakpoint_type.in; do not edit. */
#if !(defined(HW_BREAKPOINT_EMPTY) || (defined(HAVE_DECL_HW_BREAKPOINT_EMPTY) && HAVE_DECL_HW_BREAKPOINT_EMPTY))
# define HW_BREAKPOINT_EMPTY 0
#endif
#if !(defined(HW_BREAKPOINT_R) || (defined(HAVE_DECL_HW_BREAKPOINT_R) && HAVE_DECL_HW_BREAKPOINT_R))
# define HW_BREAKPOINT_R 1
#endif
#if !(defined(HW_BREAKPOINT_W) || (defined(HAVE_DECL_HW_BREAKPOINT_W) && HAVE_DECL_HW_BREAKPOINT_W))
# define HW_BREAKPOINT_W 2
#endif
#if !(defined(HW_BREAKPOINT_RW) || (defined(HAVE_DECL_HW_BREAKPOINT_RW) && HAVE_DECL_HW_BREAKPOINT_RW))
# define HW_BREAKPOINT_RW HW_BREAKPOINT_R | HW_BREAKPOINT_W
#endif
#if !(defined(HW_BREAKPOINT_X) || (defined(HAVE_DECL_HW_BREAKPOINT_X) && HAVE_DECL_HW_BREAKPOINT_X))
# define HW_BREAKPOINT_X 4
#endif

#ifdef IN_MPERS

# error static const struct xlat hw_breakpoint_type in mpers mode

#else

static
const struct xlat hw_breakpoint_type[] = {
 XLAT(HW_BREAKPOINT_EMPTY),
 XLAT(HW_BREAKPOINT_R),
 XLAT(HW_BREAKPOINT_W),
 XLAT(HW_BREAKPOINT_RW),
 XLAT(HW_BREAKPOINT_X),
 /* this array should remain not NULL-terminated */
};

#endif /* !IN_MPERS */
