/* Generated by ./xlat/gen.sh from ./xlat/if_dqinfo_flags.in; do not edit. */
#if !(defined(DQF_ROOT_SQUASH) || (defined(HAVE_DECL_DQF_ROOT_SQUASH) && HAVE_DECL_DQF_ROOT_SQUASH))
# define DQF_ROOT_SQUASH (1 << 0)
#endif
#if !(defined(DQF_SYS_FILE) || (defined(HAVE_DECL_DQF_SYS_FILE) && HAVE_DECL_DQF_SYS_FILE))
# define DQF_SYS_FILE (1 << 16)
#endif

#ifdef IN_MPERS

# error static const struct xlat if_dqinfo_flags in mpers mode

#else

static
const struct xlat if_dqinfo_flags[] = {
 XLAT(DQF_ROOT_SQUASH),
 XLAT(DQF_SYS_FILE),
 XLAT_END
};

#endif /* !IN_MPERS */
