/* Generated by ./xlat/gen.sh from ./xlat/inet_diag_bytecodes.in; do not edit. */

#ifdef IN_MPERS

# error static const struct xlat inet_diag_bytecodes in mpers mode

#else

static
const struct xlat inet_diag_bytecodes[] = {
 XLAT(INET_DIAG_BC_NOP),
 XLAT(INET_DIAG_BC_JMP),
 XLAT(INET_DIAG_BC_S_GE),
 XLAT(INET_DIAG_BC_S_LE),
 XLAT(INET_DIAG_BC_D_GE),
 XLAT(INET_DIAG_BC_D_LE),
 XLAT(INET_DIAG_BC_AUTO),
 XLAT(INET_DIAG_BC_S_COND),
 XLAT(INET_DIAG_BC_D_COND),
 XLAT(INET_DIAG_BC_DEV_COND),
 XLAT(INET_DIAG_BC_MARK_COND),
 XLAT_END
};

#endif /* !IN_MPERS */
