/* Generated by ./xlat/gen.sh from ./xlat/inet_diag_req_attrs.in; do not edit. */

#ifdef IN_MPERS

# error static const struct xlat inet_diag_req_attrs in mpers mode

#else

static
const struct xlat inet_diag_req_attrs[] = {
 XLAT(INET_DIAG_REQ_NONE),
 XLAT(INET_DIAG_REQ_BYTECODE),
 XLAT_END
};

#endif /* !IN_MPERS */
