/* Generated by ./xlat/gen.sh from ./xlat/inotify_init_flags.in; do not edit. */
#if !(defined(IN_NONBLOCK) || (defined(HAVE_DECL_IN_NONBLOCK) && HAVE_DECL_IN_NONBLOCK))
# define IN_NONBLOCK O_NONBLOCK
#endif
#if defined IN_CLOEXEC || defined O_CLOEXEC
#if !(defined(IN_CLOEXEC) || (defined(HAVE_DECL_IN_CLOEXEC) && HAVE_DECL_IN_CLOEXEC))
# define IN_CLOEXEC O_CLOEXEC
#endif
#endif

#ifdef IN_MPERS

# error static const struct xlat inotify_init_flags in mpers mode

#else

static
const struct xlat inotify_init_flags[] = {
 XLAT(IN_NONBLOCK),
#if defined IN_CLOEXEC || defined O_CLOEXEC
 XLAT(IN_CLOEXEC),
#endif
 XLAT_END
};

#endif /* !IN_MPERS */
