/* Generated by ./xlat/gen.sh from ./xlat/loop_cmds.in; do not edit. */
#if !(defined(LOOP_SET_FD) || (defined(HAVE_DECL_LOOP_SET_FD) && HAVE_DECL_LOOP_SET_FD))
# define LOOP_SET_FD 0x4C00
#endif
#if !(defined(LOOP_CLR_FD) || (defined(HAVE_DECL_LOOP_CLR_FD) && HAVE_DECL_LOOP_CLR_FD))
# define LOOP_CLR_FD 0x4C01
#endif
#if !(defined(LOOP_SET_STATUS) || (defined(HAVE_DECL_LOOP_SET_STATUS) && HAVE_DECL_LOOP_SET_STATUS))
# define LOOP_SET_STATUS 0x4C02
#endif
#if !(defined(LOOP_GET_STATUS) || (defined(HAVE_DECL_LOOP_GET_STATUS) && HAVE_DECL_LOOP_GET_STATUS))
# define LOOP_GET_STATUS 0x4C03
#endif
#if !(defined(LOOP_SET_STATUS64) || (defined(HAVE_DECL_LOOP_SET_STATUS64) && HAVE_DECL_LOOP_SET_STATUS64))
# define LOOP_SET_STATUS64 0x4C04
#endif
#if !(defined(LOOP_GET_STATUS64) || (defined(HAVE_DECL_LOOP_GET_STATUS64) && HAVE_DECL_LOOP_GET_STATUS64))
# define LOOP_GET_STATUS64 0x4C05
#endif
#if !(defined(LOOP_CHANGE_FD) || (defined(HAVE_DECL_LOOP_CHANGE_FD) && HAVE_DECL_LOOP_CHANGE_FD))
# define LOOP_CHANGE_FD 0x4C06
#endif
#if !(defined(LOOP_SET_CAPACITY) || (defined(HAVE_DECL_LOOP_SET_CAPACITY) && HAVE_DECL_LOOP_SET_CAPACITY))
# define LOOP_SET_CAPACITY 0x4C07
#endif
#if !(defined(LOOP_SET_DIRECT_IO) || (defined(HAVE_DECL_LOOP_SET_DIRECT_IO) && HAVE_DECL_LOOP_SET_DIRECT_IO))
# define LOOP_SET_DIRECT_IO 0x4C08
#endif
#if !(defined(LOOP_CTL_ADD) || (defined(HAVE_DECL_LOOP_CTL_ADD) && HAVE_DECL_LOOP_CTL_ADD))
# define LOOP_CTL_ADD 0x4C80
#endif
#if !(defined(LOOP_CTL_REMOVE) || (defined(HAVE_DECL_LOOP_CTL_REMOVE) && HAVE_DECL_LOOP_CTL_REMOVE))
# define LOOP_CTL_REMOVE 0x4C81
#endif
#if !(defined(LOOP_CTL_GET_FREE) || (defined(HAVE_DECL_LOOP_CTL_GET_FREE) && HAVE_DECL_LOOP_CTL_GET_FREE))
# define LOOP_CTL_GET_FREE 0x4C82
#endif
