/* Generated by ./xlat/gen.sh from ./xlat/mbindflags.in; do not edit. */
#if !(defined(MPOL_MF_STRICT) || (defined(HAVE_DECL_MPOL_MF_STRICT) && HAVE_DECL_MPOL_MF_STRICT))
# define MPOL_MF_STRICT 1
#endif
#if !(defined(MPOL_MF_MOVE) || (defined(HAVE_DECL_MPOL_MF_MOVE) && HAVE_DECL_MPOL_MF_MOVE))
# define MPOL_MF_MOVE 2
#endif
#if !(defined(MPOL_MF_MOVE_ALL) || (defined(HAVE_DECL_MPOL_MF_MOVE_ALL) && HAVE_DECL_MPOL_MF_MOVE_ALL))
# define MPOL_MF_MOVE_ALL 4
#endif

#ifdef IN_MPERS

# error static const struct xlat mbindflags in mpers mode

#else

static
const struct xlat mbindflags[] = {
 XLAT(MPOL_MF_STRICT),
 XLAT(MPOL_MF_MOVE),
 XLAT(MPOL_MF_MOVE_ALL),
 XLAT_END
};

#endif /* !IN_MPERS */
