/* Generated by ./xlat/gen.sh from ./xlat/mdb_states.in; do not edit. */

#ifdef IN_MPERS

# error static const struct xlat mdb_states in mpers mode

#else

static
const struct xlat mdb_states[] = {
#if defined(MDB_TEMPORARY) || (defined(HAVE_DECL_MDB_TEMPORARY) && HAVE_DECL_MDB_TEMPORARY)
  XLAT(MDB_TEMPORARY),
#endif
#if defined(MDB_PERMANENT) || (defined(HAVE_DECL_MDB_PERMANENT) && HAVE_DECL_MDB_PERMANENT)
  XLAT(MDB_PERMANENT),
#endif
 XLAT_END
};

#endif /* !IN_MPERS */
