/* Generated by ./xlat/gen.sh from ./xlat/memfd_create_flags.in; do not edit. */
#if !(defined(MFD_CLOEXEC) || (defined(HAVE_DECL_MFD_CLOEXEC) && HAVE_DECL_MFD_CLOEXEC))
# define MFD_CLOEXEC 1
#endif
#if !(defined(MFD_ALLOW_SEALING) || (defined(HAVE_DECL_MFD_ALLOW_SEALING) && HAVE_DECL_MFD_ALLOW_SEALING))
# define MFD_ALLOW_SEALING 2
#endif
#if !(defined(MFD_HUGETLB) || (defined(HAVE_DECL_MFD_HUGETLB) && HAVE_DECL_MFD_HUGETLB))
# define MFD_HUGETLB 4
#endif

#ifdef IN_MPERS

# error static const struct xlat memfd_create_flags in mpers mode

#else

static
const struct xlat memfd_create_flags[] = {
 XLAT(MFD_CLOEXEC),
 XLAT(MFD_ALLOW_SEALING),
 XLAT(MFD_HUGETLB),
 XLAT_END
};

#endif /* !IN_MPERS */
