/* Generated by ./xlat/gen.sh from ./xlat/mount_flags.in; do not edit. */

static const struct xlat mount_flags[] = {
#if !(defined(MS_RDONLY) || (defined(HAVE_DECL_MS_RDONLY) && HAVE_DECL_MS_RDONLY))
# define MS_RDONLY 1
#endif
 XLAT(MS_RDONLY),
#if !(defined(MS_NOSUID) || (defined(HAVE_DECL_MS_NOSUID) && HAVE_DECL_MS_NOSUID))
# define MS_NOSUID 2
#endif
 XLAT(MS_NOSUID),
#if !(defined(MS_NODEV) || (defined(HAVE_DECL_MS_NODEV) && HAVE_DECL_MS_NODEV))
# define MS_NODEV 4
#endif
 XLAT(MS_NODEV),
#if !(defined(MS_NOEXEC) || (defined(HAVE_DECL_MS_NOEXEC) && HAVE_DECL_MS_NOEXEC))
# define MS_NOEXEC 8
#endif
 XLAT(MS_NOEXEC),
#if !(defined(MS_SYNCHRONOUS) || (defined(HAVE_DECL_MS_SYNCHRONOUS) && HAVE_DECL_MS_SYNCHRONOUS))
# define MS_SYNCHRONOUS 16
#endif
 XLAT(MS_SYNCHRONOUS),
#if !(defined(MS_REMOUNT) || (defined(HAVE_DECL_MS_REMOUNT) && HAVE_DECL_MS_REMOUNT))
# define MS_REMOUNT 32
#endif
 XLAT(MS_REMOUNT),
#if !(defined(MS_MANDLOCK) || (defined(HAVE_DECL_MS_MANDLOCK) && HAVE_DECL_MS_MANDLOCK))
# define MS_MANDLOCK 64
#endif
 XLAT(MS_MANDLOCK),
#if !(defined(MS_DIRSYNC) || (defined(HAVE_DECL_MS_DIRSYNC) && HAVE_DECL_MS_DIRSYNC))
# define MS_DIRSYNC 128
#endif
 XLAT(MS_DIRSYNC),
#if !(defined(MS_NOATIME) || (defined(HAVE_DECL_MS_NOATIME) && HAVE_DECL_MS_NOATIME))
# define MS_NOATIME 1024
#endif
 XLAT(MS_NOATIME),
#if !(defined(MS_NODIRATIME) || (defined(HAVE_DECL_MS_NODIRATIME) && HAVE_DECL_MS_NODIRATIME))
# define MS_NODIRATIME 2048
#endif
 XLAT(MS_NODIRATIME),
#if !(defined(MS_BIND) || (defined(HAVE_DECL_MS_BIND) && HAVE_DECL_MS_BIND))
# define MS_BIND 4096
#endif
 XLAT(MS_BIND),
#if !(defined(MS_MOVE) || (defined(HAVE_DECL_MS_MOVE) && HAVE_DECL_MS_MOVE))
# define MS_MOVE 8192
#endif
 XLAT(MS_MOVE),
#if !(defined(MS_REC) || (defined(HAVE_DECL_MS_REC) && HAVE_DECL_MS_REC))
# define MS_REC 16384
#endif
 XLAT(MS_REC),
#if !(defined(MS_SILENT) || (defined(HAVE_DECL_MS_SILENT) && HAVE_DECL_MS_SILENT))
# define MS_SILENT 32768
#endif
 XLAT(MS_SILENT),
#if !(defined(MS_POSIXACL) || (defined(HAVE_DECL_MS_POSIXACL) && HAVE_DECL_MS_POSIXACL))
# define MS_POSIXACL (1<<16)
#endif
 XLAT(MS_POSIXACL),
#if !(defined(MS_UNBINDABLE) || (defined(HAVE_DECL_MS_UNBINDABLE) && HAVE_DECL_MS_UNBINDABLE))
# define MS_UNBINDABLE (1<<17)
#endif
 XLAT(MS_UNBINDABLE),
#if !(defined(MS_PRIVATE) || (defined(HAVE_DECL_MS_PRIVATE) && HAVE_DECL_MS_PRIVATE))
# define MS_PRIVATE (1<<18)
#endif
 XLAT(MS_PRIVATE),
#if !(defined(MS_SLAVE) || (defined(HAVE_DECL_MS_SLAVE) && HAVE_DECL_MS_SLAVE))
# define MS_SLAVE (1<<19)
#endif
 XLAT(MS_SLAVE),
#if !(defined(MS_SHARED) || (defined(HAVE_DECL_MS_SHARED) && HAVE_DECL_MS_SHARED))
# define MS_SHARED (1<<20)
#endif
 XLAT(MS_SHARED),
#if !(defined(MS_RELATIME) || (defined(HAVE_DECL_MS_RELATIME) && HAVE_DECL_MS_RELATIME))
# define MS_RELATIME (1<<21)
#endif
 XLAT(MS_RELATIME),
#if !(defined(MS_KERNMOUNT) || (defined(HAVE_DECL_MS_KERNMOUNT) && HAVE_DECL_MS_KERNMOUNT))
# define MS_KERNMOUNT (1<<22)
#endif
 XLAT(MS_KERNMOUNT),
#if !(defined(MS_I_VERSION) || (defined(HAVE_DECL_MS_I_VERSION) && HAVE_DECL_MS_I_VERSION))
# define MS_I_VERSION (1<<23)
#endif
 XLAT(MS_I_VERSION),
#if !(defined(MS_STRICTATIME) || (defined(HAVE_DECL_MS_STRICTATIME) && HAVE_DECL_MS_STRICTATIME))
# define MS_STRICTATIME (1<<24)
#endif
 XLAT(MS_STRICTATIME),
#if !(defined(MS_LAZYTIME) || (defined(HAVE_DECL_MS_LAZYTIME) && HAVE_DECL_MS_LAZYTIME))
# define MS_LAZYTIME (1<<25)
#endif
 XLAT(MS_LAZYTIME),
#if !(defined(MS_NOSEC) || (defined(HAVE_DECL_MS_NOSEC) && HAVE_DECL_MS_NOSEC))
# define MS_NOSEC (1<<28)
#endif
 XLAT(MS_NOSEC),
#if !(defined(MS_BORN) || (defined(HAVE_DECL_MS_BORN) && HAVE_DECL_MS_BORN))
# define MS_BORN (1<<29)
#endif
 XLAT(MS_BORN),
#if !(defined(MS_ACTIVE) || (defined(HAVE_DECL_MS_ACTIVE) && HAVE_DECL_MS_ACTIVE))
# define MS_ACTIVE (1<<30)
#endif
 XLAT(MS_ACTIVE),
#if !(defined(MS_NOUSER) || (defined(HAVE_DECL_MS_NOUSER) && HAVE_DECL_MS_NOUSER))
# define MS_NOUSER (1<<31)
#endif
 XLAT(MS_NOUSER),
 XLAT_END
};
