/* Generated by ./xlat/gen.sh from ./xlat/mq_attr_flags.in; do not edit. */

#ifdef IN_MPERS

extern const struct xlat mq_attr_flags[];

#else

# if !(defined HAVE_M32_MPERS || defined HAVE_MX32_MPERS)
static
# endif
const struct xlat mq_attr_flags[] = {
#if defined(O_NONBLOCK) || (defined(HAVE_DECL_O_NONBLOCK) && HAVE_DECL_O_NONBLOCK)
  XLAT(O_NONBLOCK),
#endif
 XLAT_END
};

#endif /* !IN_MPERS */
