/* Generated by ./xlat/gen.sh from ./xlat/mtd_mode_options.in; do not edit. */

static const struct xlat mtd_mode_options[] = {
	XLAT(MTD_OPS_PLACE_OOB),
	XLAT(MTD_OPS_AUTO_OOB),
	XLAT(MTD_OPS_RAW),
	XLAT_END
};
