/* Generated by ./xlat/gen.sh from ./xlat/name_to_handle_at_flags.in; do not edit. */
#if !(defined(AT_SYMLINK_FOLLOW) || (defined(HAVE_DECL_AT_SYMLINK_FOLLOW) && HAVE_DECL_AT_SYMLINK_FOLLOW))
# define AT_SYMLINK_FOLLOW 0x400
#endif
#if !(defined(AT_EMPTY_PATH) || (defined(HAVE_DECL_AT_EMPTY_PATH) && HAVE_DECL_AT_EMPTY_PATH))
# define AT_EMPTY_PATH 0x1000
#endif

#ifdef IN_MPERS

# error static const struct xlat name_to_handle_at_flags in mpers mode

#else

static
const struct xlat name_to_handle_at_flags[] = {
 XLAT(AT_SYMLINK_FOLLOW),
 XLAT(AT_EMPTY_PATH),
 XLAT_END
};

#endif /* !IN_MPERS */
