/* Generated by ./xlat/gen.sh from ./xlat/netfilter_versions.in; do not edit. */
#if !(defined(NFNETLINK_V0) || (defined(HAVE_DECL_NFNETLINK_V0) && HAVE_DECL_NFNETLINK_V0))
# define NFNETLINK_V0 0
#endif
#if !(defined(NFNETLINK_V1) || (defined(HAVE_DECL_NFNETLINK_V1) && HAVE_DECL_NFNETLINK_V1))
# define NFNETLINK_V1 1
#endif

#ifdef IN_MPERS

# error static const struct xlat netfilter_versions in mpers mode

#else

static
const struct xlat netfilter_versions[] = {
 XLAT(NFNETLINK_V0),
 XLAT(NFNETLINK_V1),
 XLAT_END
};

#endif /* !IN_MPERS */
