/* Generated by ./xlat/gen.sh from ./xlat/netlink_states.in; do not edit. */
#if !(defined(NETLINK_UNCONNECTED) || (defined(HAVE_DECL_NETLINK_UNCONNECTED) && HAVE_DECL_NETLINK_UNCONNECTED))
# define NETLINK_UNCONNECTED 0
#endif
#if !(defined(NETLINK_CONNECTED) || (defined(HAVE_DECL_NETLINK_CONNECTED) && HAVE_DECL_NETLINK_CONNECTED))
# define NETLINK_CONNECTED 1
#endif

#ifdef IN_MPERS

# error static const struct xlat netlink_states in mpers mode

#else

static
const struct xlat netlink_states[] = {
 XLAT(NETLINK_UNCONNECTED),
 XLAT(NETLINK_CONNECTED),
 XLAT_END
};

#endif /* !IN_MPERS */
