/* Generated by ./xlat/gen.sh from ./xlat/netlink_types.in; do not edit. */
#if !(defined(NLMSG_NOOP) || (defined(HAVE_DECL_NLMSG_NOOP) && HAVE_DECL_NLMSG_NOOP))
# define NLMSG_NOOP 0x1
#endif
#if !(defined(NLMSG_ERROR) || (defined(HAVE_DECL_NLMSG_ERROR) && HAVE_DECL_NLMSG_ERROR))
# define NLMSG_ERROR 0x2
#endif
#if !(defined(NLMSG_DONE) || (defined(HAVE_DECL_NLMSG_DONE) && HAVE_DECL_NLMSG_DONE))
# define NLMSG_DONE 0x3
#endif
#if !(defined(NLMSG_OVERRUN) || (defined(HAVE_DECL_NLMSG_OVERRUN) && HAVE_DECL_NLMSG_OVERRUN))
# define NLMSG_OVERRUN 0x4
#endif

#ifdef IN_MPERS

# error static const struct xlat netlink_types in mpers mode

#else

static
const struct xlat netlink_types[] = {
 XLAT(NLMSG_NOOP),
 XLAT(NLMSG_ERROR),
 XLAT(NLMSG_DONE),
 XLAT(NLMSG_OVERRUN),
 XLAT_END
};

#endif /* !IN_MPERS */
