/* Generated by ./xlat/gen.sh from ./xlat/nf_nft_compat_msg_types.in; do not edit. */
#if !(defined(NFNL_MSG_COMPAT_GET) || (defined(HAVE_DECL_NFNL_MSG_COMPAT_GET) && HAVE_DECL_NFNL_MSG_COMPAT_GET))
# define NFNL_MSG_COMPAT_GET 0
#endif

#ifdef IN_MPERS

# error static const struct xlat nf_nft_compat_msg_types in mpers mode

#else

static
const struct xlat nf_nft_compat_msg_types[] = {
 XLAT(NFNL_MSG_COMPAT_GET),
 XLAT_END
};

#endif /* !IN_MPERS */
