/* Generated by ./xlat/gen.sh from ./xlat/nf_queue_msg_types.in; do not edit. */
#if !(defined(NFQNL_MSG_PACKET) || (defined(HAVE_DECL_NFQNL_MSG_PACKET) && HAVE_DECL_NFQNL_MSG_PACKET))
# define NFQNL_MSG_PACKET 0
#endif
#if !(defined(NFQNL_MSG_VERDICT) || (defined(HAVE_DECL_NFQNL_MSG_VERDICT) && HAVE_DECL_NFQNL_MSG_VERDICT))
# define NFQNL_MSG_VERDICT 1
#endif
#if !(defined(NFQNL_MSG_CONFIG) || (defined(HAVE_DECL_NFQNL_MSG_CONFIG) && HAVE_DECL_NFQNL_MSG_CONFIG))
# define NFQNL_MSG_CONFIG 2
#endif
#if !(defined(NFQNL_MSG_VERDICT_BATCH) || (defined(HAVE_DECL_NFQNL_MSG_VERDICT_BATCH) && HAVE_DECL_NFQNL_MSG_VERDICT_BATCH))
# define NFQNL_MSG_VERDICT_BATCH 3
#endif

#ifdef IN_MPERS

# error static const struct xlat nf_queue_msg_types in mpers mode

#else

static
const struct xlat nf_queue_msg_types[] = {
 XLAT(NFQNL_MSG_PACKET),
 XLAT(NFQNL_MSG_VERDICT),
 XLAT(NFQNL_MSG_CONFIG),
 XLAT(NFQNL_MSG_VERDICT_BATCH),
 XLAT_END
};

#endif /* !IN_MPERS */
