/* Generated by ./xlat/gen.sh from ./xlat/nf_ulog_msg_types.in; do not edit. */
#if !(defined(NFULNL_MSG_PACKET) || (defined(HAVE_DECL_NFULNL_MSG_PACKET) && HAVE_DECL_NFULNL_MSG_PACKET))
# define NFULNL_MSG_PACKET 0
#endif
#if !(defined(NFULNL_MSG_CONFIG) || (defined(HAVE_DECL_NFULNL_MSG_CONFIG) && HAVE_DECL_NFULNL_MSG_CONFIG))
# define NFULNL_MSG_CONFIG 1
#endif

#ifdef IN_MPERS

# error static const struct xlat nf_ulog_msg_types in mpers mode

#else

static
const struct xlat nf_ulog_msg_types[] = {
 XLAT(NFULNL_MSG_PACKET),
 XLAT(NFULNL_MSG_CONFIG),
 XLAT_END
};

#endif /* !IN_MPERS */
