/* Generated by ./xlat/gen.sh from ./xlat/nl_sock_diag_types.in; do not edit. */
#if !(defined(TCPDIAG_GETSOCK) || (defined(HAVE_DECL_TCPDIAG_GETSOCK) && HAVE_DECL_TCPDIAG_GETSOCK))
# define TCPDIAG_GETSOCK 18
#endif
#if !(defined(DCCPDIAG_GETSOCK) || (defined(HAVE_DECL_DCCPDIAG_GETSOCK) && HAVE_DECL_DCCPDIAG_GETSOCK))
# define DCCPDIAG_GETSOCK 19
#endif
#if !(defined(SOCK_DIAG_BY_FAMILY) || (defined(HAVE_DECL_SOCK_DIAG_BY_FAMILY) && HAVE_DECL_SOCK_DIAG_BY_FAMILY))
# define SOCK_DIAG_BY_FAMILY 20
#endif
#if !(defined(SOCK_DESTROY) || (defined(HAVE_DECL_SOCK_DESTROY) && HAVE_DECL_SOCK_DESTROY))
# define SOCK_DESTROY 21
#endif

#ifdef IN_MPERS

# error static const struct xlat nl_sock_diag_types in mpers mode

#else

static
const struct xlat nl_sock_diag_types[] = {
 XLAT(TCPDIAG_GETSOCK),
 XLAT(DCCPDIAG_GETSOCK),
 XLAT(SOCK_DIAG_BY_FAMILY),
 XLAT(SOCK_DESTROY),
 XLAT_END
};

#endif /* !IN_MPERS */
