/* Generated by ./xlat/gen.sh from ./xlat/nl_selinux_types.in; do not edit. */
#if !(defined(SELNL_MSG_SETENFORCE) || (defined(HAVE_DECL_SELNL_MSG_SETENFORCE) && HAVE_DECL_SELNL_MSG_SETENFORCE))
# define SELNL_MSG_SETENFORCE 0x10
#endif
#if !(defined(SELNL_MSG_POLICYLOAD) || (defined(HAVE_DECL_SELNL_MSG_POLICYLOAD) && HAVE_DECL_SELNL_MSG_POLICYLOAD))
# define SELNL_MSG_POLICYLOAD 0x11
#endif

#ifdef IN_MPERS

# error static const struct xlat nl_selinux_types in mpers mode

#else

static
const struct xlat nl_selinux_types[] = {
 XLAT(SELNL_MSG_SETENFORCE),
 XLAT(SELNL_MSG_POLICYLOAD),
 XLAT_END
};

#endif /* !IN_MPERS */
