/* Generated by ./xlat/gen.sh from ./xlat/perf_type_id.in; do not edit. */
#if !(defined(PERF_TYPE_HARDWARE) || (defined(HAVE_DECL_PERF_TYPE_HARDWARE) && HAVE_DECL_PERF_TYPE_HARDWARE))
# define PERF_TYPE_HARDWARE 0
#endif
#if !(defined(PERF_TYPE_SOFTWARE) || (defined(HAVE_DECL_PERF_TYPE_SOFTWARE) && HAVE_DECL_PERF_TYPE_SOFTWARE))
# define PERF_TYPE_SOFTWARE 1
#endif
#if !(defined(PERF_TYPE_TRACEPOINT) || (defined(HAVE_DECL_PERF_TYPE_TRACEPOINT) && HAVE_DECL_PERF_TYPE_TRACEPOINT))
# define PERF_TYPE_TRACEPOINT 2
#endif
#if !(defined(PERF_TYPE_HW_CACHE) || (defined(HAVE_DECL_PERF_TYPE_HW_CACHE) && HAVE_DECL_PERF_TYPE_HW_CACHE))
# define PERF_TYPE_HW_CACHE 3
#endif
#if !(defined(PERF_TYPE_RAW) || (defined(HAVE_DECL_PERF_TYPE_RAW) && HAVE_DECL_PERF_TYPE_RAW))
# define PERF_TYPE_RAW 4
#endif
#if !(defined(PERF_TYPE_BREAKPOINT) || (defined(HAVE_DECL_PERF_TYPE_BREAKPOINT) && HAVE_DECL_PERF_TYPE_BREAKPOINT))
# define PERF_TYPE_BREAKPOINT 5
#endif

#ifdef IN_MPERS

# error static const struct xlat perf_type_id in mpers mode

#else

static
const struct xlat perf_type_id[] = {
 XLAT(PERF_TYPE_HARDWARE),
 XLAT(PERF_TYPE_SOFTWARE),
 XLAT(PERF_TYPE_TRACEPOINT),
 XLAT(PERF_TYPE_HW_CACHE),
 XLAT(PERF_TYPE_RAW),
 XLAT(PERF_TYPE_BREAKPOINT),
 /* this array should remain not NULL-terminated */
};

#endif /* !IN_MPERS */
