/* Generated by ./xlat/gen.sh from ./xlat/pkey_access.in; do not edit. */
#if !(defined(PKEY_DISABLE_ACCESS) || (defined(HAVE_DECL_PKEY_DISABLE_ACCESS) && HAVE_DECL_PKEY_DISABLE_ACCESS))
# define PKEY_DISABLE_ACCESS 0x1
#endif
#if !(defined(PKEY_DISABLE_WRITE) || (defined(HAVE_DECL_PKEY_DISABLE_WRITE) && HAVE_DECL_PKEY_DISABLE_WRITE))
# define PKEY_DISABLE_WRITE 0x2
#endif

#ifdef IN_MPERS

# error static const struct xlat pkey_access in mpers mode

#else

static
const struct xlat pkey_access[] = {
 XLAT(PKEY_DISABLE_ACCESS),
 XLAT(PKEY_DISABLE_WRITE),
 XLAT_END
};

#endif /* !IN_MPERS */
