/* Generated by ./xlat/gen.sh from ./xlat/pollflags.in; do not edit. */
#if !(defined(POLLIN) || (defined(HAVE_DECL_POLLIN) && HAVE_DECL_POLLIN))
# define POLLIN 0x0001
#endif
#if !(defined(POLLPRI) || (defined(HAVE_DECL_POLLPRI) && HAVE_DECL_POLLPRI))
# define POLLPRI 0x0002
#endif
#if !(defined(POLLOUT) || (defined(HAVE_DECL_POLLOUT) && HAVE_DECL_POLLOUT))
# define POLLOUT 0x0004
#endif
#if !(defined(POLLRDNORM) || (defined(HAVE_DECL_POLLRDNORM) && HAVE_DECL_POLLRDNORM))
# define POLLRDNORM 0x0040
#endif
#if !(defined(POLLRDBAND) || (defined(HAVE_DECL_POLLRDBAND) && HAVE_DECL_POLLRDBAND))
# define POLLRDBAND 0x0080
#endif
#if !(defined(POLLERR) || (defined(HAVE_DECL_POLLERR) && HAVE_DECL_POLLERR))
# define POLLERR 0x0008
#endif
#if !(defined(POLLHUP) || (defined(HAVE_DECL_POLLHUP) && HAVE_DECL_POLLHUP))
# define POLLHUP 0x0010
#endif
#if !(defined(POLLNVAL) || (defined(HAVE_DECL_POLLNVAL) && HAVE_DECL_POLLNVAL))
# define POLLNVAL 0x0020
#endif
#if !(defined(POLL_BUSY_LOOP) || (defined(HAVE_DECL_POLL_BUSY_LOOP) && HAVE_DECL_POLL_BUSY_LOOP))
# define POLL_BUSY_LOOP 0x8000
#endif

#ifdef IN_MPERS

# error static const struct xlat pollflags in mpers mode

#else

static
const struct xlat pollflags[] = {
 XLAT(POLLIN),
 XLAT(POLLPRI),
 XLAT(POLLOUT),
 XLAT(POLLRDNORM),
#if defined(POLLWRNORM) || (defined(HAVE_DECL_POLLWRNORM) && HAVE_DECL_POLLWRNORM)
  XLAT(POLLWRNORM),
#endif
 XLAT(POLLRDBAND),
#if defined(POLLWRBAND) || (defined(HAVE_DECL_POLLWRBAND) && HAVE_DECL_POLLWRBAND)
  XLAT(POLLWRBAND),
#endif
 XLAT(POLLERR),
 XLAT(POLLHUP),
 XLAT(POLLNVAL),
#if defined(POLLMSG) || (defined(HAVE_DECL_POLLMSG) && HAVE_DECL_POLLMSG)
  XLAT(POLLMSG),
#endif
#if defined(POLLREMOVE) || (defined(HAVE_DECL_POLLREMOVE) && HAVE_DECL_POLLREMOVE)
  XLAT(POLLREMOVE),
#endif
#if defined(POLLRDHUP) || (defined(HAVE_DECL_POLLRDHUP) && HAVE_DECL_POLLRDHUP)
  XLAT(POLLRDHUP),
#endif
 XLAT(POLL_BUSY_LOOP),
 XLAT_END
};

#endif /* !IN_MPERS */
