/* Generated by ./xlat/gen.sh from ./xlat/pr_mce_kill.in; do not edit. */

static const struct xlat pr_mce_kill[] = {
#if !(defined(PR_MCE_KILL_CLEAR) || (defined(HAVE_DECL_PR_MCE_KILL_CLEAR) && HAVE_DECL_PR_MCE_KILL_CLEAR))
# define PR_MCE_KILL_CLEAR 0
#endif
 XLAT(PR_MCE_KILL_CLEAR),
#if !(defined(PR_MCE_KILL_SET) || (defined(HAVE_DECL_PR_MCE_KILL_SET) && HAVE_DECL_PR_MCE_KILL_SET))
# define PR_MCE_KILL_SET 1
#endif
 XLAT(PR_MCE_KILL_SET),
 XLAT_END
};
