/* Generated by ./xlat/gen.sh from ./xlat/pr_sve_vl_flags.in; do not edit. */
#if !(defined(PR_SVE_SET_VL_ONEXEC) || (defined(HAVE_DECL_PR_SVE_SET_VL_ONEXEC) && HAVE_DECL_PR_SVE_SET_VL_ONEXEC))
# define PR_SVE_SET_VL_ONEXEC (1 << 18)
#endif
#if !(defined(PR_SVE_VL_INHERIT) || (defined(HAVE_DECL_PR_SVE_VL_INHERIT) && HAVE_DECL_PR_SVE_VL_INHERIT))
# define PR_SVE_VL_INHERIT (1 << 17)
#endif

#ifdef IN_MPERS

# error static const struct xlat pr_sve_vl_flags in mpers mode

#else

static
const struct xlat pr_sve_vl_flags[] = {
 XLAT(PR_SVE_SET_VL_ONEXEC),
 XLAT(PR_SVE_VL_INHERIT),
 XLAT_END
};

#endif /* !IN_MPERS */
