/* Generated by ./xlat/gen.sh from ./xlat/ptrace_peeksiginfo_flags.in; do not edit. */
#if !(defined(PTRACE_PEEKSIGINFO_SHARED) || (defined(HAVE_DECL_PTRACE_PEEKSIGINFO_SHARED) && HAVE_DECL_PTRACE_PEEKSIGINFO_SHARED))
# define PTRACE_PEEKSIGINFO_SHARED 1
#endif

#ifdef IN_MPERS

# error static const struct xlat ptrace_peeksiginfo_flags in mpers mode

#else

static
const struct xlat ptrace_peeksiginfo_flags[] = {
 XLAT(PTRACE_PEEKSIGINFO_SHARED),
 XLAT_END
};

#endif /* !IN_MPERS */
