/* Generated by ./xlat/gen.sh from ./xlat/quotatypes.in; do not edit. */
#if !(defined(USRQUOTA) || (defined(HAVE_DECL_USRQUOTA) && HAVE_DECL_USRQUOTA))
# define USRQUOTA 0
#endif
#if !(defined(GRPQUOTA) || (defined(HAVE_DECL_GRPQUOTA) && HAVE_DECL_GRPQUOTA))
# define GRPQUOTA 1
#endif
#if !(defined(PRJQUOTA) || (defined(HAVE_DECL_PRJQUOTA) && HAVE_DECL_PRJQUOTA))
# define PRJQUOTA 2
#endif

#ifdef IN_MPERS

# error static const struct xlat quotatypes in mpers mode

#else

static
const struct xlat quotatypes[] = {
 XLAT(USRQUOTA),
 XLAT(GRPQUOTA),
 XLAT(PRJQUOTA),
 XLAT_END
};

#endif /* !IN_MPERS */
