/* Generated by ./xlat/gen.sh from ./xlat/rename_flags.in; do not edit. */
#if !(defined(RENAME_NOREPLACE) || (defined(HAVE_DECL_RENAME_NOREPLACE) && HAVE_DECL_RENAME_NOREPLACE))
# define RENAME_NOREPLACE 1
#endif
#if !(defined(RENAME_EXCHANGE) || (defined(HAVE_DECL_RENAME_EXCHANGE) && HAVE_DECL_RENAME_EXCHANGE))
# define RENAME_EXCHANGE 2
#endif
#if !(defined(RENAME_WHITEOUT) || (defined(HAVE_DECL_RENAME_WHITEOUT) && HAVE_DECL_RENAME_WHITEOUT))
# define RENAME_WHITEOUT 4
#endif

#ifdef IN_MPERS

# error static const struct xlat rename_flags in mpers mode

#else

static
const struct xlat rename_flags[] = {
 XLAT(RENAME_NOREPLACE),
 XLAT(RENAME_EXCHANGE),
 XLAT(RENAME_WHITEOUT),
 XLAT_END
};

#endif /* !IN_MPERS */
