/* Generated by ./xlat/gen.sh from ./xlat/rename_flags.in; do not edit. */

static const struct xlat rename_flags[] = {
#if defined(RENAME_NOREPLACE) || (defined(HAVE_DECL_RENAME_NOREPLACE) && HAVE_DECL_RENAME_NOREPLACE)
	XLAT(RENAME_NOREPLACE),
#endif
#if defined(RENAME_EXCHANGE) || (defined(HAVE_DECL_RENAME_EXCHANGE) && HAVE_DECL_RENAME_EXCHANGE)
	XLAT(RENAME_EXCHANGE),
#endif
	XLAT_END
};
