/* Generated by ./xlat/gen.sh from ./xlat/riscv_flush_icache_flags.in; do not edit. */
#if !(defined(SYS_RISCV_FLUSH_ICACHE_LOCAL) || (defined(HAVE_DECL_SYS_RISCV_FLUSH_ICACHE_LOCAL) && HAVE_DECL_SYS_RISCV_FLUSH_ICACHE_LOCAL))
# define SYS_RISCV_FLUSH_ICACHE_LOCAL 1
#endif

#ifdef IN_MPERS

# error static const struct xlat riscv_flush_icache_flags in mpers mode

#else

static
const struct xlat riscv_flush_icache_flags[] = {
 XLAT(SYS_RISCV_FLUSH_ICACHE_LOCAL),
 XLAT_END
};

#endif /* !IN_MPERS */
