/* Generated by ./xlat/gen.sh from ./xlat/rtnl_mdba_router_pattr_attrs.in; do not edit. */
#if !(defined(MDBA_ROUTER_PATTR_UNSPEC) || (defined(HAVE_DECL_MDBA_ROUTER_PATTR_UNSPEC) && HAVE_DECL_MDBA_ROUTER_PATTR_UNSPEC))
# define MDBA_ROUTER_PATTR_UNSPEC 0
#endif
#if !(defined(MDBA_ROUTER_PATTR_TIMER) || (defined(HAVE_DECL_MDBA_ROUTER_PATTR_TIMER) && HAVE_DECL_MDBA_ROUTER_PATTR_TIMER))
# define MDBA_ROUTER_PATTR_TIMER 1
#endif
#if !(defined(MDBA_ROUTER_PATTR_TYPE) || (defined(HAVE_DECL_MDBA_ROUTER_PATTR_TYPE) && HAVE_DECL_MDBA_ROUTER_PATTR_TYPE))
# define MDBA_ROUTER_PATTR_TYPE 2
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_mdba_router_pattr_attrs in mpers mode

#else

static
const struct xlat rtnl_mdba_router_pattr_attrs[] = {
 XLAT(MDBA_ROUTER_PATTR_UNSPEC),
 XLAT(MDBA_ROUTER_PATTR_TIMER),
 XLAT(MDBA_ROUTER_PATTR_TYPE),
 XLAT_END
};

#endif /* !IN_MPERS */
