/* Generated by ./xlat/gen.sh from ./xlat/rtnl_mdba_mdb_attrs.in; do not edit. */
#if !(defined(MDBA_MDB_UNSPEC) || (defined(HAVE_DECL_MDBA_MDB_UNSPEC) && HAVE_DECL_MDBA_MDB_UNSPEC))
# define MDBA_MDB_UNSPEC 0
#endif
#if !(defined(MDBA_MDB_ENTRY) || (defined(HAVE_DECL_MDBA_MDB_ENTRY) && HAVE_DECL_MDBA_MDB_ENTRY))
# define MDBA_MDB_ENTRY 1
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_mdba_mdb_attrs in mpers mode

#else

static
const struct xlat rtnl_mdba_mdb_attrs[] = {
 XLAT(MDBA_MDB_UNSPEC),
 XLAT(MDBA_MDB_ENTRY),
 XLAT_END
};

#endif /* !IN_MPERS */
