/* Generated by ./xlat/gen.sh from ./xlat/rtnl_addrlabel_attrs.in; do not edit. */
#if !(defined(IFAL_ADDRESS) || (defined(HAVE_DECL_IFAL_ADDRESS) && HAVE_DECL_IFAL_ADDRESS))
# define IFAL_ADDRESS 1
#endif
#if !(defined(IFAL_LABEL) || (defined(HAVE_DECL_IFAL_LABEL) && HAVE_DECL_IFAL_LABEL))
# define IFAL_LABEL 2
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_addrlabel_attrs in mpers mode

#else

static
const struct xlat rtnl_addrlabel_attrs[] = {
 XLAT(IFAL_ADDRESS),
 XLAT(IFAL_LABEL),
 XLAT_END
};

#endif /* !IN_MPERS */
