/* Generated by ./xlat/gen.sh from ./xlat/rtnl_mdba_mdb_eattr_attrs.in; do not edit. */
#if !(defined(MDBA_MDB_EATTR_UNSPEC) || (defined(HAVE_DECL_MDBA_MDB_EATTR_UNSPEC) && HAVE_DECL_MDBA_MDB_EATTR_UNSPEC))
# define MDBA_MDB_EATTR_UNSPEC 0
#endif
#if !(defined(MDBA_MDB_EATTR_TIMER) || (defined(HAVE_DECL_MDBA_MDB_EATTR_TIMER) && HAVE_DECL_MDBA_MDB_EATTR_TIMER))
# define MDBA_MDB_EATTR_TIMER 1
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_mdba_mdb_eattr_attrs in mpers mode

#else

static
const struct xlat rtnl_mdba_mdb_eattr_attrs[] = {
 XLAT(MDBA_MDB_EATTR_UNSPEC),
 XLAT(MDBA_MDB_EATTR_TIMER),
 XLAT_END
};

#endif /* !IN_MPERS */
