/* Generated by ./xlat/gen.sh from ./xlat/rtnl_ifla_info_attrs.in; do not edit. */
#if !(defined(IFLA_INFO_UNSPEC) || (defined(HAVE_DECL_IFLA_INFO_UNSPEC) && HAVE_DECL_IFLA_INFO_UNSPEC))
# define IFLA_INFO_UNSPEC 0
#endif
#if !(defined(IFLA_INFO_KIND) || (defined(HAVE_DECL_IFLA_INFO_KIND) && HAVE_DECL_IFLA_INFO_KIND))
# define IFLA_INFO_KIND 1
#endif
#if !(defined(IFLA_INFO_DATA) || (defined(HAVE_DECL_IFLA_INFO_DATA) && HAVE_DECL_IFLA_INFO_DATA))
# define IFLA_INFO_DATA 2
#endif
#if !(defined(IFLA_INFO_XSTATS) || (defined(HAVE_DECL_IFLA_INFO_XSTATS) && HAVE_DECL_IFLA_INFO_XSTATS))
# define IFLA_INFO_XSTATS 3
#endif
#if !(defined(IFLA_INFO_SLAVE_KIND) || (defined(HAVE_DECL_IFLA_INFO_SLAVE_KIND) && HAVE_DECL_IFLA_INFO_SLAVE_KIND))
# define IFLA_INFO_SLAVE_KIND 4
#endif
#if !(defined(IFLA_INFO_SLAVE_DATA) || (defined(HAVE_DECL_IFLA_INFO_SLAVE_DATA) && HAVE_DECL_IFLA_INFO_SLAVE_DATA))
# define IFLA_INFO_SLAVE_DATA 5
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_ifla_info_attrs in mpers mode

#else

static
const struct xlat rtnl_ifla_info_attrs[] = {
 XLAT(IFLA_INFO_UNSPEC),
 XLAT(IFLA_INFO_KIND),
 XLAT(IFLA_INFO_DATA),
 XLAT(IFLA_INFO_XSTATS),
 XLAT(IFLA_INFO_SLAVE_KIND),
 XLAT(IFLA_INFO_SLAVE_DATA),
 XLAT_END
};

#endif /* !IN_MPERS */
