/* Generated by ./xlat/gen.sh from ./xlat/rtnl_ifla_xdp_attrs.in; do not edit. */
#if !(defined(IFLA_XDP_UNSPEC) || (defined(HAVE_DECL_IFLA_XDP_UNSPEC) && HAVE_DECL_IFLA_XDP_UNSPEC))
# define IFLA_XDP_UNSPEC 0
#endif
#if !(defined(IFLA_XDP_FD) || (defined(HAVE_DECL_IFLA_XDP_FD) && HAVE_DECL_IFLA_XDP_FD))
# define IFLA_XDP_FD 1
#endif
#if !(defined(IFLA_XDP_ATTACHED) || (defined(HAVE_DECL_IFLA_XDP_ATTACHED) && HAVE_DECL_IFLA_XDP_ATTACHED))
# define IFLA_XDP_ATTACHED 2
#endif
#if !(defined(IFLA_XDP_FLAGS) || (defined(HAVE_DECL_IFLA_XDP_FLAGS) && HAVE_DECL_IFLA_XDP_FLAGS))
# define IFLA_XDP_FLAGS 3
#endif
#if !(defined(IFLA_XDP_PROG_ID) || (defined(HAVE_DECL_IFLA_XDP_PROG_ID) && HAVE_DECL_IFLA_XDP_PROG_ID))
# define IFLA_XDP_PROG_ID 4
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_ifla_xdp_attrs in mpers mode

#else

static
const struct xlat rtnl_ifla_xdp_attrs[] = {
 XLAT(IFLA_XDP_UNSPEC),
 XLAT(IFLA_XDP_FD),
 XLAT(IFLA_XDP_ATTACHED),
 XLAT(IFLA_XDP_FLAGS),
 XLAT(IFLA_XDP_PROG_ID),
 XLAT_END
};

#endif /* !IN_MPERS */
