/* Generated by ./xlat/gen.sh from ./xlat/rtnl_ifla_vf_port_attrs.in; do not edit. */
#if !(defined(IFLA_VF_PORT_UNSPEC) || (defined(HAVE_DECL_IFLA_VF_PORT_UNSPEC) && HAVE_DECL_IFLA_VF_PORT_UNSPEC))
# define IFLA_VF_PORT_UNSPEC 0
#endif
#if !(defined(IFLA_VF_PORT) || (defined(HAVE_DECL_IFLA_VF_PORT) && HAVE_DECL_IFLA_VF_PORT))
# define IFLA_VF_PORT 1
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_ifla_vf_port_attrs in mpers mode

#else

static
const struct xlat rtnl_ifla_vf_port_attrs[] = {
 XLAT(IFLA_VF_PORT_UNSPEC),
 XLAT(IFLA_VF_PORT),
 XLAT_END
};

#endif /* !IN_MPERS */
