/* Generated by ./xlat/gen.sh from ./xlat/rtnl_mdb_attrs.in; do not edit. */
#if !(defined(MDBA_UNSPEC) || (defined(HAVE_DECL_MDBA_UNSPEC) && HAVE_DECL_MDBA_UNSPEC))
# define MDBA_UNSPEC 0
#endif
#if !(defined(MDBA_MDB) || (defined(HAVE_DECL_MDBA_MDB) && HAVE_DECL_MDBA_MDB))
# define MDBA_MDB 1
#endif
#if !(defined(MDBA_ROUTER) || (defined(HAVE_DECL_MDBA_ROUTER) && HAVE_DECL_MDBA_ROUTER))
# define MDBA_ROUTER 2
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_mdb_attrs in mpers mode

#else

static
const struct xlat rtnl_mdb_attrs[] = {
 XLAT(MDBA_UNSPEC),
 XLAT(MDBA_MDB),
 XLAT(MDBA_ROUTER),
 XLAT_END
};

#endif /* !IN_MPERS */
