/* Generated by ./xlat/gen.sh from ./xlat/rtnl_mdba_mdb_entry_attrs.in; do not edit. */
#if !(defined(MDBA_MDB_ENTRY_UNSPEC) || (defined(HAVE_DECL_MDBA_MDB_ENTRY_UNSPEC) && HAVE_DECL_MDBA_MDB_ENTRY_UNSPEC))
# define MDBA_MDB_ENTRY_UNSPEC 0
#endif
#if !(defined(MDBA_MDB_ENTRY_INFO) || (defined(HAVE_DECL_MDBA_MDB_ENTRY_INFO) && HAVE_DECL_MDBA_MDB_ENTRY_INFO))
# define MDBA_MDB_ENTRY_INFO 1
#endif

#ifdef IN_MPERS

# error static const struct xlat rtnl_mdba_mdb_entry_attrs in mpers mode

#else

static
const struct xlat rtnl_mdba_mdb_entry_attrs[] = {
 XLAT(MDBA_MDB_ENTRY_UNSPEC),
 XLAT(MDBA_MDB_ENTRY_INFO),
 XLAT_END
};

#endif /* !IN_MPERS */
