/* Generated by ./xlat/gen.sh from ./xlat/rwf_flags.in; do not edit. */
#if !(defined(RWF_HIPRI) || (defined(HAVE_DECL_RWF_HIPRI) && HAVE_DECL_RWF_HIPRI))
# define RWF_HIPRI 1
#endif

#ifdef IN_MPERS

# error static const struct xlat rwf_flags in mpers mode

#else

static
const struct xlat rwf_flags[] = {
 XLAT(RWF_HIPRI),
 XLAT_END
};

#endif /* !IN_MPERS */
