/* Generated by ./xlat/gen.sh from ./xlat/s390_guarded_storage_commands.in; do not edit. */
#if !(defined(GS_ENABLE) || (defined(HAVE_DECL_GS_ENABLE) && HAVE_DECL_GS_ENABLE))
# define GS_ENABLE 0
#endif
#if !(defined(GS_DISABLE) || (defined(HAVE_DECL_GS_DISABLE) && HAVE_DECL_GS_DISABLE))
# define GS_DISABLE 1
#endif
#if !(defined(GS_SET_BC_CB) || (defined(HAVE_DECL_GS_SET_BC_CB) && HAVE_DECL_GS_SET_BC_CB))
# define GS_SET_BC_CB 2
#endif
#if !(defined(GS_CLEAR_BC_CB) || (defined(HAVE_DECL_GS_CLEAR_BC_CB) && HAVE_DECL_GS_CLEAR_BC_CB))
# define GS_CLEAR_BC_CB 3
#endif
#if !(defined(GS_BROADCAST) || (defined(HAVE_DECL_GS_BROADCAST) && HAVE_DECL_GS_BROADCAST))
# define GS_BROADCAST 4
#endif

#ifdef IN_MPERS

# error static const struct xlat s390_guarded_storage_commands in mpers mode

#else

static
const struct xlat s390_guarded_storage_commands[] = {
 XLAT(GS_ENABLE),
 XLAT(GS_DISABLE),
 XLAT(GS_SET_BC_CB),
 XLAT(GS_CLEAR_BC_CB),
 XLAT(GS_BROADCAST),
 XLAT_END
};

#endif /* !IN_MPERS */
