/* Generated by ./xlat/gen.sh from ./xlat/s390_sthyi_function_codes.in; do not edit. */
#if !(defined(STHYI_FC_CP_IFL_CAP) || (defined(HAVE_DECL_STHYI_FC_CP_IFL_CAP) && HAVE_DECL_STHYI_FC_CP_IFL_CAP))
# define STHYI_FC_CP_IFL_CAP 0
#endif

#ifdef IN_MPERS

# error static const struct xlat s390_sthyi_function_codes in mpers mode

#else

static
const struct xlat s390_sthyi_function_codes[] = {
 XLAT(STHYI_FC_CP_IFL_CAP),
 XLAT_END
};

#endif /* !IN_MPERS */
