/* Generated by ./xlat/gen.sh from ./xlat/s390_runtime_instr_commands.in; do not edit. */
#if !(defined(S390_RUNTIME_INSTR_START) || (defined(HAVE_DECL_S390_RUNTIME_INSTR_START) && HAVE_DECL_S390_RUNTIME_INSTR_START))
# define S390_RUNTIME_INSTR_START 0x1
#endif
#if !(defined(S390_RUNTIME_INSTR_STOP) || (defined(HAVE_DECL_S390_RUNTIME_INSTR_STOP) && HAVE_DECL_S390_RUNTIME_INSTR_STOP))
# define S390_RUNTIME_INSTR_STOP 0x2
#endif

#ifdef IN_MPERS

# error static const struct xlat s390_runtime_instr_commands in mpers mode

#else

static
const struct xlat s390_runtime_instr_commands[] = {
 XLAT(S390_RUNTIME_INSTR_START),
 XLAT(S390_RUNTIME_INSTR_STOP),
 XLAT_END
};

#endif /* !IN_MPERS */
