/* Generated by ./xlat/gen.sh from ./xlat/seccomp_filter_flags.in; do not edit. */
#if !(defined(SECCOMP_FILTER_FLAG_TSYNC) || (defined(HAVE_DECL_SECCOMP_FILTER_FLAG_TSYNC) && HAVE_DECL_SECCOMP_FILTER_FLAG_TSYNC))
# define SECCOMP_FILTER_FLAG_TSYNC 1
#endif
#if !(defined(SECCOMP_FILTER_FLAG_LOG) || (defined(HAVE_DECL_SECCOMP_FILTER_FLAG_LOG) && HAVE_DECL_SECCOMP_FILTER_FLAG_LOG))
# define SECCOMP_FILTER_FLAG_LOG 2
#endif

#ifdef IN_MPERS

# error static const struct xlat seccomp_filter_flags in mpers mode

#else

static
const struct xlat seccomp_filter_flags[] = {
 XLAT(SECCOMP_FILTER_FLAG_TSYNC),
 XLAT(SECCOMP_FILTER_FLAG_LOG),
 XLAT_END
};

#endif /* !IN_MPERS */
