/* Generated by ./xlat/gen.sh from ./xlat/shutdown_modes.in; do not edit. */
#if !(defined(SHUT_RD) || (defined(HAVE_DECL_SHUT_RD) && HAVE_DECL_SHUT_RD))
# define SHUT_RD 0
#endif
#if !(defined(SHUT_WR) || (defined(HAVE_DECL_SHUT_WR) && HAVE_DECL_SHUT_WR))
# define SHUT_WR 1
#endif
#if !(defined(SHUT_RDWR) || (defined(HAVE_DECL_SHUT_RDWR) && HAVE_DECL_SHUT_RDWR))
# define SHUT_RDWR 2
#endif

#ifdef IN_MPERS

# error static const struct xlat shutdown_modes in mpers mode

#else

static
const struct xlat shutdown_modes[] = {
 XLAT(SHUT_RD),
 XLAT(SHUT_WR),
 XLAT(SHUT_RDWR),
 XLAT_END
};

#endif /* !IN_MPERS */
