/* Generated by ./xlat/gen.sh from ./xlat/sigbus_codes.in; do not edit. */

static const struct xlat sigbus_codes[] = {
#if !(defined(BUS_ADRALN) || (defined(HAVE_DECL_BUS_ADRALN) && HAVE_DECL_BUS_ADRALN))
# define BUS_ADRALN 1
#endif
 XLAT(BUS_ADRALN),
#if !(defined(BUS_ADRERR) || (defined(HAVE_DECL_BUS_ADRERR) && HAVE_DECL_BUS_ADRERR))
# define BUS_ADRERR 2
#endif
 XLAT(BUS_ADRERR),
#if !(defined(BUS_OBJERR) || (defined(HAVE_DECL_BUS_OBJERR) && HAVE_DECL_BUS_OBJERR))
# define BUS_OBJERR 3
#endif
 XLAT(BUS_OBJERR),
#if !(defined(BUS_MCEERR_AR) || (defined(HAVE_DECL_BUS_MCEERR_AR) && HAVE_DECL_BUS_MCEERR_AR))
# define BUS_MCEERR_AR 4
#endif
 XLAT(BUS_MCEERR_AR),
#if !(defined(BUS_MCEERR_AO) || (defined(HAVE_DECL_BUS_MCEERR_AO) && HAVE_DECL_BUS_MCEERR_AO))
# define BUS_MCEERR_AO 5
#endif
 XLAT(BUS_MCEERR_AO),
 XLAT_END
};
