/* Generated by ./xlat/gen.sh from ./xlat/sigemt_codes.in; do not edit. */

static const struct xlat sigemt_codes[] = {
#if !(defined(EMT_TAGOVF) || (defined(HAVE_DECL_EMT_TAGOVF) && HAVE_DECL_EMT_TAGOVF))
# define EMT_TAGOVF 1
#endif
 XLAT(EMT_TAGOVF),
 XLAT_END
};
