/* Generated by ./xlat/gen.sh from ./xlat/smc_diag_attrs.in; do not edit. */

#ifdef IN_MPERS

# error static const struct xlat smc_diag_attrs in mpers mode

#else

static
const struct xlat smc_diag_attrs[] = {
 XLAT(SMC_DIAG_NONE),
 XLAT(SMC_DIAG_CONNINFO),
 XLAT(SMC_DIAG_LGRINFO),
 XLAT(SMC_DIAG_SHUTDOWN),
 XLAT_END
};

#endif /* !IN_MPERS */
