/* Generated by ./xlat/gen.sh from ./xlat/sparc_kern_features.in; do not edit. */
#if !(defined(KERN_FEATURE_MIXED_MODE_STACK) || (defined(HAVE_DECL_KERN_FEATURE_MIXED_MODE_STACK) && HAVE_DECL_KERN_FEATURE_MIXED_MODE_STACK))
# define KERN_FEATURE_MIXED_MODE_STACK 1
#endif

#ifdef IN_MPERS

# error static const struct xlat sparc_kern_features in mpers mode

#else

static
const struct xlat sparc_kern_features[] = {
 XLAT(KERN_FEATURE_MIXED_MODE_STACK),
 XLAT_END
};

#endif /* !IN_MPERS */
