/* Generated by ./xlat/gen.sh from ./xlat/statfs_flags.in; do not edit. */
#if !(defined(ST_VALID) || (defined(HAVE_DECL_ST_VALID) && HAVE_DECL_ST_VALID))
# define ST_VALID 0x0020
#endif
#if !(defined(ST_RDONLY) || (defined(HAVE_DECL_ST_RDONLY) && HAVE_DECL_ST_RDONLY))
# define ST_RDONLY 0x0001
#endif
#if !(defined(ST_NOSUID) || (defined(HAVE_DECL_ST_NOSUID) && HAVE_DECL_ST_NOSUID))
# define ST_NOSUID 0x0002
#endif
#if !(defined(ST_NODEV) || (defined(HAVE_DECL_ST_NODEV) && HAVE_DECL_ST_NODEV))
# define ST_NODEV 0x0004
#endif
#if !(defined(ST_NOEXEC) || (defined(HAVE_DECL_ST_NOEXEC) && HAVE_DECL_ST_NOEXEC))
# define ST_NOEXEC 0x0008
#endif
#if !(defined(ST_SYNCHRONOUS) || (defined(HAVE_DECL_ST_SYNCHRONOUS) && HAVE_DECL_ST_SYNCHRONOUS))
# define ST_SYNCHRONOUS 0x0010
#endif
#if !(defined(ST_MANDLOCK) || (defined(HAVE_DECL_ST_MANDLOCK) && HAVE_DECL_ST_MANDLOCK))
# define ST_MANDLOCK 0x0040
#endif
#if !(defined(ST_NOATIME) || (defined(HAVE_DECL_ST_NOATIME) && HAVE_DECL_ST_NOATIME))
# define ST_NOATIME 0x0400
#endif
#if !(defined(ST_NODIRATIME) || (defined(HAVE_DECL_ST_NODIRATIME) && HAVE_DECL_ST_NODIRATIME))
# define ST_NODIRATIME 0x0800
#endif
#if !(defined(ST_RELATIME) || (defined(HAVE_DECL_ST_RELATIME) && HAVE_DECL_ST_RELATIME))
# define ST_RELATIME 0x1000
#endif

#ifdef IN_MPERS

# error static const struct xlat statfs_flags in mpers mode

#else

static
const struct xlat statfs_flags[] = {
 XLAT(ST_VALID),
 XLAT(ST_RDONLY),
 XLAT(ST_NOSUID),
 XLAT(ST_NODEV),
 XLAT(ST_NOEXEC),
 XLAT(ST_SYNCHRONOUS),
 XLAT(ST_MANDLOCK),
 XLAT(ST_NOATIME),
 XLAT(ST_NODIRATIME),
 XLAT(ST_RELATIME),
 XLAT_END
};

#endif /* !IN_MPERS */
