/* Generated by ./xlat/gen.sh from ./xlat/sysctl_net_unix.in; do not edit. */

#ifdef IN_MPERS

# error static const struct xlat sysctl_net_unix in mpers mode

#else

static
const struct xlat sysctl_net_unix[] = {
 XLAT(NET_UNIX_DESTROY_DELAY),
 XLAT(NET_UNIX_DELETE_DELAY),
 XLAT(NET_UNIX_MAX_DGRAM_QLEN),
 XLAT_END
};

#endif /* !IN_MPERS */
