/* Generated by ./xlat/gen.sh from ./xlat/timerfdflags.in; do not edit. */

static const struct xlat timerfdflags[] = {
#if defined(TFD_TIMER_ABSTIME) || (defined(HAVE_DECL_TFD_TIMER_ABSTIME) && HAVE_DECL_TFD_TIMER_ABSTIME)
	XLAT(TFD_TIMER_ABSTIME),
#endif
	XLAT_END
};
