/* Generated by ./xlat/gen.sh from ./xlat/uffd_zeropage_flags.in; do not edit. */

#ifdef IN_MPERS

# error static const struct xlat uffd_zeropage_flags in mpers mode

#else

static
const struct xlat uffd_zeropage_flags[] = {
#if defined(UFFDIO_ZEROPAGE_MODE_DONTWAKE) || (defined(HAVE_DECL_UFFDIO_ZEROPAGE_MODE_DONTWAKE) && HAVE_DECL_UFFDIO_ZEROPAGE_MODE_DONTWAKE)
  XLAT_TYPE(uint64_t, UFFDIO_ZEROPAGE_MODE_DONTWAKE),
#endif
 XLAT_END
};

#endif /* !IN_MPERS */
