/* Generated by ./xlat/gen.sh from ./xlat/xattrflags.in; do not edit. */

static const struct xlat xattrflags[] = {
#if !(defined(XATTR_CREATE) || (defined(HAVE_DECL_XATTR_CREATE) && HAVE_DECL_XATTR_CREATE))
# define XATTR_CREATE 1
#endif
 XLAT(XATTR_CREATE),
#if !(defined(XATTR_REPLACE) || (defined(HAVE_DECL_XATTR_REPLACE) && HAVE_DECL_XATTR_REPLACE))
# define XATTR_REPLACE 2
#endif
 XLAT(XATTR_REPLACE),
 XLAT_END
};
