/* Generated by ./xlat/gen.sh from ./xlat/xattrflags.in; do not edit. */

static const struct xlat xattrflags[] = {
#if defined(XATTR_CREATE) || (defined(HAVE_DECL_XATTR_CREATE) && HAVE_DECL_XATTR_CREATE)
	XLAT(XATTR_CREATE),
#endif
#if defined(XATTR_REPLACE) || (defined(HAVE_DECL_XATTR_REPLACE) && HAVE_DECL_XATTR_REPLACE)
	XLAT(XATTR_REPLACE),
#endif
	XLAT_END
};
