/* Generated by ./xlat/gen.sh from ./xlat/xfs_dqblk_flags.in; do not edit. */
#if !(defined(XFS_USER_QUOTA) || (defined(HAVE_DECL_XFS_USER_QUOTA) && HAVE_DECL_XFS_USER_QUOTA))
# define XFS_USER_QUOTA (1<<0)
#endif
#if !(defined(XFS_PROJ_QUOTA) || (defined(HAVE_DECL_XFS_PROJ_QUOTA) && HAVE_DECL_XFS_PROJ_QUOTA))
# define XFS_PROJ_QUOTA (1<<1)
#endif
#if !(defined(XFS_GROUP_QUOTA) || (defined(HAVE_DECL_XFS_GROUP_QUOTA) && HAVE_DECL_XFS_GROUP_QUOTA))
# define XFS_GROUP_QUOTA (1<<2)
#endif

#ifdef IN_MPERS

# error static const struct xlat xfs_dqblk_flags in mpers mode

#else

static
const struct xlat xfs_dqblk_flags[] = {
 XLAT(XFS_USER_QUOTA),
 XLAT(XFS_PROJ_QUOTA),
 XLAT(XFS_GROUP_QUOTA),
 XLAT_END
};

#endif /* !IN_MPERS */
